### ISSUE TITLE
Improve active node highlighting in 3D view

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1037]
Hi,

colors on the trees tab and in the 4th viewport seem to be different.
Please look at the movie - colors in the viewport are much darker - and (not sure though) there seems to be only a few colors while on the trees tab are many.

When I activate one node out of the tree that node seems to get the correct color

movie:
https://datashare.rzg.mpg.de/index.php/s/tBOFlN0nf4hubfN

Best,
Heiko

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1037/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Colors are matching now.
