### ISSUE TITLE
Fail import if Dataset doesn't contain a single cube

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1196]
Each folder in the respective binaryData folder should correspond to a line in the Show advanced view menu.
Either it is already imported, it should offer the import or it should explain why no import is offered (e.g. no settings.json found)
Also it would be super cool to be able to trigger the scanning of the folder manually, but this is the stretch goal :-)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1196/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
Resolved by #1896
