### ISSUE TITLE
how to create new root teams

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1210]
is it desirable to have a way in the front end to create new root teams?
If not, what would be the work flow for example for the external.webknossos.io deploy?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1210/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
New organisations will be created directly in the DB. No need for a UI just now.
