### ISSUE TITLE
Make setting dataset team permission option more discoverable

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1211]
I don't think it is possible to set dataset permissions in the front end? Do we want to be able to do that? If not, how should I proceed if teams need to share datasets?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1211/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Will be solved with PR #2563
