### ISSUE TITLE
Automated team separation testing

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1219]
on the external.webknossos.io server, there are now teams with content that mustn't be seen by other teams.. i.e. people would be very mad at us if that happened. If you do automatic testing, this would be a great thing to test

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1219/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Duplicate of #2340
