### ISSUE TITLE
admin of parent team

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1222]
I just got the message
User Kevin Boergens can't be assigned administrative rights in team Baier Department because he doesnt belong to the teams parent team.
Why is that so? Also, in the view it still shows my rights as admin (until reload)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1222/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Duplicate of #2160
