### ISSUE TITLE
Allow a single datastore to connect to multiple WK instances

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1236]
We should discuss how to use datasets on multiple releases. More specifically we currently need the big MEC dataset from Garching on external.webknossos.io.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1236/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
Recent improvements to the import of datasets, allow multiple datastores to access the same datasets. In fact, we have already set up a second datastore in Garching to connect to https://demo.webknossos.org.

**Comment by normanrz** [comment]
Using multiple datastore instances is more flexible, because you can restrict the datasets which are published and change teams. Symlinks on the host allow to share the data.
