### ISSUE TITLE
Mappings implementation

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1241]
I don't understand super well yet what we would need them for.. perhaps you can explain next time we talk :-)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1241/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@kevinbbb87 do you think there is anything left to be done here? as far as I remember, the discussion above was mostly about multi-level mappings. I suggest we start a new discussion as soon as this becomes relevant.
