### ISSUE TITLE
Support multiple bbox's when viewing merged tracings

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1249]
When have a project with many tasks each with a different bounding box - then you click view on project to view all tasks - you then see all tasks but only the dataset of ONE of these bounding boxes (probably the first)

Could not test on release because I missed the tasks menu to create those tasks

Best
Heiko

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1249/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Closing as this currently not on the roadmap. Please reopen when needed.
