### ISSUE TITLE
User registration notifications to team leaders

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1255]
currently new users notifications from external.webknossos.io arrive at our normal mail queue. It would be helpful if we could set these notification receivers on a per-team-basis

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1255/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
This has been solved in the meantime.
