### ISSUE TITLE
Clean up starting arguments

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#1261]
The typical startup arguments for webknossos are repeated multiple times:
- [cmd.sh](https://github.com/scalableminds/oxalis/commits/dev/buildtools/cmd.sh)
- more to come...
  This should be cleaned up and abstracted somehow.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1261/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
I think we should get rid of `cmd.sh`. In all our deployments we use explicit arguments anyways.

**Comment by normanrz** [comment]
Fixed in #2258
