### ISSUE TITLE
Hidden sign up page

### ISSUE THREAD

**Issue by KevinBoergens** [scalableminds/webknossos#1278]
The more groups and users there are and the more deploys, the better the chance that users register at wrong instances and/or teams..
Perhaps make it a deploy option to hide the sign-up page and every team gets a separate sign-up page with a non-guessable link?
Just an idea..

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1278/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
I think a URL that prefills the team selection would be nice, e.g. `https://webknossos.brain.mpg.de/auth/register?team=Connectomics%20department`

**Comment by normanrz** [comment]
@philippotto Should we pick this back up? I think it would be great if we could print the url in the onboarding flow for admins to invite other users.

**Comment by philippotto** [comment]
@normanrz Sure sounds good. Do you think it would be better to use the organization id in the url? Then, it's not guessable (somewhat) and we would also circumvent encoding issues in the url. Just a thought... I'm not sure what's better.

**Comment by normanrz** [comment]
Yeah, we can do that. Although, I think it‘s not important that the organisation is non-guessable.
