### ISSUE TITLE
Remove team assignment from tasks 

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1279]
Since tasks are required to belong to a project and a project itself is assigned to a team, it is unecessary and possibly confusing to have a team assignment on the task level as well.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1279/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@rschwanhold maybe in the wake of this you could also have a look why the project list page does not show the project’s team (probably related to sending IDs vs names)

**Comment by rschwanhold** [comment]
@fm3 The 'team'-field of the project contains indeed the id and not the name of the team. Should the frontend do an extra look up for the name, or should the backend send the name in the first place?

**Comment by fm3** [comment]
I’d say send the name, if it’s not too much of a pain in the backend :) 
(if you _replace_ the field, check if the ID is maybe used elsewhere in the frontend. It’s also ok to send both)
