### ISSUE TITLE
Branchpoints flight mode

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1289]
It's hard to see a successful branch point setting in flight mode.. a good&quick solution would be a toast

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1289/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
I think this is fixed now. Setting a branch point in flight mode shows a toast. Please reopen in case this is still an issue.
