### ISSUE TITLE
Improve usage statistics

### ISSUE THREAD

**Issue by KevinBoergens** [scalableminds/webknossos#1293]
It would be interesting to see how often interaction elements are used.. Are there good packages for gathering usage statistics of the front end?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1293/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Our usage of analytics can be further improved:

- [ ] ensure that requests to google analytics are properly batched
- [ ] even though we record all redux actions, there are still some crucial interactions which are not analyzed. The most prominent example is probably "download as NML".

**Comment by daniel-wer** [comment]
I checked whether it is possible to send google analytics events in batches which does not seem to be the case :/

Regarding the crucial interactions which are not yet analyzed, I see two options:
  - Manually include a ga call at the interesting spots (when clicking certain buttons). Makes the call highly customizable and we can decide what interactions to track and what data to include. However, we'll have all these calls in our code and need to maintain them.
  - Use Google Tag Manager to track some or all button clicks (https://mediacause.org/track-button-clicks-google-tag-manager/). This would allow to track all button clicks rather easily, but I'm not sure how much insight can be gathered from these generic events. It would also allow to track specific button clicks without having to add code if I understand this correctly. The Tag Manager interface looks pretty complicated to me though.

Let's have a look and discuss in person :)

**Comment by daniel-wer** [comment]
We agreed on trying another approach: Register a custom click handler on the document that sends the `textContent` (if there is one) of any clicked elements to google analytics. During a quick prototyping session, this worked reasonably well. We'll check the results a week after deployment and will refine the approach then.
