### ISSUE TITLE
see 100 random tasks

### ISSUE THREAD

**Issue by KevinBoergens** [scalableminds/webknossos#1297]
the view link in the project view is not very helpful if it's a project with many many tasks.. there a view 100 random tasks would help more

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1297/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@kevinbbb87 Why is this feature not helpful? In case of many tasks are there too many nodes/trees in the resulting tracing?

**Comment by kevinbbb87** [comment]
@hotzenklotz If we have a project with 50,000 tasks we currently don't have an efficient way to see _some_ of them. I can pull the task list with the API and then use the API to download 100 random tasks and then upload them as explorative annotations but perhaps there is a better way? I'm not sure

**Comment by philippotto** [comment]
Should be covered by #2803.
