### ISSUE TITLE
Disable dataset actions that are reserved for WK datasets (e.g. reimport)

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1301]
Actions that are not possible on external datasets e.g. on a ndstore server should not be shown to the user 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1301/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Closing this, since the nd store is not supported anymore anyway.
