### ISSUE TITLE
Flight mode improvement

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1306]
Part 1: Setting nodes only onKeyDown(Space).
We found that often many nodes are outside the current process. We then looked how beginners are actually tracing and found that they do it  by holding down space, not using the direction keys, following the process with their eyes for about 3 seconds. Then they release space, recenter onto the process and continue. This is in principle fine, but of course generates many false nodes. If the nodes would only be generated on activation of flight movement, the problem of false nodes would disappear.

Part 2: Smarter branch points in Flight Mode.
Reviewers felt that we don't put enough attention on branch points and perhaps they are not wrong about that. The problem is that the current branch point mode is very difficult in flight mode, because one has to reorient in the branch point.. definitely not beginner friendly. What we want to try now is a branch point "shooting" mode where not the current node is set as branch point but a secondary one (we had something like that a while back in Orthogonal Mode, but only Heiko used it and it was deactivated).
The exact mode would work like this:

Pressing B enters a separate mode. In this mode clicking with the mouse does the following things
- Placing a node X at the current center location (this probably should happen as soon as B is pressed)
- Placing a node Y at where you clicked (this is the trickiest bit I think because one has to map a click in the sphere onto a 3D position)
- Pushing node Y to the branchpoint stack
- \- Pushing the current view Z to the "branchpoint view stack". This includes rot and pos.
- Giving focus back to node X
- On pressing J, the following things happen:
- - Popping node Y off the stack
- \- Giving focus to node Y
- \- Popping view Z off the stack
- \- Restoring view Z
- \- "Flashing" node Y

All things marked with star would be a second step only taken if the first step turns out to be a viable interaction mode.

I felt that the easiest way to test these thing would be in a seperate branch, quick and dirty to give all stake holders a chance to try it out and form their opinions.

What do you think? Do you think this will improve things? Is it feasible technically?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1306/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
Position and rotation were restored when deleting nodes or jumping to a branchpoint in flight mode, so Part 2 was addressed. I just noticed that this no longer works, it will be fixed as part of #1977.

Not sure about Part 1 though. That would change how users would need to trace in flight mode. They would need to press space repeatedly and I think that would slow them down, wouldn't it? If the movement is too fast to recenter onto the process (using mouse or arrow keys) while holding Space, the movement value should be decreased I would say.
@kevinbbb87 Do you still think Part 1 needs to be solved?
