### ISSUE TITLE
Assist on branch pop in flight mode

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1317]
We have to decide how to do - one option is jump, then fly a bit backwards automatically. Then the user has usually seen the 2nd exit. 

@daniel-wer didn't you implement some animation a while back for something that we could reuse here?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1317/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Closing this stale issue.
