### ISSUE TITLE
Improve comment sorting

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1401]
Hi guys,

the sort button in the comments panel currently only sorts comments within the respective treeIDs, but does not affect the ordering of the actual trees. 

For nmls containing multiple trees with meaningful IDs it would be handy to have the trees alphabetically sorted as well. 

Here is an example file for that:

https://webknossos.brain.mpg.de/annotations/Explorational/579f92075d00003342a4a202#20912,27327,513,0,0.16,19182

I'd like to have the sort button arrange the trees like that:

> brain em
> brain lm
> donald em
> donald em
> ....

Thanks for solving this!

Florian

florian.drawitsch@brain.mpg.de

 Reported by: Florian Drawitsch (florian@mhlab.net) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1401/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
See also discussion: https://discuss.webknossos.org/t/wk-comment-sorting/398/3

I suggest using "localeCompare" and let's use natural sort order (i.e. "z2" < "z11")
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by hotzenklotz** [comment]
Fixed by PR #1940
