### ISSUE TITLE
measure average speed that annotators have available

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1403]
to determine whether annotators are limited by training level or insufficient internet speed it would be helpful to be able to record how quickly data arrived while tracing

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1403/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@kevinbbb87 Is this still relevant or was this only for the paper?
If so, my suggestion would be to not measure the connection speed, but rather assess, how much / which? data is missing during rendering, since this is what really limits the tracer.

**Comment by kevinbbb87** [comment]
@jfrohnhofen it was only relevant during paper experiments. We also didn't use the data in the end
