### ISSUE TITLE
password reset by admin

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1405]
Hi,

I should be able to reset passwords.
Not every admin should be able to do so (because some hiwis get admin status to be able to access tracings)

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1405/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
users can now reset their own password as part of #2048
