### ISSUE TITLE
Connect RESCOP Service to validate annotation quality

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1440]
To evaluate a tracers performance we are going to use a RESCOP service that given a tracings data evaluate the fitness of that tracing.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1440/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
This is no longer relevant right now. Please reopen when needed.
