### ISSUE TITLE
Disable auto-save

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1473]
Sometimes it would be useful to only save, when save is explicitly clicked and not automatically.
We could introduce an option to deactivate auto-save. 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1473/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
@normanrz Do you have a specific use case in mind here?

**Comment by normanrz** [comment]
Not really. Probably is obsolete with undo. Lets reopen when this comes up again
