### ISSUE TITLE
tif cubing creates incomplete raw files

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1498]
The KNOSSOS standard expects all raw files to be padded up to 128x128x128 voxel, the tif file importer fills it up only as much as needed.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1498/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
no longer applicable, since tiff import is deprecated
