### ISSUE TITLE
replace tracing

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1513]
Hi,
is there any chance I can replace an existing tracing with one I have on my PC?
Best
Heiko

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1513/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@heikowissler is this still relevant?
