### ISSUE TITLE
Create annotation admin page to search and view annotations

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1517]
When I get the annotation ID from a user (for example 582460c37b00009900f5ba73) I can not find the task because the annotation ID can not be used at Administratin - tasks - search for ID.

We should have a similar search page, which we have for tasks, for annotations as well. It should allow to search by annotation id and to view the resulting annotations details. 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1517/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Closing this issue, since it's stale.
