### ISSUE TITLE
Implement oauth2_proxy for dev servers

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1534]
Replace basic auth with [oauth2_proxy](https://github.com/bitly/oauth2_proxy).
We should probably do this for the new kubernetes setup with docker: https://github.com/crate/docker-oauth2_proxy

We could restrict access for a given github team, that should be easiest to manage: https://github.com/bitly/oauth2_proxy#github-auth-provider

The proxy can be integrated with nginx: https://github.com/bitly/oauth2_proxy#configuring-for-use-with-the-nginx-auth_request-directive

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1534/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
No longer relevant. Basic auth is no long used.
