### ISSUE TITLE
Volume outline suggestion from previous plane

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1543]
Hey Guys,

another feature I would love is to have the volume trace from the previous plane copied. The idea would be to only add/remove partially and that's it. Most of the next planes look really similar and minor modifications would do the job.

Best,
Philipp

 Reported by: Philipp Bastians (philipp@mhlab.net) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1543/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@hotzenklotz @daniel-wer @philippotto 
Isn't this the same as #2044 and should be closed?

**Comment by hotzenklotz** [comment]
Yes, it's a duplicate of #2044
