### ISSUE TITLE
Migrate datasets to Garching

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1554]
- [ ] rsync all datasets to Garching
- [ ] confirm with checksums (`find path/to -type f -print0 | xargs -0 sha512sum | tee checksums.txt`)
- [ ] disable datastore on oxalisone (depends on #1561)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1554/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
has been resolved in the meantime
