### ISSUE TITLE
reopen + transfer

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1560]
Hi I think it would be amazing to have a feature which does "reopen" + "transfer" to an user at the same time. Would this be somehow possible?

Cheers and thx in advance 
Raphael k

 Reported by: Raphael Kneissl (raphael-kneissl@web.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1560/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
This has been deployed, see https://discuss.webknossos.org/t/reopen-transfer-in-one-button/64
