### ISSUE TITLE
Current review server backup

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1568]
It would be very important that the review server is back-upped as well as master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1568/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@kevinbbb87 @normanrz can be closed, right?

**Comment by normanrz** [comment]
Yeah. We did a manual backup and cancelled the server.
