### ISSUE TITLE
Remove superfluous return statements

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1583]
CoffeeScript had automatic returns for every function. With JS we don't necessarily need that, so let's get rid of that.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1583/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@normanrz Can this be closed? We had some many code revision lately that I feel we eliminated most of the superfluous return statements.
