### ISSUE TITLE
popup at type-change

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1623]
Hi,
we had this problem:
two almost identical projects (BS_L4_inhibitory_synapse_mergeMode_postSyn and BS_L4_inhibitory_synapse_mergeMode).
The hiwi thought it is the same (and therefor has ignored the NEW task description). In the end the task was a complete different and many hours were wasted.

If a user get a new task within the tracing via "finish and get a new task" the user gets a popup if this is a different.
Maybe we can get something for the "get a new task" button too?
For example : compare task type of the last one the user finished with the one the user would get. If it is a different show the popup "this is probably a new task description" or like the text for the other popup.

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1623/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Duplicate of #2374
