### ISSUE TITLE
show coming project in "get a new task" button

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#1624]
The usecase:
we have many projects with different priorities. But sometimes we want 3-4 hiwis to get a very specific task. Once these specific tasks are all gone the 3-4 hiwis do not know that there are no more of these specific tasks and gets one from another project.
The hiwis know that these specific tasks are urgent and try from time to time again and again. 

Then they have 5 tasks and can not get another one.
And even if they only have 3-4 tasks where each last 10 hours - then the other project would last forever.

Therefor: It would be very useful to show the upcoming project on the button, for example show "get a new task (project: XXXX)"

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1624/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Fixed by PR #2374
