### ISSUE TITLE
Rename `Connectomics Department` on disc directory

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1733]
There are a couple things that need changing:
- [ ] add new field to teams (one will be internal one will be shown everywhere) - we can also go for a single field solution and only allow characters and numbers and replace spaces
- [ ] double check what happens to datastore.json and information stored in the database concerning datasets
- [ ] ensure rights management is still working

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1733/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
Fixed with #2869
