### ISSUE TITLE
Always load lower resolution data when requesting buckets

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1781]
We might want to update our data fetching strategy to always fetch lower resolution buckets. This has only a ~14% overhead, but can ensure that users will never see a black screen and might enhance user experience quite a bit. Google's neuroglancer uses this strategy and it looked quite promising.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1781/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
This should be covered by #2442. With the new GPU rendering, we cannot use buckets of a higher resolution than the current zoomstep to interpolate. That's why I adapted the ping strategy to always load buckets of the next "poorer" zoomstep.
