### ISSUE TITLE
Render frontend textures in WebGL shader

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1782]
This has several benefits:
- frees up CPU time for other operations
- probably improves rendering speed / framerates (if necessary)
- single rendering codebase for all three viewports
- support for segmentation in arbitrary viewports / flight mode

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1782/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Covered by #2295.
