### ISSUE TITLE
Additional mask layer

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1784]
see https://discuss.webknossos.org/t/additional-mask-layer/74

this should not be done before I finish my refactoring!

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1784/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
related: https://discuss.webknossos.org/t/multiple-layers-cause-bucket-cache-problem/140

**Comment by philippotto** [comment]
@jfrohnhofen Are you done with your refactoring?

**Comment by philippotto** [comment]
I think we can re-open this when/if this becomes relevant again.
