### ISSUE TITLE
Freeze objects which are returned by the API and enforce strict mode in user scripts

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#1796]
At the moments, the user scripts can try to modify the objects which are returned by the API. Since this is not be allowed, we should also enforce this.

I suggest to do it by:

- freezing everything which is returned by the API (ideally, our whole app state would be frozen but it seems like this is a too big performance hit at the moment)
- enforce "use strict" in the user scripts, since only then errors will be thrown when trying to mutate the state.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1796/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Can we close this?

**Comment by daniel-wer** [comment]
I'll add a PR on friday that takes care of the freezing.

**Comment by daniel-wer** [comment]
Yep, that didn't happen ^^ I don't think this is important for now, we never had an issue with it. I'll close the issue.
