### ISSUE TITLE
Investigate backend API testing possibilities

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1817]
to make the backend more robust (import not working / download not working / no segmentation etc.) we could add a couple of simple test cases for the HTTP API: simply define a set of HTTP requests and the expected JSON responses / status codes.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1817/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@philippotto is currently working on frontend snapshot testing. Depending on the results and his experiences, we could use snapshots-test the REST api. Those snapshots could also be used to improve frontend testing performance, since they could be used to mock the server.

**Comment by fm3** [comment]
closed through #2309 and follow-ups
