### ISSUE TITLE
Zoom value should feel the same for all tracing modes

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1829]
Currently switching between ortho and flightmode with the same constant zoom value will result in one being zoomed in far more than the other.
This is most likely caused due to the 3D camera being closer to the plane the flight mode. Perhaps we can set up the scene identically for both tracing modes so that zoom feels the same.

See also: https://discuss.webknossos.org/t/zoom-is-combined-since-update/217

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1829/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@jfrohnhofen Is this really fixed or did you change it by accident?

**Comment by daniel-wer** [comment]
This seems to have been an accident, the issue still persists. @jfrohnhofen did a big merge which included the original commit from @normanrz that was supposed to fix this issue, but was reverted later.
