### ISSUE TITLE
Reactify controller

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#1858]
In order to go further in the data centric direction, we need to refactor the controllers. One task is to move controller functionality into the API so it's more reusable. The other task is to make the controllers react components, so that we can reap life cycle hooks and better composition. The latter task shall be covered in this issue.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1858/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
I didn't take part in your discussion with @normanrz and @hotzenklotz regarding the further direction of this issue. Can you briefly lay out the next steps here or would it be easier to do this in person?

**Comment by philippotto** [comment]
@daniel-wer I think it would be easier to do this in person :)

**Comment by hotzenklotz** [comment]
Let's close this for now. If we plan to reactify as specific other component we will file a new issue.
