### ISSUE TITLE
Properly handle duplicate dataset names

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1878]
- [ ] dataStore should report owning organization with datasource
- [ ] wK should identify dataSets by a `name + organization`
- [ ] when users request data, the organization should be derived from the requesting user

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1878/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
What about public datasets? The request is not sent by a logged-in user then

**Comment by jfrohnhofen** [comment]
we could/should make datasets accessible as `team/datasetName`. The only time we need to match a "pure" dataset name without a team is when parsing NMLs. But all uploads should have a logged-in user.

**Comment by fm3** [comment]
I see, yes that sounds possible. Thanks for your reply :)
