### ISSUE TITLE
automatically detect bounding box in new datastore during import

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1897]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1897/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@youri-k The code you need to touch for this issue is in the braingames-libs repo. Have you already worked with the libs? You will need to change the `version` in the `version` file (to e.g. `11.3.9-detect-bb-SNAPSHOT`) and set wK to the same version in `project/Build.scala`. You can then run `sbt publish-local` whenever you want changes you make in the libs to be available in wK, but will have to restart the server each time to force the dependency to be updated.
We can go over this in person if you are experiencing trouble. @fm3 is also able to help you out with this.

**Comment by youri-k** [comment]
I think I once did it with @fm3 so it wasn't such a big trouble
I opened a PR on the braingames-lib repo. Maybe you both can comment your thoughts @jfrohnhofen and @fm3 ?

**Comment by fm3** [comment]
for the archives, a link to the [corresponding PR](https://github.com/scalableminds/braingames-libs/pull/63)
