### ISSUE TITLE
Group skeleton updateActions for proper versions

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1900]
I discussed the semantics of versions in skeleton updateActions with Norman and Daniel and we agreed on the following format. Versions must be increasing and unique and all actions belonging to one version MUST be in the same array in the same request.

```
[
  {
    version: 123,
    timestamp: 123456789,
    actions: [
      {
        name: "updateTracing",
        value: { ... }
      }, ...
    ]
  }, ...
]

```

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1900/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
I like that.
This is now the expected format as of [this commit](https://github.com/scalableminds/braingames-libs/commit/69053e62b45651c4e0d291407136b2802b2b230a)

**Comment by daniel-wer** [comment]
@jfrohnhofen I'm not sure how to proceed with this. Is there already a release containing the commit that @fm3 mentioned that I could use for development or should I implement the frontend changes without the new backend and we'll merge later?

**Comment by jfrohnhofen** [comment]
@daniel-wer The only branch I could offer you right now barely compiles and you will most certainly not be able to start a skeleton tracing there. So if you don't mind, implement this on a separate branch from master and we will merge later. Otherwise you can wait until we have the backend somewhat ready and just implement it on our branch then.

**Comment by daniel-wer** [comment]
No problem, the frontend changes are pretty clear, I'll develop on a separate branch, which you can then use to test :)

**Comment by daniel-wer** [comment]
Currently we're sending a request to `/annotations/${tracingType}/${tracingId}?version=${version + 1}`. I'm assuming the version as a get parameter is then no longer needed as the version numbers are contained in the data payload, correct?

**Comment by fm3** [comment]
that’s right, it’s now read only from the json body. (the exact route will change again at some point though)

**Comment by daniel-wer** [comment]
I just pushed the frontend changes on the `group-update-actions` branch. I repaired the tests and added a couple of new ones specifically for this change, but as I couldn't end-to-end test this, I'm not perfectly sure whether everything really works ^^ Please report back once you were able to test :)

**Comment by daniel-wer** [comment]
I would opt to leave this open as it is not merged yet, right?

**Comment by jfrohnhofen** [comment]
Sure. But is this issue referenced from some commit / PR so it can be auto closed?
