### ISSUE TITLE
Validate dataSource name before upload

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1901]
When uploading datasets, the validity of the upload (e.g. whether the chosen name is taken / valid) only take place after the potentially large upload is completed. Instead, wK should issues a token validating an upload. When a user requests such a token, the suggested dataset name is validated and then reserved, so that uploads can no longer fail (given a valid token is supplied).

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1901/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
I'm not sure if the token and reservation is necessary. But a simple frontend check would be great.
