### ISSUE TITLE
Use `api/queries` route to validate task ids

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1913]
As of now, when merging, `taskIDs` are validated using the `api/find` route handled by the `SeachController`. However, the `QueryController` already provides a sufficient query api. To get rid of the `SeachController`, we need to the front-end to migrate to the `api/queries` api.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1913/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
If I read the frontend code correctly the `api/find` endpoint is actually used to verify explorative tracing ids.

My expert scala knowledge tells me, this is not going to work for the `QueryController`:

```scala
def handleQuery(`type`: String, query: JsObject, limit: Int, user: Option[User])(implicit ctx: DBAccessContext): Fox[JsValue] = `type` match {
    case "task" =>
      for{
        resultObjects <- TaskDAO.executeUserQuery(query, limit = limit)
        jsResult <- Fox.serialSequence(resultObjects)(t => Task.transformToJson(t, user))
      } yield JsArray(jsResult)
    case _ =>
      Logger.error("Invalid query type")
      Fox.failure("Invalid query type")
  }
```

:grinning:

**Comment by jfrohnhofen** [comment]
I removed the call to `api/find` entirely, since the merge takes care of validating the ID and returns an error in case of invalid IDs, that is already properly handles.
