### ISSUE TITLE
use "normal" authentication instead of basic-auth on dev server

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1919]
There are still problems with Basic-Auth on dev, which inhibit volume tracings. However, since we have data on dev that the lab wants password protected, how about disable Basic-Auth and disabling the auto-login for the scmboy user on dev. Are there any advantages of BasicAuth that we are overlooking?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1919/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
I think that's a good idea. Don't think there's a very good reason for basic auth over login. People could sign up, but wouldn't be activated, so, thats fine.
