### ISSUE TITLE
Add undo functionality

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#1925]
See https://discuss.webknossos.org/t/undo-user-actions/146

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1925/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@daniel-wer there is a related discussion: https://discuss.webknossos.org/t/undo-user-actions/146
