### ISSUE TITLE
Activate document validation in mongodb

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1929]
As of version 3.2 mongo supports document validation, that can be used to enforce a data schema on a per-collection basis. To increase the consistency of our data and reduce the risk of failed updates, I suggest activating validation step-by-step for all collections 

Next steps:
- [x] refine schemas with regex etc. where appropriate
- [ ] run schema validation on dump / copy of production database, to identify documents not matching the schema
- [ ] identify cross-collection constraints
- [ ] implement cross-collection constraint validation, that can run on the production DB and measure performance impact
- [ ] think about `validationAction` and `validationLevel`
- [x] identify strategy / protocol to handle schema changes and to validate existing data, since mongo only checks updates and inserts
- [ ] integrate schemas / constraint validation / validation of existing documents into production sysyem

<a  href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1929/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
oxalisone still runs on 2.6 xD

**Comment by jfrohnhofen** [comment]
Is updating a major obstacle? I think the validation alone would be worth it.
We would still need to think about how / where to store the schemas and how to apply / enforce them.

**Comment by normanrz** [comment]
I agree. I don't want to update on the current oxalisone just now. Seems to risky to me. When we move to a new server we'll of course use the latest mongo.

**Comment by jfrohnhofen** [comment]
Sure. This was more of a mid- to long-term idea.
