### ISSUE TITLE
Improve volume download format

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1931]
see https://discuss.webknossos.org/t/volume-tracing-download/170

things to add
- [ ] versions
- [ ] bounding boxes
- [ ] with or without underlying layer

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1931/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Will be solved in individual issues if needed.
