### ISSUE TITLE
Disable mongo evolutions for tests?

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1945]
mir ist vorhin mit @tom aufgefallen, dass beim Ausführen der Tests erst die Evolutions ausgeführt werden und dann die DB gedropped bzw. importiert wird. Das heißt, dass man 1) Tests nicht starten kann, wenn die Datenbank kaputt ist, weil die Evolutions fehlschlagen und 2) man trotz der vorhandenen Evolutions die Testdaten anpassen muss, weil die Evolutions vor dem Import laufen

Außerdem scheinen beim Testen nicht alle Evolutions applied zu werden und manche in der falschen Reihenfolge

Vielleicht wollen wir evolutions für die Tests einfach dekativieren?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1945/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@normanrz @tmbo any thoughts?

**Comment by normanrz** [comment]
Lets get rid of them, if they don't do anything after all. Or is it possible to run the evolutions after import?

**Comment by jfrohnhofen** [comment]
Since the script doing the import is started from SBT (which applies the evolutions before doing anything else), there is no way unless we change the way the tests are started (i.e. have another script, that first prepares the db and then calls `sbt test`)

**Comment by jfrohnhofen** [comment]
I created a PR in https://github.com/scalableminds/play-mongev/pull/11
