### ISSUE TITLE
Add tags to explorative tracing dashboard

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1971]
- [x] Add tags to annotations
- [x] Clicking on tags lists them above the tracing list for reference / deselection and filters the list
- [x] Selecting multiple tags (could) filters them using an "AND" semantic
- [x] Persist selected tags across sessions in local storage
- [x] Consider using tracing type (skeleton/volume) and/or dataset name as (automatic) tags
- [x] Perhaps show last modified date instead of creation date
- [x] (Consider adding the search terms as temporary tags so that search terms persist)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1971/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
My objection from the other issue:

> (Consider adding the search terms as temporary tags so that search terms persist)

> This is the only thing I'm hesitant to agree with. Filtering Tags should only show tracings which have the desired tag attributes. Search terms on the other hand search through all (or some) properties of tracings. Displaying them as tags would mix two different filter mechanisms.

But maybe I'm getting it wrong? I don't understand the purpose in the first place. If you want to persist the search, you could just persist the string in the search box?

**Comment by hotzenklotz** [comment]
@jfrohnhofen I just add server side saving for the tags. It works fine with one little quirk. Naively, I send all the tags belonging to the annotation including the default "dataSetName" and "contentType". The next time I call the API those default tabs will be added to the tags again , creating duplicates. 
Either the client filters these or the server. Any preference?

**Comment by hotzenklotz** [comment]
@philippotto I am not sure we understand each other correctly. Please take a look at the `dashboard-tags`. All features are implemented and may need some finetuning. I would like to hear your opinion on the tag system. Thanks.

**Comment by jfrohnhofen** [comment]
@tom tags are now stored / delived as sets (instead of lists), which should take care of the duplicates on the server. However, I could not test whether that works, because when I added tags, those did not get saved to the server (no request was made).

Another minor thing: I think it would be nice that, when you click the plus sign, the appearing input would automatically be focused, to save the user an additional click. Same for renaming tracings in the dashboard

**Comment by hotzenklotz** [comment]
@jfrohnhofen Ups. Forgot to push.  *blush* Anyway, the sets work like a charm. Good idea to use those.
