### ISSUE TITLE
Route /api/scripts requires admin privileges 

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1980]
Every regular "user" gets a warning toast when opening a tracing: "You are not allowed to view this resource". This is cause by a request to `/api/scripts` from the "Add Script" modal.

![image](https://user-images.githubusercontent.com/1105056/29413148-ac45573a-835b-11e7-8099-66156b3df36c.png)

Either, make this route public/non-admin or find a different solution. 
@fm3 @daniel-wer Can you please take a look / discuss. 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1980/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
In order for this feature to work, getting a list of user scripts from `/api/scripts` is essential. I would vote to add read permissions for non-admins on this route, it's not security critical, write permissions should remain admin-only. Do you agree @fm3 @jfrohnhofen ?
