### ISSUE TITLE
Increase task-assignment performance

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1987]
instead of creating an `OpenAssignment` instance for each possible task instance, we should only have a single instance with an integer representing the number of open instances left.
This integer could also be part of each `Task` - making OpenAssignments obsolete altogether, but I am not sure how well that integrates with the mturk task handling.

follow up to: https://discuss.webknossos.org/t/finish-and-get-a-new-task-does-not-work/430/11

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1987/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
@tmbo Do you know why we switched from a counter to `OpenAssignment` instances?

**Comment by tmbo** [comment]
Mhm, I don't remember the precise reason. But I think it was related to duplicate assignments and race conditions (due to the flight mode and short tracing this became an issue) - I am not sure though why it didn't work with a counter anymore.

https://github.com/scalableminds/webknossos/issues/1117

Do you know why the performance is bad (maybe there is an index missing / not optimal)?

**Comment by normanrz** [comment]
Haha. An ACID-compliant database would come in handy here.

@jfrohnhofen found that the query `db.getCollection('openAssignments').find({"$and":[{"priority":{"$gte":0},"$or":[{"neededExperience.domain":"hotswap_training","neededExperience.value":{"$lte":1}},{"neededExperience.domain":"focus_flight","neededExperience.value":{"$lte":1}},{"neededExperience.domain":"","neededExperience.value":0}]},{"team":{"$in":["Connectomics department","Tracing crew"]}}]})` yields ~20k results. For each of these open assignments a query is triggered to test whether the current user has already worked on this task (until a new one is found, i guess). This potentially takes forever.

**Comment by jfrohnhofen** [comment]
Independent of whether we have ACID or not, we are currently relying on the WriteResult to check whether the `OpenAssignment` was actually deleted. I think making the same check on an update, that decrements the counter should work equally well?

**Comment by tmbo** [comment]
As Norman suggested, I do not think the performance is due to a separate object, it is due to the excessive amount of elements that get checked before a viable task is found. Therefore, I don't see how this is solved by using a counter.

**Comment by jfrohnhofen** [comment]
Yes, but that "excessive amount of elements that get checked" results from checking each possible task instance instead of checking each task. Right know there are 200 tasks with 100 instances each, which results in 20k checks vs 200 checks.

**Comment by jfrohnhofen** [comment]
MongoDB guarantees atomicity for update operators such as `$set`, `$push` etc. So we should not have any trouble with race conditions, if we run a query a la `db.update({openInstances: {$gt: 0}}, {openInstances: {$inc: -1}})` and check the `WriteResult` from mongo
