### ISSUE TITLE
Error message on public tracings

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1997]
Open in incognito browser: https://demo.webknossos.org/annotations/Explorational/599ad6f66c000070000ea174/readOnly#769,547,353,0,2.00,1
Error message: `You are not allowed to view this resource`

I suppose this is due to requests to `/api/scripts` or `/api/taskTypes`.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1997/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
I had a look and yes there are requests to `api/user`, `api/scripts` and `api/taskTypes` that return status code 403 - Forbidden. I'll make sure this error message won't show up.

But as I was looking at this public tracing I saw that there are also buttons like `Copy to my account`, `Merge Tracing` or the `Share` modal itself available. Currently executing an action there, redirects to the login with the correct redirect url. Should those buttons and modals remain accessible or should they be hidden?

**Comment by daniel-wer** [comment]
Renaming the tracing also fails with an alert error message in public tracings.

**Comment by kevinbbb87** [comment]
@daniel-wer 
I think Copy to my account does the right thing, Merge Tracing shouldn't exist and Share should work without logging in (without the tick box)
Would that be feasible?

**Comment by daniel-wer** [comment]
@jfrohnhofen Currently `restrictions.allowFinish` is `true` for public tracings that are accessed without being logged in, would it be possible for the server to set that to `false` for non-logged-in users?
