### ISSUE TITLE
VolumeTracing Saving broken for one dataset

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2022]
### Problem
For the `PL_st115_MT3` saving is flaky. In some regions of the dataset it works in others the save request fails. The failing requests return HTTP error 500 and a hint that the `CORs` header is not set.

### Observations
- Other volume datasets on the RZG server work fine. (e.g. PL_st115_MT2)
- @jfrohnhofen attached a debugger and the update request never actually reached the wK server but was blocked by Nginx instead 

### Steps to Reproduce
1. Open a volume tracing of the dataset PL_st115_MT3
2. Navigate to an area with existing segmentation
3. Try to save it/wait until autosave is triggered

### Possbile Solution
- Check Nginx logs / configuration why some requests are blocked

https://discuss.webknossos.org/t/save-volume-tracing/457

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2022/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
Are those requests for the datastore in garching or for webknossos?

**Comment by hotzenklotz** [comment]
In this case garching. We double checked: the mount was working and the dataset present.

**Comment by hotzenklotz** [comment]
@normanrz Can this be closed? Did you fix the "out of hard disk space" problem?
