### ISSUE TITLE
Allow creation of volume tracings without underlying segmentation

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2033]
see https://discuss.webknossos.org/t/volume-tracing-not-really-possible-with-segmentation/466/10

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2033/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@daniel-wer @philippotto we need some frontend support for this. Essentially, on volume tracing creation, the client has to ask the user, what he actually wants and then add a post parameter to the request. This parameter could either be a `bool` (use underlying segmentation?) or `string?` (which layer to use as fallback or none). The second approach is more general, in case we ever have multiple segmentation layers for one dataset.
I am also not sure, how/if the client can handle multiple segmentation layers. If the dataset already has a segmentation layer, and the user decides to create a fresh layer for the tracing, the resulting dataset for the tracing will have two segmentation layers. I think that is not yet properly handled.

**Comment by jfrohnhofen** [comment]
There is now a branch `optional-fallback`, that will (for now) always create a new volume tracing layer. As expected, the client is not able to handle this properly.

**Comment by hotzenklotz** [comment]
@philippotto @jfrohnhofen What's the status here? It looks like all the parts are in place and this could be merged?
