### ISSUE TITLE
Add "comment" field to tracings

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2041]
Users want to add comments about the experiment + settings that resulted in a particular tracing.

- [x] The tracing interface should have a free text comment field. 
- [x] A downloaded NML version should contain that comment as well.
- [x] NML import should read the comment field.
- [x] Uploading multiple NMLs will likely merge the comments(?)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2041/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@hotzenklotz Backend implementation is finished on `nml-description`. The info-JSON contains a new `description` field, that contains the current description of the annotation. The client can update the description in the same way `names`, `tags` and `isPublic` are updated.
