### ISSUE TITLE
Store user bounding boxes for explorative tracings

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2043]
Users want the their manually set bounding boxes to persist between sessions. The "user bounding box" can be set from the settings menu on the left. (see picture)

![image](https://user-images.githubusercontent.com/1105056/30734624-4c927524-9f7c-11e7-8649-4f9cf6304be5.png)

Either save on the server (or maybe local storage?).

https://discuss.webknossos.org/t/storing-a-bounding-box-with-a-tracing/284

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2043/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
I created a branch userBoundingBox, branching from braveNewWorldSkeletons.
there the backend stores an optional userBoundingBox in each tracing (in the protocol buffer data on the datastore). It is also serialized as json with the tracing, and it can be updated with the updateTracing update actions.
It is also serialized to and parsed from NML files.
The frontend changes to use and update this field are still open
