### ISSUE TITLE
Webknossos tells you there are no tasks available even there are

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2046]
see here: https://discuss.webknossos.org/t/webknossos-tells-you-there-are-no-tasks-available-even-there-are/479

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2046/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
Closed via #2060

**Comment by fm3** [comment]
should we possibly keep this open until we are sure that the PR 2060 fixes this? (by watching the logfiles for a couple of days)

**Comment by jfrohnhofen** [comment]
How log do you think we will need to wait? It is hard to prove a negative, after all.

**Comment by fm3** [comment]
While debugging I looked at the logfiles of three consecutive days (selected to match four user reports), and they actually contained 150 instances of the error. So I think if it’s now clean for three days we should be fairly safe
