### ISSUE TITLE
Use user-tokens from silhouette for dataStore authentication

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2057]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2057/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
The silhouette user tokens have a very long lifetime (unless revoked in the UI). The tokens we currently use for dataStore authentication live only one day. Do you think that is problem?

If we use the silhouette token for both, even users who don’t explicitly use the Auth Token from the wk menu have to be careful not to let their token be stolen

**Comment by jfrohnhofen** [comment]
Can we have multiple tokens per user with silhouette? Then we could have the same token mechanism, but different lifetimes. Alternatively we could use the user token, if it exists and create a short lifetime token otherwise, if that does not introduce too much additional complexity.

**Comment by rschwanhold** [comment]
Currently we only allow obe token per user. But if we can get rid of the UserToken class this way, maybe that would be a reason to chabge that.

**Comment by hotzenklotz** [comment]
@fm3 Is this issue still relevant or have you already worked on this integration.

**Comment by fm3** [comment]
Still alive, but I tend to think it has a relatively low priority…?

**Comment by hotzenklotz** [comment]
@fm3 Not very important. Just checking if this is still avilable for @rschwanhold.
