### ISSUE TITLE
downloading large volume tracings via API does not work

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2064]
https://discuss.webknossos.org/t/volume-tracing-download-through-api-error-for-larger-bboxes/521

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2064/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
This was resolved by using paginated requests to fossildb, see PR #2379 in WK and [PR 15 in FossilDB](https://github.com/scalableminds/fossildb/pull/15). Related issue is #2345. On top of that, PR #2380 will slightly optimize the memory usage.
The download is still suspiciously slow, though.
