### ISSUE TITLE
Get rid of mongo evolution plugin / load testing database on dev servers

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2072]
The mongev plugin is currently neither used for production systems (since evolutions are applied by hand there) nor the testing environment (data is loaded from JSON files for the tests). The only current use-case for the plugin is local development (switching branches etc.), where IMO the plugin does more harm than good. Does anybody really use this feature? I tend to drop my DB when switching branches / stuff seems broken due to missing evolutions.

Another thing: We currently add very little initial data to the DB from `Global.scala`, but have much richer data available from the testing database. What do you think about automatically loading this data for dev deployments and getting rid of the Scala code?

@normanrz @tomh @daniel-wer @philippotto @jstriebel @fm3 @youri-k @rschwanhold 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2072/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Sound good to me.

**Comment by normanrz** [comment]
Makes sense. How would this work on dev servers?

**Comment by jfrohnhofen** [comment]
do you / can ypu run a script on each deployment? I would basically reuse the script that drops and loads the db before the e2e tests.

**Comment by normanrz** [comment]
@jstriebel ^

**Comment by jstriebel** [comment]
For the dev-server deployment we can include that in the current setup as well as in the future kubernetes setup.
