### ISSUE TITLE
Investigate UsedAnnotations and whether we need them

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2098]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2098/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
Our code does not depend on the UsedAnnotations, it only keeps them updated. However, other scripts accessing our DB might need them.
Compare https://discuss.webknossos.org/t/scripts-for-hiwi-administration/607
