### ISSUE TITLE
Copy To My Account for Volumes

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2123]
…should be supported by the datastore

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2123/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
…or remove the button?

**Comment by hotzenklotz** [comment]
I removed the "copy to my account" button for volume tracing for now. Yet, we might still consider adding the this feature to the data-store.
