### ISSUE TITLE
Add touch controls to 3D View

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2137]
Users want to select node in the 3D view when using mobile devices / iPads. 

### Use Case
1. Click on a "interesting" node in the 3D view to select it
2. The other viewport sync to this position
3. Show off the cool data at that coordinate 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2137/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
As part of this issue I'll also make sure that it's possible to rotate the 3D view on mobile devices :)
