### ISSUE TITLE
Move braingames-libs to webknossos repo

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2153]
and update `Build.scala` to `build.sbt` in the process.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2153/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
do you have experience moving stuff across repos? something like http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/ ?
