### ISSUE TITLE
Fix incorrect bounding box for some tasks

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2165]
The task bounding boxes got messed up for some tasks. Perhaps we can directly fix these in the MongoDB. (e.g. by removing the bounding box entirely from the affected annotations)

See https://discuss.webknossos.org/t/dataset-remain-black/582/3

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2165/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@youri-k Please double check with @normanrz which steps he has already undertaken to fix the above issue.

**Comment by fm3** [comment]
The Tasks in MongoDB were already fixed by norman. The problem persists because the BoundingBox is also stored with the tracings in the RocksDB.
To repair them, we either have to write a script that accesses the RocksDB (means downtime for the datastores) or wait for FossilDB to be deployed.
