### ISSUE TITLE
unify userTokens, tokens (and maybe even bearerTokenAuthenticators?)

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2185]
It doesn’t seem right that we need three kinds of tokens.
Current situation:
```

Case Class                Collection                 Usage                Associated Classes

UserToken                 userTokens                 DataStore auth       object UserTokenService, UserTokenDAO
UserToken2                tokens                     Password-Reset       class UserTokenService, MongoUserTokenDao
BearerTokenAuthenticator  bearerTokenAuthenticators  X-Auth-Token         BearerTokenAuthenticatorDAO
```
UserToken and UserToken2 seem easily mergeable.
I’m not sure if the bearerTokenAuthenticator can maybe even replace both?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2185/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@rschwanhold [`UserToken2.createLoginToken`](https://github.com/scalableminds/webknossos/blob/master/app/models/user/UserToken.scala#L70) seems to be never used to me, is that right? also `isLogin`? I assume this was replaced by the `bearerTokenAuthenticators`?

**Comment by rschwanhold** [comment]
Yes this is indeed replaced by bearerToken.
