### ISSUE TITLE
Add Snapshot Tests for REST API

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2190]
We should snapshot all routes of the REST API.  A good place to start would be [here](https://github.com/scalableminds/webknossos/blob/master/app/assets/javascripts/admin/admin_rest_api.js)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2190/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
- Added tests for most REST endpoints in PR  #2309
- Still open:
  - [ ] Tests for Annotations API
  - [ ] Tests for Tasks API

**Comment by philippotto** [comment]
- [ ] In order to be able to test all endpoints for annotations/tasks, we need to run the datastore for the testing environment

**Comment by daniel-wer** [comment]
@jstriebel Would it be hard to run the datastore when executing `docker-compose up e2e-tests`. This would allow us to test the backend api more thoroughly and I'm also blocked by this while trying to e2e-test the actual tracing view :)

**Comment by jstriebel** [comment]
Please disregard my previous comment, my information was already outdated, sorry^^ Let me know when I can help, I think having the datastore in the e2e tests would be great :rocket:

**Comment by hotzenklotz** [comment]
@philippotto This can be closed, right? We have added more E2E tests in the meantime.

**Comment by philippotto** [comment]
True!
