### ISSUE TITLE
Tool selection is misaligned in volume mode

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2192]
<img width="607" alt="screen shot 2017-11-30 at 12 58 59 pm" src="https://user-images.githubusercontent.com/1701977/33429742-59718ab8-d5ce-11e7-83ef-ef0c71b4920a.png">

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2192/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Thanks. We did some CSS cleanup and alignment for the tool bar in PR https://github.com/scalableminds/webknossos/pull/2188. Hopefully that should fix it.

**Comment by hotzenklotz** [comment]
Fix on master.
