### ISSUE TITLE
Improve tree visibility toggles

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2206]
The keyboard shortcuts "1" and "2" both toggle the visibility of tree in different ways. The behaviour should be finetuned a bit more to increase usablilty.

For details see: https://discuss.webknossos.org/t/toggle-skeleton-visibility-is-broken/630

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2206/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
Closing this since this seems to be not important anymore.
