### ISSUE TITLE
Check dynamic segmentation mapping for high zoom steps

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2212]
According to this [discuss post](https://discuss.webknossos.org/t/segments-merger-mode-do-not-change-colour-with-right-mouse-click/618), there could be an issue with dynamic segmentation mappings for higher zoom steps. We should check up on that and verify that segmentation mapping works in all zoom steps.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2212/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
I think we can close this, @daniel-wer, right? The discuss post went stale, as it could not be reproduced.

**Comment by philippotto** [comment]
I'll close it; re-open if you disagree @daniel-wer :)
