### ISSUE TITLE
Login / Logout for discuss.webknossos.org is buggy

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2224]
While login to discuss.webknossos.org works in general, there are some usability issues:

- [ ] One can not log out from discuss itself. You have to logout from wK and then be auto logged off from discuss as well.
- [x] When logged out, navigating to discuss.webknossos.org shows you the `401` error message. There is no way / redirect to login.

Perhaps, we can find a way around these issues within the new Silhouette framework.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2224/create?referer=github" target="_blank">Log Time</a>

**Comment by rschwanhold** [comment]
Did I get it right that only the second point is important right now (because the first one would be to much effort)?
If so, then I would create a PR for it.

**Comment by hotzenklotz** [comment]
@rschwanhold Yes, you are absolutely correct.
