### ISSUE TITLE
Add Metadata Header to NMLs

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2234]
I was wondering whether we should introduce a metadata field in the NML header to include such things such as creation date and creation software etc. Such information is very common in other file formats, e.g. JPEGs generated by Photoshop.

I propose this change given that we now have several ways of exporting NML files in wK: From the Backend and Frontend. 

This should be very easy to integrate, yet provide valuable insights when debugging invalid / inconsistent NMLs.

@fm3 @daniel-wer @jfrohnhofen @normanrz @amotta What do you think?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2234/create?referer=github" target="_blank">Log Time</a>

**Comment by amotta** [comment]
Did you have specific data elements in mind other than the NML writer and its version? The webKNOSSOS version would definitively be useful.

Not sure if this is the kind of meta data that you were thinking about, but it would also be useful to have access to
* the project ID + name
* the task ID
* the webKNOSSOS username

The latter two are currently parsed from the file name, if needed.

**Comment by hotzenklotz** [comment]
I am sure we can thing of several headers fields. Date and Software name were the first that came to my mind.

Project + task information is neither available for explorative annotations nor for NMLs generated from matlab. Usernames could be useful.

**Comment by amotta** [comment]
> Project + task information is neither available for explorative annotations nor for NMLs generated from matlab.
Is this a reason not to add them if available?

**Comment by daniel-wer** [comment]
@hotzenklotz Did you agree on the kind of meta data that should be added?

- NML writer (js or scala) and version (webknossos commit hash?)
- current datetime

These two would be fairly general:
- annotation id?
- username?

These two would be specific to tasks, but could of course be added:
- project id (when downloading all nmls of a project)?
- task id?

**Comment by hotzenklotz** [comment]
@daniel-wer All of the above sound good. If "task specific" is to hard, then skip that.

**Comment by daniel-wer** [comment]
@rschwanhold I've added this to our frontend serializer, branch is `nml-meta`. I've oriented myself on the HTML meta tag, see https://www.w3schools.com/tags/tag_meta.asp

Example Nml:
```xml
`<things>
  <meta name="software" content="nml_helpers.js - fc0ea6432ec7107e8f9b5b308ee0e90eae0e7b17" />
  <meta name="timestamp" content="123456789" />
  <meta name="annotationId" content="5a5f6110410000ad00bf208f" />
  <meta name="username" content="SCM Boy" />
  <meta name="taskId" content="5a5f63474100001201bf2097" />
  <parameters>
   ...
```
The software is the filename of the serializer and the current webknossos commit hash.
The timestamp is a Unix timestamp in ms.
Not included in the example is `<meta name="projectId" content="someProjectId" />`.
The other tags should be self explanatory.
The meta values are ignored during nml import.

Open for comments and remarks :)

**Comment by hotzenklotz** [comment]
Looks good. I wonder whether the git commit should be its own meta tag?

**Comment by daniel-wer** [comment]
Sure, let's make it `meta name="version" content="fc0ea6432ec7107e8f9b5b308ee0e90eae0e7b17" />.

**Comment by fm3** [comment]
maybe "version" is confusing (it’s not the nml-version or the version of this file). maybe softwareVersion (or how about generator and generatorVersion? I’ve seen that in html

**Comment by amotta** [comment]
What about putting the `meta` elements into a `head`? This seems nicer than putting it into `things`.

It's possible that the NML format will change in the future (e.g., finally giving `things` a clearer name, such as `tracings`). In this case it would be important to have a `nmlVersion` field in a file part that is decoupled from the actual payload.

**Comment by daniel-wer** [comment]
Iirc xml only allows a single top level element, so in that case we would need a new top level element.

**Comment by hotzenklotz** [comment]
<meta name="git-commit"> or "git-hash"?

**Comment by amotta** [comment]
@daniel-wer True, I forgot about that.
@hotzenklotz `git-commit` and `git-hash` seem too generic. (Maybe we'll do versioned skeletons with git in the future.) `writerVersion`, `writerGitCommit`, or `writerGitHash` would be clearer.

**Comment by daniel-wer** [comment]
@rschwanhold I split up the `software` meta tag into `writer` and `writerGitCommit`, see: 

```xml
<meta name="writer" content="nml_helpers.js" />␊
<meta name="writerGitCommit" content="fc0ea6432ec7107e8f9b5b308ee0e90eae0e7b17" />
```
