### ISSUE TITLE
UploadAnnotation in dashboard bug

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2240]
Two things I noticed:
1) when I don't select a file, but press cancel, a request is still send to the server
2) after an unsuccessful upload (due to broken NML), uploading another NML does not work, but a reload is required

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2240/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
The second point is already being addressed as part of #2106. I believe @daniel-wer already fix this last night.

As for the first point, we might have to investigate again.

**Comment by daniel-wer** [comment]
@jfrohnhofen (2.) is fixed, I cannot reproduce (1.), can you still repro?

**Comment by jfrohnhofen** [comment]
@daniel-wer cant reproduce 1 either

**Comment by hotzenklotz** [comment]
Perhaps 1) was fixed when we updated to Antd v3.
