### ISSUE TITLE
Consolidate annotation states

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2283]
Seems like we are only using 3 of the 4 states in code. Maybe we should consolidate:

`Unassigned` -> `Cancelled`
`Assigned` -> `Active`
`InProgress` -> `Active`
`Finished` -> `Finished`

@rschwanhold Did you find any uses of `Assigned` in the code?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2283/create?referer=github" target="_blank">Log Time</a>

**Comment by rschwanhold** [comment]
Thats correct, I didn't find any other usage in the code. I already talked with @fm3 about it and he also would like to combine `Assigned` and `InProgress`
