### ISSUE TITLE
Enable independent axis scaling for anisotropic datasets

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2295]
In order to support anisotropic datasets wK needs to support different scaling factor along all three axis. For more details see: https://discuss.webknossos.org/t/anisotropic-datasets-and-downsampling/604

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2295/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@daniel-wer sitzt du da jetzt dran? der backend-teil ist im PR #2308 zumindest so weit, dass sich das interface für das frontend nicht mehr ändern sollte

**Comment by daniel-wer** [comment]
Nice, let's talk about it tomorrow then :)
