### ISSUE TITLE
Remove defaults for config parameters in code

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2326]
To see what could be configured and what are the defaults _easily_, we should have all config options with their defaults in the `application.conf`. To ensure this, we can simply remove the defaults in the code and fail if something is not set.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2326/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
for future reference, things to consider here:
- removing getOrElse in scala code leads to exceptions if cofig key is not present
- test coverage is likely not high enough to guarantee that those problems are discovered in tests
- idea: central object (per subproject) containing all config keys, in code, only read from there
- problem with that: redundancy, no mechanism to enforce that raw config is never used, is this thing injected? is it constructed at startup? different for subprojects?

**Comment by jfrohnhofen** [comment]
I agree with @fm3 in that removing the defaults can lead to unnecessary runtime crashes and would like to avoid this. do we have an automatic way of extracting access to the config? so we can check, that all keys used are actually defined?
i don't really see how Flo's idea solved the central problem. imo it only defers the problem from the config file to some place in the code.
maybe we can agree on having all keys in the config and having the getOrElse only as a last resort. We could also log an error message whenever we need to fallback on a config??

**Comment by jstriebel** [comment]
I think that having fallback values in the code easily leads to an inconsistent `application.conf`. Not having them should fail much earlier, e.g. by some tests in the CI. The central object florian proposes could make sure that the application fails directly during __startup__, as all necessary config options are captured there and loaded at startup. Therefore the CI (and also local development) would fail, if something is missing.

I think only showing error messages are currently something we easily oversee, as there are many of them.

**Comment by jfrohnhofen** [comment]
I am not sure, why you think `application.conf` will become inconsistent, while the global object will not.

**Comment by jfrohnhofen** [comment]
I don't have a strong opinion about this. I just don't see any benefit in changing what we have right now, only the (slightly increased) change of unnecessary runtime errors

**Comment by jstriebel** [comment]
Because you could enforce the correct usage by using members. This covers this case:
* application.conf: `my-special.key = 10`
* in code: `config("my-special-key").getOrElse(100)`
(This actually was/is the case already.)

With a scala-object, having members:
* application.conf: `my-special.key = 10`
* config-object: member `my-special-key` (Populating this will fail on startup)
* in code: `config.my-special-key`

or:
* application.conf: `my-special.key = 10`
* config-object: member `my-special.key`
* in code: `config.my-special-key` (Will fail during compilation, as member does not exist)

I'm seeing the application.conf as the operational API of wk, so having typos there is a problem and currently very hard to track. But this surely should not be of high priority.
