### ISSUE TITLE
Authentication snapshot testing

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2340]
The snapshot tests in #2190 only test for successful requests. However, it doesn't test the authentication system where users may be unauthorized to perform tasks.

These tests could either be implemented using snapshot tests or validating HTTP status codes.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2340/create?referer=github" target="_blank">Log Time</a>

**Comment by rschwanhold** [comment]
@normanrz is this still relevant or was it solved with #2395 ?

**Comment by normanrz** [comment]
Yep, was solved. #2500 remains, tho
