### ISSUE TITLE
Non-admins can access user list

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2346]
Calling `/api/users` as a non-admin users doesn't filter out any users (or fields). I would have guessed that only the user itself is accessible. Or is there a place where we need to know all users?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2346/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
Currently you see all users that share a team with you
(plus all that have no teams at all, but that shouldn’t happen).

What is the desired behavior?

**Comment by fm3** [comment]
for reference: discussed that this is ok for the present
