### ISSUE TITLE
test datastore/fossildb connection in CI

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2359]
We should test that the datastore is fully accessible, including fossildb.
One approach could be to add another health endpoint, that checks for fossildb. We could curl this endpoint in our smoke-tests.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2359/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
resolved via #2637
