### ISSUE TITLE
Passthrough feature flags to frontend

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2367]
Sometimes we want to enable features for different instances of webKnossos. These could easily be specified in the corresponding `application.conf`. However, these values are not accessible by the frontend.
It would be great if a dedicated `features` (or other specifier) section of the `application.conf` could be exposed to the frontend.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2367/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
Backend part resolved in issue #2368 and the corresponding PR #2369
