### ISSUE TITLE
Hybrid tracings: Add annotations to volume tracings

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2383]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2383/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
https://discuss.webknossos.org/t/hybrid-skeleton-and-volume-tracings/715

**Comment by philippotto** [comment]
We should agree on a format which is used when requesting and saving such tracings.

**Comment by daniel-wer** [comment]
If I remember correctly, the only thing left here is to enable the feature.
@normanrz Currently this is hidden behind a feature flag (`hybridTracings`) and can be configured per instance. Should we enable this for one lab first or should I remove the feature flag and enable it globally?

**Comment by normanrz** [comment]
yep, sounds good :+1: we can configure the instances tmrw

**Comment by fm3** [comment]
closed through #2984 #2985 #3025 #3040 and #3090 – for now marked as »experimental« feature until further feedback is gathered
