### ISSUE TITLE
dataset upload truncates layer directory if there is only one layer

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2408]
in `DataSourceService`/`handleUpload`, unzip is called with `truncateCommonPrefix = true`, which creates invalid dataset directory structure if there is just one layer (making the layer directory a part of the common prefix).

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2408/create?referer=github" target="_blank">Log Time</a>

**Comment by youri-k** [comment]
first idea is to check if the commonPrefix contains a layer category and strip that part of the path
