### ISSUE TITLE
Sort layer resolutions when delivering it to the front-end

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2423]
Resolutions should be sorted (numerically) when requesting the corresponding layer information.

![image](https://user-images.githubusercontent.com/2486553/37466645-939a3c20-285e-11e8-9afc-727ab9d7f391.png)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2423/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@philippotto I pushed the branch `sort-resolutions-backend` – could you try if this solves the issue for you? I’m not sure since I could not reproduce it in the first place, but I think it should do the trick.
