### ISSUE TITLE
Sbt runs out of Metaspace memory when run in dev mode

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2432]
After a while, sbt runs out of memory. The error message is:

`java.lang.OutOfMemoryError: Metaspace`

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2432/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
likely caused by slick / postgres connections not properly recycled on sbt/play hot reloading.

**Comment by fm3** [comment]
workaround for frontend people seems to be ./clean – after that, changes in js files don’t trigger recompiles

**Comment by fm3** [comment]
@philippotto are you still experiencing this? Did not come up for me again in at least a month

**Comment by philippotto** [comment]
I'm getting this very rarely (maybe once a week) and it's usually only after switching branches. So, I think we can close this :tada:

**Comment by fm3** [comment]
came up again with sbt 1.2

**Comment by fm3** [comment]
As part of 3344 I added the argument `-J-XX:MaxMetaspaceSize=2048m` to the sbt call in `yarn start` as this reportedly helps. Let’s monitor if this really works and/or has unwanted other effects.
