### ISSUE TITLE
datasource-properties.json seems to be ignored upon upload

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2433]
If you upload a dataset with an existing `datasource-properties.json` as a zipfile with the upload feature, the metadata seems to be ignored and the parameters are guessed.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2433/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
what is the desired behavior here? when I try this, the scale from datasource-properties is used.

after the upload, the import/edit dialog comes up, which indeed runs the resolution guessing (but uses the supplied scale, for example). You don’t have to use this dialog though, if there exists a datasource-properties.json. directly navigating to the dashboard shows the dataset as imported.

**Comment by normanrz** [comment]
The guessing shouldn't overwrite any predefined resolutions or bounding boxes. Basically, if a valid datasource-properties.json is supplied, it should be used unchanged.

**Comment by fm3** [comment]
Works for me both with ROI2017_wkw and e2006_knossos

**Comment by fm3** [comment]
@normanrz The `datasource-properties.json` with which this problem occured, had an invalid format (no `cubeLength` for `wkwResolutions`). This caused the datastore to discard the supplied json (import failed), and the then upcoming import dialogue uses a new “guessed” one.
webKnossos should report that more clearly in the uploading process. We should discuss how that should look.

**Comment by fm3** [comment]
I notice that after the upload, a GET request on `api/datasets/:name` is already sent and answered with the detail `Error: Invalid json format in …` – so I would suggest showing this information on the then-shown import page. what do you think @normanrz @hotzenklotz ?
