### ISSUE TITLE
finishing tasks from scripts randomly fails

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2448]
https://discuss.webknossos.org/t/tasks-accumulated-in-user-account/806

…and it also still requests a new task

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2448/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
…probably caused by the frontend API finishAndGetNextTask being called multiple times.

**Comment by hotzenklotz** [comment]
Triggering "Finish" twice can lead to problems. The old tracing is finished, but not yet replaced in the tracing view. (still loading) At the some time, the second triggering tries to finish the already finished (aka "old") annotation, again --> Fail.

Proposed solutions:
1. Add a "semaphore" to frontend API. One should only be able to "finish" as long as no task is being loaded.
2. Make sure that the backend handles task assignment as one transaction. Tracing lookup, finish and task creation should work like an atomic operation. If one or the other fails, the other steps should fail / abort as well.

**Comment by fm3** [comment]
I agree that this is likely the cause of the problems.

I can add a route to the backend that handles both finishing and new task assignment. However, it is at this point non-trivial to have those steps be truly atomic in the backend.
Also, if this route is called twice (and say the second fails, because the annotation is already finshed), will the error on the second one not lead to problems in the frontend navigation as well?

I would as a first step suggest to change the frontend api implementation so that a failed finishing operation will abort the finishAndGetNextTask method, so that the requestTask is not called in that case.

Note that amotta’s script uses the old api version 2, so his script will need to be adapted if we change the newer version.
