### ISSUE TITLE
Long searches for Tasks fail

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2449]
Search for task by tasktype kann cause the server to crash / respond with http code `500`

## How To Reproduce:
1. Go to https://webknossos.brain.mpg.de/tasks
2. Search for task type `synapse_boutonTracing`
3. Click Search and wait for error

![image](https://user-images.githubusercontent.com/1105056/38304671-7d33b554-380a-11e8-96b4-441a717a65f0.png)

Exception ID `77fga52mm`

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2449/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
Yep, too many queued postgres queries. I’ll see how well we can replace this by complex queries.
What we can also do, of course, is to further increase postgres queueSize, see https://github.com/scalableminds/webknossos/blob/master/conf/application.conf#L139

or does it make sense to introduce a limit? Maybe loading so many tasks isn’t really required?
