### ISSUE TITLE
Turn model initialization into saga

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2452]
The singleton model now contains a lot of initialization code that could be put into a saga. Most of that code is untested.

A saga would make it easier to test and could reveal the timing dependencies more clearly.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2452/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
The initialization code is already in a separate module. I don't see a big benefit in converting it to a saga right now. Closing for now.
