### ISSUE TITLE
Splitting/merging trees with cycles doesn't work as expected

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2504]
See https://discuss.webknossos.org/t/upload-of-nml-created-by-merging-trees-not-possible/837/6

Probably backend, because the missing edges only show up after page reload.

**Comment by daniel-wer** [comment]
@fm3 two things I noticed:
The nml contains edges with the same source and target id (e.g. 644 to 644).
The nml contains duplicate edges (e.g. 1 to 2).

Both of these types of issues should be flagged by the backend when uploading the nml (in fact if you import the nml through "Import NML" in the frontend, errors are shown and the nml is not imported).
I would suggest fixing these checks in the backend (or adding them) - the splitting should then work fine using the cleaned nml :)
