### ISSUE TITLE
Update dataset configuration: transaction management

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2509]
either retry or find another way to properly serialize this.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2509/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
#2511 implements retry, which will for now probably fix the error, but does not really look like a final solution

**Comment by fm3** [comment]
@daniel-wer I noticed that the frontend posts the new dataset configuration every time a slider is moved (meaning before mouseup), resulting in very many queries in short succession. Is there a way this could be throttled in the frontend?

**Comment by daniel-wer** [comment]
That should be possible, I'll have a look at it @fm3 :)

**Comment by daniel-wer** [comment]
@fm3 I just had a look, the server requests for the update of user/dataset/layer settings are already throttled (https://github.com/redux-saga/redux-saga/blob/master/docs/recipes/README.md#throttling). The current value is 500ms - I could change it to 2000ms or another more appropriate value, what do you think?
Do you already have a branch for this issue?

**Comment by fm3** [comment]
Thanks for taking a look! 500ms should be ok. Might be, then, that the problems are solved by using a proper upsert query in the backend.

**Comment by fm3** [comment]
closing this, retry is good enough, should not be a problem if requests are already throttled
