### ISSUE TITLE
NML Parser: reject NMLs with duplicate edges or loops

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2515]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2515/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
@fm3 Just to be sure, by loops you mean edges with the same source and target id (cycles of length 1) but longer cycles are still supported, right? :)

**Comment by fm3** [comment]
yes, that’s right
