### ISSUE TITLE
Bulk Task creation expects teamID now, but teamID is not shown in frontend

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2517]
either we should get it to work with team name again, or the team list view needs to show IDs

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2517/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@hotzenklotz @youri-k what do you think is the better option? change the api back or show team IDs to team administrators?

**Comment by hotzenklotz** [comment]
Unless, it is a big pain I would preserve the old behavior.
