### ISSUE TITLE
Add custom organization logos to datasets

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2522]
Currently, when viewing a dataset the MPI logo is always shown. Now that we have other labs using wK and hosted datasets from other researchers this should be changed.

Ideally each dataset could have a custom logo that defaults to the organization.

Related to #2501

![image](https://user-images.githubusercontent.com/1105056/41288190-c26978c2-6e45-11e8-8c3e-ef0f68e5266d.png)

**Comment by hotzenklotz** [comment]
@philippotto Can we integrate this issues into the next sprint please. This is becoming more important since we will be hosting Eliot's data from Rockefeller University soon. They requested we replace the logo.

Perhaps, we have a default logo registered with the organization and a way to customize it on a per dataset basis? Especially on the `demo.wk...` instance there will most likely always just be one org but datasets from several institutes.

**Comment by hotzenklotz** [comment]
Let's start with URL first and expand it later if needed.

**Comment by fm3** [comment]
proposed backend part:
add logoUrl column to organization and also to dataset, send to frontend with dataset (organization logo is fallback)
