### ISSUE TITLE
Use reacts new lifecycle hooks / scroll to active tree does not work

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2526]
Using react's new lifecycle hooks might fix this [problem](https://discuss.webknossos.org/t/jump-to-selected-tree/845). At the moment, the ListTreeItemView is re-rendered when the active tree changes. However, `componentDidUpdate()` is not triggered. This seems like a react bug and might be fixed automatically by converting to the new life cycle hooks.

https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2526/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
I've updated to React v16.3 on the `tree-groups` branch and also rewrote the whole tree tab while implementing the tree hierarchies. I'll open a PR soon - let's test whether this issue still persists then.

**Comment by philippotto** [comment]
Ah cool, I didn't know that you updated react in the process. Weirdly, I
cannot reproduce the issue locally. Let's see whether the update fixes the
problem.

Daniel <notifications@github.com> schrieb am Do., 26. Apr. 2018, 11:10:

**Comment by philippotto** [comment]
I think this is resolved by #2546.
