### ISSUE TITLE
dev deployments: no initial user inserted?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2538]
might be a db creation timing issue

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2538/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
global.scala does not enforce sequential execution here

**Comment by fm3** [comment]
but it does in branch sequential-init-verbose yet the error occurred there too, suggesting that something else may be off there. also odd that no error output was logged

**Comment by daniel-wer** [comment]
@fm3 Have you got any ideas here? I'm starting to hit this problem nearly every time a dev branch is deployed :/

**Comment by philippotto** [comment]
Maybe we can push a dirty workaround for that?

**Comment by fm3** [comment]
I couldn’t yet figure out what’s going on here. Will debug again

@philippotto Well, we could create a trigger route that inserts the initial data, but we’d have to make sure this is not possible on production instances.

**Comment by philippotto** [comment]
This workaround sounds very reasonable to me!
Should save some headaches until we find the actual problem :)

Florian M <notifications@github.com> schrieb am Mi., 6. Juni 2018, 16:09:

**Comment by philippotto** [comment]
Any updates on that? It's really annoying :(

**Comment by fm3** [comment]
I’ll create the route workaround as proposed above today. Tried to debug more yesterday, but I couldn’t really find anything

**Comment by fm3** [comment]
#2714 adds a workaround, but this remains open

**Comment by philippotto** [comment]
> For the record, since you added the workaround, this happened exactly once (some days after you added the workaround). I didn't encounter this for at least two months now :)
@philippotto Did you encounter this again?

I think, I experienced it more than once (maybe three times), but only very shortly after the workaround was implemented. Maybe there were some other changes which fixed this as a side-effect? I think, we can close this issue and re-open if it reoccurs?

**Comment by fm3** [comment]
I can’t really think of any related changes in the last time, but I agree, let’s reopen this if it occurs again :)

**Comment by daniel-wer** [comment]
@fm3 I experienced this issue again today, for example, on the https://annoyingscratch.webknossos.xyz/ branch. I tried removing/installing the branch again, but no luck yet. The trigger no longer exists, right?

**Comment by daniel-wer** [comment]
Fixed it by removing/installing again, but we should keep an eye on this :)
