### ISSUE TITLE
wrong application.conf is loaded (on some machines, local development only)

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2560]
sbt/play on some machines decides to load the application.conf of the datastore subproject even if the main webknossos project is launched. this leads to misbehavior.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2560/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@rschwanhold you had this issue on ubuntu too, right? if you have any ideas on how to debug this, that would be super cool.

**Comment by fm3** [comment]
we determined that this issue is gone if the datastore application.conf is renamed, e.g. `mv webknossos-datastore/conf/application.conf webknossos-datastore/conf/standalone-datastore.conf`

@jstriebel could we do that permanently and, only in the CI, rename it back, directly before building the standalone-datastore?

**Comment by jstriebel** [comment]
That sounds like a very unintuitive hack to me. I would rather [set the filename on startup then](https://www.playframework.com/documentation/2.4.x/Configuration#Specifying-an-alternative-configuration-file), if we need to rename it.
It seems like all `application.conf`s from the classpath are read:
https://github.com/lightbend/config#standard-behavior

**Comment by fm3** [comment]
the command in yarn start is supposed to set the filename of the wk main project on startup via `config.file`, but it does not seem to have any effect on the machines where this issue occurs.

Maybe we could set the config filename on the startup of the standalone-datastore. Not sure, though, if there are any load orders that should be respected in the deployments?
