### ISSUE TITLE
Transition to New Relic Alerts

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2569]
It seems we're using the legacy alerts for New Relic which are phased out next week. We should transition to the new system soon: https://docs.newrelic.com/docs/alerts/new-relic-alerts/getting-started/transition-legacy-alerting-new-relic-alerts

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2569/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
In newrelic, I get `You do not have sufficient permissions to view this page.` on the alert settings page. Maybe, we could look at this together?

**Comment by normanrz** [comment]
I created a new alert policy: https://alerts.newrelic.com/accounts/1357014/policies/298376
Not sure if that makes sense. We can also add alerts for other user-defined metrics or events.

**Comment by fm3** [comment]
I added alerts for the error rate (also external + demo) as this is what we usually looked at :)
