### ISSUE TITLE
frontend crashes when entering a search query in team list view

### ISSUE THREAD

**Issue by youri-k** [scalableminds/webknossos#2571]
I don't know if this happens just to me or just my branch but I feel like I didn't change anything.

Just tested it on webknossos master and the same behavior can be observed.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2571/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Last time we had trouble with the search feature it was due to the name change of a property of a team. Perhaps this is the case here as well.
