### ISSUE TITLE
Warn when datastore is unavailable

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2604]
During the update of the deployed datastore, users are likely to experience errors in WK. In this case, it should be clear to the user why these errors appear and that they should check back in a few minutes. One simple way to implement this, is to check the status code of failed requests.

- [X] ping datastore health endpoint on errors
- [x] integrate fossildb into datastore health ceck

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2604/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
closed through the sum of #2633 and #2637
