### ISSUE TITLE
Tracing Action Statistics

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2608]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2608/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
Put on hold for undisclosed period of time. I'm not sure whether we still want to merge the small script I wrote or leave it on the extra branch (tracing-statistics).

**Comment by philippotto** [comment]
We can reopen when it becomes relevant again.
