### ISSUE TITLE
Update Antd

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2628]
I'm opening this issue to include a notice for when we're next updating Antd (because I found this out painstakingly while investigating a bug).

The createTaskFromNML functionality will break silently as antd has changed how File formValues are transferred to the `form.validateFields(async (err, formValues) => { ... })` function. Earlier if one of the formValues was a File object, the respective form value contained that File. With newer antd versions, the original file is contained in `formValue.originFileObj`. When sending the multipart request, the original file object needs to be included, so this needs to be adapted.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2628/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
does wK use other File formValues apart from `createTaskFromNML`?

**Comment by daniel-wer** [comment]
As far as I can see, we use it everywhere we use Antd's Upload.Dragger component, which is in 3 files:
`dataset_upload_view, task_create_bulk_view, task_create_form_view`.
