### ISSUE TITLE
e2e-tests: timetracking doesn’t match on some machines

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2636]
is this another race condition?

```
       {
         activeInstances: 1,
         finishedInstances: 0,
-        openInstances: 19,
+        openInstances: 39,
         paused: false,
         projectName: 'Test_Project',
-        totalInstances: 20,
+        totalInstances: 40,
         totalTasks: 2,
       },
     ]
 ```

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2636/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@hotzenklotz @rschwanhold 
this is caused by a race condition. if
https://github.com/scalableminds/webknossos/blob/master/app/assets/javascripts/test/backend-snapshot-tests/projects.e2e.js#L82
is executed before https://github.com/scalableminds/webknossos/blob/master/app/assets/javascripts/test/backend-snapshot-tests/timetracking.e2e.js#L38 then the result of the latter differs from the other order. can we enforce this somehow? (or instead use a different team / project for the tests?)

**Comment by rschwanhold** [comment]
Can single tests really run simultaneously or is it just the order important?
If it is only about the order, then after increasing 'TaskAssignment' you could decrease it again to avoid influence other test
