### ISSUE TITLE
[Airbrake] [Dev-customviewports] Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2641]
**Airbrake error:** [#9795](https://scm.airbrake.io/projects/95438/groups/2221011094532319795)
**Airbrake project:** webknossos

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'map' of undefined ``
**Where:** `<no information>`
**Occurred at:** May 23, 2018 11:05:54 UTC
**First seen at:** May 23, 2018 09:52:35 UTC
**Occurrences:** 76 ( since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://customviewports.webknossos.xyz/annotations/Explorational/5b054ae53400003601a77e9b](https://customviewports.webknossos.xyz/annotations/Explorational/5b054ae53400003601a77e9b)
**File:** `/PROJECT_ROOT/assets/bundle/main.js?nocache=dbb2bfb8cf9b83a3dcbe616035abc2f5fe0496ee`

**Backtrace:**
```
/PROJECT_ROOT/assets/bundle/main.js?nocache=dbb2bfb8cf9b83a3dcbe616035abc2f5fe0496ee:1:in e
/PROJECT_ROOT/assets/bundle/main.js?nocache=dbb2bfb8cf9b83a3dcbe616035abc2f5fe0496ee:1:in t.map.t
<anonymous>::in Array.map
/PROJECT_ROOT/assets/bundle/main.js?nocache=dbb2bfb8cf9b83a3dcbe616035abc2f5fe0496ee:1:in e
```

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2641/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@philippotto Please take a look at this new airbrake error for custom viewport branch., thanks

**Comment by philippotto** [comment]
This is already fixed.
