### ISSUE TITLE
initial tree of task not named

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2686]
there should be an updateAction renaming the first tree of a task annotation. Looks like the first tree is given a name only within the frontend. did this exist in the past?
@daniel-wer @philippotto 

steps to reproduce:
request at ask, trace a bit, create a second tree, save
download as NML, you should see that the initial tree has no name

https://discuss.webknossos.org/t/tree-name-missing-id/923

**Comment by daniel-wer** [comment]
Yep, I just confirmed, the renaming only happens in the frontend. I investigated and it looks like a race condition: The tree renaming saga runs before the save saga is initialized with the initial tracing. Therefore, the save saga considers the tracing with the renamed tree to be the initial tracing and doesn't send an update action.
This could be solved by registering sagas in a different order (and they probably were at some point in time), but I don't really like this, it breaks too easily (see this bug), we'll have to think of a different approach. Any ideas @philippotto?
