### ISSUE TITLE
Saved default position and scale are not applied

### ISSUE THREAD

**Issue by valentin-pinkau** [scalableminds/webknossos#2697]

**Comment by fm3** [comment]
resolved in the meantime

**Comment by daniel-wer** [comment]
As this bug reoccurred at least once now, we should think about adding a test (maybe a snapshot test is sufficient) :)

**Comment by philippotto** [comment]
@valentin-pinkau Unfortunately, we cannote reproduce this issue. Can you give us some details to reproduce when you are back in the office?

**Comment by valentin-pinkau** [comment]
Seems to be fixed - can't reproduce it either.
