### ISSUE TITLE
task creation while fossildb is down leads to zombie-tasks that have no annotation base

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2700]
should fail altogether, without creating task objects in the db

**Comment by jstriebel** [comment]
steps to reproduce:
* start wk + datastore (tested with external)
* stop fossildb
* try to create task in admin view
* try `Get a New Task`
* get the toast `Failed to retrieve annotation base.`, should be `There is currently no task available`

**Comment by fm3** [comment]
will be useful here: https://github.com/scalableminds/webknossos-wiki/wiki/Set-up-a-standalone-datastore-locally
