### ISSUE TITLE
Task Page - TypeError: e.innerMenu.getWrappedInstance is not a function

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2711]
It's unclear to me how this can be reproduced. Seems to be triggered by some keyboard invocation. Maybe we should wait until this gets reported by a user who can voice what doesn't work for him/her.

https://scm.airbrake.io/projects/95438/groups/2232176119045222211?tab=overview

**Comment by philippotto** [comment]
@daniel-wer This issue seems to exist since the latest antd update :S I tried to update it again, but that didn't help. Not sure if we should just downgrade again. There wasn't a strong reason to use the newer version, right?

**Comment by daniel-wer** [comment]
No strong reason, but we updated because antd added the possibility to update notifications without having to destroy/re-create them (which we use when changing the move value). If this error doesn't affect usability, I wouldn't downgrade.

**Comment by philippotto** [comment]
> If this error doesn't affect usability, I wouldn't downgrade.

Ok, I'll move it back to backlog.

**Comment by daniel-wer** [comment]
This even happens when copying one of Antd's Select examples (which work fine on Antd's site) to our codebase. Seems to have something to do with our specific build setup or dependencies.

**Comment by daniel-wer** [comment]
Fixed in #2950
