### ISSUE TITLE
update imprint for demo instance

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2712]

**Comment by neuronflow** [comment]
Where do I find the imprint?
https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo/view?utm_source=site#2867,4297,1770,0,1.21

I think German law (potentially) and/or our legal team (most likely) require me to add an imprint and data sharing agreement on the website 🤖

**Comment by fm3** [comment]
The imprint can be found at /imprint and the privacy statement at /privacy 

(webknossos.org is a special case there, but those routes should also work in self-hosted environment).

Note that `webKnossos.operatorData` from application.conf is used for the imprint content.

You are right, however, that these two pages are not obvious to find. I wrote https://github.com/scalableminds/webknossos/issues/6798 to track that.
