### ISSUE TITLE
Remove transform-async-to-generator

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2737]
According to [caniuse](https://caniuse.com/#search=await) the relevant browsers support native `await` which is why we don't need it anymore. Despite `babel-preset-env`, async code was still transformed.

Steps:
- [ ] delete babel-plugin-transform-async-to-generator from babelrc
- [ ] run test protocol under major browsers

**Comment by philippotto** [comment]
`transform-regenerator` is in `exclude` at the moment, but async code is still transformed.

- [ ] Investigate whether `transform-regenerator` and the other transform plugins can just be removed altogether

**Comment by unckleg** [comment]
How did you manage to remove it ?

**Comment by unckleg** [comment]
@philippotto 

Maybe you can help with this one: https://github.com/babel/babel/issues/8890.

Thanks.
