### ISSUE TITLE
uploaded Volume Tracing shows parts of Segmentation Layer even when deselected

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2739]
quoting @daniel-wer: Create a volume tracing (with new segmentation), brush a bit, then download the tracing. Upload the zip-File again. Suddenly the tracing contains parts of the original segmentation again (although it was created using "new segmentation").

**Comment by philippotto** [comment]
Feel free to re-assign, @fm3, but I think you are the right one to investigate this :)

**Comment by fm3** [comment]
Uploaded volume tracings are always initialized with a fallback layer.
I can disable this, but then uploaded volume tracings would __never__ be initialized with a fallback layer.

The problem is that the information of wether or not there should be one is not included in the NML and is also not a user-supplied value during the upload.

What do you think we should do? Add it to the NML spec? @philippotto @normanrz  @daniel-wer

**Comment by fm3** [comment]
closed as too-low priority unless someone complains
