### ISSUE TITLE
Enhancements for dataset gallery

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2744]
See https://discuss.webknossos.org/t/enhancements-for-demo-instance/803/14

  - [x] Add the possibility to supply a personalized dataset preview image (the automatically generated preview image could be used if no personalized preview image is supplied)
  - [ ] Add the possibility to supply a dataset publication date, so the dataset list can be sorted by publication date by default (the upload date could be used if no publication date is supplied)

**Comment by philippotto** [comment]
Re 1: @fm3 noted that you can already edit the default view position and zoom step for a dataset. These attributes are used when viewing a dataset **and** for creating the thumbnail.

**Comment by youri-k** [comment]
2: backend part is finished and the sorting key is also added to as a flow type but some frontend work needs to be done
