### ISSUE TITLE
Clear cache for dataset

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#2754]
Would it be possible to make a button that clears the dataset cache for one dataset? A cache invalidation based on file timestamps could also work.

When tweaking datasets, the cache is a bit annoying because it may show stale data or even yield errors.

**Comment by normanrz** [comment]
I was referring to 3

**Comment by fm3** [comment]
not so easy since there is one cache for all datasets, and the lookup happens via a combination of dataset and coordinates etc. So we can clear the entire cache, individual buckets, or we need to reengineer this

**Comment by normanrz** [comment]
Clearing the entire cache sounds good to me :-)
