### ISSUE TITLE
Color design of gallery dataset 

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#2771]
Change the color and other appearance related properties of a dataset preview to make it look better.

- [x] change the background color to white and the font-color to black
- [x] add a border and make round corners
- [x] add some more padding to the description
- [x] decrease the density of the skeleton and column tracing when the user is not logged in

**Comment by philippotto** [comment]
Maybe you can take some inspiration from here for colors/borders/paddings:

https://ant.design/components/card/

![image](https://user-images.githubusercontent.com/2486553/41603818-06b2804e-73de-11e8-9434-c532e7965821.png)
