### ISSUE TITLE
Display datasets in the dataset gallery grouped by organisation

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#2772]
Sort the datasets display in the dataset gallery by organization and display them as a group.

- [x] sort the datasets by organization
- [x] display the datasets grouped by the organisation
- [x] add a title for each grouping ~~with the label of the organization next to it~~
- [x] provide something like a show more area when there a many datasets of a single organization

**Comment by philippotto** [comment]
> provide something like a drop down when there a many datasets of a single organization

I'd suggest a "show more" button which makes the container holding all the datasets larger so that more datasets are shown. We can also talk about this in person, if it's not entirely clear :)
