### ISSUE TITLE
bucket loading: Error processing WKW file. File is already closed

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2781]
see https://discuss.webknossos.org/t/error-processing-wkw-file/950

**Comment by fm3** [comment]
Could not reproduce :( Also, our code does not feature "error processing" at all, which makes it hard to track where this came from. Possibly through heavy IO load on the datastore

**Comment by philippotto** [comment]
Can we change the code so that we get better debug information for such errors? The lab seems to still hit this every now and then.

**Comment by fm3** [comment]
found the source in https://github.com/scalableminds/webknossos-wrap/blob/master/scala/src/main/scala/com/scalableminds/webknossos/wrap/WKWFile.scala#L177
still unclear why and where `readBlock` is called after `close`

**Comment by fm3** [comment]
#2974 did not fix the issue. However, it is now low priority since #2968 introduced a retry, which does the trick from a user perspective.

**Comment by fm3** [comment]
nope, came up again :( (still behind the retry, though, so still harmless)

**Comment by jstriebel** [comment]
@fm3 Looking at the newrelic stats, I think #3169 finally resolved this. How do you feel about removing the retry?

**Comment by fm3** [comment]
Fine with me :) low priority, though. Tracking that in refactoring issue #3189
