### ISSUE TITLE
Redesign user task list

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2817]
During an over-the-shoulder tracing session we noticed that the design of the user task list is not optimal.
The description, which is often rather large, should be enlarged vertically to avoid scroll bars. The projectName/taskType are often times very long and currently get line-wrapped several times, which is not ideal.

Maybe the table-row approach can be replaced by a card-style approach that avoids wasted white-space and maximizes readability.

@philippotto Can you add a screenshot of the quick mockup we did for this?

**Comment by philippotto** [comment]
![image](https://user-images.githubusercontent.com/2486553/42025113-1e91bc7e-7ac4-11e8-8246-57dc70440c14.png)
