### ISSUE TITLE
Rich text (segment) annotations

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2824]
Tune webKnossos comment functionality to allow for rich text segment/node annotations:

  - [x] Virtualize comment list
  - [x] Render markdown for comments
  - [x] Allow to link to nodes/positions in comments, maybe using `#<nodeid>` and `#<x,y,z>`

**Comment by daniel-wer** [comment]
When importing an NML into an existing tracing or when merging tracings in the backend, we'll have to rewrite comments that include nodeId links (#nodeId) if we change those nodeIds.

**Comment by philippotto** [comment]
Based on https://discuss.webknossos.org/t/synapse-edges/111, it would probably be cool to add a way to link trees, too. Not sure about the format, but maybe ##treeId?
