### ISSUE TITLE
Gallery Design Follow Up

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2833]
Ideas from the discussion with @philippotto , @normanrz  & @hotzenklotz  to further enhance the design of the dataset gallery view:

- [ ] Optimize the view for external visitors and remove the gallery from the dashboard of logged in users
- [x] Add a call to action button "View Dataset" that open the view mode. Perhaps, remove the "create skeleton / volume" button entirely
- [x] Pimp the gallery preview with [CSS effects](https://codepen.io/afinedayproductions/pen/EzvLp/) for added "wow" effect: 
- [ ] Try grouping all datasets of one project/experiment into a single "card" with a "Show More" button
- [x] Introduce a "display name" for organisation. e.g. "connectomics department" is really called MPI for Brain Research #2850 
- [ ] Extend our dev deployment setup to showcase some of the default datasets as public for visual QA on deployed branches

**Comment by philippotto** [comment]
In discussion with @normanrz, we agreed on leaving this as is for now. Closing this. We can reopen when necessary.
