### ISSUE TITLE
release first versioned tag & add CI support

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2843]
The steps to have specific versions are (as @normanrz suggested in #2841):
* add a CI build for tags, which results in the correctly tagged docker image
* tag a first version
* call it `2018-0?` (this indicates it's based on a date, I agree that semver is not appropriate here)
* update the changelog / migration guide / release notes appropriately

**Comment by normanrz** [comment]
My 2 cents:
- I'd vote for the Ubuntu naming scheme: `18.06` and `18.06.1` in case we need to deploy hotfixes
- At the beginning of every month, the release officer selects one commit as release, updates the release notes etc and creates the git tag
- Let's start with `18.07` which should be a stable commit from June
- I did some stuff for building tags in chatroom: https://github.com/scalableminds/chatroom/blob/master/.circleci/config.yml#L29
