### ISSUE TITLE
Make importing a dataset easier

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2852]
The JSON input could be hidden behind a "advanced tab". Instead, we could show a simple form which suffices for most of the use cases when uploading a dataset.

**Comment by philippotto** [comment]
### Current state:

At the moment, the server looks for a `datasource-properties.json` and shows that JSON to the user if it exists. Otherwise, it "guesses" an initial JSON, which then needs some potential adaptions by the user.

### New state (open for discussion)

For the case, that there's a `datasource-properties.json` we assume, the user knows what he is doing and just show it to make the user double check it.

For the case, that there's no config file, we only ask for the properties which we cannot derive from the data. That would be:

- the dataset scale
- largest segment id if there's a segmentation layer
- resolutions per layer?

These properties should be asked for via specialized UI elements (vector3 input for scale, number input with range defined by bitdepth of segmentation layer etc). After the user has filled out these fields, there should be no need to review a JSON, anymore. To stay backward compatible, we should allow to adapt the pure JSON nevertheless.

Do you agree, @normanrz @fm3 ?

**Comment by normanrz** [comment]
I think that is a good approach!
In the simplified view, I wouldn't show layer resolutions (they should be correctly inferred by the existing folders), but bounding box. Only coarse bounding boxes are inferred, perhaps people want to make them more precise.

**Comment by philippotto** [comment]
Ok, sounds good :+1: 

Is it likely that someone uploads a dataset with a datasource-properties.json file which is missing scale or largest segment id? I don't know whether labs have tools to generate the json, which don't provide properties. In that case, the import process wouldn't be improved..

**Comment by normanrz** [comment]
I could imagine that it is quite likely that people upload a dataset with faulty json 🙈
