### ISSUE TITLE
Handle multiple volume resolutions for hybrid annotations

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#286]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/286/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
let's do "volume annotations for an arbitrary, pre-selected magnification" as a first step. the following things need to be done:

- integrate into tasks
- NMLS
- UI
- ...

**Comment by philippotto** [comment]
For hybrid tracings, this topic becomes very relevant again. With the current constraints, an existing segmentation would just disappear in mag 2 and higher when opening a new hybrid tracing.

A simplistic solution could be to show the fallback segmentation in higher mags by default. If a volume tracing exists in mag 1, there could be a warning that mag 2 and higher will show an "out of sync" segmentation? Also, the user could select to hide the segmentation in higher mags to suppress the warning? Something along these lines?

**Comment by philippotto** [comment]
We should also consider the case where one creates a hybrid tracing for a dataset where the segmentation only exists in mag 2 (also see #4339). Maybe my above suggestion covers fine. That's probably up for discussion.

Also see https://github.com/scalableminds/webknossos/issues/4471 for a not-annoying way to communicate to the user of critical information (as "the different mags are out of sync").

**Comment by MichaelBuessemeyer** [comment]
I think this issue isn't really up-to-date anymore, as we discussed the following:

- The user always annotates volumes for all magnifications, independent of the magnification the user is currently in. Thus there is no way that the different volume magnifications are out of sync. 

Or am I missing something?

When there is not fallback layer for mag 1 -> The backend should upsample the mag 2 fallback layer to mag 1 and then this upsampled fallback layer should be used in mag 1 and merged with the annotation in mag 1.

**Comment by philippotto** [comment]
You are completely right :+1: The issue wasn't updated after our discussion.
