### ISSUE TITLE
Update eslint to v5, and eslint related plugins

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2880]
Issues:

  - [ ] Circular class dependencies due to flow types (https://github.com/babel/babel-eslint/pull/584)
  - [x] eslint-config-airbnb eslint v5 support (https://github.com/airbnb/javascript/issues/1834)
  - [x] button-has-type false positive - wait till https://github.com/yannickcr/eslint-plugin-react/pull/1851 is released

**Comment by daniel-wer** [comment]
After updating `eslint-config-airbnb` we need to discuss whether to tweak/disable some of the new rules. @philippotto @normanrz What do you think? :)

  - [ ] [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) Could be fixed automatically according to the docs. Imo this could be helpful.
  - [ ] [import/no-cycle](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) I don't really see us fixing that.
  - [ ] [react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md) I disabled it for now as this caused a loooot (> 500) of errors. (every time `this.props.<anything>` was used in any react component render method...)
  - [ ] [react/no-access-state-in-setstate](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) Around 50 errors.
  - [ ] [lines-between-class-members](https://eslint.org/docs/rules/lines-between-class-members) Reasonable with the `"exceptAfterSingleLine": true` option imo (for declaring instance variables without a newline). Unfortunately, this errors if a flow type definition causes an instance variable declaration to have multiple lines :(
 For example eslint wants a newline after the `dataLayers` line in this example:
  ```javascript
connectionInfo: ConnectionInfo;
  dataLayers: {
    [key: string]: DataLayer,
  };
  isMappingSupported: boolean = true;
  maximumDataTextureCountForLayer: number;
```

If you want to have a look at the linting errors yourself, check out the `update-eslint` branch and run `yarn lint`.

**Comment by philippotto** [comment]
> import/order Could be fixed automatically according to the docs. Imo this could be helpful.

Nice :+1:   

> import/no-cycle I don't really see us fixing that.
>  react/destructuring-assignment I disabled it for now as this caused a loooot (> 500) of errors. (every time this.props.<anything> was used in any react component render method...)

Agree.

>  react/no-access-state-in-setstate Around 50 errors.

I'd disable it for now and create a separate issue for it, so that it doesn't block the update in general. As @normanrz said, it's probably nice for future proofing.

>  lines-between-class-members Reasonable with the "exceptAfterSingleLine": true option imo (for declaring instance variables without a newline). Unfortunately, this errors if a flow type definition causes an instance variable declaration to have multiple lines :(
For example eslint wants a newline after the dataLayers line in this example: [...]

Let's ignore that for now, since it brings new problems.
