### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2902]
We are seeing a lot of "TypeError: Failed to fetch" errors in airbrake. As far as I understand, this error is shown when there is a cross-origin problem. I assume that the actual problem is a token which got invalid. ~When I'm doing a fetch request with an invalid token, I get exactly this error.~

~For example, try:~

```
fetch("https://data1-brain.esc.rzg.mpg.de/data/datasets/AG_P9_L4_30-06-2016/layers/color/data?token=invalid", {"credentials":"omit","headers":{},"referrer":"https://webknossos.brain.mpg.de/annotations/Explorational/5aa92f54280000ed01c0e3b0","referrerPolicy":"no-referrer-when-downgrade","body":"[{\"position\":[5216,4672,1408],\"zoomStep\":0,\"cubeSize\":32,\"fourBit\":false},{\"position\":[5248,4576,1408],\"zoomStep\":0,\"cubeSize\":32,\"fourBit\":false},{\"position\":[5056,4448,1408],\"zoomStep\":0,\"cubeSize\":32,\"fourBit\":false}]","method":"POST","mode":"cors"});
```

~The front-end will try to get a new token if this request fails, but only if the response code is `403`. However, I'm getting a `415 (Unsupported Media Type)` from the datastore. Is this something we can change to 403, @fm3? Alternatively, the front-end could also handle 415, but this doesn't seem right to me.~

The code will get a new token if the old one is invalid. It's unclear why the errors occur in the first place.

**Comment by philippotto** [comment]
Apparently, this was an issue with using fetch directly in the chrome console. It's not clear how the airbrake errors were triggered. Renaming the issue.

**Comment by philippotto** [comment]
@daniel-wer  @normanrz Do you happen to have an idea what the reason for this error could be? Supposedly, this message is shown when there are cross-origin problems (see [here](https://gauntface.com/blog/2015/02/11/fetch-is-the-new-xhr)), but I don't see why this should only be a problem **sometimes**?

**Comment by normanrz** [comment]
Can you narrow it down to specific users?
Does it also occur, when the connection drops mid-request?

**Comment by philippotto** [comment]
> Can you narrow it down to specific users?

There are a handful of users, for which the error was thrown. Since it happens for a wide range of browsers and different OS, I think it's not a system-specific bug.

> Does it also occur, when the connection drops mid-request?

Maybe, but this is probably not the cause for most of the bug reports. For example, Hamza Kebiri triggered the error > 1000 times in an old wk tab which he had hanging around in the background.
