### ISSUE TITLE
Improve the handling of datasets with common image data (only differing segmentation)

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2918]
A lot of datasets share the image data and only differ in their segmentation layers. As a result, the dataset list shows a lot of redundancy. Also, the handling of such datasets could need some improvement in general. For example, there is no easy way to switch between different segmentations of the same dataset.

In the long run, it's probably reasonable to change the assumption that a segmentation layer is part of the dataset. However, as a first step we could also group datasets with the same image data in the dashboard. It still needs to be discussed how such a grouping would exactly look and behave like.

**Comment by philippotto** [comment]
I'll create a first UI mock for the visual grouping.

**Comment by philippotto** [comment]
If we decide to go with "segmentations as layers", we should think hard about what would need to change. E.g.,:

- tasks for a specific dataset **with a specific layer** (should the user be allowed to switch the layer?)
- permissions per layer? (hopefully not)
- segmentation hot-swap in view/tracing mode (the first iteration could make a simple page refresh; but swapping the datalayer should not be ultra hard, either)
- links to a dataset should be able to hold a segmentation parameter
- the "active layer" would need to become a property of tracings
- deleting and adding a segmentation layer should probably be possible via UI

**Comment by hotzenklotz** [comment]
@philippotto Some parts of this issue are already covered like "segmentation as layers. Probably our ideas for the new dataset management will cover the rest. Perhaps, add the issue to the collection of ideas for dataset management or close.
