### ISSUE TITLE
[idea dump] newrelic alternatives

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2923]
### Tracing Systems
* https://www.jaegertracing.io/
* https://zipkin.io

Both are [opentracing](http://opentracing.io/) compatible

### Comparisons
* https://sematext.com/blog/jaeger-vs-zipkin-opentracing-distributed-tracers/
* https://dzone.com/articles/zipkin-vs-jaeger-getting-started-with-tracing?utm_medium=feed&utm_source=feedpress.me&utm_campaign=Feed:%20dzone

### Instrumentation Libraries
* https://www.jaegertracing.io/docs/client-libraries/
* https://zipkin.io/pages/existing_instrumentations
* https://github.com/kamon-io/kamon-jaeger
* https://github.com/opentracing-contrib/scala-concurrent
* https://github.com/opentracing-contrib/scala-akka

**Comment by philippotto** [comment]
Let's reopen when necessary.
