### ISSUE TITLE
Show a "there are new, inactive users" hint

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2928]
At the moment, it's quite hidden that inactive users need to be activated. Show a more prominent (but not too much in-your-face) hint.

**Comment by normanrz** [comment]
I think it would be great to list those users directly for the admin to activate. These users should only be newly created users (say last 2 weeks).

![img_1766](https://user-images.githubusercontent.com/335438/42994298-0135f57c-8c0e-11e8-8250-5351f1c732db.jpg)
