### ISSUE TITLE
scala: explore async-await (instead of for-yield)

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2952]
At some points in the backend code we use the for-yield syntax, where an async-await might fit better. Let's just try this at some exampes in the code.

Especially nested for-yields might benefit from this, like `(for {} yield { for {} yield x }).flatten`.

This was originally discussed in PR #2913.

**Comment by philippotto** [comment]
Is this still relevant @jstriebel @fm3 ?

**Comment by jstriebel** [comment]
Probably not, closing for now.
