### ISSUE TITLE
Upgrade or replace font-awesome

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2964]
Antd's icon set leaves a lot to be desired and in their docs (http://2x.ant.design/docs/react/recommendation) they specifically state that they do not want to mirror existing libraries, but instead recommend using 3rd-Party libs.

Font awesome v4 is not very "react-y", which they changed with v5 I think. However, they also offer a subset of their functionality under a paid yearly subscription (5 developers, pay extra for more devs) now (e.g., all `fa-...-o` outline icons), so we'll have to discuss whether that's worth it.

Another lib antd suggests is https://github.com/react-icons/react-icons, which combines multiple icon sources.

**Comment by hotzenklotz** [comment]
FIY, we have a FA5 license already.

**Comment by philippotto** [comment]
@MichaelBuessemeyer you just did that, right? please close if that's true :)

**Comment by daniel-wer** [comment]
Done in https://github.com/scalableminds/webknossos/pull/4783
