### ISSUE TITLE
Importing NML with groups does not correctly save the groups

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2971]
[Link to Discuss](https://discuss.webknossos.org/t/drag-and-drop-import-of-multiple-nml-files/1021)

Reproducible with the new "create group for file" option or just by downloading a tracing with groups and re-uploading it.

**Comment by daniel-wer** [comment]
I've debugged this and to me it looks like the backend is ignoring the `groupId` attribute of `createTree` update actions. The "correct" update actions are sent by the frontend when uploading an NML with trees contained in groups, e.g.:
`{"name":"createTree","value":{"id":5,"color":[0,0,1],"name":"explorative_2017-12-15_SCM_Boy_002","timestamp":1532941556642,"comments":[{"nodeId":6,"content":"test"}],"branchPoints":[],"groupId":3}}`

However, when reloading the page, the groupId attributes are missing from the trees.
@fm3 Could you have a look? :)

**Comment by daniel-wer** [comment]
When changing the color of one of the uploaded trees, which provokes an `updateTree` update actions, this tree remains in the correct group after reloading, so the problem indeed seem to be `createTree` update actions :)
