### ISSUE TITLE
Allow markdown / multi-line descriptions 

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3006]
[Link to Discuss](https://discuss.webknossos.org/t/multi-line-descriptions/1038)

Rendering as markdown should be straight-forward. For editing purposes, we might want to reuse the markdown functionality for comments, @daniel-wer.

**Comment by fm3** [comment]
presumably also blocked by #2991

**Comment by daniel-wer** [comment]
Yes that is correct.
