### ISSUE TITLE
Make experience field in task creation an antd select component

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3031]
We could render a "Tags" field (third example in first column here: https://ant.design/components/select/). In the on-change handler we could make sure that not more than one tag is active. Then, we would have auto-complete + the possibility to enter a **new** experience domain.

Not sure whether there's a backend route for gathering the experiences, @fm3?

**Comment by fm3** [comment]
There is not, I think, but of course we can add it

**Comment by philippotto** [comment]
> There is not, I think, but of course we can add it

That would be great! Could you do this in the context of this issue?

**Comment by fm3** [comment]
@MichaelBuessemeyer I added the route `api/tasks/experienceDomains` in PR #3060 (already merged) so feel free to adapt the frontend :)
