### ISSUE TITLE
Improve "Change experience" modal

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3033]
Context: Users table

Editing experiences for users is not very intuitive at the moment. Multiple things can be improved:

- When clicking the experience labels in the table, the edit-experience-modal should show up (at the moment, you have to check the checkbox in the right row and then click a button)
- The modal should have some description text to explain what experience domains are at all.
- Editing experiences itself should be improved (see below).

To change an experience level, an admin has to type in manually a domain and then type in a new value (which is suboptimal). The modal doesn't even show the already existing experiences?
The three buttons "increase", "set" and "delete" seem a bit cumbersome and not intuitive.

I'd imagine a table like this:

```
ProTracerDomainA          [-]   3   [+]    [trash icon]   
ProTracerDomainB          [-]   3   [+]    [trash icon]
[Add new experience domain]-button

[Save] [Cancel]
```

After the button is clicked:
```
ProTracerDomainA          [-]   3   [+]    [trash icon]   
ProTracerDomainB          [-]   3   [+]    [trash icon]
[input box (antd tag mode) for name]         [-]   1   [+]    [trash icon]

[Save] [Cancel]
```

The numbers itself should probably be input fields, too, so that you can input 90 without having to click the button 89 times :)

**However, beware:**
The modal can be used to change the experience domain for several users at once. If the users have different existing domains, the above approach for rendering domains does not work. We need to think about a good way here.

**Comment by philippotto** [comment]
Ok, we agreed on the following in the discussion:

If a single user is selected for editing, we list all experience domains (see UI mockup in the first comment).
If multiple users are selected, we stick to the current UI, with the following differences:
- the top of the modal lists the intersection of the exp domains of all users (e.g., "The selected users have the following domains in common: ...")
- the experience input is a antd select (see https://github.com/scalableminds/webknossos/issues/3031)
- if the user inputs a domain which is not possessed by all users, we show a light-weight warning (shown immediately; not on ok click), like "The experience domain you selected is not owned by all of the selected users. Changing, increasing or deleting the domain will affect **all selected** users.

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer About hiding the scrollbar of the tables I found this unsatisfying [issue](https://github.com/ant-design/ant-design/issues/6800). So i'll try to solve this problem manually with some css.
