### ISSUE TITLE
Update immutability-helper to make use of TS typing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3055]
### /edit
The text below is not up-to-date. Instead, we should update the [immutability-helper](https://github.com/kolodny/immutability-helper) package to make use of the TS typing in its newest version.

### Outdated:
Unfortunately, the clever syntax of `update`'s API, most of our reducers are barely typed. Flow simply accepts all possible objects for `update` even though only specific structures yield the intended benefit.

One way to solve this would be to always use object spreads. Since this becomes quite verbose, we should try to find good helper functions which itself are typed. For example, instead of

```js
const oldState = state;
const oldTracing = state.tracing;
{
  ...oldState,
  tracing: {
    ...oldTracing,
    someAttr: someNewValue
  }
}
```

we could have:
```js
updateTracing(state, {
	someAttr: someNewValue
})
```

with
```js
function updateTracing(oldState: StoreType, tracingShape: $Shape<TracingType>): StoreType {
	return {
		...oldState,
		tracing: {
			...oldState,
			...tracingShape
		}
	}
}
```

**Comment by philippotto** [comment]
To do:

- [X] implement typed update utility functions
- [X] adapt settings reducer
- [X] adapt annotations reducer
- [ ] adapt view mode reducer
- [ ] adapt task reducer
- [ ] adapt ui reducer
- [ ] adapt user reducer
- [ ] adapt flycam reducer
- [ ] adapt save reducer
- [ ] adapt volume tracing reducer
- [ ] adapt skeletontracing reducer

I suggest to not do everything at once, but instead do it successively (starting with the easier ones).

**Comment by hotzenklotz** [comment]
@philippotto Is this still an issue with typescript?

**Comment by philippotto** [comment]
yes, it's still relevant, but easier and a bit different: we should update the [immutability-helper](https://github.com/kolodny/immutability-helper) package to make use of its TS typing. I adapted the issue accordingly.
