### ISSUE TITLE
Towards Play 2.6: Use Dependency Injection for DAOs + Services

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3059]
part of #1622

**Comment by jstriebel** [comment]
not sure yet, if this is actually needed

**Comment by fm3** [comment]
Current assumption is that we need to inject everything that accesses the Play “global state” – e.g. the config. This might be transitive, so that everything accessing the config and other such things will also have to be an injected class. So we might end up with this situation again. However, we don’t have to remove *all* objects, apparently, and I would suggest going along the compiler errors / necessary changes as they come up, rather than systematically change everything.
