### ISSUE TITLE
Show welcome header when no organizations

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3118]
Also show the welcome header when navigating to `/` when there are no organizations. Remove the automatic redirect.

**Comment by MichaelBuessemeyer** [comment]
@normanrz  with automatic redirect you mean that the path `/` automatically redirects to the dashboard if you are logged in?

**Comment by normanrz** [comment]
No, I meant the redirect to the onboarding screen. When there are no organizations and go to `/` you are redirected to `/onboarding`.
