### ISSUE TITLE
“Unknown Error occured” toast shortly flashes when navigating away during page loads

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3122]

**Comment by philippotto** [comment]
@fm3 Do you know a reliable way to reproduce this? @MichaelBuessemeyer and I weren't able to reproduce it :/

**Comment by fm3** [comment]
I don’t know a reliable way. When I’ll see it the next time, I’ll try to reproduce it reliably with that.

**Comment by MichaelBuessemeyer** [comment]
As we can't reproduce this bug, I close this issue. If you can reproduce the bug, just re-open this issue :slightly_smiling_face:
