### ISSUE TITLE
Versioned volume tracings

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3146]

**Comment by youri-k** [comment]
@daniel-wer The backend part seems to be finished and it would be great if you could enable the frontend ui.

**Comment by daniel-wer** [comment]
@youri-k We need one more thing to enable the **preview** of previous versions of a volume tracing. We need to be able to request older versions of segmentation buckets without restoring the tracing first (so the `GET /datasets/:organizationName/:dataSetName/layers/:dataLayerName/data` route). Is this already possible? If not is it possible to add that? I've pushed my current state on the `volume-restore` branch.

**Comment by fm3** [comment]
should already be part of #3281 – which we hope to merge soon
