### ISSUE TITLE
Show fallback data when buckets of better magnification do not exist

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3148]
https://discuss.webknossos.org/t/magnification-2-visible-at-high-zoom-levels-when-magnification-1-does-not-exist/1072

I think, this should already work in theory, but the back-end seems to deliver black data if it doesn't find the requested buckets if the position is within the bbox?

To reproduce: I copied a dataset and removed some cubes from the best mag level. When opening the tracing, I can see at zoom step 2 that all data is there. If I zoom in, I can see a "hole" in the data (corresponding to the cubes I deleted). If I zoom into this hole, so that the viewport is black, and refresh the page, the network tab only shows successful requests. The front-end cannot know about these holes, which is why the back-end seems to deliver valid responses (i.e., black data). This would need to change so that the request simply fails (saying "data was not found" to avoid retries).

Can you have a look at this, @fm3, or delegate this to somebody else from the back-end team?

**Comment by fm3** [comment]
The black data “empty bucket” is created in BinaryDataService.handleBucketRequest and also sent if loading returned Empty in `BinaryDataService.loadWithRetry`
@rschwanhold please coordinate with @philippotto to see how this behavior needs to change.
I’d say this has a higher priority than #3087
