### ISSUE TITLE
Run screenshot tests periodically or on-demand

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3150]
Running the dataset rendering screenshot tests on my machine takes roughly 4 minutes and uses up all 800% of my CPU :sweat_smile: 

Ideally we would run the screenshot tests periodically or at least make it possible to execute them on demand **on another machine**.
To run the screenshot tests we need a deployed and up-to-date dev instance, e.g. `https://master.webknossos.xyz/`. The tests can then be run using the command URL=`https://master.webknossos.xyz/ docker-compose up screenshot-tests`.
I'm not sure whether it's possible to auto-deploy `https://master.webknossos.xyz/` every time the master changes? In that case we could create a simple cron job or circle CI [scheduled job](https://support.circleci.com/hc/en-us/articles/115015481128-Scheduling-jobs-cron-for-builds-) that runs the tests every night on weekdays or so.

**Alternatively**, we could execute the screenshot tests using a local webknossos instance, but then we would need the dev datasets for that.

**Or** we could create a slack command that executes the tests on one of our servers using a supplied URL of a specific wK instance. In that case, the user triggering the tests would make sure that the wK instance is up to date.

@normanrz or @jstriebel Any ideas or comments on the easiest approach here?

**Comment by jstriebel** [comment]
I think there's currently one piece missing, that would ease nightly triggers and slack commands:
We should split the current slack-commands into two services: `slack-commands` and `release-api`. The later is just a bunch of endpoints that has includes the git changes of the slack commands (installing & upgrading releases), and `slack-commands` only calls them.

Having that in place, we can have different scenarios, all of them valid in my opinion:
* Keeping `master.webknossos.xyz` up-to-date: We can either:
  1. Keep `master.webknossos.xyz` always up to date (actually having a staging environment). For this we would have a post-CI hook (either in CircleCI or on [dockerhub](https://docs.docker.com/docker-hub/webhooks/) that calls the `release-api`, or we
  2. Only update `master.webknossos.xyz` right before the screenshot-tests, and wait some time for it to finish.
* Independently of this we can then implement
  * a slack-command that triggers the screenshot tests for a dev instance, and/or
  * nightly builds that run the screenshot tests.

@normanrz Do you agree that having a `release-api` is the way to go? Regarding `i.` and `ii.` I don't have strong opinions.

**Comment by normanrz** [comment]
Sounds good to me. @twollnik would you be interested in helping with the `slack-commands` / `release-api`?

**Comment by twollnik** [comment]
@normanrz Sure, but I would need some pointers since this is completely new for me.

**Comment by jstriebel** [comment]
@twollnik A good start is probably to read the [slack-commands code](https://github.com/scalableminds/kube/blob/master/charts/slack-commands/code/slack-commands.py), and then we should probably have a call, as quite some components are involved there.

**Comment by twollnik** [comment]
@jstriebel Ok that sounds good.
