### ISSUE TITLE
diff schema can’t be run in wk docker image: node not found

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3161]

**Comment by jstriebel** [comment]
For the record: I tried to run js on the JVM with Trireme, Avatar & Nodyn, but they do not support modern JS. With Trireme it is possible to run the script with small changes, I will submit a PR soon.

If we use GraalVM in the future, this would naturally support it, so we could switch to it.

Alternatively, we could remove this from the startup and (possibly) make it a service:
  * expose schema.sql via some endpoint
  * have a cronjob that runs the diff-script of the running db against the exposed schema.sql
