### ISSUE TITLE
Refine dashboard task list view sorting and UI

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3163]
Quote:

> Therefore we would like to have only the task ID, project name and finish date per task. This should thin the list.
Now to the sorting. It would be nice if the tasks could be sorted after finished date, means the task on top is the task finished most recently

See https://discuss.webknossos.org/t/sorting-of-finished-tasks/1092

**Comment by daniel-wer** [comment]
From @fm3: The annotation belonging to a task has a modified field which could be used here.

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer 
> For the unfinished I suggest to keep it as is
Does this mean that the List does not change when `unfinished tasks` is selected (description and so will still be displayed). And when choosing `finished tasks` the list will be reduced to only `task ID, project name, finished date` and sorted after the finished date?
=> is it correct that the is no real `finished date` and that I can user `task.annotation.modified` for that?
