### ISSUE TITLE
Guessed BoundingBoxes all zero for Knossos Dataset

### ISSUE THREAD

**Issue by youri-k** [scalableminds/webknossos#3204]
wK guesses 0 for all bounding box values for a knossos dataset without properties.json

**Comment by fm3** [comment]
Not a bug, guessing bounding boxes is not supported for the Knossos data format
(see https://github.com/scalableminds/webknossos/blob/3e8c6b9926b92aa39c2b6a43127df504a571e416/webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataFormat.scala#L62 )
