### ISSUE TITLE
DataSet SharingToken AccessContext should’t be overwritten, but augmented by the User AccessContext

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3205]
This way logged-in users can also see datasets they couldn’t normally access, if they have a sharingToken.

Maybe the `SharingTokenContainer` could also (optionally, if logged in) hold the user?

**Comment by rschwanhold** [comment]
Can we create a `case class` that extends `DBAccessContextPayload` similar to `SharingTokenContainer` that takes both a sharingToken and a User as parameter?

**Comment by fm3** [comment]
Yes, sounds good :) Feel free to self-assign if you want to work on this when you’re free again
