### ISSUE TITLE
Investigate Linter and/or Formatter for Scala

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3211]

**Comment by youri-k** [comment]
Useful tools taken from this article https://leaks.wanari.com/2017/05/04/scala-code-formatters/ that I will check out in detail later 
Linter:
- [WartRemover](https://github.com/wartremover/wartremover)
- [Scapegoat](https://github.com/sksamuel/scapegoat)
- [Scalastyle](https://github.com/scalastyle/scalastyle)
Formatter:
- [scalafmt](https://github.com/scalameta/scalafmt)
