### ISSUE TITLE
Color and segmentation data is missing or corrupted sometimes

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3259]
See https://discuss.webknossos.org/t/volume-mode-is-corrupted/1127

I can reproduce this issue using the 2012-09-28_ex145_07x2 dataset with a 16-bit segmentation (However the online dataset has a 32-bit segmentation). The buckets that are loaded first, seem to be black. When moving away and back to the start again, they are rendered correctly. I cannot reproduce the totally scrambled segmentation locally.

Reverting #3164 did not fix the issue for me locally.

**Comment by philippotto** [comment]
I assume it's a front-end issue since the successfully rendered data differs between page reloads. I doubt that the server responds with flaky data.
