### ISSUE TITLE
Copy to my account for volume fails with 502

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3263]
Might be a temporary problem, but when trying to copy this tracing:

https://webknossos.brain.mpg.de/annotations/Explorational/5a96cca54b00008e03d86b55#16264,16746,2148,3,0.74

to my account, the request is pending for approx. 1 min (time out limit?) and then I get a 502 with the HTML template for "we're updating".

**Comment by philippotto** [comment]
Ok, it seems that fossildb was working quite a bit which made the entire server unresponsive. I don't know how large the tracing is.. Anyway, we should think about how to speed this up and/or how to not use up all resources while copying a tracing.

**Comment by fm3** [comment]
fossildb shouldn’t really be able to make the whole server unresponsive.
Possibly, the 502 is related to https://www.playframework.com/documentation/2.6.x/Migration26#Akka-HTTP-server-timeouts

**Comment by philippotto** [comment]
I think @normanrz and I had a look at htop on the server and the fossildb process was maxing out iirc :thinking:

**Comment by fm3** [comment]
closing this as #3268 should prevent clicking the button multiply, and with a bit of patience, this seems to work just fine
