### ISSUE TITLE
Finalize Hybrid tracings

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3288]
When we have versioning for volume tracing, we should try to push hybrid tracings to being the new standard. This includes:

- [x] Backend
  - [x] complete versioning for volume mode
  - [x] allow "conversion" of skeleton/volume to hybrid (lazy initialize the missing part)
  - [ ] restrictions where appropriate (e.g., tasks)
- [x] Frontend
  - [x] complete versioning for volume mode
  - [x] allow "conversion" of skeleton/volume to hybrid (lazy initialize the missing part)
  - [x] restrictions where appropriate (e.g., tasks)
- [x] mark hybrids as non-experimental
- [ ] remove "create only skeleton/volume tracing" from UI or make it non-default (**later**)

**Comment by philippotto** [comment]
@youri-k The backend would also need to support skeleton/volume mode for tasks (types). It should probably be enough to have a some sort of tracing type flag for a task (type?). So, it's either "skeleton", "volume" or hybrid. In the UI, we would probably show this as two checkboxes (one for skeleton and one for volume) for which at least one has to be active.

**Comment by daniel-wer** [comment]
@youri-k It looks like when making a skeleton tracing hybrid, the created volume tracing is created using the "use a new segmentation layer" option, which makes the segmentation, that was visible in the skeleton tracing before, disappear. I would think the "use existing segmentation layer" option is more appropriate in this case, what do you think?

**Comment by fm3** [comment]
Note that tasks do not have volume mode yet because some things are not defined for volumes (like merging multiple ones). This might be slightly more complex than thought.

**Comment by daniel-wer** [comment]
Followup in #3433.
