### ISSUE TITLE
Store Meshes in Postgres

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3289]

**Comment by fm3** [comment]
Should we discuss how we want this to behave? Meshes are dragged into the viewport, right? So we want a way to store those dragged-in meshes with the annotation, right? Do they also have properties like position? Should this be versioned with the tracings? Maybe we should treat it as a third category of skeleton/volume/mesh ? That would suggest update actions + protobuf storage etc. Or does it more sense to hold this in the postgres db? What would the desired API look like?
