### ISSUE TITLE
Increase max attachment size in discourse

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3303]
[Users](https://discuss.webknossos.org/t/bogus-data-shown/1143) are having problems attaching screenshots to posts, see https://meta.discourse.org/t/changing-max-attachment-size/26435?u=sam for a how-to.

**Comment by philippotto** [comment]
I remember vaguely that we configured discourse correctly but that nginx is the one which is misconfigured (but I might be wrong).

**Comment by jstriebel** [comment]
@philippotto What was the size that failed for you in discourse? If I remember correctly, it was ~200MB? If I see it correctly, @normanrz changed the upload limit to 20MB, so we just need to increase it further.

**Comment by philippotto** [comment]
@jstriebel Unfortunately, already a 2 mb file is causing problems. So, the limit of 20 MB is definitely not working.

**Comment by jstriebel** [comment]
@normanrz did you also update the limit in the settings? I can't access it myself:
https://discuss.webknossos.org/admin/site_settings/category/files

**Comment by normanrz** [comment]
Should be fixed with https://github.com/scalableminds/kube/pull/213
