### ISSUE TITLE
Show dataset extent (in voxel and mm) in info tab

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3306]
Use bounding box (for extent in voxels) and bounding box + resolution (for extent in nm) to display the extent of the dataset. Have a look into how the width of the viewports is calculated. There we already have a nice function which picks the appropriate metric (nm vs. mm etc).

**Comment by MichaelBuessemeyer** [comment]
> Have a look into how the width of the viewports is calculated.

You mean the [zoom level](https://github.com/scalableminds/webknossos/blob/8b6795f312d153094240bbdb0da1726dac38dbd9/app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js#L92) right? 😅

**Comment by MichaelBuessemeyer** [comment]
@philippotto Is there even an efficient way to calculate / get the total bounding of a dataset?
I can't find a property of Store.dataset that has the bounding of the whole dataset stored directly. The only thing I came up with is iterating through all datalayers and thereby calculating the bounding :confused:
If that's really the case shall we add this as an additional property send by the backend?

**Comment by philippotto** [comment]
> You mean the [zoom level](https://github.com/scalableminds/webknossos/blob/8b6795f312d153094240bbdb0da1726dac38dbd9/app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js#L92) right?

Well, yeah, it's used for calculating the viewport width. The function could use some renaming probably.
https://github.com/scalableminds/webknossos/blob/8b6795f312d153094240bbdb0da1726dac38dbd9/app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js#L235



> @philippotto Is there even an efficient way to calculate / get the total bounding of a dataset?

Yes, the bounding box of the dataset can be used for that. You need to multiply the bounding box extent with the scale and bucket size, since the bounding box is specified in buckets (i.e., for [11, 11, 24] scale and bounding box from 0, 0, 0 to 10, 10, 10, the extent is 11 * 10 * 32, 11 * 10 * 32, 24 * 10 * 32).
