### ISSUE TITLE
Give WK direct access to /tmpscratch

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3310]
Copying from /tmpscratch to /wklive is a bottleneck. Additional /wkscratch might no be necessary.

**Comment by normanrz** [comment]
@fm3 wouls it be feasible that the datastore watches multiple folders?

**Comment by fm3** [comment]
I think we could change it to do that, yes. I’ll have a look next week

**Comment by jstriebel** [comment]
@normanrz Do you know if it would be easy to mount `/tmpscratch`? I'm not aware of the internal filesystem workflows. But if that's easily possible, we might just do this and watch multiple folders.
Who would be affected from the lab?

**Comment by fm3** [comment]
closed by #3330 and various changes in the garching deployment
