### ISSUE TITLE
Add some documentation for REST API

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3314]
Ideally, we should also make sure that very common use cases for the REST API are also covered via the UI (e.g., download all explorative tracings or similar).

**Comment by philippotto** [comment]
- [ ] Clarify high-level goal which makes REST API necessary.

**Comment by fm3** [comment]
I’d say it is relatively safe to release those routes:
```
GET    /api/buildinfo

GET    /api/user
GET    /api/user/annotations

GET    /api/datasets

POST   /api/annotations/upload
POST   /api/annotations/Explorational/:id/duplicate
PATCH  /api/annotations/Explorational/:id/edit
PATCH  /api/annotations/Explorational/:id/finish
PATCH  /api/annotations/Explorational/:id/reopen
GET    /api/annotations/Explorational/:id/info
POST   /api/annotations/Explorational/:id/merge/Explorational/:mergedId
GET    /api/annotations/Explorational/:id/download
```
however, we should add a disclaimer note that these may change at any time (but the change will be documented). Only if this becomes a really important use case we should introduce api versioning etc.

**Comment by fm3** [comment]
let’s wait for further feedback in discuss
