### ISSUE TITLE
Add compatibility for JDK 9+

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#3316]
Currently there is an error when trying to run sbt with Java 9+ (at least the error appears for java 10).

The error thrown is ``` play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InaccessibleObjectException: Unable to make public void jdk.internal.misc.Unsafe.copyMemory(java.lang.Object,long,java.lang.Object,long,long) accessible: module java.base does not "exports jdk.internal.misc" to unnamed module @1a76a661]]
    at  ... ```

**Comment by normanrz** [comment]
Maybe we should aim for OpenJDK 11

**Comment by youri-k** [comment]
As recommended in this [docs entry](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html) I think we should keep java version 8. Higher JDK are not fully supported.
