### ISSUE TITLE
Allow admins to revoke admin rights from others

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3329]
right now this can only be done directly in the database

**Comment by philippotto** [comment]
I'd think so. Usually, an administrator has permissions to do everything, so why not revoke other's admins rights? However, at least super admins (which is still a thing, right?) should be able to do that.

**Comment by fm3** [comment]
Super admins are still a thing, but the only thing that they can do is use the switch route + see the datastore token.
The backend already allows regular admins to change the admin rights of others (using the user put request), so I guess a button in the frontend is needed.
