### ISSUE TITLE
document how to apply migrations in locally running docker-based wK

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3337]
@georgwiese You had this problem, right? Did you solve it with psql in docker? Or did you work around it? Could you let us know what other usability issues you had? Then we can hopefully make things easier both for you and others :)

- [x] `docker-compose run psql` gives access to the db, but in its shell using `\i` I get `conf/evolutions/reversions/32-scratch-datastores.sql: No such file or directory`
- [x] is the db persistent?
- [x] what’s up with the file permissions? failed to create organization dir. binaryData is owned by root now, so as normal user I can’t put datasets in there either
- [x] can I test changes to this locally without them being in master?
- [x] add commented-out   `# - -Dplay.http.router="noDS.Routes"` to docker-compose

**Comment by georgwiese** [comment]
I believe I ended up dropping the database.

**Comment by fm3** [comment]
@jstriebel I’m somewhat stuck here, could we maybe talk about this tomorrow or next week? Thanks! :)
