### ISSUE TITLE
“Chinese Quote” font used for more symbols than intended

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3359]
we have a `@font-face` rule in the bundled css that selects "Chinese quote" for a bunch of unicode symbols. This includes for example ’, which makes some texts look weird. Why is this, is this in our control?

**Comment by daniel-wer** [comment]
I adapted some css rules, and fixed the occurrences I could find in a past PR. Unfortunately, antd resets the font-family for quite a few components, so if we encounter this again, we'll have to add that component type to the list in `antd_overwrites.less`.
