### ISSUE TITLE
Allow to specify recommended user settings via task type

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3363]
See https://discuss.webknossos.org/t/settings-via-task-type/1173

**Comment by philippotto** [comment]
I think the easiest way would be to allow the task type creator to add some settings JSON which is then persisted and upon task start we can show a message "the following settings are recommended for this task. do you want to apply these?". The only problem with this approach is that we would need to expose our internal settings JSON format.

Another possibility would be to add the settings UI to the task type dialog. Then we would encapsulate the json setting names away. What do you think @daniel-wer ?

**Comment by fm3** [comment]
@philippotto @daniel-wer do you already have plans for this? What do you need from the backend? :)

**Comment by philippotto** [comment]
I think we would only need a route to put and get some json object on a task type (e.g., a `preferredSettings` attribute). I'll double-check with heiko whether this should be per task type or for each task.

**Comment by fm3** [comment]
backend part should be done through #3415 :)
