### ISSUE TITLE
after e2e-tests: Permission denied /root/.ivy2/cache/scala_2.12/sbt_1.0/…

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3419]
`…com.typesafe.play/sbt-plugin/jars/sbt-plugin-2.6.18.jar`

when running `sbt run` the next time. `./clean` helps, but would be nice if that weren’t necessary.

Why does sbt think it should use the ivy cache from that dir?

**Comment by fm3** [comment]
`grep -rl "/root/.ivy2" project/target/ | xargs sed -i 's|/root/.ivy2|~/.ivy2|g'` helps

**Comment by jstriebel** [comment]
Seeing @fm3's quickfix I know the underlying cause:
In the sbt docker image some paths are set via env variables, and somehow they are cached in the `project/target` directory. I will try to remove them in the future, maybe they are not necessary:
https://github.com/scalableminds/dockerfiles/blob/master/sbt/Dockerfile#L19

**Comment by philippotto** [comment]
> I will try to remove or change the env vars in the future, maybe they are not necessary:

Can you gauge how much effort this would be (time-wise)? The problem is hitting our toes quite regularly :/

**Comment by jstriebel** [comment]
@philippotto If my previous guess is correct, the fix is quite easy (https://github.com/scalableminds/dockerfiles/pull/18). I created a new sbt-base-image, see #4034 
Can you test if this fixes this issue?

**Comment by fm3** [comment]
I’m testing it now

**Comment by fm3** [comment]
(let’s discuss further in PR #4034)
