### ISSUE TITLE
large mappings cause wK to freeze

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#3429]
to reproduce:
- go to `https://webknossos.brain.mpg.de/datasets/Connectomics_Department/H2_3_v2_U1_SubI/view`
- run `mappings.activate("IN_v1")`
- wK freezes for ~2 minutes while activating the mapping

**Comment by daniel-wer** [comment]
Is the mapping working, then, after the two minutes?
I want to make sure whether this issue is about the freezing (where we should at least show a spinner or so and, better, move the work to a webworker) or large mappings not working at all :)

**Comment by jfrohnhofen** [comment]
yes, it is working in principle, but it took so long that I closed wK several times thinking it was frozen completely.

**Comment by hotzenklotz** [comment]
Just tried this. Many optimizations have been made and applying a mapping now is kinda smooth. wK did not freeze, there wasa progress indicatior for donwloading the mapping, applying it, etc.

Closing for now.
