### ISSUE TITLE
Paginate Dataset Gallery

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3442]
this should save load both in server and client since not all thumbnails are then requested at the same time

related: #3418

**Comment by philippotto** [comment]
Is the thumbnail route the bottleneck? If so, we could implement some "load picture when in viewport" logic. Might be simpler than pagination.

Also: Is the thumbnail route a bottleneck only for the client but also for the server? Isn't the server's cache duration randomized per thumbnail?

**Comment by fm3** [comment]
I wouldn’t call it the main bottleneck, but it definitely contributes noticably.
It is also putting load on the server since (1) the cache is invalidated when wK restarts, so several times a day for mhlab and (2) I think sending 2000 not-exactly-small images at the same time is also creating some load even if they are not re-generated from the raw data.

load-when-in-viewport sounds reasonable (or maybe an area twice the viewport size or something, so that a bit of scrolling is still supported without delay)
