### ISSUE TITLE
volume tracing: right-click brushing should remove pixels that come from from fallback segmentation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3453]
right now, when i want to un-segment a cell, i need to brush it with a new color, and then right-click-brush it after that.

**Comment by fm3** [comment]
@philippotto do you know if this is by design? Norman said it probably is not

**Comment by philippotto** [comment]
@fm3 Have you tried holding down CTRL? There are different modes when annotating segmentation. By default, right click starts "DELETE_FROM_ACTIVE_CELL" which means that the cell you are deleting must have the current cell id. Holding down CTRL starts the "DELETE_FROM_ANY_CELL" mode.

**Comment by fm3** [comment]
Thanks, I wasn’t aware of that. All good then :) Sorry to bother you about this!
