### ISSUE TITLE
Merge Queue Tool

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3456]

**Comment by philippotto** [comment]
I had a look at bors-ng, but it doesn't seem to support our squash-per-pr workflow. This makes rolling back specific PRs very tedious, which I wouldn't use it until https://github.com/bors-ng/bors-ng/issues/194 is resolved. Also, I couldn't find a better alternative yet.

**Comment by jstriebel** [comment]
How about any of those alternatives:
https://github.com/palantir/bulldozer
https://github.com/bobvanderlinden/probot-auto-merge
https://mergify.io/
