### ISSUE TITLE
log admin interactions

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3498]
“[timestamp]: user [a@b.de] added experience [sampleExp:5] to user [x@y.de]”
“[timestamp]: user [a@b.de] changed priority of project [sampleProject] to 100”
(This is relatively complex to do, but it also doesn’t have to be all done at once. Right now, we would use it to debug #3458 )

**Comment by philippotto** [comment]
I think, this is not relevant anymore, right? Feel free to re-open if you think otherwise.
