### ISSUE TITLE
Consider persisting buckets to disk instead of discarding them

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3525]
At the moment, the front-end does not hold more than 5000 buckets per layer. If memory is needed for a new bucket, an old bucket is discarded. If that bucket happens to be needed again, it has to be fetched again from the back-end. Instead of simply discarding such buckets, we could write them to disk (e.g., via IndexedDB using [localForage](https://github.com/localForage/localForage)).

Of course, this storage should be capped, too. However, we are not bound by RAM anymore. Consequently, this means we might be able to reduce RAM consumption by lowering the limit of 5000 buckets without sacrificing performance (almost?). We would need to run some benchmarks first for that.

**Comment by normanrz** [comment]
It would be cool, if we could estimate the RAM availability and adjust the threshold based on that.
I think there is still some space for more caching. Even with `uint32` that is only `5000*32768*4 Bytes = 655 MB`.

**Comment by philippotto** [comment]
The limit for buckets is dynamic now. Persisting to disk would add an additional complexity which is why I'm against it currently.
