### ISSUE TITLE
viewing someone elses annotation: TimeSpan error message

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3544]
FAILED: TimeSpanDAO.update Show debug information <~ FAILED: TimeSpanSQLDAO.assertUpdateAccess <~ Access denied.

why is this even attempted?
does not seem to come up every time…

**Comment by valentin-pinkau** [comment]
So I saw the issue here, but it does not come up every time. https://webknossos.brain.mpg.de/annotations/Explorational/5ce3e1550100000e076aa414#140212,151282,1372,0,0.126,4553

**Comment by fm3** [comment]
#4110 _probably_ fixes this, I’d suggest reopening the issue if it happens again :)
