### ISSUE TITLE
Too high network load due to superfluous (?) bucket loading

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3553]
I created a hybrid tracing here:

https://webknossos.brain.mpg.de/annotations/Explorational/5c1026fe0100009e0ae5c15d#6092,3712,2074,0,0.13

Don't know whether it's related to the dataset, but in any case, it seems as if the amount of downloaded buckets is way too high (> 10 000 requests can be provoked).

Needs investigation.

**Comment by daniel-wer** [comment]
I would assume this issue should be mitigated by #3656 as well :)
