### ISSUE TITLE
(Auto) min-max to determine brightness / contrast

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3583]
The brightness / contrast sliders are equal to a min and max value. We could think about exposing these values directly via the UI (one user requested this).

Even better would be an automatic determination of appropriate min/max values. This could work by inspecting the data within a bounding box and building a histogram to derive these values.

**Comment by MichaelBuessemeyer** [comment]
on hold till #3975 is merged

**Comment by philippotto** [comment]
@MichaelBuessemeyer https://github.com/scalableminds/webknossos/pull/4014 is merged now. Can you estimate roughly when your PR will be ready-to-merge?
Also, I couldn't find your PR? Or didn't you open one yet? If so, please open one with a [WIP] in the title :)
