### ISSUE TITLE
Clean up wk core UI

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3585]
Maybe it's a good idea to create a completely new design prototype to get fresh ideas. Then, we can determine what we want to implement.

Related to #3470 which addresses more specific "small-picture" issues.

**Comment by hotzenklotz** [comment]
Still relevant? I am pretty happy with current state? The status bar helps with explainability. The context-menu hide a lot of complex functions while still a very common pattern. The dataset layers are well organized.

@philippotto Voting to close.
