### ISSUE TITLE
Polish mesh rendering & isosurface computation

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3587]

**Comment by philippotto** [comment]
Plan of attack from our discussion:

Now:
- [ ] add tracking to the import stl feature (only for stls which were not generated by webknossos, as these will appear as "meshes")

Later (sorted by priority):
- [ ] remove the existing "meshes" feature, as the tracking will probably show that the feature is not used
- [ ] rename "meshes" tab to "isosurfaces" tab
- [ ] show generated isosurfaces in a list in the "isosurfaces" tab
- [ ] for each isosurface, show a loading indicator and a cancel button if the isosurface is loading. if it's not loading, indicate this somehow
- [ ] in case of empty list, show hint for "shift + click" and in case the option is not enabled in the setting, show a button for that

Later / Nice to have:
- [ ] "resume"-button for incomplete isosurfaces
- [ ] "create dense isosurfaces for current viewport"-button

**Comment by philippotto** [comment]
> remove the existing "meshes" feature, as the tracking will probably show that the feature is not used

As assumed, the analytics data shows that the STL import has been almost completely unused (zero for mhlab and two occurrences on demo in the last 3 months).

So, we should be ok to remove the mesh functionality and follow the steps outlined above.

**Comment by philippotto** [comment]
Update: For our segmentation project, we are currently planning a "compute isosurface" feature which outputs STLs. So, it seems as if we would need to keep the STL feature after all.

**Comment by fm3** [comment]
It would also be cool to place the precomputed meshes on the server (next to the segmentation layer) and serve them via webknossos

**Comment by normanrz** [comment]
I think this issue is superseded by newer ones. See Epic #5228
