### ISSUE TITLE
Implementation and documentation for wk-related tools and libs

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3588]
The readme should feature all wk-related tools/libs (e.g., the nml lib).

**Comment by hotzenklotz** [comment]
FYI, this is available in webKnossos docs https://docs.webknossos.org/reference/tooling

Probably still a good idea to update the ReadME to point it to the docs.

**Comment by jstriebel** [comment]
superseded by https://github.com/scalableminds/webknossos-libs/issues/379
