### ISSUE TITLE
Public tracings for non-public datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3599]
Currently, the frontend forbids public tracings for non-public datasets. However, non-public datasets may be shared with a token. It would be great to allow the publication of the tracing and compose an URL with dataset token, e.g. `/annotations/Explorational/<annotation_id>?token=<dataset_token>#2083,4052,1830,0,2.20,75`.

**Comment by daniel-wer** [comment]
@normanrz Didn't you mention this already worked if the dataset_token was appended manually? I can't get this to work locally :/
I copy the URL of the explorative tracing, then log out and then append the dataset_token obtained in the Dataset - Edit view. Then I get an `Annotation couldn’t be found. If the annotation is not public, you need to log in to see it.` error.

**Comment by daniel-wer** [comment]
Nvm, got it now. You had to make the dataset public first, then make the tracing public, then make the dataset private again. Afterwards, you can include the dataset_token manually to access the annotation when not logged in.
I'll adapt the frontend to include the dataset_token in the annotation sharing link if the dataset is not public.

**Comment by daniel-wer** [comment]
@philippotto @normanrz Should it still be possible to make a dataset public from the annotation share modal? It's not strictly needed any longer, because the dataset_token is included in the sharing link if the dataset is not public.

**Comment by normanrz** [comment]
I changed the switched the annotation to public in the database directly.
I don't think it is necessary to make the dataset public from that modal, anymore.
