### ISSUE TITLE
datastore tokens expire, saving fails without good message

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3607]
datastore tokens expire after 1 day. we see users keeping open tracing tabs for longer than that, though. we should discuss how this is handled. can the frontend maybe request a new token?
I’ll also see that the back-end will send a more appropriate error message.

**Comment by daniel-wer** [comment]
I was under the impression that the frontend _should_ request a new token in that case. Is this the token requested at `/api/userToken/generate`?

**Comment by daniel-wer** [comment]
I'll check whether the token renewal still works as expected :)
