### ISSUE TITLE
Show proper error for unsupported mappings (8-Bit and 16-Bit)

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3636]
When activating a mapping on a 16-bit segmentation, it is correctly applied in the "segmentation" tab, but not in the viewports:

![screenshot 2019-01-16 at 16 49 44](https://user-images.githubusercontent.com/1701960/51260569-de887700-19ae-11e9-93e2-684064e93dd9.png)

Here you can see how the two segments at current position and mouse position are both mapped to ID 1, but they are rendered in different colors.

I wasn't able to repreduce this on a 32-Bit segmentation.

**Comment by philippotto** [comment]
See #2738 ;) Is this important for your workflow, @georgwiese?

**Comment by georgwiese** [comment]
Ah, I see :)

Actually, it's not important, because we can just use 32-Bit segmentations. That makes sense for us anyway because 2<sup>16</sup> isn't a lot. For my purpose, it would be fine if WK didn't support it, but it shouldn't fail silently.

**Comment by philippotto** [comment]
Ok, cool, then I'll change this issue to cover proper error reporting and leave the other issue at low-pri.
