### ISSUE TITLE
Datastores occasionally crash with SIGBUS

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3643]
in `~StubRoutines::jlong_disjoint_arraycopy`

**Comment by fm3** [comment]
traced this back to memory mapped files in `ExtendedMappedByteBuffer` of webknossos-wrap.
```
sun.reflect.GeneratedMethodAccessor6.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (383
com.scalableminds.webknossos.wrap.util.ExtendedTypes$ExtendedMappedByteBuffer$$Lambda$1736.apply$mcV$sp()
```

**Comment by fm3** [comment]
closing this for now, as the frequency is fairly low and docker-compose’s autoheal should permit to recover from it.

**Comment by fm3** [comment]
Autoheal still works but it could be worth the effort of some more investigation to avoid the occasional few minutes of downtime. Could a JDK upgrade possibly help?

**Comment by youri-k** [comment]
I was reading this blog article of sublime concerning the risks of `mmap` (https://www.sublimetext.com/blog/articles/use-mmap-with-care) and they specifically mention `SIGBUS` as possible caveat. However, I don't really know, how feasible their workaround is for us.

**Comment by fm3** [comment]
Has not occurred since https://github.com/scalableminds/webknossos-wrap/pull/67 was deployed several months ago. The description from the above link indicates that the change is no guarantee, but let’s reopen this issue if it occurs again
