### ISSUE TITLE
Allow NML download without opening new window

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3667]
When downloading an NML, we currently open a new window which is not the best UX in my opinion. Something like this should work, too:

> You don't need window.open(). It's plain ugly and prone to popupblockers (where you have no control over in clients). Just window.location is sufficient if the response header of the requested download URL contains Content-Disposition: attachment. This won't change the current URL in the browser address bar nor the current page, but just pop a Save As dialogue.
>
> E.g.
> 
> `window.location = 'http://download.winzip.com/winzip145.exe';`

source: https://stackoverflow.com/a/3645025/896760

The back-end could set the content-disposition label only when the URL has a specific get parameter (e.g., `forceDownload=true`), in case the URL is also used to directly view the NML in the browser.

**Comment by fm3** [comment]
This has been fixed in the meantime (at least for me in firefox, no new tab is opened anymore)
