### ISSUE TITLE
Avoid page reload when navigating across wK

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3672]
Using code like `<a href="/dashboard">` to navigate across wK will cause a new page load, forfeiting the benefits of wK being a single page app. We should replace those occurrences with a Link (`<Link to="/dashboard">`) which is much faster, because it doesn't cause a new page load.

**Comment by hotzenklotz** [comment]
@daniel-wer As far as I can tell, most links now use the `<Link> tag. Only outgoing links rely on the traditional `<a>` tags. I vote to close this issue.

**Comment by daniel-wer** [comment]
Seems fair, if we find any offenders we'll create separate specific issues.
