### ISSUE TITLE
Improve sign-up flow on demo.webknossos.org

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3683]
We need to rethink the user journey on demo because it is complicated and confusing.
* The user looks at the gallery and opens a dataset.
* Next, they want to start an annotation and click on the button.
* Then, they should be redirected to the signup page with a suitable org pre-selected (e.g. Demo organization).
* This signup should be auto-activated and they are logged in immediately.
* Now they should be back in the dataset with a new annotation.
* Boom.

Steps:
- [x] Add "start annotation" button #3490 
- [ ] Pre-select default org
- [ ] Auto-activate for particular org
- [ ] Redirect after signup/login
- [ ] Add some friendly text to explain what the user is doing

**Comment by daniel-wer** [comment]
> * Add some friendly text to explain what the user is doing

Did you have something in mind here? Which step of the sign-up flow is this about? :)

**Comment by normanrz** [comment]
With your modal solution, I think there is no need for explanatory texts.

**Comment by daniel-wer** [comment]
@normanrz The `defaultOrganization` can now be set in the application.conf/kube template. Also auto verification can be enabled per organization in the DB using `update webknossos.organizations set enableAutoVerify = true where name = '<organization_name>'`.
