### ISSUE TITLE
Sparse mappings

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3735]
It should be possible to define a "fallback segment id" to which unmentioned segments are mapped. That way, you could map everything to "hidden" (id == 0), except for only a few classes. This would reduce this size of mappings in several cases.

**Comment by daniel-wer** [comment]
The mapping.json file that is put on disk in the dataset folder, has an optional `hideUnmappedIds` boolean property which should be exactly what you're looking for. :)

For example, a mapping like this:
```
{
  "name": "unmapped",
  "classes": [[1, 2, 3], [4, 5, 6]],
  "hideUnmappedIds": true
}
```
will map all ids but 1-6 to 0 (hidden).

**Comment by philippotto** [comment]
Ah, nice! I vaguely remember that you implemented this now :) @georgwiese Is this would you had in mind?

**Comment by manuel-berning** [comment]
Hi Philipp & Daniel,

Sounds like exactly what I need (I was talking to Georg about this on Monday and I guess he forwarded accordingly). Thanks for the clarification, will try it!
