### ISSUE TITLE
Create org from register form and register from onboarding

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3742]
Currently, users are asked to contact us for creating an organization on demo. But actually they can do that themselves with the onboarding flow. We can just link there.
<img width="578" alt="bildschirmfoto 2019-02-06 um 17 27 21" src="https://user-images.githubusercontent.com/335438/52356649-e75fec00-2a34-11e9-9449-6181d6456011.png">

Similarly, the onboarding flow should have a way to register/login instead of creating a new org. 

Relates to #3683 (somewhat).

**Comment by daniel-wer** [comment]
> Similarly, the onboarding flow should have a way to register/login instead of creating a new org.

I don't see the use case for this, yet, wouldn't the user simply login/register if there already is an organization? Or is this for the case where the onboarding flow is interrupted/not completed?
