### ISSUE TITLE
Make webKnossos black?

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3755]
Let's discuss ⚔️ 
![](https://media.giphy.com/media/6x4CLjC8KofaU/giphy.gif)

**Comment by hotzenklotz** [comment]
We had this once before and hardly anyone used a dark theme. 

IMO dark themes are only useful when working in the dark. wK is a professional science tool - most people will use it during the day.

**Comment by philippotto** [comment]
I'd only do it if we find a working css rule set specialized for antd, since that will be the biggest cost for implementation and maintenance. So far, I couldn't find such rule set, which is why I'd defer this issue.

**Comment by philippotto** [comment]
Let's reopen in a year :P

**Comment by normanrz** [comment]
<img width="1457" alt="Bildschirmfoto 2019-10-10 um 18 30 40" src="https://user-images.githubusercontent.com/335438/66588188-347bfb00-eb8c-11e9-8e21-23eb021fdac6.png">
<img width="1457" alt="Bildschirmfoto 2019-10-10 um 18 19 22" src="https://user-images.githubusercontent.com/335438/66588189-35149180-eb8c-11e9-96de-36766d54bf3b.png">
<img width="1457" alt="Bildschirmfoto 2019-10-10 um 18 24 26" src="https://user-images.githubusercontent.com/335438/66588190-35149180-eb8c-11e9-9d38-3c7da553dd75.png">
<img width="1457" alt="Bildschirmfoto 2019-10-10 um 18 19 18" src="https://user-images.githubusercontent.com/335438/66588192-35149180-eb8c-11e9-9642-8d1a2e59bf6a.png">

**Comment by jstriebel** [comment]
[![](https://img.youtube.com/vi/XlgqZeeoOtI/0.jpg)](https://www.youtube.com/watch?v=XlgqZeeoOtI)

**Comment by daniel-wer** [comment]
Done in https://github.com/scalableminds/webknossos/pull/5407
