### ISSUE TITLE
Bug in onboarding flow dataset upload

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3803]
How to reproduce:
* Freshly clone webknossos
* `docker-compose pull webknossos && ./start-docker.sh`
* http://localhost:9000 -> Get started -> Dataset
* Drop [e2006](https://static.webknossos.org/data/e2006_wkw.zip)
* Error message in Dataset import modal

**Comment by fm3** [comment]
This works for me, it was probably fixed along with #3802. closing this now, please reopen if it occurs again :)
