### ISSUE TITLE
Add features and pricing to demo startpage

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3839]
<img width="1634" alt="bildschirmfoto 2019-02-27 um 14 13 38" src="https://user-images.githubusercontent.com/335438/53493335-6af08400-3a9b-11e9-9fb5-4b84270395a3.png">

* Add page with webKnossos features
* Add page with pricing information
* Add support page
* Add special navbar for public webKnossos area
* Rework the buttons in the header

**Comment by hotzenklotz** [comment]
Feature and Pricing Mockup WIP 
https://ho6qk.draftium.site
