### ISSUE TITLE
Moving black bar in oblique mode

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3846]
The bar moves vertically when moving through the dataset.

![roi2017_wkw__574_533_562__oblique](https://user-images.githubusercontent.com/1702075/53572070-ad34c680-3b6a-11e9-9bda-3a7c1302b67c.png)

**Comment by philippotto** [comment]
@daniel-wer Do you have a link to reproduce this?

**Comment by daniel-wer** [comment]
For example in this dataset: https://webknossos.brain.mpg.de/annotations/Explorational/5c7e80db010000fb04ab9da1#2715,4395,1728,2,2.00,0.00,0.00,0.00

**Comment by hotzenklotz** [comment]
@daniel-wer I was not able to reproduce this any longer, perhaps this issue can be closed.

**Comment by daniel-wer** [comment]
Yep, I cannot reproduce it either.
