### ISSUE TITLE
3D viewport for low res datasets is broken

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3849]
<img width="584" alt="bildschirmfoto 2019-02-28 um 18 18 02" src="https://user-images.githubusercontent.com/335438/53585005-3ce76e80-3b85-11e9-915e-f5281ea0a8b0.png">
See https://webknossos.org/datasets/Demo_Organization/MPRAGE_250um/view#320,440,440,0,1.30
Reproduce locally with https://static.webknossos.org/data/MPRAGE_250um.zip

**Comment by hotzenklotz** [comment]
Additional information: The dataset itself is not very large, but the voxel size is in millimeter (`mm`). Likely, the 3D viewport uses same constants in `nm` and that messes with things.
