### ISSUE TITLE
/ redirects to login after fresh repository clone, should be onboarding flow?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3871]
* Freshly clone webknossos
* `docker-compose pull webknossos && ./start-docker.sh`
* `http://localhost:9000`

**Comment by fm3** [comment]
@daniel-wer I believe you made some changes here, is this intentional?

**Comment by daniel-wer** [comment]
No this is not intentional, but it is caused by my recent changes, yes.
I suppose, if there are no organizations yet, users should be redirected to the spotlight page (as before) or maybe even better directly to the onboarding page.
