### ISSUE TITLE
volume project download: zipfiles truncated after timeout?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3874]

**Comment by fm3** [comment]
looks related to previously closed #3007 (the fix from then is still in place though)

**Comment by philippotto** [comment]
@fm3 can you share the workaround script please?

**Comment by fm3** [comment]
workaround:
download zip the normal way, it should give the NMLs with the metadata.
to get the full volume zips, 

save the output of the sql query
```
select a._task, a.volumeTracingId from webknossos.annotations_ a
join webknossos.tasks_ t on a._task = t._id
join webknossos.projects_ p on t._project = p._id
where p.name = '<volumeProjectName>'
and a.state = 'Finished'
group by a._task, a.volumetracingid
```
as csv, should look like
```
"_task","volumetracingid"
"5f5c42020100003521a33f21","32d2a10a-d731-4251-ac51-860e805a2c40"
"5c5c71f90100007020c30560","d07d9735-49ec-451a-b1f1-120300c18fd8"
…
```
which I edited using multicursor to be

```
$token="<replace me by what you see at /api/buildinfo>"

wget -O 5f5c42020100003521a33f21.zip https://<tracingStoreDomain>/tracings/volume/32d2a10a-d731-4251-ac51-860e805a2c40/allData?token=$token
wget -O 5c5c71f90100007020c30560.zip https://<tracingStoreDomain>/tracings/volume/d07d9735-49ec-451a-b1f1-120300c18fd8/allData?token=$token
…
```

**Comment by daniel-wer** [comment]
Can we consider this fixed for now? :)

**Comment by fm3** [comment]
I guess so, yes. One last thing: since this operation is blocking on the server and can take quite a while, it might be worth communicating to the user that they have to wait for some time. Could the front-end provide some sort of loading indicator there? Otherwise, users may get frustrated and leave, or restart, and thus stressing the server. But this might be better tracked in a separate issue
