### ISSUE TITLE
Store layout configs on server instead of localStorage

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3877]
Should be one json field in the user configuration, so that localStorage set/get is "simply" replaced with a get/set route to the backend.

**Comment by youri-k** [comment]
@philippotto I added a the `null` default for the layouts key. If you need anything more, just ping me :slightly_smiling_face:

**Comment by philippotto** [comment]
@youri-k On a second thought, I'm hesitant to add the layout to the user settings, since it can be relatively big. A typical user config is around 1 kb at the moment. A layout config can easily be 20 to 40 kb. Thus, the size of the user config would increase by a factor of at least 20. Maybe we should put this into a different route?

also @fm3 for one more opinion..

**Comment by fm3** [comment]
That’s a good point, at least the current procedure of updating the user config on every slider move would possibly be hindered. I’m not sure how big the effect is, but an additional field / route is of course also feasible.

**Comment by philippotto** [comment]
> but an additional field / route is of course also feasible.

Ok, then let's do this. (@youri-k :see_no_evil:)

**Comment by philippotto** [comment]
@youri-k just a friendly reminder :) can you estimate when you will be able to get to this?

**Comment by philippotto** [comment]
It turned out to be a bit tougher than expected and was down-prioritized. Closing for now.
