### ISSUE TITLE
Reset Layout breaks inputcatcher mouse handling

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3879]
After resetting the layout, inputcatcher mouse handling is broken. Setting a node, using right-click, will place the node at a wrong position, zooming in the 3D view is also not working as intended.
I investigated this and it seems to happen because the `domSelector` reference in the `input.js` - `InputMouse` is obsolete after resetting the layout (`this.domElement.getBoundingClientRect()` always returns 0s).

One way to fix this would be to always use `document.getElementById(...)` instead of caching the reference. According to https://stackoverflow.com/questions/12514970/is-getelementbyid-efficient this is fairly efficient.

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer Thanks a lot for already investigating this issue and also providing a conceptual fix :smile:
