### ISSUE TITLE
Starting tracing with only the 3d viewport visible breaks the other viewports

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#3881]
Open any tracing view in orthogonal view mode. 
Arrange the viewports as displayed in the picture and set the 3d viewport to be visible.
Then reload the page and open a tracing viewport. All 3 other viewports are colored only in their specific color. Rearanging and resizing of viewports does not help, only reloading the page.

**Comment by MichaelBuessemeyer** [comment]
![Screenshot from 2019-03-12 13-58-12](https://user-images.githubusercontent.com/39529669/54202170-bd846400-44cf-11e9-927b-1128676e2564.png)

**Comment by MichaelBuessemeyer** [comment]
This might be related to #3882

**Comment by daniel-wer** [comment]
Cannot reproduce any longer on our master, can you confirm @MichaelBuessemeyer ? If so, the issue can be closed.

**Comment by MichaelBuessemeyer** [comment]
Closing this issue as this is acceptable behavior.
