### ISSUE TITLE
Make frontpage usable on mobile

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3890]
Some low hanging fruits to make the frontpage more usable on mobile. This is necessary for our SEO ranking (bad mobile UX will be downranked).

- Organize login into dropdown (see #3765) 
- [Set viewport](http://html5-mobile.de/blog/meta-viewport-fuer-mobile-anpassen) maybe to 600px
- Adapt publication gallery to work with the smaller viewport

**Comment by philippotto** [comment]
@hotzenklotz Can you create a PR for your commits and summarize what still needs to be done? Then, we can delegate the remaining work if needed.

**Comment by hotzenklotz** [comment]
Yes, Sir!

<img src="https://media.giphy.com/media/gKmwTEH4vyd2M/giphy.gif">
