### ISSUE TITLE
in skeleton tracings, load downsampled segmentation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3894]
the argument that only segmentation that can also be edited should be loaded does not hold for skeleton-only tracings

**Comment by philippotto** [comment]
Hmm, seems to work in some cases. E.g., https://webknossos.brain.mpg.de/annotations/Explorational/5ee1ffba010000f0131ce406#4941,2651,4096,0,2.200

Not sure what the difference is.

**Comment by philippotto** [comment]
Couldn't reproduce this. And additionally this should also be resolved with the upcoming hybrid + multi-res volume approach.
