### ISSUE TITLE
Support adding neuroglancer dataset with authentication

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3898]

**Comment by daniel-wer** [comment]
@jstriebel I remember that I read more about this somewhere but I can't find it :/ Could you refer me to a description of what to do to implement this or add it here?

**Comment by jstriebel** [comment]
@daniel-wer Sure. There is an old example from the PR here:
https://github.com/scalableminds/webknossos-connect/blob/ee1ad366e72fe4e185292b87d2354a36547e487a/data/datasets.json#L30-L49

I deleted the credentials mentioned there, but it shows the principle. The idea was to upload the credentials json and post it in the `credentials` field.
