### ISSUE TITLE
Add Intercom to webknossos-demo

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3918]

**Comment by normanrz** [comment]
```
<script src="https://embed.small.chat/T02A8MN9KGH57WQMC5.js" async></script>
```

**Comment by hotzenklotz** [comment]
FYI, our Hubspot has a chat bubble thingy.

**Comment by philippotto** [comment]
@normanrz do we still want to do this?

**Comment by normanrz** [comment]
Yeah, would be neat. But low-pri.

**Comment by hotzenklotz** [comment]
Related to #6502

**Comment by philippotto** [comment]
> Related to #6502

I think the issue covers the intercom idea sufficiently. The intercom integration wouldn't give immediate replies anyway, since we wouldn't use a chat bot, so, the rest of the conversation would be via email anyway.

Closing. Feel free to reopen if you disagree.
