### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3925]
For some datasets, I can open them by clicking "view" on the dataset page, but if I try to open a link in a new tab, or copy the link, or refresh the page, I'm getting a 404.

**Comment by fm3** [comment]
the 404 is coming from the back-end, which is unexpected.
https://github.com/scalableminds/webknossos/blob/master/app/RequestHandler.scala#L28 and following should serve the main html (resulting in the front-end router deciding what to show). This is where we should investigate
