### ISSUE TITLE
Add shortcut to maximize pane

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3926]
Should maximize the pane that "contains" the mouse cursor.

**Comment by MichaelBuessemeyer** [comment]
I'd suggest about win/command + up key for maximizing and win/command + down key returning from maximized view. These are the shortcuts used on windows / linux. I don't know how iOS handles this :slightly_smiling_face:

**Comment by daniel-wer** [comment]
I'd think that would interfere with the native shortcuts then, what if the user wants to maximize/minimize the browser window where webKnossos is opened :/ There already is some ongoing discussion in #3927 regarding the shortcut :)
