### ISSUE TITLE
Improve Apple Magic Mouse support

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3933]
When using WK, I often accidentally scroll and then lose the position.

I see two ways to improve this:
- [ ] A simple fix should be to disable scrolling while dragging. It happens to me a lot that I want to move in the XY plane and suddenly move in Z.
- [ ] First, it seems like WK is very sensitive when it comes to scrolling. When I scroll slowly, I'm moving at the same speed than if I scroll fast. I'm guessing that the scroll events sent to the JS code reflect that difference but WK ignores it. Scrolling just one slice is nearly impossible.

**Comment by philippotto** [comment]
> First, it seems like WK is very sensitive when it comes to scrolling. When I scroll slowly, I'm moving at the same speed than if I scroll fast. I'm guessing that the scroll events sent to the JS code reflect that difference but WK ignores it. Scrolling just one slice is nearly impossible.

That's an interesting problem. I researched a bit, but found no obvious solutions to this problem. We probably have to play around with various mice to test this. Also, I'll put this here for reference:  https://gist.github.com/akella/11574989a9f3cc9e0ad47e401c12ccaf

> A simple fix should be to disable scrolling while dragging. It happens to me a lot that I want to move in the XY plane and suddenly move in Z.

We can do that, but to be honest, this sounds like a poor mouse design if you can't drag without scrolling :see_no_evil: *scnr*

**Comment by philippotto** [comment]
Let's do the first item in this sprint.

**Comment by georgwiese** [comment]
Disabling scrolling while the mouse button is pressed fixes the issue for me!

Would it be possible to do the same in the 3D viewport?

**Comment by philippotto** [comment]
> Would it be possible to do the same in the 3D viewport?

Yes, this sounds sensible. I'm afraid it's a bit more cumbersome to do, because we are using some pre-baked 3D camera code which we have to fumble with. However, let's have a look at it.
