### ISSUE TITLE
Opening settings moves everything else to the right

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3934]
For example, when one plane is maximized, you can't close it without scrolling right.

**Comment by valentin-pinkau** [comment]
![settings](https://user-images.githubusercontent.com/2582395/54763597-8f510380-4bf6-11e9-985b-0df8a55da4bf.gif)

**Comment by hotzenklotz** [comment]
checkout https://ant.design/components/drawer/

**Comment by hotzenklotz** [comment]
Drawer solution was discarded since it overlayed on the data/blocked visibility.

https://user-images.githubusercontent.com/1105056/60337515-90d35a00-99a3-11e9-8c76-d0dd2778a457.gif
