### ISSUE TITLE
Wobbling XY plane

### ISSUE THREAD

**Issue by valentin-pinkau** [scalableminds/webknossos#3935]
Without interpolation, slow moving speed (100 nm/s), and medium render quality the XY plane is wobbling as you move in the y-direction:
![whiggle_webknossos](https://user-images.githubusercontent.com/2582395/54763974-36359f80-4bf7-11e9-9e3c-fe419916d472.gif)

**Comment by philippotto** [comment]
See https://stackoverflow.com/questions/55531292/how-to-avoid-rendering-artifacts-due-to-imprecise-world-coordinates-in-webgl.

**Comment by philippotto** [comment]
We might be able to clip the move value to appropriate values, but I'm not sure how to do this reliably/predictably.

**Comment by philippotto** [comment]
Can't/won't fix for now.

**Comment by philippotto** [comment]
Due to priority, this issue is probably still a won't fix, but I came across this article which might be of interest in case we change our mind at some point: https://news.ycombinator.com/item?id=33948769
Not sure how the article relates, but it also talks about wobble artifacts.
