### ISSUE TITLE
Show case annotations in publications view

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3937]
Right now, featured publications link datasets (including segmentations in case of volume annotations). However, skeleton tracings cannot be linked currently. It would be cool to be able to also link concrete annotations instead of only datasets.

**Comment by normanrz** [comment]
We are now routinely having annotations as part of a publication. It would be great if there was a way to attach them to a publication entity.

**Comment by fm3** [comment]
I guess the simplest way for this would be a n:1 relationship (meaning a publication can have n annotations, but an annotation belongs to at most one publication). Do you think that is sufficient?

I would also suggest introducing new routes `GET api/publications` and `GET api/publications/:id`, as opposed to the current approach of using the dataset list to scrape this together.

**Comment by normanrz** [comment]
sounds good

**Comment by fm3** [comment]
- [ ] new api route api/publication with new json schema
 - [ ] annotation table (schema.sql) should have column _publication, be fetched for above route
 - [ ] evolution + version bump for sql schema
 - [ ] thumbnail route in tracingstore
    - [ ] use mapping, edit position, zoom level from tracing object
    - [ ] fetch fallback layer data if needed
 - [ ] coordinate with front-end how the api is used 
   - [ ] (should there be a thumbnail redirect on wk side `/annotations/:typ/:id/layer/:tracingId/thumbnail` or can the front-end directly query from tracingstore?)
    - [ ] what should be in the json? What should be omitted (to avoid data leaks)

**Comment by leowe** [comment]
While working on the thumbnail route for the annotations, @fm3 and I noticed that it requires a lot more effort than previously thought (which position to show in the thumbnail, how to get all layers from the data set as well, apply mappings, how to fetch the data so that in the buckets where there is no annotation the segmentation is loaded), so we decided to split this task into multiple parts.

Follow-up: #6332
