### ISSUE TITLE
Unable to navigate away from viewer

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#3947]
Sometime I am stuck in the tracing UI and can not navigate away. Most of the times this happens when clicking the wk logo but sometimes also when using the browser back button.

Steps to reproduce on wk.org:
1. Open any public dataset in view mode (not logged in)
2. Move around
3. Click on wk logo
4. Site is refreshed (whitepage with "wk is refresh" is shortly visible) then the tracing UI loads again instead of the dashboard :-(

I am not sure if it helps to navigate back and forth a few times in between datasets to mess up the history object?

**Comment by philippotto** [comment]
I cannot reproduce this on Linux :S Do we know whether this only affects OS X users?

**Comment by fm3** [comment]
I can also not reproduce this. Is this still happening for you @hotzenklotz ?

**Comment by hotzenklotz** [comment]
I haven't experienced this in some time. Closing for now.
