### ISSUE TITLE
Shared space for annotations

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3950]
Currently, each user can have their own explorative annotations. The only way to share these is to send a link to colleagues or look up annotations from the user page.
It would be great if there was a way to permanently share annotations with teams or users. Solutions could be a) a shared team space for annotations, b) a tab with "shared with me" annotations or something else 👯

**Comment by philippotto** [comment]
Maybe we could do this with #3937 in mind.

**Comment by philippotto** [comment]
@normanrz do you want to set up a meeting for this topic?

**Comment by normanrz** [comment]
Maybe we can have a brief chat after today's sprint meeting

**Comment by philippotto** [comment]
- [ ] add a page which lists "listed" annotations (which are visible for the current user)
- [ ] change visibility modal to
  - [ ] allow making an annotation listed (exact UX yet to be determined)
  - [ ] list teams for which the annotation should be visible and/or (?) listed
