### ISSUE TITLE
It is hard to scale the brush size with wheel

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3964]
Maybe a logarithmic scale would help

**Comment by MichaelBuessemeyer** [comment]
@normanrz With logarithmic scale you mean, that the changes of the brush size are not detailed enough when already having a big size? Or is it not detailed enough for small sizes? Could you please clarify this? :slightly_smiling_face:

**Comment by normanrz** [comment]
Changes are too fast when small. I cannot get a precise size when the brush is small.
