### ISSUE TITLE
Public datasets are missing form onboarding

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#3972]
User feedback:

> While creating my organisation on webknossos.org I didn't see the full flight brain datasets. Would be nice if this was a default test dataset

On wk.org, when using the onboarding flow and creating a new organization you are prompted to upload a dataset or download a test datasets. The public datasets on the wk instance are ignored / not shown.

We should feature the public datasets more prominently in this step. Perhaps, have a list of the first 10 public datasets and "see more" or so.

![image](https://user-images.githubusercontent.com/1105056/55225809-c6856d00-5213-11e9-9be0-79365ba072ca.png)

**Comment by hotzenklotz** [comment]
Mayhaps, we could consider to skip this step entirely. ATM, users are not encouraged to upload their own data on the free tier of wk.org.

**Comment by philippotto** [comment]
- [ ] remove page when on demo
