### ISSUE TITLE
Why no find data for segementation?

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3973]
<img width="341" alt="Bildschirmfoto 2019-03-29 um 12 07 11" src="https://user-images.githubusercontent.com/335438/55228781-4f53d700-521b-11e9-8559-283064c7c767.png">

**Comment by MichaelBuessemeyer** [comment]
@philippotto @normanrz  What about also adding a switch for visibility toggling?

**Comment by normanrz** [comment]
Yes. I think we should treat segmentation layers the same as color layers in the UI (as much as possible).

**Comment by MichaelBuessemeyer** [comment]
The visibility toggling feature for segmentation layer will be done in another issue and pr.

ToDo: add reference to this issue
