### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#3980]
Currently CI (again) needs >20min even if only the README changed. Some ideas how to change it:
* split frontend & backend
  This would help with parallel builds and caching, only rerunning actually differing parts.
  Even if we don't split it for now, we should at least perform only relevant tests/linting/…

- [x] merge-queue to lessen the pain
* speed up scala compilation
  @fm3 Had some ideas here (moar privates I think?)
* beefier CI servers

**Comment by fm3** [comment]
(not sure if more private fields would decrease the CI compile time. I think it’s mostly about incremental compilation)

**Comment by jstriebel** [comment]
Parallelizing the steps would be a win! We might directly consider moving to gh actions.

**Comment by hotzenklotz** [comment]
We recently update to a beefier CircleCI server. I don't think there are any other easy wins. Voting to close this issue.

**Comment by fm3** [comment]
One thing that could still produce speedups with relatively little effort is skipping steps depending on git diff to master. I created the additional issue #6523 for that, so let’s close this one here.
