### ISSUE TITLE
Add undo for volume annotations

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4001]

**Comment by MichaelBuessemeyer** [comment]
I just did some brainstorming about this feature:
 The main problem that came into my mind is, that if the user draws about already annotated voxels, the previous label of those voxels cannot be reconstructed by simply saving the "drawingActions" and reverting them.
=> All buckets that got annotated need to be saved in the state they were before they got annotated. The memory consumption of this might be pretty high, even when the data is compressed with the newest volume feature all magnifications are edited at once.


My thoughts about how to implement this assuming all buckets are already loaded by the backend: 
 - Once a bucket gets annotated during the annotation process, the bucket itself pushes its data without the annotation to the "volume undo bucket stack". 
 - If the bucket was already pushed, don't push the bucket again.
 - The undo saga has the "volume undo bucket stack" and tracks all "Start editing" and "finish editing" volume actions and saves them in a list together with the compressed (lz4) buckets that got annotated.

- The user uses undo, all bucket between the last "finish editing" and "start editing" action in the will replace the current buckets. Thus the whole annotation stroke should be undone. 

@philippotto Does this make sence?
