### ISSUE TITLE
merge demo feature flags into one

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4008]

**Comment by hotzenklotz** [comment]
Some demo specific stuff that I remember
- Pricing & Features links in Header (and Router)
https://github.com/scalableminds/webknossos/blob/master/frontend/javascripts/navbar.js#L308

**Comment by jstriebel** [comment]
see flags here:
https://github.com/scalableminds/kube/blob/master/charts/webknossos/release-values/demo.yaml#L24-L29
