### ISSUE TITLE
Straight cut in isosurfaces rendering

### ISSUE THREAD

**Issue by leowe** [scalableminds/webknossos#4013]
Looks like there might be an off by one error somewhere?
Could also be caused by my data...
![Bildschirmaufnahme 2019-04-11 um 18 56 14](https://user-images.githubusercontent.com/13684843/55976736-6a97fb00-5c8d-11e9-8219-6987dfe4c580.gif)

**Comment by philippotto** [comment]
Can you share the segmentation layer somewhere?

**Comment by philippotto** [comment]
@leowe ping :)

**Comment by leowe** [comment]
Sorry, I somehow screwed my notification settings up...

**Comment by philippotto** [comment]
@leowe Can you share the segmentation layer somewhere?

**Comment by leowe** [comment]
https://drive.google.com/open?id=1rizxfwRdPADqueeHFvDn5SXrTazlOQs4 I uploaded the color+segmentation layer
