### ISSUE TITLE
Bug in organisation-signup

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4023]
- Open https://webknossos.org/auth/register?organizationName=Paradromics
- `The link is not valid, since the specified organization does not exist. You are being redirected to the general registration form`

**Comment by daniel-wer** [comment]
Can you still reproduce this error? I don't see any error when visiting that link.

**Comment by normanrz** [comment]
No, I can't reproduce the issue. But I just noticed the problem was a trailing `?` in the url -.-
