### ISSUE TITLE
Consider to use getElementById instead of querySelecter where possible

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4030]
By looking at the current code: We are using `document.querySelector` pretty often to look for an element given by id. Using `getElementById` would definitely speed up things (but the impact is very likely no noticeable.) 
Here is a reference post for this: [https://www.sitepoint.com/community/t/getelementbyid-vs-queryselector/280663/5](https://www.sitepoint.com/community/t/getelementbyid-vs-queryselector/280663/5)

**Comment by philippotto** [comment]
Thanks for opening this issue proactively! However, I think the perf would only matter if the method is called within a tight loop. Unless, we notice that the code is a bottleneck (e.g., via benchmarking), I'd not do anything here :)

Feel free to re-open if you disagree!
