### ISSUE TITLE
Changing the viewport distorts 3D view

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4064]
The 3D viewport doesn't survive a large layout change such as maximizing one panel:

![May-03-2019 16-57-17](https://user-images.githubusercontent.com/335438/57145984-9b6adc00-6dc4-11e9-9972-b0f520d45ae0.gif)

**Comment by MichaelBuessemeyer** [comment]
I am pretty sure that's a duplicate of #3882.
