### ISSUE TITLE
Select user when clicking on the row

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4068]
Currently, it is not possible to select a user in the user view (only for admins) by clicking anywhere on the row. Adding this would increase the UX imo.

Let's add this feature to wk :slightly_smiling_face:.

**Comment by MichaelBuessemeyer** [comment]
Here is a spike made by philipp https://codesandbox.io/s/000vqw38rl.

**Comment by philippotto** [comment]
Btw, I didn't create the code ;) It's linked from the antd docs.

**Comment by fm3** [comment]
closed via #4663 :)
