### ISSUE TITLE
Tree tab content only appears after re-switching to it

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4072]
[Link to Discuss](https://discuss.webknossos.org/t/no-trees/1464)

**Comment by daniel-wer** [comment]
Should be fixed by #4083

**Comment by daniel-wer** [comment]
Did not fix the issue, unfortunately :/

**Comment by fm3** [comment]
@daniel-wer is this a duplicate of #4807 (and thus closed by #4816)?

**Comment by daniel-wer** [comment]
Yes, good find, I'll close it :)
