### ISSUE TITLE
Reactivate GPU Factor and rename quality setting

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4074]
todo:
- [ ] reactivate quality setting / gpu factor
- [ ] properly solve the "enforce mag" issue #4075 
- [ ] rename quality to something else since existing docs point out that "quality" should be set to "high"

**Comment by hotzenklotz** [comment]
<img src="https://media.giphy.com/media/3oAkag9N2S3iZXg0ec/giphy-downsized.gif">
