### ISSUE TITLE
Allow to enforce specific mag(s) for tasks

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4075]
If the user is zoomed out too far, a toast should appear which says "please zoom in".

**Comment by philippotto** [comment]
@youri-k Could you add an `allowedMagnifications` property to the `AnnotationSettings` case class (plus all moving parts around it). I want to be able to store this property for tasks so that annotations created for a task have that property. The value should have the type `Array<Array<int>>` so that properties, such as `[[1, 1, 1], [2, 2, 2]]` are valid. I'm also fine with a general JSON type. The property should be optional. Let me know in case you have questions :)

**Comment by philippotto** [comment]
On a second thought, I think a JSON type is better. I'll probably use something as `{minMagnification: [1, 1, 1], maxMagnification: [4, 4, 4]}`.

**Comment by youri-k** [comment]
@philippotto I added the property as you can see in the commit. I hope you didn't already started working on another branch. Let me know if you need anything more :slightly_smiling_face:

**Comment by philippotto** [comment]
Excellent! I'll use your work tomorrow. However, the CI build failed in `Assert schema.sql and evolutions are equal`. Can you have a look? :)
