### ISSUE TITLE
Improve time tracking

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4076]
See https://discuss.webknossos.org/t/a-few-updates-for-the-time-tracking-tool/1374

**Comment by hotzenklotz** [comment]
Google Charts Docs: https://developers.google.com/chart/interactive/docs/gallery/timeline

**Comment by philippotto** [comment]
@MichaelBuessemeyer As I see it, the main issue is resolved, but there are three smaller follow-ups necessary (see discuss). You are on that, right?

https://discuss.webknossos.org/t/a-few-updates-for-the-time-tracking-tool/1374/8?u=potto
