### ISSUE TITLE
Deleting all trees via root group does not work

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4102]
In the cog menu for the root group, the option to delete the group is disabled. However, you can select the root group and click the "delete" button. However, nothing happens in that case.

I think it wouldn't hurt to allow deleting all trees (at least, that's what I wanted to do a few minutes ago).

**Comment by hotzenklotz** [comment]
Just ran into this well. :-(

![image](https://user-images.githubusercontent.com/1105056/70619347-280c3100-1c15-11ea-949a-f9fc6b4b774c.png)

**Comment by hotzenklotz** [comment]
Fixed by #6553
