### ISSUE TITLE
Ensure that antd tables are not too wide

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4106]
Can be provoked by zooming in.

**Comment by hotzenklotz** [comment]
`Start Tracing` etc is cut off on the right-hand side.

![image](https://user-images.githubusercontent.com/1105056/58235598-69a0c180-7d41-11e9-8609-9f0b46e15b9d.png)

**Comment by philippotto** [comment]
`overflow: auto`

**Comment by normanrz** [comment]
Would also be great if one could click the name to view the dataset.

**Comment by normanrz** [comment]
This is not ideal yet. On my monitor, I always have to scroll although there is plenty of empty space.

<img width="1523" alt="Bildschirmfoto 2019-07-04 um 11 54 36" src="https://user-images.githubusercontent.com/335438/60658080-c3250180-9e52-11e9-8cb3-1878c396dc1b.png">

**Comment by hotzenklotz** [comment]
Same here. I just briefly looked at the changes. Forcing the table column's to have a minimum width does not seem like a smart workaround. This always forces the table out of my 15" screen even though, the columns could be smaller. (In fact some columns define their width in the react code explicitly, which is overwritten by the CSS)

```
.large-table table > thead > tr > th:not(.ant-table-expand-icon-th) {
  min-width: 200px;
}
```

I wonder if removing the `min-width` is enough to solve this issue, or if it will break overflowing again.

**Comment by normanrz** [comment]
If you don't set a `min-width` or `width`, the table will never overflow the viewport and always squeeze into the existing space. See https://github.com/scalableminds/webknossos/pull/4136#pullrequestreview-253231396

**Comment by MichaelBuessemeyer** [comment]
> (In fact some columns define their width in the react code explicitly, which is overwritten by the CSS)

Completely removing the general `min-width` and defining it for each column separately sounds good to me. 

The current version is not correct as you can see below (This is the explorative annotations table).

![image](https://user-images.githubusercontent.com/39529669/60978260-27533400-a331-11e9-81b4-e716b2aed5f4.png)

@normanrz 

> If you don't set a min-width or width, the table will never overflow the viewport and always squeeze into the existing space

This is (afaik) correct, but some columns do not need to have a `200px min-width` so we have to reduce it for them manually.

**Comment by MichaelBuessemeyer** [comment]
Repoening this as the problem still exists for chrome.
![width-bug](https://user-images.githubusercontent.com/39529669/63166558-0caa6400-c02f-11e9-941f-84d25aaa6589.png)
