### ISSUE TITLE
Error on "Add Sample Dataset" when no dataset exists yet

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#4113]
When flollowing the installation guide from the README, I found the following error when I tried adding a sample dataset:

![Bildschirmfoto von »2019-05-24 13-39-04«](https://user-images.githubusercontent.com/7216331/58326066-ffb11680-7e2b-11e9-97f0-b97fbb40b325.png)

The log shows:
```
webknossos_1               | 2019-05-24 11:38:46,603 [DEBUG] com.scalableminds.webknossos.datastore.rpc.RPCRequest - Sending WS request to http://localhost:9000/api/datastores/localhost/verifyUpload (ID: 4). RequestBody: '{"name":"Sample_FD0144_wkw","team":"Jonathans Org"}'
webknossos_1               | 2019-05-24 11:38:46,698 [ERROR] com.scalableminds.webknossos.datastore.rpc.RPCRequest - Unsuccessful WS request to http://localhost:9000/api/datastores/localhost/verifyUpload (ID: 4).Status: 404. Response: {"messages":[{"error":"Organization {0} couldn￢ﾀﾙt be found"}]}
```

After adding a neuroglancer dataset everything works as expected, I am able to add sample datasets.

**Comment by fm3** [comment]
I traced the issue back to the organization name. The frontend passes the organization displayname to the sample dataset download (and probably also list) requests. It should be the normalized name (with underscores etc, that is already used e.g. when viewing a dataset) @daniel-wer @philippotto @MichaelBuessemeyer I’m not sure how to properly change that, could we re-assign this issue?
