### ISSUE TITLE
Hybrid tasks with given NML 

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4117]
[Link to Discuss](https://discuss.webknossos.org/t/volume-tracing-with-given-nml/1485)

@fm3 When you have a few minutes, could you give a rough estimation about how much work this would require for the back-end? 1h? 4h? More than that? :)

For the front-end, I'd estimate 4 hours.

**Comment by fm3** [comment]
I’d also go with maybe 4 hours for the backend

**Comment by youri-k** [comment]
@philippotto ToDo:
- [ ] allow creation of hybrid task types
- [ ] allow file upload for hybrid task types

**Comment by philippotto** [comment]
@youri-k I pushed a commit which should resolve these todos. Please check whether that's what you had in mind :)
