### ISSUE TITLE
Restrict dataset name length in table

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4126]
...so that the buttons on the right remain visible.

<img width="1598" alt="Bildschirmfoto 2019-06-12 um 14 47 10" src="https://user-images.githubusercontent.com/335438/59352500-22469900-8d21-11e9-9661-63e57c8a8ddb.png">

**Comment by normanrz** [comment]
I guess `word-break: break-word;` for these cells should do the trick

**Comment by philippotto** [comment]
Duplicate of #4106. I'll add break-word for the dataset names and overflow auto so that even if the table is too wide, the user can at least scroll.
