### ISSUE TITLE
add wkignore directory in dataset dirs

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4128]
a directory within a dataset dir that is not interpreted as a layer, where e.g. aligning debug files can be dumped without confusing wK

**Comment by philippotto** [comment]
So, everything would need to be moved into that directory? As an alternative, we could have a ".wkignore" file which explicitly lists what should be ignored. I don't have a strong preference here, though. An advantage of that would be that we don't need to move existing data, but instead just can dump a wkignore file into it.
