### ISSUE TITLE
Hide settings when hiding layers

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4129]
When one clicks to hide a dataset layer the histogram is hidden but other settings remain (opacity, color). I would suggest to hide them all.

![2019-06-17 10 12 54](https://user-images.githubusercontent.com/335438/59588820-c5fcc400-90e8-11e9-8dff-a393217d3df8.gif)

Somewhat related to #4044

**Comment by MichaelBuessemeyer** [comment]
Closing this issue as it was already solved by pr #4195
