### ISSUE TITLE
Try to merge duplicated data in time tracking view

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4130]
Currently, very close time tracking data points are often displayed in separate lines by the google charts library. 
![Screenshot from 2019-06-17 16-21-15](https://user-images.githubusercontent.com/39529669/59611834-5bfe1200-911c-11e9-873f-b0672fb67720.png)

It might be possible to merge close data points into one. The duration would then be the sum of all data points. A spike might show whether this is a possible fix of data being split up into two lines in the chart.

**Comment by fm3** [comment]
@MichaelBuessemeyer do you see this problem still? I think it might have been actual overlaps in the data (which should hopefully no longer exist, after recent time logging bugfixes). If so, we can close this issue until we enounter this again.

**Comment by fm3** [comment]
I checked some more real-world data and this did not occur again. I’d assume it was actually overlapping data, and fixed by #4830  . Let’s reopen the issue if we see it again :)
