### ISSUE TITLE
Add loading indicator for volume downloads

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4131]
See https://github.com/scalableminds/webknossos/issues/3874#issuecomment-503034505

won't show any "progress" but only a "loading state" probably.

**Comment by philippotto** [comment]
Also see https://github.com/scalableminds/webknossos/pull/4134#issuecomment-504045678.

**Comment by daniel-wer** [comment]
Unfortunately, this seems to have been broken. When clicking "Download" in the "Projects" view, the spinner is only shown very briefly. Afterwards, there is no visible cue that background processing is going on, but after some time the file dialog to save the zip file opens.
