### ISSUE TITLE
Only fetch datasets according to "active" filter criteria

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4137]
In order to speed up the dataset list, we can simply query the active or inactive datasets (depending on the active filter). If the filter is set to "all" we can send one query to get all datasets.

For simplicity of implementation, we could simply refetch all datasets when changing the filter. This is typically done quite rarely, anyway, so there's no strong need to re-use existing fetch results.

**Comment by fm3** [comment]
backend routes are `api/datasets?isActive=false`,  `api/datasets?isActive=true`,  `api/datasets`
