### ISSUE TITLE
Undo "Finish and Get Next Task"

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4145]
Every other day, Hiwis click the "Finish and get next task" button by accident. Then, they have to interact with managers to undo this. Would be cool, if an undo was possible within N seconds (undo = reopen old task and cancel new task ??).

**Comment by youri-k** [comment]
Link to Discuss: https://discuss.webknossos.org/t/allow-reopening-of-tasks-for-tracers/1558/
