### ISSUE TITLE
Add shortcuts for navigating to next/prev node

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4147]
Right now, it is very hard to "navigate" along a given tree. There is no easy way to to jump/navigate to the next node within a tree. Only comment nodes can be accessed directly. Selected node in the 3D view is a workaround, but not great.

I propose to have a keyboard shortcut (and perhaps a button?) to navigate to the next or previous node in a tree/skeleton. A primary use case, is the inspection of auto-generated  skeletons.

(We already have buttons/shortcuts to navigate between the trees. This features should offer the same functionality for nodes.)

**Comment by hotzenklotz** [comment]
Caveat: Next/Previous might not be immediately clear. Could depend on the direction of the camera. Or we just go by ascending/descending node IDs.

**Comment by hotzenklotz** [comment]
<img src="https://media.giphy.com/media/Lr3UeH9tYu3qJtsSUg/giphy.gif">

**Comment by daniel-wer** [comment]
@MichaelBuessemeyer and I discussed a possible implementation of this. Our best idea yet is to use a stack where all visited nodes are pushed to. When reversing the direction, the direction the pointer is moved to in the stack is reversed as well, but all nodes in the stack are kept. When reaching one of the ends of the stack, a random node that is not at the end of the stack is chosen. If a node that is not in the stack is selected, the stack is emptied. When activating a node that was read from the stack, sanity check whether the node is still a neighbor (and exists) - if not, empty the stack.

**Comment by hotzenklotz** [comment]
@daniel-wer What is the reasoning behind those shortcuts? It is weird that one needs a modifier key and the other not. Also I would prefer if we could use neighboring keys.

**Comment by daniel-wer** [comment]
I agree that it's not ideal that a modifier would be needed for only one direction. Having a lot of shortcuts already, it's getting harder to pick unoccupied keys that "make sense". Feel free to come up with a better suggestion :)
