### ISSUE TITLE
Add api method to get active mapping

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4149]
For example, this is useful to convert a merger mode tracing to a mapping object.

**Comment by hotzenklotz** [comment]
Is this covered by this frontend API call? 

https://webknossos.org/assets/docs/frontend-api/index.html#dataapigetactivemapping

**Comment by philippotto** [comment]
The API call only returns the naming of the mapping (should be called `getActiveMappingName`). however, since we want to get rid of JSON mappings in the long run, I'd consider this issue to be not relevant anymore.
