### ISSUE TITLE
toggling tree expands/collapses unrelated subgroups

### ISSUE THREAD

**Issue by valentin-pinkau** [scalableminds/webknossos#4162]
The new feature of collapsing subtrees introduced a bug.
Activating subgroups expands or collapses other subgroups.
First bug:
Reproduce: root expand all; click on any tree -> all subgroups collapse
Second bug:
Reproduce: root collapse all; click on any tree -> all subgroups expand

**Comment by hotzenklotz** [comment]
@MichaelBuessemeyer Dod you already start with this one? Otherwise I might take a look at it.

**Comment by MichaelBuessemeyer** [comment]
@hotzenklotz I did some follow-up work on the `add-collapse-all-groups` branch for the pr [#4143](https://github.com/scalableminds/webknossos/pull/4143). But this is not related to the issue/bug.

I also shortly tried to find the bug but did not succeed. If you want you can take a look at it.

**Comment by hotzenklotz** [comment]
@MichaelBuessemeyer I have fixed the bug in PR #4178 but nothing more. No usability improvements or other feedback. Just the bug reported here. Feel free to include these other changes as well.
