### ISSUE TITLE
Volume Segmentation disappears when changing size of viewport

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4173]
When resizing the viewports in volume mode, sometimes the segmentation disappears.

Movie: https://datashare.rzg.mpg.de/s/7LLdkRrCSMZTfJ6 2

See for details: https://discuss.webknossos.org/t/segmentation-disappears-when-changing-size-of-viewport/1514

I can confirm that this happens for me as well.

**Comment by daniel-wer** [comment]
I confirmed and commented that this is expected behavior as the used magnification level is changing and therefore likely a "won't fix".
What should be improved, however, is that the "volume tracing is only possible in mag1" message should be displayed in such a case as well.

**Comment by philippotto** [comment]
Ah, you were quicker than me :) I just opened #4181 for this. Let's close this issue.
