### ISSUE TITLE
Broken annotation after uploading large NML

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4209]
See https://webknossos.brain.mpg.de/annotations/Explorational/5d3eb465010000b9b16f2ce5.

The NML could not be saved correctly (stopped at 99% upload) and the error message "the tracing was edited in another window" appeared (which was not the case, though).
The dashboard shows a lot of nodes and trees for that tracing, but the annotation cannot be opened anymore. It's owned by Valentin.

Overall, rather low-pri, since no external users are impacted. Nevertheless, we should find out how to fix this for the future.

**Comment by philippotto** [comment]
Check whether this is reproducible first.

**Comment by fm3** [comment]
Works for me 🤔 I’d say let’s reopen this issue if it comes up again. Valentin reported the NML was about 200MB. Since this already results in fairly poor performance but the saving still worked for me I’d expect this case to be very rare.
