### ISSUE TITLE
Indicator for scrollability

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4225]
The optimized dataset table is good, but people don't understand that the table can be scrolled  horizontally. Perhaps we can add a visual indicator for scrollability.

<img width="1223" alt="Bildschirmfoto 2019-08-07 um 18 01 55" src="https://user-images.githubusercontent.com/335438/62638395-a9894500-b93d-11e9-9753-e06cc440a6b5.png">

**Comment by philippotto** [comment]
@MichaelBuessemeyer It would be cool if you could do this issue before starting another :) 

One idea to tackle this, is to make the table responsive. That is, hide some columns if the screen is too narrow. For example, the "allowed teams" column is not really crucial. It could be moved into the expandable part (which can be opened via the "plus" on the left side).

**Comment by normanrz** [comment]
This does not only affect the dataset list. I think an indicator like this [1] could be more generic (or with a shadow along the side).

[1] https://benfrain.com/a-horizontal-scrolling-navigation-pattern-for-touch-and-mouse-with-moving-current-indicator/

**Comment by MichaelBuessemeyer** [comment]
@normanrz  @philippotto In the post linked by norman the author also build something like a drag and drop area. This area makes the scrolling incredibly easy. 

In my opinion, this is a valid way of tackling the problem that you have when you to scroll to the right. Currently, you have to first scroll down, then to the right and the up again. This is definitely not the best UX.

**Comment by philippotto** [comment]
> @normanrz @philippotto In the post linked by norman the author also build something like a drag and drop area. This area makes the scrolling incredibly easy.
> 
> In my opinion, this is a valid way of tackling the problem that you have when you to scroll to the right. Currently, you have to first scroll down, then to the right and the up again. This is definitely not the best UX.

Yes, I agree :+1: Feel free to implement the indicator solution described in the linked article.
