### ISSUE TITLE
Statistics available for all users 

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4230]
[Link to Discuss](https://discuss.webknossos.org/t/statistics-availlable-for-users/1526)

When visiting the `/statistics` directly (there is no link to it) as a non-admin, you can see hours/weeek, #users, #datasets, #annotations, #open_assignments. Not sure how easy/sensible it is to restrict this within the back-end. @fm3 Can you comment on that?

In any case, we can show a 404 if the logged in user is not an admin/team manager.

**Comment by fm3** [comment]
Yes, this can and should also be restricted in the back-end, in `StatisticsController.scala`
