### ISSUE TITLE
Cannot scroll through slices on android

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4239]
I just noticed that I cannot scroll through slices when viewing a dataset on webknossos.org. Dragging a pane does not work out. However, zooming wand scrolling the tabs (like info tab) works alright.

**Comment by philippotto** [comment]
Is this a duplicate of https://github.com/scalableminds/webknossos/issues/3780 ?

**Comment by MichaelBuessemeyer** [comment]
Oh looks like it. I wasn't aware of this issue. Thanks for noticing :)
