### ISSUE TITLE
Show and jump to center of layer bounding boxes 

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4287]
[Link to Discuss](https://discuss.webknossos.org/t/show-and-jump-to-center-of-layer-bounding-boxes/1542)

**Comment by youri-k** [comment]
When there's data in the center, `Find data` should jump to the center.

**Comment by philippotto** [comment]
Yes, but there should be a way to jump to the center in a more "deterministic" way :)

**Comment by philippotto** [comment]
From our discussion: let's use the find-my-data button and adapt it so that it jumps to the center if no data is found at all (in the front-end). I'll do that.
