### ISSUE TITLE
Set initial layer color trough datasource-properties.json

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4298]
It would be nice to set the color of a layer in the `datasource-properties.json`. I still think the users should be able to edit that color, but this could be the default.

**Comment by philippotto** [comment]
Ok, I gave this some thought and I think, we should extend the `datasource-properties.json` with all default-view-related properties. That is, `position`, `zoom`,  `segmentationOpacity` and `interpolation` (for the dataset) as well as `color`, `alpha` and `intensityRange` (per layer).
The back-end should read these settings from the `datasource-properties.json` file and return them when the view configuration is requested from the front-end.

To stay backwards-compatible with existing view-configurations which are not controlled via the `datasource-properties.json`, we still keep the `View Configuration` settings. If they are empty, the back-end reads the properties from the disk. If they were changed, the new values are written to the DB and then read from there.

Do you agree, @fm3?

**Comment by fm3** [comment]
well we have to save those things somewhere on the wk side (amongst the rest of the „datasource“ properties, since the json itself is only available for the datastore). but I guess we can maybe afford to duplicate this in the db. what do you think @youri-k ?
