### ISSUE TITLE
Doublecheck whether "reload" button re-reports datasource properties

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4326]
#3764 should have fixed this, but maybe there was a regression? @hotzenklotz reports that the "reload" button didn't work for him.

@fm3 From the top of your head, do you think something changed in the corresponding implementation what could have caused this?

**Comment by fm3** [comment]
can’t think of anything right now… also, I’m using this all the time and I’m pretty sure it works. maybe he used the »refresh« button above the list instead? …though that one should probably do this too, even. can you reproduce it?

**Comment by philippotto** [comment]
@hotzenklotz can you reproduce it consistently? then, we can investigate that setup.

**Comment by hotzenklotz** [comment]
Seems to work as expect. False alarm.
