### ISSUE TITLE
Give "reload" button loading indicator or disable view links as long as reloading is processing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4327]
Right now, it's not obvious that you have to wait for a success-toast when clicking on "reload" for a dataset in a dashboard. This poses the risk that you click on "reload" and directly view the dataset which then uses old metadata.

**Comment by MichaelBuessemeyer** [comment]
1. Use backend api call to clear cache and reload the dataset
2. Use frontend api to drop all buckets in frontend

**Comment by MichaelBuessemeyer** [comment]
closed via #4421
