### ISSUE TITLE
histogram filters zero-values, check if this is intended or change

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4328]
in histogram_view.js 
`value > 0 ? (Math.log(value) / Math.log(maxValue)) * canvasHeight : 0`

**Comment by MichaelBuessemeyer** [comment]
I just checked why there is a `>` comparison instead of `>=`. The reason is pretty simple: The logarithm of 0 equals - infinity. Therefore this check is correct. Maybe a comment would be helpful to clarify this :).

I am adding the comment in PR #4349
