### ISSUE TITLE
During nml drag’n’drop: Cannot call hover while not dragging

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4336]
I get a toast message when dragging an NML into an already-big-and-slow tracing:

`An unknown error occurred. Please consider refreshing this page to avoid an inconsistent state. Error message: Invariant Violation: Cannot call hover while not dragging.`

The import dialog shows up only when i release the mouse, after clicking away the error I can continue normally.

**Comment by philippotto** [comment]
solution for now: don't show this toast. maybe there is a blacklist functionality we can re-use.

**Comment by MichaelBuessemeyer** [comment]
Sadly this bug is caused by the library `react-dropzone`, updating does not help. [Here](https://github.com/react-dropzone/react-dropzone/issues/685) is the issue about this error.

I'll just blacklist the error as suggested :+1:

**Comment by MichaelBuessemeyer** [comment]
btw: The error is independent of the tracing size. The dropdown modal just gets messed up when using the import often enough when the window is maximized. But that's only how I reproduced this bug :man_shrugging:
