### ISSUE TITLE
Allow to set colors of nodes in NML

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4353]
We could either add a new 3-byte `color` attribute to the node geometry or replace the existing `isCommented` attribute. When parsing NMLs, we would need to extract the optional node colors and store that in the store. The protobuf format and the corresponding schema for the tracingstore would need to be updated, too.

**Comment by hotzenklotz** [comment]
I am not sure if I understand this issue correctly. As far as I know, wK only assigns color to trees not individual nodes. NML-files can also already include `color` attributes to `<thing>`-tags (aka trees).

@philippotto Can explain this issues further. Did you really mean to add a color attribute on a per node basis?

**Comment by philippotto** [comment]
> @philippotto Can explain this issues further. Did you really mean to add a color attribute on a per node basis?

Yes, I think, this was the original idea and there was probably a user requesting it. However, I haven't heard anything about this in the past 2 years, so the priority seems to go near zero. I'll close it for now.
