### ISSUE TITLE
Zip import in tracing view should be either supported or have a better error message

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4372]
Right now, protobuf is assumed when the ending is not NML.

**Comment by hotzenklotz** [comment]
Is there a way to easily test some headers to determine the file type? I just tried (acciendentally) load a `*.nm.txt` file and ran into the same issue.

**Comment by philippotto** [comment]
Hm, not that I know. But maybe we simply should simply try parsing the different formats (if the guessed one didn't work). If the format doesn't match, it's likely to crash very fast, anyway (so, it's not a performance problem).

**Comment by philippotto** [comment]
Also, `xml` should be handled as `nml`.
