### ISSUE TITLE
Make import of NMLs more resilient

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4374]
To make it easier to switch from Knossos to WK, the import of NMLs should support:

-  unconnected components (the unconnected components should be split into different trees (which then are grouped together using our group feature). See this script: https://github.com/scalableminds/wknml/blob/master/examples/fix_unlinked_nml.py)
- `<things>` without names (can default to "Unnamed tree 1" or similar) (already supported by the backend)

Might need to happen in front-end in back-end.

**Comment by hotzenklotz** [comment]
NML for reference:
[test.k 1.zip](https://github.com/scalableminds/webknossos/files/3951520/test.k.1.zip)

Timestamps also seem to differ in various NML importer/exporters out there. Perhaps we can ignore those on import when they don't match. Or replace them with the current time etc.

**Comment by philippotto** [comment]
Related to #4396.

**Comment by philippotto** [comment]
Let's do it in front-end first.

**Comment by daniel-wer** [comment]
Frontend is done and merged.

**Comment by fm3** [comment]
The knossos-generated NML is accepted by our back-end parser. It also handles unnamed trees. So I suppose the only thing left there is splitting unconnected-component-trees
