### ISSUE TITLE
[Bug] Undoing NML Import Delete Root Tree

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4385]
I found an interesting bug. When importing a bunch of NMLs and then Undoing (CTRL+Z) the import, one is able to delete ALL trees. As far as I know, wk always operates under the assumption that at least one root tree is present. Otherwise no operation works as intended, e.g. placing new nodes.

### How To Recreate
1. Import one or many NMLs. (in my case it was a hybrid tracing)
2. Undo the import with CTRL+Z repeatedly until all imported trees are gone
3. Undo once more to remove the root tree
4. In my case I, reimported the same NMLs again. Weirdly enough, instead of 10+ trees I only could see one. Saving this state was also broken.

![Kapture 2019-12-19 at 15 29 07](https://user-images.githubusercontent.com/1105056/71181393-583a7c00-2274-11ea-8c85-c5205665079a.gif)

**Comment by MichaelBuessemeyer** [comment]
I took a look at this bug. The bug does have nothing to do with the import. It just occurs when creating a new tracing.
My guess: A new tracing triggers an action to create the first tree. This action then can be reverted leading to the situation where no trees exist.
