### ISSUE TITLE
[Bug] Tree Names are not visible

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4399]
Recently, I can not see/access the trees & comments section when trying for the first time. The section loads, but not tree names are shown/displayed. When switching to a different tab (e.g. "Info") and switching back, the tree names "appear". See GIF

This only happens, when wK is not launched with the tree tab in focus/selected. (e.g. Info tab was last selected when closing wK)

![Kapture 2020-01-08 at 15 08 09](https://user-images.githubusercontent.com/1105056/71984222-b7aefa80-3228-11ea-9255-f3f96a24a96f.gif)

@georgwiese has the same problem. Perhaps, Mac-related? 

Both the tree & comment list are "virtualized", right? Perhaps something to do with that?

**Comment by georgwiese** [comment]
I think also this only happens with a fairly large number of UI elements. Perhaps it would help to also "collapse all subgroups" by default.

**Comment by hotzenklotz** [comment]
Perhaps related - I often have the left-hand menu bar open. Effectively, this pushes the whole viewport to the right and "out of the screen/window". (e.g. scrollbars appear) Perhaps, this causes some React/Ant.d/virtualized component to think, that the tree tab is out of focus/not visible...

**Comment by hotzenklotz** [comment]
> I think also this only happens with a fairly large number of UI elements. Perhaps it would help to also "collapse all subgroups" by default.

I had it happen with this fairly small annotation (<300 nodes): https://webknossos.brain.mpg.de/annotations/Explorational/5e15df25010000e4492a7f9f#9912,11003,2587,0,0.534,207

Number of Trees: 201
Number of Nodes: 278
Number of Edges: 78

**Comment by MichaelBuessemeyer** [comment]
I tried reproducing this issue with your tracing and on my local machine (using firefox) but failed. Maybe the issue only exists in chrome :thinking:
@daniel-wer Could you please try to reproduce this issue? 
Maybe this is a race condition that is dependant on the computer / the speed of the browser. My computer is pretty slow compared to other machines which might cause this error to never occur ...

**Comment by MichaelBuessemeyer** [comment]
Nevertheless, I will open a PR to upgrade the sortable tree dependency. This might fix the issue

**Comment by daniel-wer** [comment]
I also had no luck reliably reproducing this. The two times I saw it, it was "fixed" when I opened the developer tools, so I wasn't able to investigate. Let's hope we won't see new reports after merging #4513 with the two library updates.
