### ISSUE TITLE
Some mouse wheel movements are not interpreted correctly

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4418]
@hotzenklotz uses an external mouse on Mac OS X and shift+mouse wheel to change the brush size always decreases the brush size (no matter in which direction is scrolled). I assume the OS maps shift+mouse wheel to horizontal scroll and our code only checks the vertical scroll direction (which is why the direction is not interpreted correctly?). Weirdly, it works on my system. So, some platform specific stuff seems to be going on. Needs further investigation.

**Comment by fm3** [comment]
Do you know if this was fixed by #5215 ?

**Comment by philippotto** [comment]
Since this issue sounds like an exact duplicate of https://github.com/scalableminds/webknossos/issues/4854, I'd assume, that we can close this. Feel free to reopen.
