### ISSUE TITLE
Allow to list projects which use a specific task type

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4420]
[Link to Discuss](https://discuss.webknossos.org/t/task-types-view/1568)

In the task types view, there should be a "view projects" button for each task type which lists the projects which use said task type.

Maybe, this can replace the "view" function (we need to clarify whether there aren't users that need this feature).

**Comment by MichaelBuessemeyer** [comment]
either new view or integrate it into the project list view

**Comment by fm3** [comment]
A difficulty is that projects don’t have a specific task type. Tasks do. So to determine the projects for a given task type, we have to join all the tasks (which is bound to be slow) or just assume that all tasks of a project use the same task type.
