### ISSUE TITLE
Reload/restart page after logging in to view dataset

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4443]
When you open a non-public dataset, you have to log in and then manually refresh the page. That's not obvious and also annoying.

To solve this we could simply refresh the page. It should also be possible to reload the dataset without refreshing the entire page, but that's probably not worth the effort right now.

**Comment by philippotto** [comment]
Also, showing the login view would be useful here.

**Comment by MichaelBuessemeyer** [comment]
resolved in #4467
