### ISSUE TITLE
"Convert to Hybrid" tracing leads to page with "volume" mode activated

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4460]
Instead, "Orthgonal" should be activated. Otherwise, the trees tab is invisible.

Originally experienced by @valentin-pinkau.

**Comment by MichaelBuessemeyer** [comment]
This bug only occurs when you convert a volume tracing into hybrid tracings. The reason for this bug is, that the old URL is used and the volume mode is encoded into this URL. For more see #4467
