### ISSUE TITLE
Is increasing the datasources auto-refresh rate an option?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4462]
The datastores periodically report their datasets to wk. Since some performance improvements have been made, could we increase the frequency for more user convenience?

**Comment by fm3** [comment]
or: could we introduce a filesystem-watcher? and re-report only individual datasets immediately when they are changed (on the top levels only, probably, not every wkw file)

**Comment by philippotto** [comment]
Can you name some numbers? How often is the report done right now? Clicking the refresh button manually only takes ~ 5 seconds. So, polling more often sounds like the simplest, viable solution.

**Comment by fm3** [comment]
Right now it’s at 10 minutes. I’d say we can probably afford one minute
