### ISSUE TITLE
Improve warning UI (get rid of most toasts)

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4471]
For example, telling the user that volume tracing is only possible in mag 1 is quite obnoxious right now (a toast which re-appears every time when zooming). ~Such a warning might be more effective (and less annoying) with a sort of "status indicator" à la~:

<details>

![image](https://user-images.githubusercontent.com/2486553/76227592-d6793f80-621f-11ea-9a5e-a797350b7a6b.png)

</details>

~Hovering over that red information icon would show a tooltip with a proper explanation.~

~Similarly, such an indicator could also be used for telling the user that one of the active layers is not available in the current mags.~

See comments below.

**Comment by philippotto** [comment]
Another idea:

When a layer cannot be shown (e.g., because the mag does not exist or it's not supported for other reasons), we could simply show an "i" indicator in the "layers" settings. If the user doesn't see their data, they will double-check the visibility of the layer anyways.
Such an icon could then show on hover the explanation for why the layer isn't shown:
- the mag does not exist
- volume tracing is not supported in this mag
- you are outside of the layer's bounding box (this is not the same as the dataset bounding box for which we already have a warning)

That should be pretty unobtrusive, in my opinion.

**Comment by philippotto** [comment]
For the "brushing not supported warning", there could be an indicator around the "tool" UI in the navbar (only if the brush is active).

In general, I think that warnings should be positioned where they make semantically sense (layer not visible warning --> show it in the layer UI etc). That should be a good guideline to avoid high amount of toasts :bread: 

If a warning is hidden in the closed settings, we could add a small red badge icon to the settings button. I don't think it's crucial, though.

**Comment by fm3** [comment]
I think the mag issue is solved by now, right? Is there another case for which this applies?

**Comment by philippotto** [comment]
I think that was the most dominant one. Closing the issue now :tada: :)
