### ISSUE TITLE
Remove duplicate shortcut to disable segmentation in merge mode

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4478]
Currently, the merger mode itself has an enable/disable segmentation visibility [shortcut (key "9")](https://github.com/scalableminds/webknossos/blob/76bff2ad82a3c83c0a0c6c6425f503ea4c51c9a6/frontend/javascripts/oxalis/merger_mode.js#L313).

But such a keyboard shortcut is already defined in the [controller](https://github.com/scalableminds/webknossos/blob/76bff2ad82a3c83c0a0c6c6425f503ea4c51c9a6/frontend/javascripts/oxalis/controller.js#L246). Thus the keyboard shortcut in the merger mode is just a useless duplicate or am I missing something here?

If I am correct, I'd suggest removing the keyboard shortcut defined in the merger mode script.

**Comment by MichaelBuessemeyer** [comment]
@philippotto Could you please check whether I am correct here?

Can you think of a scenario where the shortcut from the controller is not available but the shortcut from the merger mode is?

**Comment by philippotto** [comment]
Hm, you are right. This seems to be redundant. However, it's difficult to remove one shortcut, since this won't be backwards compatible (e.g., if we remove the shortcut defined in the merger mode, users of the merger mode will wonder why hitting `9` doesn't work anymore). So, I'd suggest to keep it just as is?

**Comment by MichaelBuessemeyer** [comment]
Currently when starting the merger mode a modal with instructions and all shortcuts is shown. 

Maybe we could replace the `9` in the "toggle segmentation"-shortcut with a `3` and add an info sentence (or something like this) saying that the shortcut was changed from 9 to 3. Do you think this is a valid solution? 🤔

**Comment by philippotto** [comment]
We could do that, but I'm not sure whether it's worth it. (a) we have to spend time for implementing this and (b) the user's have to read this message and have to get used to this. And we would only do this to save ~ 10 lines of code and remove a bit of redundancy. I don't think, that's worth the hassle :)

**Comment by MichaelBuessemeyer** [comment]
alright 👍
I think your are right that the time investment is not worth it
