### ISSUE TITLE
Sorting in tree tab should also sort tree groups by name

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4490]
Currently it only sorts the trees themselves

**Comment by daniel-wer** [comment]
@fm3 Can you confirm this report?

From the code and from my testing, the groups are always sorted by name (within their respective nesting level). Trees are sorted by name or creation date (as selected).

See for example this tracing: https://webknossos.brain.mpg.de/annotations/Explorational/5e8dfe0a010000e743f5baa2#6355,4340,2615,0,2.000

If I change a group name, the sorting is adapted accordingly.

**Comment by fm3** [comment]
Good point, no, it works for me too. I’ve asked the original reporter for more details
