### ISSUE TITLE
Communicate to the user if 64 bit segmentation ids are truncated to 32 bit

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4492]
If the user wants to pick ids in the segmentation tab, those IDs may be wrong if the segmentation was converted. This should be obvious to the user

**Comment by philippotto** [comment]
Maybe the front-end doesn't know that the underlying data is 64 bit.

**Comment by MichaelBuessemeyer** [comment]
look if there is a way to determine whether the segmentation is 32 or 64 bit

**Comment by MichaelBuessemeyer** [comment]
Oh looks like I forgot to comment this :thinking:
@philippotto  was correct: The frontend does not know that the segmentation data is 64 bit. @fm3 Do you have a suggestion to fix this?
I think that: the backend sending the information that the segmentation is 64-bit to the frontend would be a solution. The frontend could then still could treat the data from the backend as 32-bit and additionally knows that the original segmentation is 64-bit

**Comment by fm3** [comment]
yes, maybe @youri-k could add an optional additional field to the datasource json, containing the original type? At the same code path where the 64 is replaced by 32 in the first place, I suppose
