### ISSUE TITLE
plus and minus keys as aliases for i and o zooming?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4522]
I think it may help the discoverability. Is there any reason against that?

**Comment by grittaweisheit** [comment]
Doesn't seem like there is a reason against it. :)

**Comment by grittaweisheit** [comment]
Sadly [KeyboardJS](https://github.com/RobertWHurst/KeyboardJS) (our keyboard input library) doesn't recognize the plus key. Thus I think it could be more work than it's worth.

**Comment by fm3** [comment]
There seems to be some discussion about that in https://github.com/RobertWHurst/KeyboardJS/issues/147 – could their workaround do the trick for us too?

**Comment by grittaweisheit** [comment]
It does not seem to help with recognizing the plus key.

**Comment by fm3** [comment]
Apparently the problem is with german keyboard layouts. In english keyboard layouts (which keyboardJS was designed for), there is no plus key, instead it is reached by shift combined with equalsign.
In Firefox, the keyboardJS demo page does not recognize any keys when pressing the plus key on german key layout. In chrome it (wrongly) calls it equalsign.
While attaching the zoom in to equalsign would solve the issue for chrome users with german keyboard layouts, I believe this would lead to confusion. Let’s stick with I and O, then, as there have not been many complaints about that, anyway.
Thanks for your tests!
