### ISSUE TITLE
Extremely slow rendering of viewports 

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4533]
[Link to Discuss](https://discuss.webknossos.org/t/extremely-slow-rendering-of-viewports/1588)

see https://webknossos.brain.mpg.de/annotations/Explorational/5e8dba2a010000b433f5b7b9

spontaneous ideas:
- invisible trees are still in the scene and only get the invisible color. can we avoid that threejs executes the shader for invisible trees? (not sure, if my assumptions are correct here)
- see https://github.com/scalableminds/webknossos/issues/3598

**Comment by hotzenklotz** [comment]
Mhm, I just opened the link above in Safari and everything loaded pretty quickly. Over the years we have rebuild many code paths, optimized time and again and rebuild the interface a couple of time. 

I am voting to close the issue since it does not track a specify actions/ToDo.
