### ISSUE TITLE
Frontend NML parser: show error details in toast

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4548]
In the toast I only get "x.nml could not be parsed as either NML or protobuf."
It would be nice if error summaries from the different parsing attempts, as are already present in the console, could also be included in the toast (or at least “press f12 for error details in the browser console” or something like that)

**Comment by daniel-wer** [comment]
Will be fixed in https://github.com/scalableminds/webknossos/pull/4541 :)
