### ISSUE TITLE
Clean up registration/onboarding handling

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4560]
- [ ] `/onboarding` view should redirect  to appropriate view if called for an instance where it doesn't make sense (this guards against incorrect links to `/onboarding` which certainly exist)
- [ ] `/register` view should redirect  to appropriate view if called for an instance where it doesn't make sense  (i.e., demo instance) OR make it work, too

**Comment by fm3** [comment]
I think some of this may have been fixed in the meantime. Let’s take the time to check the different cases

**Comment by fm3** [comment]
True enough, this has been taken care of in the meantime, #4677 and #4685 :)
