### ISSUE TITLE
agglomerate mapping too slow for large amounts of segments

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4577]
if you have downsampled segmentations you tend to request buckets with a lot of different segments. this makes looking up the IDs in the agglomerate file extremely slow, even overloading the server. what to do about this?

**Comment by fm3** [comment]
let’s disable this feature for mag 8 and lower for now, to save server capacity

**Comment by valentin-pinkau** [comment]
There exists a mapping between segmentation chunk and a contiguous segment id range.
We could use this to reduce the scattered reading when translating segment ids.
