### ISSUE TITLE
Backend reports existing buckets as missing when activating an agglomerate file mapping

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#4599]
Most of the time when I activate an agglomerate file mapping, the segmentation buckets in the middle of the viewports never appear.

![agglobug](https://user-images.githubusercontent.com/1702075/81092907-98d42280-8f01-11ea-8fbc-2a4b11506b0a.gif)

I checked the requests and it looks like the buckets in the very first requests are always marked as missing by the backend, although they actually exist. This can be seen when re-activating the same mapping as suddenly the buckets are no longer reported as missing and appear in the viewport.

First Request Payload:
```json
[
  {"position":[64,64,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"},
  {"position":[96,64,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"},
  {"position":[96,96,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"}
]
```
First Response: missing-buckets: [0, 1, 2]

Second Request Payload (2/3 buckets are the same as in the first request):
```json
[
  {"position":[64,64,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"},
  {"position":[64,96,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"},
  {"position":[96,64,64],"zoomStep":0,"cubeSize":32,"fourBit":false,"applyAgglomerate":"agglomerate_view_35"}
]
```
Second Response: missing-buckets: []

**Comment by valentin-pinkau** [comment]
@youri-k This happened to me again. Maybe this is still an issue:
![Screenshot 2020-08-17 at 13 27 51](https://user-images.githubusercontent.com/2582395/90391710-dc583400-e08d-11ea-81c9-3636ae08ccf2.png)

**Comment by daniel-wer** [comment]
Yes, can confirm, this happens intermittently for me as well. As far as I can see, the behavior is the same as when I reported this bug initially, existing buckets are sent with a header like `MISSING-BUCKETS: [0, 1, 2]` when activating the agglomerate mapping for the first time. When activating the mapping again, the bucket is sent without the `MISSING-BUCKETS` and everything is displayed correctly.

**Comment by youri-k** [comment]
Didn't occur anymore. Feel free to reopen, if it happens again :slightly_smiling_face:
