### ISSUE TITLE
Allow applying result of merger mode tracing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4603]
There's already a script to apply the skeleton tracing on the segmentation. This could be integrated into webknossos-worker.

**Comment by normanrz** [comment]
https://gist.github.com/normanrz/b83c5a205434bf5fc05b8848a1d1135c

**Comment by MichaelBuessemeyer** [comment]
updated script: https://docs.webknossos.org/webknossos-py/examples/apply_merger_mode.html

**Comment by MichaelBuessemeyer** [comment]
@normanrz or @philippotto Do you already have in mind where in the UI the button to apply the merger mode tracing should be?

**Comment by philippotto** [comment]
I think, having a dedicated button in the toolbar could work (only if merger mode is enabled). Alternatively, the "Process Dataset" would be ok, but I think, it doesn't really make much sense to fill that menu up with all worker-jobs, since the user shouldn't really care whether an action is worker-related or not.
