### ISSUE TITLE
Frontend NML parser doesn't accept ">" in attributes

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4605]
We just encountered the following nml which was produced by NmlWriter.scala. The `>` in the `description` attribute caused the NML to be rejected by the frontend NML parser. Backend parser accepted it.

```
<things>
  <meta name="writer" content="NmlWriter.scala" />
  ...
  <parameters>
    <experiment name="..." organization="..." description="&lt;no description>" />
```

**Comment by fm3** [comment]
As per the [xml specification](https://www.w3.org/TR/xml/#syntax), the character `>` needn’t be escaped in attributes, also compare [this SO answer](https://stackoverflow.com/a/1091953).
The Java XMLStreamWriter which we’re using in the wK backend escapes only the characters that must be escaped in attributes (`<`, `&`, `"`). I’d argue that this is correct behavior and rather investigate what parsers didn’t accept the generated XML.

**Comment by normanrz** [comment]
The frontend parser didn't accept this NML.

**Comment by philippotto** [comment]
Let's remove the <> brackets from the default fallback when exporting the NML.

**Comment by fm3** [comment]
I created https://github.com/matteodelabre/saxophone/issues/14 but the needed changes there look nontrivial. So I agree that a quick workaround for us would be to avoid generating XML files that have this property.

**Comment by fm3** [comment]
moving this back to backlog, as PR https://github.com/scalableminds/webknossos/pull/4703 implements the workaround discussed above.
