### ISSUE TITLE
Select all trees that match a search

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4626]
Recently, I used the tree search a lot. It would be nice if the search widget would also have a button for selecting all trees that match the query.

**Comment by dieknolle3333** [comment]
![Image](https://github.com/user-attachments/assets/c67b6b2d-e750-4d71-8366-4f31f90f64a7)

@normanrz I would simply add a button next to the arrow down

**Comment by dieknolle3333** [comment]
This search popover is the same component for segments, comments and skeletons. Comments cannot be selected, but segments can. So I propose to build this for segments and skeletons.
