### ISSUE TITLE
enable deleting datasets from UI

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4628]
users that have no access to the filesystem but only use the upload dataset UI have no possibility to remove datasets again. it would be beneficial if they could hide them via an archive button (then the dataset list could filter for those as well)

**Comment by hotzenklotz** [comment]
This is fairly important for some clients that don't have file system access but are required to remove datasets for legal reasons. Perhaps, archiving isn't even the right thing, but deletion would be better.

In this particular case a lot of datasets were uploaded/created after trying and iterating on dataset conversion/cubing. E.g. after 4 tries with the wKCuber the dataset was correct, leaving 3 iterations of broken data behind.

Perhaps something that we should look into for the next sprint.
