### ISSUE TITLE
Volume layer opacity does not persist

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#4650]
After changing the opacity of volume layer in tracing mode (say to 50), if I view a dataset with default segmentation opacity that is different (say 20), then this new opacity (20) is also applied to the tracing mode. Would it be possible to make this setting persistent in tracing mode?

**Comment by philippotto** [comment]
The opacity setting is persisted for each dataset (and for each user) independently (regardless of view or tracing mode). At least, this is how it's supposed to be right now if I'm not mistaken.
For example, if you change the opacity for the segmentation layer in dataset A, it should only change if you change it by yourself. When opening another dataset B, the segmentation opacity will default to 20 again for that dataset, but dataset A should still open with the opacity you had before.

You can change the defaults for a given dataset by editing the dataset in the dashboard. That way, you can set the default for all users who will use the dataset (so, this is only interesting for a multi-user setup).

Does this make sense? And does this match the behavior you are experiencing?

**Comment by cnzqy1** [comment]
Yes, that makes sense. It doesn't exactly match the behavior I'm experiencing, however. Seems that it's more complicated than what I described in the initial post, so I'll troubleshoot a bit more to find out what triggers the reset.

**Comment by cnzqy1** [comment]
OK, the actual issue is as following:

1. Dataset X does not have a segmentation layer.
2. I make a new segmentation on this dataset using either explorational annotation or task, and change opacity to 50.
3. After I view the same dataset X in view mode, the default opacity 20 is now propagated to the tracing mode when I open the annotation again.

This issue doesn't seem to occur when the dataset has a pre-existing segmentation layer.

**Comment by philippotto** [comment]
Thank you for the detailed reproduction steps! We'll look into fixing this.

**Comment by youri-k** [comment]
I could reproduce the bug and trace it's origin to the handling of the `user dataset configurations`. An easy solution would be to move the `alpha` value of the layer configuration to the annotation. @MichaelBuessemeyer Do you think this would be feasible in the frontend as well?

**Comment by philippotto** [comment]
> @MichaelBuessemeyer Do you think this would be feasible in the frontend as well?

Ping :)

**Comment by MichaelBuessemeyer** [comment]
Sorry for not replaying. I somehow did not see this issue / mention.

> Do you think this would be feasible in the frontend as well?

I think that this is possible/ feasible but that would kinda spread the location of where the settings of a layer are saved in the store, which might be confusing. Additionally, if we move the `alpha` value, shouldn't this step also be necessary for the other configurations (`color`, `intensityRange`, [etc.](https://github.com/scalableminds/webknossos/blob/75a63d73eaeef8e063acc294fb06909c167062fc/frontend/javascripts/oxalis/store.js#L248))?
