### ISSUE TITLE
Show dataset name or explorative tracing name in webknossos tab title

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#4653]
I'm often working with lots of webknossos tabs open. However, as all tabs share the same title (`webKnossos - <organization_name>`) identifying individual tabs can only be done by memorization or inspection.

![webknossos-tab-titles](https://user-images.githubusercontent.com/1702075/84051705-ce13da80-a9af-11ea-9763-f70d8d2c4784.png)

It would be great if instead of the organization name, which is usually equal for all tabs anyways, the dataset name (or the explorative tracing name, if there is one) could be shown in the title, instead.

**Comment by philippotto** [comment]
The new title format could be: `<dataset_or_tracing_name> <organization_name> webKnossos`.

This react hook should it make quite easy to implement: https://github.com/rehooks/document-title
