### ISSUE TITLE
Undo in merger mode does not work as expected

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4655]
When merging two nodes, the corresponding segments are merged (i.e., they share the same color / segment id). When hitting undo, the nodes are split again but the segments are still merged.

**Comment by hotzenklotz** [comment]
Funny enough: Deleting a tree in merge mode, DOES undo the merger.

**Comment by philippotto** [comment]
I had a look at this now and it turns out to be a bit more work to fix this. Right now, the merger mode works by listening to some actions (e.g., create-node, or delete-node). Since it doesn't react to all possible action types (which would be a lot of code, too), there are actions which can trigger the above bug. Undo/redo is an example for this.

However, we have a pattern for this exact problem. Namely, call `diffSkeletonTracing` and process the primitive `UpdateActions` which are returned. That way, undoing the creation of a node will be treated exactly like the deletion of that node (since the differ will say, that one node has to be removed).

So in my opinion, we should change the implementation strategy for the merger mode to call diffSkeletonTracing and handle all cases (similar to how the scene controller does it). For a quick "fix", it might be enough to handle the create node/tree, delete node/tree actions, as the current merger mode doesn't handle more, anyway. That way, things would still break when merging two trees, for example. However, undo/redo would work.

**Comment by daniel-wer** [comment]
@philippotto Thanks for sketching out a solution to this. As far as I can see, using the `diffSkeletonTracing` output makes the code even easier. Only reacting to `createNode` and `deleteNode` diffing actions works for all cases: undo, redo, split, merge, ... .
This is a result of our "primitive" diffing which breaks down all complex skeleton modifications into these low-level primitives. Update actions like `mergeTree` are only reconstructed from the simple diffing actions, later, when sending updates to the server. See https://github.com/scalableminds/webknossos/pull/4669 for details :tada:

**Comment by philippotto** [comment]
Thank you for taking care of this @daniel-wer :heart:

> Only reacting to `createNode` and `deleteNode` diffing actions works for all cases: undo, redo, split, merge, ... .

That's great to hear! However, I thought that merges and splits are usually represented with the `moveTreeComponent` update action instead of `createNode` and `deleteNode`? That's why, I thought this would need to be handled, too, strictly speaking. But I assume you tested this, anyway, so I probably have made an error in reasoning somewhere here :)
