### ISSUE TITLE
Date range unexpectedly changes in Statistics > Overview

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#4664]
The date range unexpectedly changes under certain circumstances. One way of reproducing this behavior:

1. Navigate to https://webknossos.org/dashboard/datasets.
2. Click on Statistics > Overview, the date range is 14.06 - 20.06.2020.
3. Click on Dashboard > My Datasets.
4. Click on Statistics > Overview again, the date range is now 15.06 - 21.06.2020 instead.

**Comment by hotzenklotz** [comment]
I can not reproduce this issue. A few months ago we switched our date and times library from `momentjs` to `dayjs` which might have fixed this issue. 

@cnzqy1  @fm3 Can you still reproduce this?

**Comment by fm3** [comment]
I could reproduce it at the time of reporting, but now no longer. Closing this issue. Feel free to reopen if this still happens for you.
