### ISSUE TITLE
Are fallback layers actually used?

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4666]
I know that the fallback layers in volume annotations have a complexity cost for the users and in the code. Are they actually used or could we get rid of them? If still in use, maybe there are other ways to satisfy the same use case?

**Comment by cnzqy1** [comment]
Does creating new volume annotations using existing segmentation layer rely on the fallback layer? We do occasionally use this functionality to have a sense of what has been reconstructed when making new annotations, especially when we did not divide up the tasks in a systematic way such as using bboxes.
