### ISSUE TITLE
List of manually created segments

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4667]
In volume tracings, there is no UI for seeing all manually created segments. For skeletons, there are tree and comment lists.

It would be nice to see all segments in one view and maybe also have some metadata, e.g. voxel count. This would only show manually created segments.

**Comment by normanrz** [comment]
This came up again in the workshops.

**Comment by philippotto** [comment]
Design doc: https://www.notion.so/scalableminds/Design-Doc-Segment-Lists-c8ec5e23764b4a578a452a4c7290000e
