### ISSUE TITLE
User Study for dataset management

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4670]
Currently datasets are handled in a flat list. With up to 2000 datasets, this is not very usable. 

Some observations:
- We introduced tags a while back, but they don't seem to used very much.
- Many EM datasets are actually just variations of a different dataset. Raw data is reused, but other layers or bboxes may be selected.
- When think of MRI scans, this picture is very different, however. There are many individual scans. They may have a grouping, but it could be due to metadata (e.g. patient, organ, study, cohort).
- Also, webKnossos doesn't have a concept of one-off datasets. Sometimes, people just want to quickly look at one dataset without importing it to their persisted collection. Could also be solved through #4668.

**Comment by hotzenklotz** [comment]
Quote @normanrz "Close as completed"
