### ISSUE TITLE
separate saving dataset sharing from updating properties

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4672]
a user could not share a dataset with a team because wk guessed invalid json properties. this should not block the other tabs of the edit view

**Comment by fm3** [comment]
maybe make saving the properties opt-in (if there exists a json on the server?)
 (we are now also often using write protection on the server, where even trivial suggestions like "you had 1-1-1, but I inferred 1" can cause this workflow to freeze)

**Comment by MichaelBuessemeyer** [comment]
We discussed the following:
- If the backend already has valid options, then the backend settings should be loaded and if the frontend has suggestions, this should be mentioned in the blue banner. The changes can be applied optionally by clicking a button in that banner. 
- If the existing settings on the backend side are invalid, then the suggested changes should be loaded directly. This is currently the case. I think the automated adjustment of the settings is indicated by the text in the blue banner -> Check whether that is true.
- If there were no changes compared to the settings in the backend, then no save request should be sent.
  - If the frontend applied suggestions, an update request must be sent.
- There should be an update request for each tab and they should fail individually.
