### ISSUE TITLE
Update antd to v4.x

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#4678]
See migration guide at https://ant.design/docs/react/migration-v4

Some relevant improvements I spotted:
  - Better Form handling, no more getFieldDecorator etc. (https://ant.design/components/form/v3/#Remove-Form.create)
  - Icons are separate components, allowing tree shaking and a smaller bundle (https://ant.design/docs/react/migration-v4#Icon-upgrade)
  - Tree, Select, TreeSelect, AutoComplete use virtual scrolling

We could then also use the `loading` prop of Selects instead of the `notFoundContent` workaround introduced in https://github.com/scalableminds/webknossos/pull/4671

**Comment by philippotto** [comment]
This is a duplicate, but provides way more detail than the old issue. So, I'm closing the other one :p 

Quoting from: https://github.com/scalableminds/webknossos/issues/4576#issue-607628087
> Then, we can check out the new dark mode. See: ant-design/ant-design#21656

**Comment by philippotto** [comment]
Also important to note: There is an automatic code mod for the update. It probably won't cover all the necessary work, but hopefully most of it. I just used it in another project and worked quite well: https://ant.design/docs/react/migration-v4#Start-upgrading
