### ISSUE TITLE
Task Bounding Box lost when using "copy to my account"

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#4679]
To reproduce:
- Download a finished volume tracing task -> NML contains `taskBoundingBox`
- Open it and click "copy to my account"
- Download this tracing -> The bounding box is lost

This process is sometimes applied to correct volume tracings done by HiWis.

**Comment by georgwiese** [comment]
From Alessandro:

> It appears that the issue is more subtle than that:
>
> The task bounding box is correctly carried over by the "copy to my
> account" functionality (as evident from the green box). However, when
> downloading the resulting tracing, the NML file lacks the task bounding
> box.

**Comment by fm3** [comment]
work-in-progress PR #4536 should handle that
