### ISSUE TITLE
Dataset Permission should be in separate tab

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4683]
With the recent permissions system refactoring, the `allowed teams` option should be more prominent since it is important property of the dataset.

I suggest to move it out of the `Metadata` tab into its own, separate tab `Permissions` (or `Access Permissions`) to make this feature more prominent. This is a cosmetic change only. No further functionality needs to be changed. 

![image](https://user-images.githubusercontent.com/1105056/85397726-579cde00-b554-11ea-9ba4-6b0e1223669f.png)

**Comment by fm3** [comment]
How about renaming “Sharing” to “Permissions & Sharing” and include it there (at the top)?
I agree that “Metadata” is the wrong place.
