### ISSUE TITLE
Improve visual separation of layer-specific sections in settings

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4687]
See https://discuss.webknossos.org/t/opacity-or-opacity/1602/3?u=potto.

I'd vote for improving the vertical padding between the sections. One needs to be careful that this also looks good with the various states of collapsed/expanded sections which can be adjacent to each other.

**Comment by daniel-wer** [comment]
Maybe adding a light gray horizontal divider between the different layers would help in addition to the increased vertical padding.

**Comment by philippotto** [comment]
Fixed by #4722.

@grittaweisheit If you use `fixes #4687` in the PR description (instead of `solves #4687`), this issue would have been closed automatically when the PR is merged. Just as a tip.. :)
