### ISSUE TITLE
Unify color handling in frontend

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4692]
On the first look, it seems like the range of colors is not always the same way.

- the trees and user bounding boxes have a range of `[0,1]`
- and layers seem to have a range from `[0,255]`

**Comment by hotzenklotz** [comment]
@philippotto Recently you introduced a new color picker component. I wonder, does this component already "unify" colors?

**Comment by philippotto** [comment]
No, the color picker didn't change anything about the color ranges. However, I don't think that we will get very far with unifying these, as there are various domains for we can't dictate the value ranges (e.g., CSS, GLSL, Canvas, TypedArrays, UI components from NPM). So, I'd be fine with closing this. It's annoying, but an uphill battle in my opinion.
