### ISSUE TITLE
Allow to split segments

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4713]
When there's a merger in an oversegmentation, one should be able to split a cell into the original parts.

The goal should be to preserve as much as possible of initial oversegmentation to minimize the "repainting" effort. All that should need to be repainted is the surface where the merger is occurring.

There are different levels of how to tackle this (sorted from hard to easy):

1) Draw the missing boundary into a cell for each slice. initiate a "split" action to reassign the ids appropriately. (could be done by performing a connected-components algorithm.)
2) A variant of the above could be to have a paintbucket-like volume-filling tool. when clicking on a segment, the id of that segment is changed for all voxels which are directly connected to it (flood-fill style).
3) Instead of the flood-filling, the user could configure the brush so that it can only override a specific ID. Then, they can paint over the segment manually to swap the ID.

The 3rd option is not possible right now, but should be rather easy to implement. However, it's still not very user-friendly and the UI will probably get convoluted to allow this configuration.
The 2nd option sounds like a good solution to me. It would add a quite generic tool (or "mode" for the brush) which covers the use-case in an almost equal manner to (1).

A crucial aspect of this feature, though, will be how to avoid that the execution "explodes" when doing this on a huge segment. It could be limited to the current viewport (as it's done for the copy-segmentation-tool, too).
Also, the first implementation of this feature might be slow since it will suffer from the same performance problems as the copy-segmentation feature.

**Comment by MichaelBuessemeyer** [comment]
Let's go for the 2nd option :+1:
