### ISSUE TITLE
Better support for 2D data

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4736]
The WKW file format doesn't work very well for large 2D images. It would be great if the datastore (or connect) could also work with flat files (maybe tiled) as well. 

Also, the UI could be adapted when using 2D images, see #4738

**Comment by hotzenklotz** [comment]
@normanrz Is Zarr the solution?

**Comment by normanrz** [comment]
Yes. zarr is much better when using a chunk_shape of (*, *, 1). The datastore will still send (32,32,32) chunks to the frontend.  But, at least the data storage is more efficient with Zarr.
