### ISSUE TITLE
Allow to remove fallback layer from a volume tracing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4741]
Consequently, we can remove the "do you want a fallback layer or not?" decision when creating a new tracing. By default, a fallback layer is always used (if it exists on disk). If the user does not want this, they can chose to remove the fallback layer from the tracing.

For volume (or hybrid) tracings, the "Volume Layer" in the settings could have a button to remove this.

**Comment by youri-k** [comment]
I added a `UpdateAction` in the backend that removes the fallback layer from the `VolumeTracing`. I think the rest can be done in the frontend. @MichaelBuessemeyer @philippotto @daniel-wer could one of you do the necessary changes?
See the `remove-fallback-layer` branch for progress.

**Comment by philippotto** [comment]
I think, the front-part can be done by @grittaweisheit. Here's a bit more of context:

- when creating a new tracing from the dashboard, one can select a hybrid (or volume) annotation with or without the existing segmentation layer
- if the user selects the "existing segmentation"-option, the layer settings for the segmentation layer should show a small button to remove that existing segmentation layer again (maybe use `<Icon type="minus-square" />` as an icon)
- when the user clicks that button, the back-end route @youri-k implemented needs to be invoked. after that request finished, the entire tab should be reloaded

In order to know whether to show the button or not, you can check the `fallbackLayer` property in the `APISegmentationLayer`. If it's not null, the button should be shown. Let me know if you have any other questions!

**Comment by philippotto** [comment]
Two additional notes:
- the delete button should open an "are you sure" modal (see other usages of `Modal.confirm`)
- the delete button should NOT be shown if the active tracing is a task. additionally, it might make sense to disable this feature in the back-end (if it's not already done) @youri-k ?
