### ISSUE TITLE
Introduce restrictions to allow/disallow skeleton or volume tracing in tasks

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4747]
Introduce restrictions to allow/disallow skeleton or volume tracing in tasks.

Should be checkboxes.

**Comment by fm3** [comment]
@philippotto not sure how this differs from the current implementation with Skeleton/Volume/Hybrid radio buttons in task types? Should this be moved to tasks? Is it just the UI that is to change?

**Comment by philippotto** [comment]
Good point, somehow I thought that tasks cannot be hybrid yet. But this seems to be wrong, as there are already the skeleton/volume/hybrid radio buttons in the task type (as you said). I'd simply change the Skeleton vs Volume vs Hybrid radio buttons to two Checkboxes: Skeleton and Volume. With the requirement that at least one has to be set in the front-end.
The internal representation can probably stay the same. Theoretically, we could also stick to the current UI, but I think it would be better if we didn't impose the word "hybrid" on the user.

**Comment by fm3** [comment]
I fear that two checkboxes, where at least one of them has to be checked, is a UI that is somewhat difficult to discover 🤔. How would you feel about radio buttons with »skeleton only«, »volume only«, »skeleton and volume« (or »both«)? so basically just a renaming?

**Comment by philippotto** [comment]
Yes, you've got a point :+1: "Skeleton and volume" sounds very good to me :)
