### ISSUE TITLE
Disable volume trace tool in higher mags

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4748]
When the currently rendered magnification is not mag 1, the volume-trace-tool should be disabled to avoid that the user can create huge volume tracings with a single action.
Ideally, the mouse should turn into `pointer: not-allowed` (via CSS) and the tool-UI in the navbar could be highlighted somehow. When hovering over the toolbar, there could be a hint, which explains why the tool is disabled.

**Comment by philippotto** [comment]
@grittaweisheit Before starting with this issue, please talk to @MichaelBuessemeyer about the details (e.g., the changes should probably be done on the branch `multires-volumes` or might already be solved there?).

**Comment by MichaelBuessemeyer** [comment]
@philippotto I accidentally already implemented this in #4755 :sweat_smile:

**Comment by philippotto** [comment]
Should be covered by https://github.com/scalableminds/webknossos/pull/4755.
