### ISSUE TITLE
Improve collapsed layers settings 

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4749]
<img width="346" alt="Screenshot 2020-08-03 at 16 47 40" src="https://user-images.githubusercontent.com/335438/89196574-b0778180-d5aa-11ea-926a-cb6828c45247.png">

a) When the layer is deactivated, there is no need for adjusting the histogram, reloading the layer or finding data. I'd make these icons invisible or deactivate them and gray them out.
b) The spacing of the min/max inputs looks uneven. I'd use the full width and move the labels closer to their input and have a larger margin between both inputs.

**Comment by philippotto** [comment]
I merged this issue into #4732, since there's a very high overlap.
