### ISSUE TITLE
Support merger mode in higher magnifications

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4756]
Currently, the merger mode only works in magnification 1, but the merger mode should also be supported in all magnifications.

Things to keep in mind:
 - What if only mag 1 exists and the user traces in mag 2 and sees the downsampled data by the frontend?
 - What if mag 1 does not exists and the user traces in mag 1?
=> always use the best magnification

**Comment by hotzenklotz** [comment]
@MichaelBuessemeyer I think this has been fixed on the meantime. I just tried it and merge mode also works in higher mags. Closing for now.
