### ISSUE TITLE
Do not let merger mode rely on unique node ids

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4759]
The current merger mode looks like it only works when the node ids are global unique. But the ids only need to be unique for each tree. Thus the merger mode needs to be adapted.

**Comment by philippotto** [comment]
> But the ids only need to be unique for each tree.

Are you sure about this? I thought, the node ids would also be unique. For example, the parse_nml code also enforces this property if I'm not mistaken?

**Comment by MichaelBuessemeyer** [comment]
IF that's the case, I misunderstood something sometime 🤷
