### ISSUE TITLE
Unify naming of "zoomStep" and "resolution" / "resolutionIndex"

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4762]
Currently, the frontend uses "zoomStep" and "resolutionIndex" for the same thing and the resolutions in the store are all saved in as "resolutions".

I suggest sticking to one term for the "resolution"/"resolutionIndex". I think "resolutionIndex" is the better term as it works well with the term "resolutions". But on the other hand "zoomStep" is used much more frequent.

**Comment by fm3** [comment]
related: #4893

also note this discussion https://github.com/scalableminds/webknossos/pull/4755#issuecomment-715367049

**Comment by fm3** [comment]
superseded by #4893
