### ISSUE TITLE
Rework skeleton and volume toolbar

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4787]
The current tools for skeleton and volume tracings are not very explorable. A lot of behavior is hidden behind shortcuts and or not intuitive modes. For example, to create skeletons you have to be in the "move" tool :see_no_evil: And the existence of the upcoming fill-tool will also be very hard to find out.

There are multiple ways to improve this situation (and we might want to do this in multiple stages).

My vision for a round experience would be:
- have a tool for each dedicated action and use icons instead of labels (e.g.,  the new fill-tool should have an own button)
  - theoretically, actions such as "removing an edge" or "merging two trees" could be a separate tool, too (using the existing shortcuts could still work)
- categorize the tools according to skeleton vs volume. maybe, it could also make sense to have a general skeleton-vs-volume mode button (so, you are either in the skeleton or in the volume mode). I think, this would also be intuitive for users, since one usually focuses on one tracing type (even in hybrids). Additionally, it would save space in the navbar.
- different modes within these tools, should be presented in the navbar as additional buttons (see screenshot below for how Gimp does this)
- in general, all shortcuts which modify the tool behavior, should immediately reflect the state change in the toolbar (also comparable to how gimp does it). For example, if you press a modifier while using the brush tool, the mode button would switch to show that you are overwriting only the current cell.

![image](https://user-images.githubusercontent.com/2486553/91549847-e3056780-e927-11ea-8525-595994ada36e.png)

**Comment by normanrz** [comment]
Making a toolbar with icons is a good idea. This would also match 99% of existing drawing tools.

**Comment by hotzenklotz** [comment]
I agree. 

(While we are at it: Is merge mode also a tool? Or is it a state? If it is a tool, it should also have a button)

**Comment by philippotto** [comment]
> (While we are at it: Is merge mode also a tool? Or is it a state? If it is a tool, it should also have a button)

I thought about that too and I think that it is a special mode (or state), because one can be in merger mode and still want to switch between moving, creating/deleting nodes (and theoretically also brushing).
