### ISSUE TITLE
How to organize segments?

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4796]
Currently, webKnossos does very little to organize segments of a segmentation. There is no list of segments, there are no names for segments etc. 
It would be nice if we had such functionality. Perhaps this can be achieved through our skeleton features, e.g. a reverse lookup to find a node based on a selected segment. That way users could organize their segments by placing nodes inside them which are organized in an arbitrary hierarchy. The node would be accessible by clicking on the segment instead of searching for it manually in potentially large segments.

**Comment by philippotto** [comment]
Also see https://github.com/scalableminds/webknossos/issues/4667.

And in the long-term picture, we should also consider the isosurface feature for this (see https://github.com/scalableminds/webknossos/pull/4567 where this was also briefly discussed)

**Comment by hotzenklotz** [comment]
We now have a segment list and segment names. Also, meshes are organized under their respective segments. Further, the segment list offer the ability to add user interactions through a right-click menu.

@normanrz I vote to close this issue and open new one with more specific features/work packages.
