### ISSUE TITLE
Show name of annotation in navbar

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4798]
On regular screens, the navbar has plenty of space left. We could show the name or id of the annotation there.

**Comment by hotzenklotz** [comment]
With the introduction of the different "tools" in the navbar, I feel like there is not so much space left for anything else:

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/1105056/197203227-3243391d-d91b-4d06-8b0e-fb4edc348cfd.png">
