### ISSUE TITLE
Merger mode should work if segmentation is not available in mag 1

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#4820]
The merger mode should also work for datasets which don't have a segmentation layer in mag 1. It should probably always use the highest-resolution available for the segmentation layer. Looking at the code, it could be sufficient to add that zoomstep to all `const segmentId = await api.data.getDataValue(segmentationLayerName, position);` (optional third parameter of `getDataValue`).

**Comment by philippotto** [comment]
I'll check whether this is still an issue.

**Comment by philippotto** [comment]
I just tested this and it seems to work (I used a segmentation layer where mag 1 was missing).
