### ISSUE TITLE
Show "resource" summary of tracing in info tab

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4836]
The info tab could show:
- which layers exist (and how many are currently active)
- (segmentation) mapping summary (how many and which is active)
- meshes (count)
- trees+nodes (already done, but maybe the active id could also be shown?)

**Comment by hotzenklotz** [comment]
Mhm, I believe most of the mentioned points have been implemented in one way or the other:
- statusbar
- layer side-panel
- segments tab

@philippotto Do you agree? Voting to close this.

**Comment by philippotto** [comment]
I think, the original idea was to have one place where all resources are summarized (instead of them being scattered around in various spots). However, I don't see a high priority for it, anymore. So, I'm fine with closing it.
