### ISSUE TITLE
Suppress “ResizeObserverLoop” error toasts

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4839]
For some users error toasts saying “resizeobserver loop completed with undelivered notifications” crop up but nothing seems broken. Can we suppress the error toasts?

**Comment by daniel-wer** [comment]
Do you have the full error message or a source/screenshot where this error was reported? If so it'll be easy to suppress the toast.

**Comment by fm3** [comment]
I’m not sure anymore who reported this, could it have been @grittaweisheit ? If I see it again I’ll post a screenshot.

**Comment by grittaweisheit** [comment]
Yes, I see this quite frequently.
![Screenshot from 2020-10-15 11-23-22](https://user-images.githubusercontent.com/44833037/96104769-84954800-0ed9-11eb-8c64-522e8ef7bf4b.png)
