### ISSUE TITLE
Use Authenticated Docker Pulls in CircleCI

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4850]
From CircleCI email: “On November 1st, Docker Hub will begin limiting anonymous image pulls. […] Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions.”

Does this affect the webKnossos CI runs?

**Comment by hotzenklotz** [comment]
Our CircleCI builds still work. So either we fixed it or did not affect us.
