### ISSUE TITLE
Consider higher batch-count when fetching buckets

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4863]
Right now, we usually fetch 3 buckets per HTTP request from the server. This constant has been like this for the last ~ 7 years, I'd guess. It might make sense to tune the number.

I created a dev instance, where I doubled the number (so, 6 buckets are fetched per request). Preliminary measurements suggest that the full load time of a tracing is 10% faster.

I performed the test by opening the devtools and loading the following pages (sequentially). The network tab will show the total time to complete.
https://master.webknossos.xyz/datasets/sample_organization/ROI2017_wkw/view#512,512,512,0,1.000
https://morebucketbatching.webknossos.xyz/datasets/sample_organization/ROI2017_wkw/view#512,512,512,0,1.000

Note that adjusting the constant in question might also have an effect on UX and on server load. We could deploy the new constant to production and measure the performance there somehow. If we implement airbrake-logging for failed bucket requests (see https://github.com/scalableminds/webknossos/issues/4819), that should also be an interesting metric to test against.

**Comment by philippotto** [comment]
Bumping up the batch size would mean, that the loading appearance of data might feel "choppier". However, it might make sense to read the bucket responses as streams so that one can already render buckets if only parts of the request have finished yet.

In JS, this can be done like described here: https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams

However, it might be necessary to change the back-end, too (don't know whether the response is only started when all buckets are there?).

Not sure, whether this gives a worthwhile benefit. Just came to my mind..

**Comment by philippotto** [comment]
@youri-k I only vaguely remember that we talked about this in person. What did we agree on?
We already have logging for the cases where bucket requests take longer (or fail) on the server, right? And via airbrake, we also log failing bucket requests. So, I would say that we can simply bump up the constant in production and compare the numbers after a month or so. Do you agree? I opened this PR here and assigned you as a reviewer :) https://github.com/scalableminds/webknossos/pull/5031

**Comment by youri-k** [comment]
Yes, I agree. I just approved the corresponding PR :slightly_smiling_face:

**Comment by philippotto** [comment]
I couldn't really spot an influence of this in the airbrake analytics. I'd just keep it as is and close the issue for now.
