### ISSUE TITLE
error when brushing into negative coordinates 

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4877]
if in a volume annotation I brush into negative coordinates, an error alert comes up:
```
Internal error.
Please reload the page to avoid losing data.

TypeError: k[e] is undefined S@main.js:1:380703
drawHorizontalLine2d
``'

**Comment by philippotto** [comment]
@MichaelBuessemeyer I'm currently working on the continuous brush, anyway, (and also found the culprit while doing that). So, I'm stealing this issue from you :)
