### ISSUE TITLE
Remember "overwrite mode" in the new toolbar

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#4894]
With the new toolbar currently the overwrite mode overwrites other cell IDs both for adding annotation (i.e. left click) and deleting annotation (i.e. right click). This is a change in behavior from the previous version, where only adding annotation overwrites other cell IDs and deleting annotation does not overwrite.

I could not think of a clear use case for overwriting other cell IDs on deletion, and given that this changes the previous default behavior and causes inconvenience in certain cases, maybe it is worth considering no overwriting on deletion for either mode (i.e. changing the mode only affects adding annotation)?

**Comment by philippotto** [comment]
Yes, you are correct that the default behavior changed. With the redesigned toolbar, we tried to make the available operations and modes more transparent and intuitive. While doing that, we noticed that the differing default overwrite behaviors between drawing and deleting are not very intuitive (and consequentially also not easy to depict in the new mode-buttons). Therefore, we decided to unify the behaviors. In the end, this is a trade-off in favor of UX simplicity and intelligibility.
Note that the behavior can easily be toggled by either pressing CTRL or by switching the mode in the toolbar. So, this change should not be a big annoyance for existing workflows.

**Comment by cnzqy1** [comment]
Thanks for the explanation! We rarely have use for the overwrite mode, so maybe another option would be making the choice of mode persistent? Currently every time we open the annotation mode it defaults to overwrite and does not recall the previous mode selection.

**Comment by philippotto** [comment]
> maybe another option would be making the choice of mode persistent?

Very good point! I'll try to get to this soon :+1:
