### ISSUE TITLE
Shortest path (length) between two nodes / More UI

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4906]
It should be possible to get the shortest distance between two nodes (See https://discuss.webknossos.org/t/show-pathlength-for-a-skeleton/1620/8.)

I think, the crucial part will be to do the UI well. For such scenarios, a context menu might be a good option? Shift+Rightclick on a node could open a menu with the following options:

- "create edge to this node" (if possible)
- "delete edge to this node" (if possible)
- "delete this node"
- "measure shortest distance to this node"
- "measure total distance of this tree"

etc.

What do you think? @normanrz @fm3 @daniel-wer ?

**Comment by normanrz** [comment]
sounds good!
