### ISSUE TITLE
show volume download toast “fallback data is excluded” only if fallback layer exists

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4919]
when downloading volume annotations that have *no fallback layer*, the user should not receive information about how fallback layers are handled

**Comment by grittaweisheit** [comment]
I'm not getting the info toast when there is no fallback layer. @fm3 , could you please have a look, if you experience different behaviour?

**Comment by fm3** [comment]
Works for me too now, maybe this changed since I noticed it. Thanks for checking!
