### ISSUE TITLE
Fill-tool produces spotty segmentation in other mags

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4923]
reproduction steps:
- zoom to mag 8-8-1
- use the fill tool on an empty plane --> produces rectangle
- zoom in --> some buckets are missing?

**Comment by valentin-pinkau** [comment]
![buckets-missing](https://user-images.githubusercontent.com/2582395/98565809-56274480-22ae-11eb-820a-40dabb0bcdc4.gif)

**Comment by MichaelBuessemeyer** [comment]
@philippotto debugged this problem and found out that this error occurs when the user labels too many buckets that do not fit into the memory.
Therefore we will restrict the magnifications in which it is allowed to use the fill tool.
