### ISSUE TITLE
Add Isosurface Support for Volume tracings with Fallback layer

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#4930]
Currently, the on the fly Isosurface generation of a tracing done by the backend is only supported for tracings without a fallback layer.
It would be nice if this feature would also support tracings with fallback layers.
The following questions need to be discussed:
- Is this actually a use case? Would our users use the isosurface generation in tracings with a fallback layer?
- What has to needs to be implemented for this feature?
  - @fm3 mentioned that to generate the isosurface data from the tracing and the datastore are required to be mixed. Currently, both stores do not have a way of communicating with each other.
- Does the value of this feature outweigh the implementation afford?

**Comment by fm3** [comment]
Yes, users asked for this feature again, so we’ll schedule it. Implementation will mostly go to the backend, streaming fallback layer data from the datastore to the tracingstore. removing the discussion label.
