### ISSUE TITLE
On public datasets, reload data button fails if logged out

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4947]
it’s fine that the un-authenticated user is not allowed to clear the server cache. however, the front-end part (reloading data from the server) could still be executed

**Comment by hotzenklotz** [comment]
Looks like the the "reload layer data" button is no longer displayed in the UI if you are not logged in. 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1105056/197476952-97ce9bf6-427c-476a-8987-405c57aaa30b.png">

Closing as solved.
