### ISSUE TITLE
Check whether k/l zoom can be removed

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4951]
The k/l zoom feature is very hard to find and can cause confusion. Additionally, removing this feature would remove a considerable amount of complexity.

The first step should be to check how often this feature is used. For that, additional analytics actions should be emitted when the shortcuts are used.

**Comment by MichaelBuessemeyer** [comment]
Reminder: If we remove this feature, we have to remove the following field from the store: `store.userConfiguration.layoutScaleValue`
