### ISSUE TITLE
Show organization display name in menu, if available

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4964]
When clicking on the my name in the navbar, I see the long ID of my organization instead of it's name. 

![image](https://user-images.githubusercontent.com/1105056/100853254-d7c25a80-3487-11eb-9d14-134560b31382.png)

**Comment by fm3** [comment]
I think this is the name. @normanrz requested that users don’t have to specify organization names on signup, but instead get auto-generated names.

They may be able to change the display name, later, which is another field. 

It may be desirable to show that one in this menu, if it is available.

**Comment by philippotto** [comment]
in the context of the global-user-issue, I just had a look at this and I'll fix/improve it on the way. right now, the display name of the org is never used.

**Comment by philippotto** [comment]
should have been fixed with the global-user-pr.
