### ISSUE TITLE
datastore should offer route to report one new dataset

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4975]
if you programmatically added a new dataset to the binaryData directory, it may be desirable to trigger a refresh (`checkInboxBlocking`) – however, if you already know the dataset path, a variant of this route should be offered that reports just that one new dataset

**Comment by youri-k** [comment]
This should already be possible with the `/triggers/reload/:organizationName/:dataSetName` of the DataStore. As far as I can tell from looking at the code, the DataSet does not need to exist beforehand.

**Comment by fm3** [comment]
Yes, that works, thanks for pointing it out!
