### ISSUE TITLE
Toggling segmentation layer off and on in volume annotation mode resets to pointer tool

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#4978]
After the multi-resolution annotation update, toggling segmentation layer off and on using keyboard shortcut `3` resets the tool to pointer. Is it possible to make the previous tool selection persistent during the tracing session (the behavior in previous versions)? Sometimes it's nice to check whether we annotated too much by turning off the segmentation layer and then make modifications.

**Comment by philippotto** [comment]
Thank you for the report. This sounds very reasonable. We will have a look at it!

**Comment by fm3** [comment]
This has now finally been implemented in #6362
