### ISSUE TITLE
Suggest organizations if email domain matches (opt-in)

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4981]
The organization admin should be able to enable that other users with a matching email domain can see the organization. This would be very useful for all institutions which have an own email domain.

See https://github.com/scalableminds/webknossos/issues/4761 for context.

**Comment by fm3** [comment]
I’d guess that this no longer really makes sense since on multi-orga instances we now typically use join-by-invite. What do you think?

**Comment by philippotto** [comment]
yes, the idea originated from a time when organizations could be selected during registration.
