### ISSUE TITLE
Brainstorm on wK layout

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4996]
Some ideas (also see https://www.notion.so/scalableminds/Design-Doc-UI-and-Shortcuts-76a59ceaa7fb49d8810df24fd56f1282):

- Get rid of tabs in current settings menu
    - Move BBoxes to own view
    - Volume options to tool-menu
    - Skeleton options to tool-menu
    - Controls + Viewport + Other → Dataset
- Have a collapsible sidebar on the left and right side
- Restrict the super-customizable layout (how much customization is really needed?)

Next step:
- [x] create one or multiple mock ups for a new layout

**Comment by normanrz** [comment]
![layout](https://user-images.githubusercontent.com/335438/103301053-c164db80-4a00-11eb-9dcb-7ad07df6b1a4.png)

I made a mockup for the layout and annotated the image a bit. Some key ideas:
- There are left and right sidebars. Both are resizable and collapsible. Inside the sidebars, tabs and containers may be re-organized. This means wK gets a full-window layout without any scrollbars
- There is a new status bar in the bottom, which holds the sidebar toggles, viewport information, useful controls (context-sensitive) und download/runtime stats.
- Skeleton and volume annotation settings are presented in the right sidebar
- Viewport and layer settings are in the left sidebar
- The right sidebar opens the relevant tabs when changing the tool (e.g. move, skeleton, volume, bbox)
- The selector for view mode are presented as icons
- We don't have bboxes as a tool initially, but I think that would be great to have in the future

**Comment by philippotto** [comment]
Looks cool :+1: 

I agree with most of the points and only have a few remarks/questions:

> Inside the sidebars, tabs and containers may be re-organized.

Maybe we should question whether we this is really necessary. We could cut a lot of complexity if the layout was simply rigid. Maybe we can run some analytics processing over the used layouts to find out what users really do with the flexible layouts right now.

> There is a new status bar in the bottom, which holds the sidebar toggles [...].

Usually, status bars are very narrow and therefore not the ideal container for click targets. Have you seen this concept in other software? I guess, we could simply give it a try, though. However, I would have expected the toggles in the top left/right corers.

> The right sidebar opens the relevant tabs when changing the tool (e.g. move, skeleton, volume, bbox)

So, switching the active tool will swap the set of visible tabs in the right sidebar, right? There probably will users who dislike this, but maybe that's ok.
In the mock-up, it feels a bit inconsistent that the info-tab is only (?) visible for the move-tool, but the skeleton-tab is visible in both move-tool and skeleton-tool. Maybe, the info-tab should always be visible?
I like that the bottom-right tab pane usually shows settings (except for the info-tab where segmentation-specific things are shown; maybe this can be made more consistent).

Also pinging @fm3 @daniel-wer @MichaelBuessemeyer for feedback.

**Comment by fm3** [comment]
Yes, looks pretty cool 👍 

I agree with Philipp on the (few) insoncistencies he pointed out.

I think the bottom bar being combined for status info AND clicktargets may be a fair compromise (even though it can’t be that narrow then. But stuff has to go somewhere… Maybe the pure output/statusbar part of it can even be two lines then?)

Concerning dropping the layout customizability: 
I personally use it only for the viewports in the middle (I sometimes rearranged them so that I see one data viewport plus the 3d viewport, or one data viewport only, or have them have different sizes). This is not supported by the fullscreen function as that one would also hide the trees tab, right?
Concerning layout customizability for the other tabs, I agree that we should find out what users are actually doing there (let’s start with a survey in our office?). I do think that this is a pretty cool feature of webKnossos. I’m not using it much but I also don’t deal very much with skeleton tracings.

Still, generally, I like the new layout idea :)

**Comment by hotzenklotz** [comment]
Nice! Mock up looks pretty good. 

@normanrz  Just for clarification on the "right sidebar": Will there always be two panes stacked on top of each other? Or in other words, is the "Segmentation Pane" always visible and only the tabs above it switch?

**Comment by normanrz** [comment]
> There is a new status bar in the bottom, which holds the sidebar toggles [...].

<img width="1214" alt="Screenshot 2021-01-04 at 09 59 03" src="https://user-images.githubusercontent.com/335438/103522416-a370fe00-4e7a-11eb-8679-a6a6d5997390.png">

Some Mac applications have that. In this screenshot you can see both toggles at the top and bottom. I think the size of the click targets can be smaller if we don't expect them to be clicked very often (not sure if that is the case here). Users are using a mouse anyways, we don't need to optimize for fat fingers.

<img width="1016" alt="Screenshot 2021-01-04 at 10 52 46" src="https://user-images.githubusercontent.com/335438/103522743-167a7480-4e7b-11eb-8727-80b86ffb520f.png">

**Comment by normanrz** [comment]
> In the mock-up, it feels a bit inconsistent that the info-tab is only (?) visible for the move-tool, but the skeleton-tab is visible in both move-tool and skeleton-tool. Maybe, the info-tab should always be visible?

I didn't know how to visualize that in excalidraw properly. I was thinking that all tabs are available at all times, but the ordering changes based on the selected tool, i.e. relevant tabs are in focus.

**Comment by normanrz** [comment]
> > Inside the sidebars, tabs and containers may be re-organized.
> 
> Maybe we should question whether we this is really necessary. We could cut a lot of complexity if the layout was simply rigid. Maybe we can run some analytics processing over the used layouts to find out what users really do with the flexible layouts right now.

Would be good to find that out. Iirc many graphics tools have the option to move around and reorganize these tool windows. I think that is useful, e.g. some user might want to stack trees and comments over one another and others want them separately. My intention was to insert layout constraints (i.e. left sidebar, center, right sidebar as rigid containers) in order to simplify the handling of the sidebars.

**Comment by normanrz** [comment]
> Just for clarification on the "right sidebar": Will there always be two panes stacked on top of each other? Or in other words, is the "Segmentation Pane" always visible and only the tabs above it switch?

That is a good question: Should 2 vertically stacked tool windows belong to the same tab or are they their own tab containers? I think I've seen both in other software.

**Comment by philippotto** [comment]
> > In the mock-up, it feels a bit inconsistent that the info-tab is only (?) visible for the move-tool, but the skeleton-tab is visible in both move-tool and skeleton-tool. Maybe, the info-tab should always be visible?
> 
> I didn't know how to visualize that in excalidraw properly. I was thinking that all tabs are available at all times, but the ordering changes based on the selected tool, i.e. relevant tabs are in focus.

Ah, ok, I like this better, since everything is always available then. I just had another thought which could be useful for this scenario. LibreOffice Writer also has a sidebar with different tab panes. These panes are all stacked above each other like an accordion. The ordering cannot be changed, but the user can decide which should be expanded. This has the following advantages:

- we don't run out of horizontal space for the tab titles (since they are stacked vertically)
- the user can open multiple "tabs" at the same time (a bit similar to completely customizable tab panes)
- we could auto-expand relevant tabs when switching tools without hiding stuff which was previously visible

Here's a screenshot ("Area" and "Position and Size" are expanded; "Line" is collapsed).

![image](https://user-images.githubusercontent.com/2486553/103526553-63614980-4e81-11eb-9a31-b64279e8ca72.png)

Also, the status bar has click targets. So, I take my previous objection back.

**Comment by hotzenklotz** [comment]
> Ah, ok, I like this better, since everything is always available then. I just had another thought which could be useful for this scenario. LibreOffice Writer also has a sidebar with different tab panes. These panes are all stacked above each other like an accordion. The ordering cannot be changed, but the user can decide which should be expanded. This has the following advantages:
> 
> * we don't run out of horizontal space for the tab titles (since they are stacked vertically)
> * the user can open multiple "tabs" at the same time (a bit similar to completely customizable tab panes)
> * we could auto-expand relevant tabs when switching tools without hiding stuff which was previously visible

With this stacked approach, I wonder how we would handle long lists of stuff. E.g. Imaging the default stacks are 1. Skeletons 2. Volumes 3. etc.  In a case were you have a list of 1000 skeletons, where would we place the next "tab"/"stack" then? Still below all skeletons? Or will the skeletons just have a scrollbar and the next "tabs"/"stacks" are still visible? 

In the second case, I am afraid we will waste a lot of vertical spaces just with the tabs/stack names as well. (Although the same argument can be made for a horizontal layout)

**Comment by philippotto** [comment]
> > Ah, ok, I like this better, since everything is always available then. I just had another thought which could be useful for this scenario. LibreOffice Writer also has a sidebar with different tab panes. These panes are all stacked above each other like an accordion. The ordering cannot be changed, but the user can decide which should be expanded. This has the following advantages:
> > 
> > * we don't run out of horizontal space for the tab titles (since they are stacked vertically)
> > * the user can open multiple "tabs" at the same time (a bit similar to completely customizable tab panes)
> > * we could auto-expand relevant tabs when switching tools without hiding stuff which was previously visible
> 
> With this stacked approach, I wonder how we would handle long lists of stuff. E.g. Imaging the default stacks are 1. Skeletons 2. Volumes 3. etc. In a case were you have a list of 1000 skeletons, where would we place the next "tab"/"stack" then? Still below all skeletons? Or will the skeletons just have a scrollbar and the next "tabs"/"stacks" are still visible?
> 
> In the second case, I am afraid we will waste a lot of vertical spaces just with the tabs/stack names as well. (Although the same argument can be made for a horizontal layout)

I think, only the second case will be usable (otherwise, you have to scroll miles to get to another tab). You are right, that vertical space can be wasted easily (however, I'm not sure how big that impact will be; 6 tab titles would mean that 6 trees less can be shown). A solution to this could be that the user can increase the height of the tree pane and then scroll the entire sidebar so that the other tab titles will be off-screen. Something like this:

![image](https://user-images.githubusercontent.com/2486553/103528900-0e273700-4e85-11eb-9c73-8fb598cdcfc0.png)

Obvious downside: the scrollbar might not be intuitive to use (primarily on osx, since they are hidden by default).

**Comment by hotzenklotz** [comment]
> > > Ah, ok, I like this better, since everything is always available then. I just had another thought which could be useful for this scenario. LibreOffice Writer also has a sidebar with different tab panes. These panes are all stacked above each other like an accordion. The ordering cannot be changed, but the user can decide which should be expanded. This has the following advantages:
> > > 
> > > * we don't run out of horizontal space for the tab titles (since they are stacked vertically)
> > > * the user can open multiple "tabs" at the same time (a bit similar to completely customizable tab panes)
> > > * we could auto-expand relevant tabs when switching tools without hiding stuff which was previously visible
> > 
> > 
> > With this stacked approach, I wonder how we would handle long lists of stuff. E.g. Imaging the default stacks are 1. Skeletons 2. Volumes 3. etc. In a case were you have a list of 1000 skeletons, where would we place the next "tab"/"stack" then? Still below all skeletons? Or will the skeletons just have a scrollbar and the next "tabs"/"stacks" are still visible?
> > In the second case, I am afraid we will waste a lot of vertical spaces just with the tabs/stack names as well. (Although the same argument can be made for a horizontal layout)
> 
> I think, only the second case will be usable (otherwise, you have to scroll miles to get to another tab). You are right, that vertical space can be wasted easily (however, I'm not sure how big that impact will be; 6 tab titles would mean that 6 trees less can be shown). A solution to this could be that the user can increase the height of the tree pane and then scroll the entire sidebar so that the other tab titles will be off-screen. Something like this:
> 
> ![image](https://user-images.githubusercontent.com/2486553/103528900-0e273700-4e85-11eb-9c73-8fb598cdcfc0.png)
> 
> Obvious downside: the scrollbar might not be intuitive to use (primarily on osx, since they are hidden by default).

I see. I would prefer not having to scroll to reach important section headers/tabs.

**Comment by philippotto** [comment]
Btw, we could give this library a go instead of golden layout:
repo: https://github.com/caplin/FlexLayout
demo: https://rawgit.com/caplin/FlexLayout/demos/demos/v0.5/demo/index.html

This lib seems to support collapsible sidebars by default and also can show tab titles vertically.

![image](https://user-images.githubusercontent.com/2486553/103548369-fe6c1a80-4ea5-11eb-9443-90663307c5c4.png)

**Comment by normanrz** [comment]
FlexLayout is better bc it is native React?

**Comment by philippotto** [comment]
> FlexLayout is better bc it is native React?

golden-layout also supports react, but the interface is a bit tedious (FlexLayout seems to be similar, though). The benefit I see is that FlexLayout supports collapsible sidebars which we could use for the sidebars in your mock-up. Achieving the same with golden-layout will probably be quite complicated, since golden-layout assumes that it owns the whole page. Shrinking its container dynamically wasn't really possible (or quite buggy) in the past (that's why the current sidebar pushes the layout to the side). If we don't want to use the sidebar-feature of FlexLayout we could still try whether it's more compatible with shrinking the container than golden-layout is.
