### ISSUE TITLE
Auto-Detect “needsConversion” on Dataset Upload

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5001]
We could unpack every dataset to a temp dir first and then check the contents to decide if it needs some conversion or is ready to be moved to destination dir as is

**Comment by philippotto** [comment]
@MichaelBuessemeyer could you have a look whether the front-end can get the file names within a ZIP without having to hold the entire zip file in memory? then, one can iterate over all files to check whether there is a wkw file. in that case, "needsConversion" can be set to false.

Here we are also looking at the file names within a zip file:
https://github.com/scalableminds/webknossos/blob/72dfd4f0a72b95e69e86967ee2030aa32aca35a1/frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js#L208-L211

However, I'm not sure whether this loads the entire zip into main memory. You can verify this by loading a 1 GB zip file into wK and read the file names in the zip. if it's fast and the RAM looks ok, this should be a good approach to close this issue :).

**Comment by MichaelBuessemeyer** [comment]
@philippotto According to this [issue](https://github.com/Stuk/jszip/issues/290) `JSZip` does not support this. However, [this project](https://gildas-lormeau.github.io/zip.js/index.html) does and it can be used pretty easily using an npm package.
The first implementation of this works and is in the upload UI rework PR.

**Comment by fm3** [comment]
Fixed in #5081 :rocket:
