### ISSUE TITLE
Sort project list by creation or last progress

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5008]
The project list doesn't have a specific ordering by default. This has the effect that the most recent (probably currently active) projects are at the bottom. It would be nice if the projects list would be ordered in a way that the most recent projects are up top.

**Comment by hotzenklotz** [comment]
The REST API does not include any timestamps for created/modified dates ATM. So it is not straight forward to add a default sorting order based on time/date.

**Comment by normanrz** [comment]
cc @fm3

**Comment by fm3** [comment]
Just pushed the branch `projects-created` where the `created` timestamp is now included in the project json. With that you should be able to work this into the front-end (or assign somebody to do it)
