### ISSUE TITLE
Shiny Reports: prevent duplicated json upload

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5029]
Running the same workflow twice will publish a report to two different URLs (the workflow name is concatted with the current date right now which makes the existing reports somewhat immutable).

In some cases, the above behavior is desired (especially, since the workflow names are not guaranteed to be unique). For ongoing projects, where one would like to share a URL to the current status (--> a mutable report would be helpful).

One idea to improve this is as follows: The user can provide a CLI parameter like `vx run ... --report_name project_x`. this report name is used to publish the report (will be overwritten if it already exists). One could also think about having this parameter as part of the config.

The downside of the above change is that the user is responsible for providing a suitable report name. In case one forgets to swap the name, another report is potentially overwritten. Do we need backups for this scenario?

What do you think? @daniel-wer @georgwiese @jstriebel @valentin-pinkau

**Comment by normanrz** [comment]
Please move to voxelytics repo.
