### ISSUE TITLE
Local storage quota exceeded

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5038]
For the second time I got the Firefox error message described here https://support.mozilla.org/de/questions/1309735 while refreshing the dataset list. Clearing site data helps, but, do we need to store that much? Or is there a leak?

Can the error be caught and handled appropriately?

**Comment by fm3** [comment]
A chrome user reported the same problem.

**Comment by philippotto** [comment]
i'll build a hotfix now.

**Comment by philippotto** [comment]
I think, we can close this issue. We've got an error boundary UI now which also shows a button to clear the local storage if this quota should be exceeded. Also, the cached dataset list is more compact now, so the chances should be rather low.
