### ISSUE TITLE
Don't scroll up on "deactivate user"

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5053]
When clicking "deactivate user" in the user list, I am scrolled to the top of the page which is very annoying when trying to deactivate multiple consecutive users. Maybe this can be fixed with a `preventDefault` call. Might also apply to other links in the list.

**Comment by fm3** [comment]
Related: https://github.com/scalableminds/webknossos/issues/4988

**Comment by fm3** [comment]
Same for other popups, e.g. “Do you really want to delete this task?”
This is a bit annoying when you want to delete a few in a row and you have to scroll there again every time
