### ISSUE TITLE
Enable parallel upload of dataset chunks during import

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5056]
might improve speed a bit. low-pri in my opinion. the following needs to be fixed then:

> The name-reserving logic of the wk backend leads to errors if upload chunk requests come in parallel. Since that fix looks nontrivial I suggest we disable parallel requests for the moment, to fix the uploads.

see https://github.com/scalableminds/webknossos/pull/5055 for context

**Comment by fm3** [comment]
Some atomic/synchronized test-and-set is required for `uploadService.isKnownUpload` there
