### ISSUE TITLE
Do not allow deactivating oneself

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5061]
Organizations can get orphaned if the last admin deactivates themselves.

Also, is there *any* case where a user should be allowed to deactivate themselves?

**Comment by philippotto** [comment]
> Also, is there any case where a user should be allowed to deactivate themselves?

Can't think of any real world scenario for this. This means, we could simply forbid that an admin disables him/herself?

**Comment by fm3** [comment]
Yes, that would be the strict version.
A less strict one would be to extend the `preventZeroAdmins` check so that it is not only triggered when admin rights are revoked but also when admins are deactivated. https://github.com/scalableminds/webknossos/blob/master/app/controllers/UserController.scala#L289

**Comment by normanrz** [comment]
I think it shouldn't be possible to deactivate oneself.
