### ISSUE TITLE
Remove Save Button from some Modals?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5074]
We should go through modals like the annotation sharing modal and see which of them should auto-save on every click, and which need an explicit save button

**Comment by normanrz** [comment]
Auto-save:
- [ ] Sharing modal in annotation

**Comment by hotzenklotz** [comment]
> ein problem ist, dass man bei dem share-modal auf “save” klicken muss. das hab ich schon ein paar mal vergessen
