### ISSUE TITLE
Proxy landing page

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5075]
For the new landing page of webknossos.org, we need to proxy some routes to a different origin.

- `/` proxy only if unauthenticated
- `/features`, `/faq`, `/pricing` and probably a growing list in the future

**Comment by fm3** [comment]
Probably using something like this 

```
def featuresPage = Action.async {
  WS.url("https://elsewhere").get().map(resp => Ok(resp.body).as("text/html"))
}
```

similar to https://gist.github.com/hanxue/8952231
