### ISSUE TITLE
Cache publication thumbnails across restarts

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5089]
Now that we are more frequently upgrading the webknossos.org instance, the thumbnail cache gets cleared very often, leading to long load times. It would be nice if the thumbnail cache could survive back-end restarts. We could use Redis or Postgres for that, or even just save them to disk.

**Comment by hotzenklotz** [comment]
@fm3 Do we still use Redis?

**Comment by fm3** [comment]
Yes, the tracingstore still uses Redis for transaction management. However, I now generalized the title of this issue, since it is not clear that redis is the best solution for this use case as well. Postgres could also be an option.
