### ISSUE TITLE
Persist seed position when downloading isosurface as STL

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5103]
Persist the seed position when downloading isosurface as STL. Then, we can parse that position and use it during the import. Right now, the seed position is missing during the import.

Context: The seed position is jumped to when clicking on an isosurface in the new list (in the meshes tab).

**Comment by hotzenklotz** [comment]
@philippotto We don't support generic STL import any longer. Therefore, this issue is no longer valid. Voting to close this.
