### ISSUE TITLE
Organization page

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5105]
There should be an admin view for configuring the organization. I think there should be the following features initially:

- Change display name
- Remove organization (shallow delete)
- See current plan (enum with basic, premium, pilot)
- Configure new user notification email

Eventually, this should also include features like:
- See current user and storage usage
- Change billing information
- Configuration of organization-specific datastores

**Comment by fm3** [comment]
organization JSON additional fields (only present when admin)

pricingPlan: String
newUserMailingList: String

new routes 

DELETE        /organizations/:organizationName
PATCH         /organizations/:organizationName
(analogue to PATCH         /datasets/:organizationName/:dataSetName)

parameters:
displayName: String
newUserMailingList: String

(both need to be set, use old value of unchanged)

will fail if not admin
