### ISSUE TITLE
Add “view dataset” shortcut button to dataset settings page

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5117]
After editing a dataset settings page I have to go back to the dashboard and find it in the list again.
Would be cool to have a simple view button on the settings page

**Comment by hotzenklotz** [comment]
Good idea. Yet, the dataset settings page includes several tabs. Where would you place this shortcut? The `Data` tab (first tab).

**Comment by fm3** [comment]
or possibly above the tabs 🤷
