### ISSUE TITLE
LayerConfiguration lookup with no layers

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5128]
We’ve had a single occurrence of this:

org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
 Position: 194: ERROR: syntax error at or near ")"
 Position: 194
Causing query: [select layerName, viewConfiguration
             from webknossos.user_dataSetLayerConfigurations
             where _dataset = ?
             and _user = ?
             and layerName in ()
         ]

The question mark is expected (displays passed parameters) but the `()` should never happen, it means an empty layer array was passed. Where did that come from?

**Comment by philippotto** [comment]
Is there a connection to the recent change where we allowed a dataset to have zero layers? I'm a bit fuzzy on the details, but I think we changed something there.

**Comment by fm3** [comment]
Possibly, that was https://github.com/scalableminds/webknossos/pull/4959 – making it “unusable”/"unimported". Do you know if the front-end still asks for layer configurations when opening an unimported dataset?

**Comment by philippotto** [comment]
Opening an "unimported" dataset should not be possible. But hitting "import" could open the edit/import view which fetches `/api/dataSetConfigurations/default/${datasetId.owningOrganization}/${datasetId.name}` as far as I can see.

**Comment by fm3** [comment]
Hmm, no that route doesn’t lead to this query, only `api/dataSetConfigurations/:organizationName/:dataSetName` does. 
I could not reproduce it with a zero-layer dataset, neither by clicking view nor import.
Maybe a race condition, the dataset was already open and then (possibly due to datastore downtime) it *became* a zero-layer dataset. 
Since there has been only a single occurrence of this I’d say it’s not super important. I’ll change the query so that an empty layer list will not result in a syntax error. Do you agree?

**Comment by philippotto** [comment]
Yes, sounds good :+1:

**Comment by fm3** [comment]
Closing this since there have been no reports of any errors concerning the layer configuration.
