### ISSUE TITLE
Cannot set scale of [1,1,1]

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5129]
When using 1,1,1, in the advanced tab of the datasource edit view, this error message is shown below the editor:

Invalid schema: instance.scale[0] must be strictly greater than true; instance.scale[1] must be strictly greater than true; instance.scale[2] must be strictly greater than true

The corresponding schema looks like this: `items: { type: "number", minimum: 0, exclusiveMinimum: true },` in `datasource.schema.js` which sounds about right. Needs investigation.

**Comment by fm3** [comment]
Not that 0.4 is also not valid, nor is 1.4. 2 is. Sounds like a truthiness thing to me »strictly greater than true«
