### ISSUE TITLE
Allow to select target mag for volume annotations

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5148]
## Detailed Description
Allow to choose a base mag for a volume annotation when
- creating tasks
- creating an explorational annotation

## Context

When creating a volume annotation (either as explorational or via task), the base mag in which the new data is annotated will be the lowest (best quality) mag which exists in the segmentation layer. If no segmentation layer exists, this defaults to mag 1.
However, annotating large processes is usually done best in a higher mag. Therefore, it should be possible to choose which mag should be used as a base.

A current workaround for this is to create a new dataset and symlink the base mag as mag 1 in the segmentation layer.

## Approach/Implementation

If we simultaneously restrict which magnifications are visible, the implementation in the front-end should be straightforward, since we could simply adapt the magnifications of the segmentation layer as if only the selected base mag (plus descendents) exist.
The back-end would need to communicate the selected base mag and we would need UI for specifying the base mag for task creation and explorational creation.

## Related issues

The volume tool restrictions would need to be loosened too then: https://github.com/scalableminds/webknossos/issues/5067

**Comment by fm3** [comment]
I think this is already partially solved by the Resolution Restrictions introduced in #4891 – we should have a closer look what is still missing for this
