### ISSUE TITLE
Remove add-sample-dataset feature from demo instances

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5155]
## Detailed Description
On webknossos.org we can simply link to a public dataset. There shouldn't be any need for downloading a sample dataset via the existing UI. Therefore, we should hide the add-sample-dataset-tab from thedataset import view if `demo==true`. As a substitute, we could link to a public dataset (see `publicDemoDatasetUrl`)

**Comment by fm3** [comment]
superseded by https://github.com/scalableminds/webknossos/issues/6005
