### ISSUE TITLE
Integrate tiled TIFF support in datastore

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5160]
## Detailed Description
The webknossos-datastore should be able to work with datasets that are a single tiled-tiff file.

## Context
WKW doesn't lend itself well to 2D datasets. We have done experiments that tiled tiff files work well (see https://github.com/scalableminds/webknossos-connect/pull/97).

**Comment by fm3** [comment]
Check out https://github.com/imglib/imglib2/ for this (possibly just for data handling as alternative to numpy, but maybe it can do even more for us)

**Comment by fm3** [comment]
@normanrz Do you think this issue is still relevant? I guess we’ll use zarr with appropriate chunks/shards for 2d data?

**Comment by normanrz** [comment]
Nope, zarr is the preferred solution here. At some point we should make the wklibs write out zarr datasets with chunk_shape = (xx, xx, 1) for 2D data
