### ISSUE TITLE
Show distances in VX

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5177]
## Detailed Description
Currently, measuring a tree will show its length in metric space (e.g., in µm). Additionally, we could/should show the distance in voxel-space (sans the dataset scale).

## Context
For example, for measuring jumps in alignments, the raw voxel distance is way more useful than the metric.

**Comment by fm3** [comment]
This has been solved in the meantime :) 
![image](https://github.com/user-attachments/assets/cdd8ec99-e803-46aa-8471-246ccc8fb257)
