### ISSUE TITLE
Clean up Config Field Naming

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5179]
The application.conf keys are messy.

- braingames.binary is not a semantic name anymore
- There is no consistent handling of units (I’d say they should be in the names, except for durations, where the Duration/FiniteDuration type should be used instead of integers)
- uri vs url vs address + port should be unified (not sure yet which is best)
- agglomerates should get their own block rather than use prefix to group
- Unclear what is in webKnossos block and what is outside of it
- naming: allowX vs xAllowed
- allow vs enable 
- Check which config fields should really be exposed (e.g. does silhouette need that many?) 
- Move silhouette to application.authentication ?
- get rid of features block; instead annotate in wkConf.scala which fields should be exposed.

Problem is that this would require extensive changes for operators in how they overwrite the keys, so we should consider if this is really worth it, and write a good explanation for the migrations guide

**Comment by normanrz** [comment]
Would it be possible to write an automated migration or support the keys in a backwards-compatible manner?

**Comment by fm3** [comment]
Possible, yes, but not trivial. As discussed in person, I think a complete and concise description in the migration guide will suffice. This is what we did with previous config changes too. If anyone is having trouble, we can probably help them as well.
