### ISSUE TITLE
Add a tool for drawing/editing bounding boxes

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5185]
## Detailed Description
Add a gui tool for drawing and editing bounding boxes. I would imagine this to work similar to rectangle drawing tools in any image editing software. Ofc webKnossos has 3D support: 1. Draw a rectangle in a viewport which gives the bbox a default depth (maybe 1) and then 2. resize the bbox in another viewport.

## Context
I think bounding boxes are one of the annotation primitives of webKnossos (next to voxel ids, skeletons aka polygons). Currently, they can only be created indirectly by specifying the coordinates. That is not very intuitive or easy; especially when annotating biological features instead of arbitrary bboxes.

**Comment by philippotto** [comment]
A very simplistic approach for creating a bounding box could also be to select a tree and choose something like "Create bounding box from nodes". Selecting this will create the bounding box which contains all nodes of the selected tree. This could also be very useful when structures are already annotated.

A fancier way of drawing/editing bounding boxes as described above would be even cooler obviously. But maybe as a step in-between..

**Comment by philippotto** [comment]
New idea: "Create Bounding Box"-button simply creates a bounding box of fixed size X around the current position (maybe offer a dropdown with different preset sizes). Additionally, add an edit mode for bounding boxes which is automatically enabled after creating a new bounding box. In this edit mode, one can resize and move the current bounding box in the 3D viewport. The controls for this are available by three.js. See https://threejs.org/docs/#examples/en/controls/TransformControls and the demo here: https://threejs.org/examples/#misc_controls_transform
