### ISSUE TITLE
Deduplicate bounding boxes on import/merge

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5190]
## Detailed Description
Importing multiple NMLs which share the same bounding boxes should deduplicate these bounding boxes. This should happen in front-end as well as back-end upload probably.

## Context
See https://github.com/scalableminds/webknossos/issues/5188.

**Comment by hotzenklotz** [comment]
@fm3 I believe you just did some (related) work on this? #6576 Does you fix also apply/cover to this issue?

**Comment by philippotto** [comment]
Yes, this is a duplicate of #6562. Closing this (even though it was created earlier).
