### ISSUE TITLE
Tiff Export for Volume Annotations

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5203]
https://github.com/scalableminds/webknossos/pull/5195 creates the possibility to export data as tiff stacks.
It would be helpful for annotation pipelines if this could include volume annotations created by the webKnossos user.

The long-running job would have to get the volume data from the tracingstore (or fossildb directly?), unpack it, and mix it with the fallback segmentation layer data.

Should probably include the possibility to select the version of the volume tracing.

**Comment by cnzqy1** [comment]
I would love to see this feature implemented, especially with the ability of downloading TIFF files mixed with the fallback segmentation layer.
