### ISSUE TITLE
Add hours to project list

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5206]
## Detailed Description
Add another column `Hours` to the projects list in the backend.
@fm3 can you comment whether this would be feasible perf-wise?

## Context
For billing purposes, we need to know the total number of hours per project.

**Comment by fm3** [comment]
I don’t think it’s a big problem, perf-wise, in my test it slowed the project list query from 600ms to 650ms

**Comment by fm3** [comment]
Also note that the project progress overview screen under statistics already shows the project hours. Maybe that is already sufficient for your purpose? However, projects vanish there after some time (and complex criteria)

**Comment by normanrz** [comment]
> projects vanish there after some time

that is my problem ;-)
