### ISSUE TITLE
Zoom with track pad

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5213]
## Detailed Description
Add pinch-to-zoom with a trackpad. Apple computers support this; linux and windows maybe. I think support is based on the pointer events API.

**Comment by philippotto** [comment]
Might be useful: https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e

It states that figma makes this work for mac trackpads. Since pinch-to-zoom doesn't work in figma for me, it seems to be not easily possible to support linux probably.

**Comment by normanrz** [comment]
We probably could also use Ctrl+Scroll for zoom. Or do we use that for something else?
