### ISSUE TITLE
Screenshot for 3D view

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5218]
## Detailed Description
`Q` should also make a screenshot of the 3D viewport

## Context
To make pretty pictures of meshes, it should be possible to make a screenshot of the 3D viewport

**Comment by daniel-wer** [comment]
I had a quick go at this and it's easily possible, however, the result is not antialiased. See [this threejs thread](https://discourse.threejs.org/t/why-is-a-custom-fbo-not-antialiased/1329). Basically, it would require WebGL 2 or FXAA via post processing. From the [threejs example](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_fxaa.html) the FXAA pass doesn't look too complicated, I'll give it a go.

The unprocessed screenshot looks like this:
![segem_test_mag_2__201_197_75__TDView](https://user-images.githubusercontent.com/1702075/111600676-f0097b80-87d1-11eb-9b6f-7da241895955.png)

**Comment by normanrz** [comment]
Un-anti-aliased looks fine as well. Better than nothing :-)
