### ISSUE TITLE
Delete tree from context menu

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5242]
## Detailed Description
In the tree tab, you can open a context menu. However, this menu doesn't include a button for delete. Instead, I need to click the button on top of the list. I find that confusing.

**Comment by amotta** [comment]
I hope that this is not too off-topic:

Similarly, it would be cool if the "shuffle tree colors" action were part of the per-group actions.

It would be most natural if this action were applied recursively. If performed on the "root" group, the result would be equivalent to the global "shuffle all tree colors" action that we have right now.

The global action could then be removed (just like in Norman's proposal for the "delete" action).
