### ISSUE TITLE
Diff schema has false positives

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5293]
Despite the recent changes, sometimes diff_schema shows a diff where there is none. Could be about trailing carriage returns again, even though the diff command already contains `--strip-trailing-cr`. We should investigate. Compare https://scm.slack.com/archives/CMBMU5684/p1616005193000700

**Comment by fm3** [comment]
Turns out psql writes the trailing cr from function definitions into the file as `\r` (as in, a backslash, and an r). Of course, the differ does not ignore that.
Options would be to strip all occurrences of `\r` before diffing, or dive deeper into sql and see if there is an option to prevent that.

@jstriebel I think just stripping all occurences should be ok, but do you think that would be too risky?

**Comment by jstriebel** [comment]
I think stripping all `\r`s should be fine :+1:

**Comment by fm3** [comment]
Turns out stripping `\r`s did not solve the issue because of trailing characters that are shifted now…

**Comment by fm3** [comment]
Closed (hopefully) via #5333
