### ISSUE TITLE
Use frontend analytics to track interesting events

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5296]
## Detailed Description
Events to track (to be extended):
- [x] Open sharing modal (annotation)
- [x] Open dataset settings
- [x] Open upload view
- [x] Add files to upload view
- [x] Customize layout (i.e. move panels, resize panels)
- [ ] Store custom layout
- [x] Load custom layout

## Context
We have analytics on the backend, but we cannot track everything from the backend. See `sendAnalyticsEvent`.

**Comment by MichaelBuessemeyer** [comment]
Closed via #5490

**Comment by MichaelBuessemeyer** [comment]
The reason why not tracking event was implemented for "Store custom layouts" can be found in #5490:

> ... adds the requested analytics tracking of #5445 except for "Store custom layout" as it does not make sense in my opinion as this is tightly coupled to "Customize layout (i.e. move panels, resize panels)" when the auto-saving layout is turned on (which is the default).
