### ISSUE TITLE
Rework Ortho Viewport Layouting

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#5307]
## Detailed Description

Currently and with the coming rework, the four viewports of the ortho view can be freely arranged. We decided to further restrict the arrangement by not allowing to move viewports anymore or stack them. It should still be possible to resize the extends of the viewports using a "splitter"/"bar" between the viewports (just like it is now). The addition would be, that the horizontal bar would be at full length / for all viewports at once and not only for one viewport pair.  
Dragging using one of the bars should only enable a horizontal/vertical change.
If the user drags the bar in the center, where the bars overlap, it should be possible to manipulate both directions.

The viewport extends should also be part of the persisted layout and should be auto reloaded next time the ortho view is loaded.

**Comment by hotzenklotz** [comment]
@philippotto It looks to me that all the points mentioned in the issue description have been implemented? Do you agree? Can we close this issues?

**Comment by philippotto** [comment]
> The addition would be, that the horizontal bar would be at full length / for all viewports at once and not only for one viewport pair.

This part hasn't been implemented. But frankly, I don't think it is worth to do so. I'd be fine with closing the issue.
