### ISSUE TITLE
Color picker closes prematurely (chrome only)

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5311]
Concerns »Select Tree Color« color picker opened via cogwheel icon in the tree list.

Quoting from https://discuss.webknossos.org/t/tree-color-box-unstable-during-manual-input/1655/2

I click at either of the RGB boxes, then manually start to enter. As soon as I type in the first digit (eg. 2 for 255 R value), the dialog box closes. Then I have to open it again from the wheel, after which it works fine.

 - The problem occurs only when trying to change a tree color for the first time after opening the tracing or creating a new tree.
 - It seems to be a problem for Chrome/Opera in windows. Firefox seems fine.
 - Noticeably Chrome/Opera and Firefox open different color options with Firefox one being more stable.

## Your Environment for bug
Chrome Windows, Chromium Linux

**Comment by hotzenklotz** [comment]
I have the same thing/something similar happening to me. Safari/OSX

When I hover over the color selection dialog, it disappears before I make a selection. I suspect the dialog loses focus and hence is closed by the browser. See GIF

![Kapture 2021-03-22 at 13 13 48](https://user-images.githubusercontent.com/1105056/111988195-785c8900-8b10-11eb-985c-175e531e9180.gif)

THEORY: Interestingly enough, when I hover of the first rows of the color picker the immediate dismissal of the dialog does NOT happen. I suspect the while my mouse cursor is still over the first color rows it is also technically still hovering of the tree item menu ("Select Tree Color", Shuffle Color etc) in the background. Once my mouse leaves the area of the background menu, a focus shift happens and the browser decides to close the color menu. I hope this make sense.

**Comment by philippotto** [comment]
I tried a quick workaround, but wasn't really successful (now, the color picker opens at x=y=0 :trollface:).

I pushed my attempt to the branch `fix-color-picker`.

@MichaelBuessemeyer In case you have some air in this sprint, maybe you can have a look at it? However, your other current issues have priority, I'd say :)

**Comment by MichaelBuessemeyer** [comment]
> I tried a quick workaround, but wasn't really successful (now, the color picker opens at x=y=0 :trollface:).

I tried to find out why sometimes the position is off. The docs and a look at antd's code did not help. From the code, I got the idea that the element that the menu is attached to cannot be found somehow.
After that and some more time, I noticed that we have a `display: none` on the icon, the menu is attached to if the tree item is not hovered. Therefore sometimes, when the CSS calculation was faster than antd trying to render the menu, the icon was set to `display: none` and therefore (my guess) antd, could not attach the menu to it.
The simple solution that fixed @philippotto fix: Use the `opacity` CSS property instead of `display` to hide the icon when the tree in the list is not hovered.

Now it works perfectly. :sparkles:

**Comment by philippotto** [comment]
Awesome! Thank you for investigating and solving this :rocket: :rocket: :rocket:

Did you push your fix somewhere? Maybe my "fix" (which explicitly stores `isColorPickerVisible`) is not even necessary then? At least, I could imagine that changing `display: none` to `opacity` could be enough to fix the entire issue. But that's just a wild guess.

**Comment by MichaelBuessemeyer** [comment]
I just tried to reproduce the bug on the master on chrome, but it is no longer present. My guess would be that this bug was resolved by the upgrade of antd. This might have changed the dropdown so that it does not close to early :man_shrugging:

**Comment by philippotto** [comment]
Awesome news! I tested it, too, with chrome and firefox on linux and everything seems to work fine. Closing :+1:
