### ISSUE TITLE
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#5322]
## Context

This warning is printed when opening the tracing view: `[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.`
I didn't find any usages of SharedArrayBuffer on first glance, but somehow this deprecation warning is printed. We should check why and mitigate if necessary.

## Your Environment for bug

* Browser name and version: Chrome 89

**Comment by daniel-wer** [comment]
`SharedArrayBuffer` is only used by React. According to https://github.com/facebook/react/issues/20829 this deprecation won't result in a breaking change. It was fixed in version 17.0.2, so we'll get it once we update React the next time.
I'll close this issue as there is no need to do something about it. (/cc @philippotto)

**Comment by philippotto** [comment]
Great, thank you for investigating!
