### ISSUE TITLE
Migrate from Flow to Typescript

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5338]
Static Type checking for JavaScript is done with Flow in webKnossos. It seems like TypeScript has a number of advantages, most notably better community support. We could try using https://github.com/Khan/flow-to-ts to migrate, also consider blog-posts like https://skovhus.github.io/blog/flow-to-typescript-migration/

**Comment by normanrz** [comment]
In the Racemap codebase the transition from flow to typescript was pretty seamless.

**Comment by philippotto** [comment]
For better flow coverage, we implemented some wrappers for parts of our code base. When migrating to typescript we should take care of these and ensure that the typing is at least on par. Some (all?) notable places:
- `effect-generators.js` and `effect-generators.js.flow` which are responsible for most of the typing in our sagas
- `deep_update.js` and `deep_update.js.flow` (for our reducers)
- `comlink_wrapper.js` (for webworkers)
- `writeFlowCheckingFile` in `e2e-setup.js` (typechecks server-generated payloads in the e2e tests)

Hopefully, these cases will be even easier with TS, but it's additional effort to consider when planning this.
