### ISSUE TITLE
Frontend analytics

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5348]
## Detailed Description
Events to track (to be extended):
- [ ] Open sharing modal (annotation)
- [ ] Open dataset settings
- [ ] Open upload view
- [ ] Add files to upload view
- [ ] Customize layout (i.e. move panels, resize panels)
- [ ] Store custom layout
- [ ] Load custom layout

## Context
We have analytics on the backend, but we cannot track everything from the backend

**Comment by fm3** [comment]
Duplicate of #5296 (I copied the todo list to there so nothing is lost)
