### ISSUE TITLE
Implement draco support for meshes

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5349]
## Detailed Description
Add a [draco](https://google.github.io/draco/)-decoder for meshes from the backend. See: https://threejs.org/docs/#examples/en/loaders/DRACOLoader

## Context
For more efficient mesh storage and transmission, future versions of the mesh file will include draco-encoded meshes instead of STL.

**Comment by hotzenklotz** [comment]
@normanrz Is this issue still valid? Do our mesh files include Draco encoding? Or are we using another binary format altogether? (binary STL?)

**Comment by normanrz** [comment]
Yes, this is still valid. We currently support binary STL, but draco could offer much better compression (on-disk and for download). The new meshfile format, will also support draco.

**Comment by hotzenklotz** [comment]
@normanrz This is implemented with the new mesh file format, right? Can we close the issue?

**Comment by normanrz** [comment]
Yep.
