### ISSUE TITLE
Dataset/Annotation view: disable hover effects while viewport is occluded

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5363]
When I’m viewing a dataset or an annotation and I am in a modal or drop down menu, the mouse movements still cause cells to be highlighted / brush preview to be shown. Additionally, since presumably the mouseout events are not correctly tracked, this occasionally happens in the wrong viewport (where the mouse is not actually placed). This is rather confusing. I’d propose disabling these effects entirely when the mouse is not actually directly above a viewport.

**Comment by fm3** [comment]
Related: #4853

**Comment by philippotto** [comment]
Should be done by #7101.
