### ISSUE TITLE
Pretty empty dataset list is not shown on wk.org

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5364]
## Expected Behavior
<img width="945" alt="Screenshot 2021-04-06 at 17 59 01" src="https://user-images.githubusercontent.com/335438/113741286-c6bd7a80-9701-11eb-8fc2-5661a8a986c8.png">

## Current Behavior
<img width="1483" alt="Screenshot 2021-04-06 at 17 55 55" src="https://user-images.githubusercontent.com/335438/113740825-59114e80-9701-11eb-89d7-0e0503d4b389.png">
sage. -->

**Comment by philippotto** [comment]
I think, this bug only occurs for users which are members of multiple organizations (if one of them has datasets). For these users, datasets of other orgas are also fetched but filtered later. I'll push a fix, but I just wanted to let you know that the impact is not as bad as it seems.

**Comment by normanrz** [comment]
Isn't that everybody on wk.org, because there are public datasets of other orgs?

**Comment by philippotto** [comment]
Hm, yes, that might be the case. Bummer. I'll open the PR now.
