### ISSUE TITLE
Remove isosurface button from 3D viewport

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5380]
## Detailed Description
Remove the "load isosurface" button from the 3D viewport.

<img width="378" alt="Screenshot 2021-04-08 at 11 47 34" src="https://user-images.githubusercontent.com/335438/114006195-86c0d980-9860-11eb-8955-47c2ef387e1d.png">

## Context
We have the `Meshes` tab now that has this feature. Also, I always think this button resets the rotation/zoom or sth; which it obviously does not.

**Comment by philippotto** [comment]
This is done now.
