### ISSUE TITLE
Position the node context menu dependent on the position of the page 

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#5383]
## Context

Currently, the node context menu is always on the right side of the clicked position and grows to the bottom. This leads to a "content" overflow if the mouse is at the bottom or at the right border of the page. These cases lead to scroll bars and that not all menu options are visible all the time.

## Expected Behavior

The node context menu should be positioned according to its position on the page just like the browser build in context menu. If the clicked position is near a border (top, left, right, bottom) the context menu should stretch into the opposite direction to not lead to an overflow and to make all options visible at a time.

## Current Behavior

Just as described above. The node context menu is always on the right side of the clicked position and grows downwards.

## Steps to Reproduce the bug

 - Open the context menu near the right border. This should lead to an overflow.  (Needs Tab rearrangement)
 - Open the context menu near the bottom border. This should lead to an overflow.

**Comment by philippotto** [comment]
For this exact problem, there is a library called [popper](https://popper.js.org/). Maybe we should use that library instead of relying on antds menu work? Not sure whether that's a good fit. Just wanted to leave it here.

**Comment by hotzenklotz** [comment]
I think I ran into the same issue. Anytime I open the context menu in the lower part of my screen it will "overflow" the wK viewports and scroll the page:

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/1105056/150346583-8ee19a31-2d29-4590-a1ae-09ac931928a2.png">

This happens in Chrome, FF and Safari (all on MacOS). I didn't do anything special to cause this. Just a right-click in the lower part of the screen to bring up the context menu.
