### ISSUE TITLE
Allow re-using names of deleted entities

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5388]
Currently, the names of deleted tasktypes, teams, and datasets (but not projects) stay reserved. We should discuss which of those should be allowed to be reused.

Also, if this constraint is released, the uniqueness of non-deleted ones should be checked in SQL, not just in scala. This could be done with trigger functions.

**Comment by fm3** [comment]
A simpler way to implement this would be to rename the entity when deleting it, e.g. ´myTeam.deleted.1705644100` (the last being a timestamp).

I think for tasktypes, teams, projects we can afford doing this, while for datasets things are more complicated (since they are stored on disk by name and are referenced by name in many places)

**Comment by philippotto** [comment]
> A simpler way to implement this might be to rename the entity when deleting it, e.g. myTeam.deleted.1705644100 (the last being a timestamp).

Sounds good. Deleted tasktypes, teams and projects cannot be seen by the user anywhere, right? I would use a special character as a delimiter for the deleted suffix (e.g., `$`) and then forbid that names contain that character.

> I think for tasktypes, teams, projects we can afford doing this

:+1:

**Comment by fm3** [comment]
For the record: As discussed in [slack](https://scm.slack.com/archives/C5AKLAV0B/p1705926670477609) we decided that this special delimiter safeguard is not necessary for the moment. the backend continues to use only the isDeleted boolean and does not parse the name.
