### ISSUE TITLE
More options for (node) context menu

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5419]
The following can be implemented:
- [x] (un)mark node as branchpoint #6012 
- [x] drag node (is this still necessary when we have smart drag?)
- [ ] ...

**Comment by hotzenklotz** [comment]
@philippotto Both ideas mentioned here are implemented. I am in favor of closing this rather unspecific issue and (re-)-open  issues for specific ideas or upgrade this to issue to an epic collecting more ideas.

**Comment by philippotto** [comment]
Yes, I think, this issue can be closed, as we already iterated quite a bit on the context menu and now that the branchpoint part is also covered, there is not much value in this issue.
