### ISSUE TITLE
Info block on wk in public datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5425]
## Detailed Description
Add an informational block about the tool webKnossos to the view mode of a public dataset. It should only be shown when viewing a published dataset and not logged in.

## Context
webKnossos is used as dataset hosting for several publications. This is a great opportunity to explain how webKnossos can be used for similar research.

**Comment by philippotto** [comment]
@Albane-dlv Could you create a mock-up for this? :)
