### ISSUE TITLE
Support float64 datasets

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5428]
## Detailed Description
Float64 datasets are not currently supported. As I understand, the rendering / js buffers cannot handle them. A workaround could be to convert down the data to float32 during loading, similar to what we do with int64 (I think).

**Comment by hotzenklotz** [comment]
@fm3 Ist `Float64` the same as `double`? We the recent push for 64-bit support, this issue might be fixed, right?

**Comment by fm3** [comment]
Yes, float64 is the same as double. No, the recent push for 64 bit support did not solve this. float/double would be for “color” layers, while our recent improvements only concerned segmentation layers.

There are a few wk issues related to implementing more features for more dtypes. I’d like to gather those into a single issue with an overview table showing what features are missing (e.g. color layer, segmentation layer support in frontend/backend, histogram, thumbnail, etc). I hope I’ll get to that soon.

**Comment by fm3** [comment]
superseded by #6581
