### ISSUE TITLE
Reposition validation icon in file list of dataset upload view

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#5438]
## Detailed Description
The validation icon in the file list view of the dataset upload view looks mispositioned. 
<img width="1247" alt="Screenshot 2021-04-29 at 15 41 36" src="https://user-images.githubusercontent.com/39529669/116567094-9aafa680-a907-11eb-91c7-2cf817ddd7f9.png">
This Icon should be repositioned. e.g. sticky at the top right corner of the file list.

## Context
Steps to reproduce this:
- Open the dataset upload view.
- Drop a valid wkw-dataset folder (not zipped) into the file upload via drag & drop.
- There should no longer be a small green checkmark icon indicating, that the upload looks valid.

**Comment by hotzenklotz** [comment]
Fixed by #5437
