### ISSUE TITLE
Add two-finger pan like scrolling

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5441]
## Detailed Description
Add a two-finger pan gesture similarly to the mousewheel gesture. The gesture needs to be tuned in a way that allows precise single-section navigation.

## Context
Using a tablet with stylus is actually quite efficient for volume tracing. It works best in the fullscreen mode. However, there is no good way to navigate to the next section.

**Comment by hotzenklotz** [comment]
Is this still relevant with the tablet and mobile UI improvements? (#7159)
