### ISSUE TITLE
Task search shows duplicates if a user has multiple instances of single task

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#5442]
## Context
Administration -> Tasks

## Expected Behavior
Tasks should not be duplicated.

## Current Behavior
Task instances for the same datasets are duplicated every time certain column headers are clicked.

## Steps to Reproduce the bug

1. Open the tasks view and search for a user that has more than one instance of task for a certain dataset (e.g. 2 instances).
2. Click on the ID/Dataset/Creation Date column header to sort. Now the dataset is listed 3 times.
3. Keep clicking the column header and every time there will be a new duplicated entry.

Sorting by Project or Type didn't cause this behavior in my hands.

## Your Environment for bug

* Browser name and version: Chrome 90
* Operating System and version: Windows 10
* Version of WebKnossos (Release or Commit): 21.05.0

**Comment by fm3** [comment]
Hi @cnzqy1 and thank you for your bug report!

Unfortunately we could not reproduce the bug on our end, sorting works fine for us. Possibly your setup contains subtle differences to ours.
Could you test this with dummy tasks that you are comfortable sharing screenshots / a screen recording of?
Another thing to try would be to hit Ctrl+F5 in your browser to force reload of all code after the release upgrade.

@philippotto what other information could we need to debug this further?

Thanks!

**Comment by philippotto** [comment]
Unfortunately, I cannot reproduce this bug either.

> Open the tasks view and search for a user that has more than one instance of task for a certain dataset (e.g. 2 instances).

Just to doublecheck: You go to `/tasks` and fill out the user-form-field (the other part stayed blank). Then, at least two results (rows) have to appear which share the same dataset. Afterwards, the bug can be provoked by sorting the right columns?

I also looked at the code to see if there are any possible culprits, but I cannot see an obvious problem right now. I'm also surprised that the column by which is sorted plays a role in this bug (since you wrote that sorting by Project doesn't produce this bug).

**Comment by cnzqy1** [comment]
It's actually a bit more complicated than what I described in the original post. Here are three videos showing the behavior on our deployment: https://drive.google.com/file/d/1cofOWxGXxTuAtrJHJ9ayjphgiALhoEE3/view?usp=sharing. In both the first and the third video you see duplication but you don't see it in the second video. Clearing cache doesn't seem to resolve this issue.

**Comment by cnzqy1** [comment]
One more video to show the behavior of these duplicated tasks: https://drive.google.com/file/d/1cgRBPHcj5K5U0BAHyhV5RtxYqQcYANjL/view?usp=sharing.

**Comment by philippotto** [comment]
Thank you for the videos! These are very helpful. We will investigate further what's happening and let you know then.
