### ISSUE TITLE
Histogram request fails for tiny datasets

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5444]
If the bounding box of a dataset is tiny (e.g. 50 × 50 × 30 voxel³) the histogram request fails.
The position sampling runs into breaking criterion `spaceBetweenWidth < DataLayer.bucketLength` already in the first iteration. How can we create a sampling strategy that also returns valid data for arbitrarily small datasets?

**Comment by fm3** [comment]
We could also discuss if the histogram request failing should cause an error toast at all.
This is a quite prominent error coming up on page load even if the user wasn’t actually intersted in the histogram. The request may still sometimes fail for one reason or the other even after this small-dataset issue is fixed. Do you think we should possibly instead show an error message _in place of_ the histogram in the sidebar? @philippotto @normanrz

**Comment by normanrz** [comment]
> instead show an error message _in place of_ the histogram in the sidebar

That is a good idea. However, I'd rather focus dev work on fixing the histogram computation than the error message :-)
