### ISSUE TITLE
Clicking "View" on a project which has no tracings produces an error

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5445]
When creating a task and directly clicking "view" for it (i.e., no tracings were created for that task), the following error is shown:

![image](https://user-images.githubusercontent.com/2486553/116694102-20daf400-a9bf-11eb-9f4b-696f34f4cdbc.png)

There should be a better explanation of what's happening. Something like: No annotation was yet finished for this task. Please ensure that the task has... (assigned hiwis?)

**Comment by fm3** [comment]
Should the button exist at all?

**Comment by philippotto** [comment]
Very good point. I thought that this information might not be easily available in the front-end, but the relevant metrc is probably simply "finished instances", right? If that's 0, it should be disabled.

**Comment by fm3** [comment]
Correct, all finished annotations of the task/project/tasktype are used for the compound annotations.

**Comment by MichaelBuessemeyer** [comment]
Little update: The bug is in the project view.
