### ISSUE TITLE
Show spinner for histogram while loading, error if loading failed, no toast

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5452]
Histograms are now highly visible in the sidebar, and on page-load they don’t show any data. It would be nice to have some kind of loading indicator there.

Additionally, as discussed in https://github.com/scalableminds/webknossos/issues/5444#issuecomment-830859221 if the loading fails, the user should not be presented an aggressive error toast for failed histogram requests. Instead, show an error indicator directly _in place_ of the histogram.

**Comment by philippotto** [comment]
Fixed by #6537.
