### ISSUE TITLE
Do we need to overwrite alt+arrows?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5460]
Alt+LeftArrow and Alt+RightArrow is used by browsers for navigation. Our dataset view overwrites this, but the behavior seems to be identical to the arrows without alt. Could we release this combination back to the browser?

**Comment by philippotto** [comment]
The advantage would be that users can use the browser's default shortcuts? Seems like a rare use case to be honest.

**Comment by fm3** [comment]
When I don’t have a my hand on a mouse I usually use alt+leftArrow instead of the browser’s back button. Not sure how common this is. My thought was that we don’t acutally _use_ alt+leftArrow for anything, it seems to b taken just by accident (because leftArrow itself is). But if you say this is complicated to change, then of course this does not have a high priority

**Comment by hotzenklotz** [comment]
I quickly looked into this one. On the surface it does not look like we are explicitly mapping the ALT + LEFT or ALT + RIGHT combination to any wK action. That being said, I can not rule out that one of the many libraries does not capture it anyways.

I am not sure if we can fix this at all, let alone easily. Voting to close the issue.

**Comment by hotzenklotz** [comment]
@fm3 Ping

**Comment by fm3** [comment]
Fair enough. It still affects me, but if this is difficult to solve, I understand that the priority is very low.
