### ISSUE TITLE
New status bar hidden by browser status bar

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#5481]
## Context
I love the new status bar!

However, on my system (MacOS, Chrome), it is frequently covered by "Waiting for..." overlay coming from the browser, as shown in the screenshot below:

![wk_status_bar](https://user-images.githubusercontent.com/1701960/117654730-73be6380-b196-11eb-8a34-7ec3f87829ff.jpg)

## Expected Behavior
Not sure what the best solution is. Perhaps the front-end can turn off these browser overlays. If that's not possible, maybe the status bar should be moved.

## Current Behavior
See above.

## Steps to Reproduce the bug
1. Open any dataset
2. Move around, overlay appears when data is being loaded.

## Your Environment for bug
Chrome 90, MacOS 11.13.1
Not sure how to find out the WK version, but I can reproduce it right now on the MH Lab deployment.

**Comment by philippotto** [comment]
I also noticed this already :( Unfortunately, it seems like the browser's overlay cannot be avoided/manipulated. I don't know how to solve this, but I agree that we should try to find a workaround..

**Comment by philippotto** [comment]
the order of shortcut hints and important data was swapped, so that only the shortcuts should be hidden by the browsers tooltip.
