### ISSUE TITLE
Importing NML with nested groups messes up hierarchy when using "Create a new tree group for this file"

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5495]
# Current State
The symptom exists in front-end and back-end (however, the bugs are caused by different conditions apparently).
- [X] fix front-end bug
- [ ] fix back-end bug

# Front-end bug

## Context
When dragging an NML file into an active tracing (i.e., front-end import is used) and checking "Create a new tree group for this file." the hierarchy is not properly wrapped.

## Expected Behavior
The entire tree hierarchy of the input NML should be wrapped by one new group `G`.

## Current Behavior
Some deeply nested trees are directly within `G`.

## Steps to Reproduce the bug
1. Ask me for the NML file I used (or try to reproduce it by downloading a "complex" hierarchy and re-uploading it).
2. Drag it into a (skeleton/hybrid) tracing.

## Your Environment for bug
chrome on linux, but this shouldn't matter.

# Back-end bug

See https://github.com/scalableminds/webknossos/issues/5495#issuecomment-858735682

**Comment by jstriebel** [comment]
Something similar happens also when dragging a NML into the View-Mode, which seems to use the backend-import. I experienced that a group-id was used within it's group, creating a recursion. This only happened when `Create a new tree group for this file` was ticked. This results in rendering artifacts and crashes, and the downloaded NML can not be re-uploaded (this might lend itself nicely as a test-case). See [this slack thread](https://scm.slack.com/archives/C5AKLAV0B/p1623331839023800) for details.

**Comment by philippotto** [comment]
I could fix the front-end bug, but the back-end bug seems to have a different cause as the same input didn't cause any problems when using the back-end import.
