### ISSUE TITLE
Allow to switch to dataset's organization if possible + necessary

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5511]
When one is member of multiple organizations (e.g., A and B, but currently A is "active"), clicking on a link to a dataset of organization B, a 404 page is shown. Ideally, the page should show:

"The dataset belongs to organization B. Do you want to switch to that organization?"

Obviously, this should only be shown, if one has access to organization B. Ideally, the switch would happen automatically, but there are some side-effects to that (since the "active organization" changes), which is why I wouldn't do this for now.

**Comment by fm3** [comment]
I agree that switching should not happen automatically as long as those side effects are present.

The Front-end could compare the organization name from the URI with those in the list the user gets from /api/organizations, right? So no back-end changes should be required?

**Comment by philippotto** [comment]
> The Front-end could compare the organization name from the URI with those in the list the user gets from /api/organizations, right? So no back-end changes should be required?

Yes, I think so!
