### ISSUE TITLE
Remove any Object annotations

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5527]
`Object` is an alias for `any` and therefore quite bad for typing coverage. We should replace it by more precise types (`{}` comes closest to representing an actual Object with arbitrary keys).

I think, it's independent of #5338 since it strenghtens the typings in both type flavors.

**Comment by hotzenklotz** [comment]
As far as I can tell there is only one `Object` type remaining: https://github.com/scalableminds/webknossos/blob/master/frontend/javascripts/admin/admin_rest_api.ts#L2215

I guess we have significantly improved our typing game in the meantime :-) Consider fixing closing the issue?
