### ISSUE TITLE
Throttle user dataset configuration updates

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5540]
When a user changes their view configuration for a dataset (e.g. moves the brightness slider), every change causes a request to the back-end. Sometimes the frequency is high enough to create a jam in SQL, yielding concurrent update errors (which we’ve seen in telemetry and postgres logging). In this case it is not guaranteed that the latest request “wins” so outdated versions may be saved.

Could the front-end throttle this saving to, say, once per second? Maybe the user interactions could reset a save timer, similar to annotation saving? What do you think @philippotto ? Would that be difficult?

**Comment by philippotto** [comment]
Sounds very plausible and should be relatively easy to do :+1:

**Comment by philippotto** [comment]
Hmm, I just had a look at the code and the updates are already throttled to 500ms (which also seems to work when I change the histogram sliders). Can you confirm that this works for you? We can certainly talk about changing the throttle threshold, but I don't expect much impact here :thinking:

**Comment by fm3** [comment]
Yes I can confirm this works 🤔 That means the reason why the sql queue jammed on June 1 remains unclear. However, it occurred only once and no user complained about any corrupted state so let’s defer further investigation until another occurrence.
Thanks for looking at this throttling!
