### ISSUE TITLE
HTTPS provisioning  for datastore

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5549]

**Comment by fm3** [comment]
Looks like play does not include functionality for managing and refreshing certificates. I also did not find a good library to include it.
So instead, I’d advise our users to manage the certificates with a separate tool, e.g. https://github.com/acmesh-official/acme.sh and then fill in the config (possibly this can be done interactively as discussed in https://github.com/scalableminds/webknossos/pull/5581#discussion_r662058693 ). The relevant config fields are `https.port=443, play.server.https.keyStore.path=/path/to/keyStore.jks, play.server.https.keyStore.password=the_password jdk.tls.ephemeralDHKeySize=2048 jdk.tls.rejectClientInitiatedRenegotiation=true` according to https://stackoverflow.com/questions/38339977/how-to-configure-a-play-application-to-use-lets-encrypt-certificate

**Comment by fm3** [comment]
Now tracked in #5468
