### ISSUE TITLE
Allow to await cross-origin API

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#5552]
## Detailed Description

The cross-origin API can be used to communicate with webKnossos embedded in an IFrame which works via [postMessage communication](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). This works. However, sometimes it needs to be possible to find out when a specific cross-origin API call has finished so that a subsequent API call can be deferred until then. Currently, this is not possible. This could be implemented by answering a cross-origin API call with a `postMessage` to the [source](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/source) of the original message once the API call was executed, thereby allowing synchronous cross-origin API calls.

## Context

Important for projects embedding and communicating with webknossos in an IFrame (e.g. the connectome viewer).

**Comment by normanrz** [comment]
Maybe you can use [comlink](https://github.com/GoogleChromeLabs/comlink) for this
