### ISSUE TITLE
Adjust Cookies so they match Firefox's requirements.

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#5554]
Firefox will soon change its cookie behaviour that will probably affect wk. At least the console is full of warnings. I think this need to be worked on.
![image](https://user-images.githubusercontent.com/39529669/120787677-e15c7600-c52f-11eb-8717-d321785d34fd.png)

## Context

Firefox seems to change something with the cookies. Just open any wk branch in firefox and look in the console.

## Expected Behavior

Would be nice if there weren't these warnings anymore so that we also support upcoming Firefox versions without having issues with the cookies. 
## Current Behavior

No more warnings :D

## Steps to Reproduce the bug

1. Just open any branch of wk in Firefox and look in the console.

## Your Environment for bug

* Browser name and version: Firefox 88.0.1 (64-bit)
* Operating System and version: Ubuntu
* Version of WebKnossos (Release or Commit): Doesn't matter afaik.

**Comment by fm3** [comment]
Hi @MichaelBuessemeyer and thanks for the report!
I believe the `msf-ws.session` cookie is not created by webKnossos. Could it be that you had any other applications running on your localhost recently? Possibly they created the cookies and now Firefox matches the origin and sends them (but notices that something is off). Could you try clearing site data for localhost:9000 in Firefox and see if the warnings crop up again?

**Comment by MichaelBuessemeyer** [comment]
Oh, interesting. You were right, somehow this cookie was defined by something else than webkossos. I simply removed it and the console warning spam is gone. Thanks for investigating + helping me out  :)
