### ISSUE TITLE
Dashboard Datasets Refresh button scrolls to top, which is too high if welcome header is present

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5562]
If on your screen the welcome header fills almost the entire screen the dataset refresh button shouldn’t scroll to page top, thus hiding itself and the datasets.

**Comment by MichaelBuessemeyer** [comment]
@fm3 Can you help me out reproducing this behavior? I can neither find the code lines that cause the page to scroll up nor the can I reproduce this behavior on the current master with firefox or chrome :/

**Comment by fm3** [comment]
Can’t reproduce it anymore either. I assume it was removed in the meantime. Thanks for checking it out!
