### ISSUE TITLE
Publish Datastore Jar for Releases

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5567]
The fat jar we build for the datastore (as of https://github.com/scalableminds/webknossos/pull/5558 ) should be published somewhere. Let’s discuss how this process should look like. Possibly publish to our own file server, and link to it from the docs (?)

It might also make sense to bundle it with a basic default config file to show how to overwrite the most important config fields.

Also it could be bundled with other files to handle auto-updates and https certificates, compare #5548 #5547 #5549

**Comment by youri-k** [comment]
@fm3 talked about open points and gathered these tasks

- [ ] auto updater update possibility
- [ ] add assets in ci to github release
- [ ] (interactive) install script
- [ ] version from build info plugin
- [ ] ability to remove datastore
- [ ] ability to work without org folder

**Comment by fm3** [comment]
Now tracked in #5468
