### ISSUE TITLE
webKnossos backend sometimes crashes after uploading/converting dataset

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5576]
- upload a dataset which needs conversion to webknossos.org
- if you are unlucky, the back-end crashes (a toast will appear saying "we are updating")
- after waiting a bit, webKnossos is available again and the converted datset is also available

In the end of the above steps, everything works again as expected, but the crash inbetween is obviously annoying.

**Comment by philippotto** [comment]
one theory is that the healthcheck is blocked which is why kubernetes restarts the pod.

**Comment by fm3** [comment]
may be fixed by #5601 – let’s monitor for a while after that one is deployed.

**Comment by fm3** [comment]
Tentatively closing this as there have been no more occurences since  #5601 was merged. Feel free to reopen if this comes up again
