### ISSUE TITLE
SPACE key can toggle fullscreen mode

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#5609]
## Context
I was browsing my data and switched to full screen mode for the XY viewport by clicking on the little window icon in the upper right of the viewport. Then I wanted to continue navigating through my dataset using the SPACE hotkey. Instead of moving in z-direction the fullscreen mode was (un)-toggled (back to mini viewport). Pressing SPACE once more toggled the fullscreen mode again. Looks like the fullscreen button still has the focus after pressing it.

## Expected Behavior
Hotkey SPACE should navigate in third dimension and not toggle fullscreen mode.

## Current Behavior
Hotkey SPACE toggles fullscreen mode after pressing on fullscreen button.

## Steps to Reproduce the bug
1. Click on fullscreen mode for any viewport with mouse
2. Press SPACE
3. See it toggle between fullscreen and regular mode

## Your Environment for bug
* Browser name and version: e.g. Chrome 91
* Operating System and version: e.g. MacOS
* Version of WebKnossos (Release or Commit): 15036

**Comment by philippotto** [comment]
> Looks like the fullscreen button still has the focus after pressing it.

That would also be my initial guess. Probably, we need to call `blur()` after pressing layout related buttons.
