### ISSUE TITLE
Add "load precomputed mesh" to view-mode context menu

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5610]
## Detailed Description
Add "load precomputed mesh" also to the context menu in view mode. It is already present in the annotation mode.

:-) <img width="293" alt="Screenshot 2021-07-08 at 13 07 41" src="https://user-images.githubusercontent.com/335438/124911818-7d751380-dfed-11eb-9731-b2b8088d142c.png">

:-( <img width="193" alt="Screenshot 2021-07-08 at 13 05 48" src="https://user-images.githubusercontent.com/335438/124911828-81089a80-dfed-11eb-92ca-bc8f23e4d731.png">

**Comment by MichaelBuessemeyer** [comment]
I think that showing this option in skeleton-only tracings is also useful.

**Comment by fm3** [comment]
closed by #5402
