### ISSUE TITLE
Enable "Load Precomputed Mesh" in context menu in view mode

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#5618]
## Detailed Description
The right-click context menu in `View` mode should give me the option to load the precomputed 3D mesh if it is available. This can be done in regular annotation mode but not in `view Mode`

## Context
Right-click in this DS and be sad :-(

https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo/view

**Comment by fm3** [comment]
This has been fixed by #5402 in the meantime (though the mesh file of the linke dataset seems broken. I’ll have a look.)

**Comment by hotzenklotz** [comment]
<img src="https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif">
