### ISSUE TITLE
Compute Mesh File: Select only mags that the segmentation layer has

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5629]
The front-end selected mag 4-4-1 for meshfile generation for my dataset, even though the segmentation layer only had 16-16-4

`getDatasetResolutionInfo` is used to list the available resolutions.  @philippotto Do you know if there is a good way to access only the (active) segmentation layer’s resolutions?

- [x] specific to long-running jobs ( jobsEnabled=true )

**Comment by philippotto** [comment]
> `getDatasetResolutionInfo` is used to list the available resolutions. @philippotto Do you know if there is a good way to access only the (active) segmentation layer’s resolutions?

Argh, thanks for investigating. There's `getResolutionInfoOfSegmentationLayer` which should solve the problem easily :) Should I create the PR?
