### ISSUE TITLE
Generate OpenAPI schema for REST API

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5643]
With an openAPI schema the rest API client could be auto-generated.
We should investigate if there is a scala lib that auto-generates this from the play routes.
We should be able to blacklist some routes (not everything is supposed to be used except by webKnossos itself)

**Comment by jstriebel** [comment]
I just had a quick look, those seem to be candidates:
* https://index.scala-lang.org/swagger-api/swagger-play/swagger-play
* http://iheartradio.github.io/play-swagger/
* https://github.com/sohoffice/descriptive-play-swagger

**Comment by jstriebel** [comment]
@fm3 @youri-k Could one of you have a look if this might work? Just having the specs for a couple of endpoints would be already very helpful.

**Comment by jstriebel** [comment]
The datastore route `/datasets/:organizationName/:dataSetName/layers/:dataLayerName/data` works great for blob download. A schema for the upload route(s) would be great, though (`POST` on `/datasets ` and `/datasets/finishUpload`?).
