### ISSUE TITLE
View Configuration: Maximum of data range is stuck at 255 for uint16 dataset

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5675]
The dataset view configuration contains the maximum value for the histogram slider. This was (we don’t know why) set to 255 for a uint16 dataset, and then the user had no means to set the slider above 255, even though the dataset has higher values.

A plausible scenario how this could happen if the datasource-properties.json first says uint8, then the user opens the dataset and changes the slider, but then goes back to fix the json so that it correctly says uint16.

There should be a way to reset this.

**Comment by fm3** [comment]
Note that a user reported that this was the *initial* state after creating the dataset with wkcuber
```
python3.6 -m wkcuber \
  --distribution_strategy slurm \
  --job_resources "{\"mem\": \"50G\", \"time\":\"5:00:00\"}"\
  --layer_name myLayer \
  --dtype uint16 \
  --scale 30000,30000,30000 \
  /path/to/source/tiffs \
  /path/to/webknossos/binaryData/myOrganization
```

**Comment by MichaelBuessemeyer** [comment]
As the min and max of the histogram slider can be changed via the edit button above the histogram this should not be an issue.
Therefore I cannot reproduce this "bug". It is likely that the user did not find this button.
