### ISSUE TITLE
If the wk worker crashes/restarts during a job, wk forever thinks the job is running

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5687]
Can we somehow get the information that this job is no longer able to complete?

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [x] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
Could we compare to uptime of the worker instance with the "uptime" of a job? E.g., if the worker was started 5 minutes ago and the job 10 minutes ago, the job "obviously" crashed?
