### ISSUE TITLE
How to turn volume annotation to on-disk segmentation layer without losing coordinates?

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5688]
## Context
I created a new volume annotation, brushed on two slices and downloaded the annotation. Afterwards, I added the downloaded wkw data as a layer to the dataset.

## Expected Behavior
The added segmentation layer should look exactly like the annotation I created manually.

## Current Behavior
The segmentation layer shows data in a slice which wasn't even brushed.
Compare the original annotation:
![image](https://user-images.githubusercontent.com/2486553/130750821-cb807701-8b20-4f6c-9555-af43ce51f278.png)

with the version which was converted to a segmentation layer:
![image](https://user-images.githubusercontent.com/2486553/130750978-1bec4217-1401-4e35-866e-8a30bae74ae3.png)

Note that I used the "reload buckets" feature in both tabs and also reloaded the page completely. So, this is not a weird state in the front-end, but instead the problem seems to be in the "download->segmentation layer" part (therefore, back-end?). Maybe related to https://github.com/scalableminds/webknossos/issues/5684, but in this case the data contains too much data.

Also note that the slice data is repeated, but only partially. The XY viewport should either show nothing or it should be completely filled. Instead, the screenshot shows a partially filled slice.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

- create a new volume annotation
- brushed on two slices
- download the annotation
- add the downloaded wkw data as a layer to the same dataset
- open dataset and inspect the surrounding slices

## Your Environment for bug

- Browser name and version: e.g. Chrome 90
- Operating System and version: e.g. Ubuntu 20.04
- Version of WebKnossos (Release or Commit): fb67f66fa
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
When you say “added the downloaded wkw data as a layer to the same dataset”, do you mean you just moved it on disk? Did you edit the datasource-properties.json? Volume Annotations have a cubeLength of 1, which may be a source of error here (either in code or in usage) – when you upload the annotation _as an annotation_ again, does it look right?

**Comment by philippotto** [comment]
> When you say “added the downloaded wkw data as a layer to the same dataset”, do you mean you just moved it on disk?

Yes.

>  Did you edit the datasource-properties.json?

I doublechecked the values and also fiddled a bit with the cube length. Are you sure that the value needs to be `1`? wK infers 32 and I also assumed that 32 would be correct, since one cube file contains one bucket (with 32 voxels per edge). The normal color layer has a value of 1024 (so, cubeLength is not the wkw file len which you might mean?).

I tried to change cubeLength to 1 and sometimes got okay results, but everything's kinda flaky. I can show it to you today.

**Comment by philippotto** [comment]
Btw, reuploading the annotation via dashboard looks fine :tada: :relieved:

**Comment by philippotto** [comment]
For the record: the bounding box for the new layer was inferred incorrectly. After fixing the bounding box, the data loading worked without any problems. Therefore, two questions/todos remain:

- Why is the bounding box inferred incorrectly for volume data?
- Why does an incorrect data lead to "data overflows" into sections which should be empty? The annotation was clipped on the X axis, but in Z there was too much data.

**Comment by fm3** [comment]
Turns out bounding box inferral is designed to be heuristic to save i/o operations: it does not lists all wkw files but only the existing y directories of a single z slice and then the x files for a single y strip. This is why non-rectangular datasets like volume annotations can have too-small inferred bounding boxes.
Does not, however, explain the second mentioned problem

**Comment by fm3** [comment]
Note that the volume tracing and the downloaded NML does contain the bounding box. I guess the client code should use that.

Do you have a concrete vision of what needs to be done/investigated further for this issue?

**Comment by philippotto** [comment]
I guess, the actual use case is already solved by the "Materialize volume layer" worker job which takes care of the proper "conversion".

However, I'm still wondering about this behavior in particular:

> Why does an incorrect data lead to "data overflows" into sections which should be empty? The annotation was clipped on the X axis, but in Z there was too much data.

I don't understand why this is happening and think that this is very confusing. Reading from WKW at places where nothing was written should simply yield zeros :thinking:

**Comment by fm3** [comment]
Hm, I tried this just now and it worked exactly as expected. 

I downloaded my fresh volume annotation (where I had brushed in two slices), placed its data as a new layer in the dataset directory, then edited the datasource-properties.json, making sure that the bbox is the same as the color layer’s, the dtype is uint32 and cubeLength is 32.
The result looks exactly like the original volume annotation, in all mags.

Maybe something has changed since the original report. Could you try if you can still reproduce this?

**Comment by philippotto** [comment]
> making sure that the bbox is the same as the color layer’s, the dtype is uint32 and cubeLength is 32.

I think this is the reason you cannot reproduce it. Quoting from above:

> For the record: the bounding box for the new layer was inferred incorrectly. After fixing the bounding box, the data loading worked without any problems. 
> ---- snip -----
> * Why does an incorrect data lead to "data overflows" into sections which should be empty? The annotation was clipped on the X axis, but in Z there was too much data.
