### ISSUE TITLE
Initial min/max values need to be changed once to get active

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5694]
## Context
When opening a dataset link, the pre-set min/max values of a color layer may end up not being used for rendering until the min/max slider was changed once.

## Expected Behavior
The displayed min/max values in the sidebar should be used for rendering without any user interaction.

## Current Behavior
The user needs to change min/max for the initial values to take effect.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. open https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_types/view#2867,4160,1770,0,0.563 in incognito tab
2. change min/max slider for color layer a tiny bit --> contrast changes dramatically (which means that the values weren't properly used before).

## Your Environment for bug

- Browser name and version: Chrome 90
- Operating System and version: Ubuntu 20.04
- Version of WebKnossos (Release or Commit): f471130fc9d580c54b74c01f472d9a2ae353a692

**Comment by MichaelBuessemeyer** [comment]
How to reproduce localy:
 - Go to the settings of a dataset and then to the "View Configurations"-tab.
 - There choose a (e.g. uint8) color layer and set `min` to 100 and `max` to 150.
 - Then make the dataset publically available under the "Sharing & Permissions"-tab, copy the sharing link and save the settings.
 - Then open the dataset with the public/sharing link in a private browser tab.
 - The rendered color layer should (with the bug) render data like the histogram slider is at `[0,255]`.
