### ISSUE TITLE
Remove highlightHoveredCellId property from existing task types

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5705]
[Link to Discuss](https://discuss.webknossos.org/t/cant-change-user-settings-in-task-type/1680/2)

Older task types which still contain the `highlightHoveredCellId` property in the recommended settings, will show as invalid when editing a task type. We should probably have created a migration when we removed the setting. I suggest to implement the migration now and update the migration guide for the version where this was done (I think, 21.07.0) and also add a comment to the next release about this.

@youri-k or @fm3 Could you have a go at writing the migration?

**Comment by fm3** [comment]
I think I’d just add this as a normal migration “now” in the timeline and include it in the next release.
We can add a note to the old release in the migration guide that users may want to run the sql command already, but without the schema version update. This way, the version numbering does not get mixed up. I can write the command on monday.
