### ISSUE TITLE
Enabling agglomerate mapping doesn't work immediately sometimes

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5712]
## Expected Behavior
When enabling an agglomerate mapping, the effect should be immediately visible.

## Current Behavior
Sometimes enabling the mapping doesn't do anything. Toggling the "Enabled" button twice will then show the applied mapping.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Open dataset with an agglomerate mapping
2. Enable agglomerate mapping
3. Sometimes there is no change visible
4.

## Your Environment for bug

- Browser name and version: Chrome latest
- Operating System and version: Ubuntu 20.04
- Version of WebKnossos (Release or Commit): latest
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by hotzenklotz** [comment]
Is this still relevant? Have you encountered this recently?

**Comment by philippotto** [comment]
No, I havent encountered this recently. Closing this now.
