### ISSUE TITLE
accessibleBySwitching request should only be sent if logged in

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5735]
Currently, when you open a (non-public) dataset while logged out, this request is sent, fails and results in an unreadable error toast.

**Comment by hotzenklotz** [comment]
I just tried to re-create the issue. As far as I can tell the request is not being send any more. Can we close this?

**Comment by fm3** [comment]
I can still reproduce it by opening an existing, non-public dataset while logged out.
![image](https://user-images.githubusercontent.com/1390035/197330382-e48abba3-72e3-45aa-abb3-b0594e0c9d74.png)
