### ISSUE TITLE
Using a hybrid as a task base does not copy the volume tracing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5770]
## Context
Tasks + Hybrid base

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Create a task type with a volume (or hybrid?) mode
2. Create a hybrid annotation and brush a bit (copy the annotation id)
3. Create a task for the task type from (1) and add an annotation base with the id from (2)
4. Get task from dashboard
Expected: the task should contain the volume data from (2).
Current: the task does not contain the volume data

**Comment by fm3** [comment]
I cannot reproduce this. Did you use a hybrid task type?

**Comment by philippotto** [comment]
I just tested this again for hybrid and volume-only tasks and couldn't reproduce it, either. Closing this issue.
