### ISSUE TITLE
Allow to set color for all trees in a group

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5773]
## Detailed Description
Right-clicking a group should show a "Set color for all trees" menu entry.

## Context
When having lots of single-node-trees which semantically belong to the same cluster, it would be helpful to give all of them the same color.

**Comment by hotzenklotz** [comment]
Related request, quoting from #5242:

> Similarly, it would be cool if the "shuffle tree colors" action were part of the per-group actions.
> 
> It would be most natural if this action were applied recursively. If performed on the "root" group, the result would be equivalent to the global "shuffle all tree colors" action that we have right now.
> 
> The global action could then be removed (just like in Norman's proposal for the "delete" action).
