### ISSUE TITLE
Simplify changing color into segmentation layer

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5776]
Currently, the following is necessary:

> Go to the Settings View of the dataset. In the "Data" tab, you can switch from "Simple" to "Advanced" and set the "category" value for the "label" layer from "color" to "segmentation" (additionally, the property "largestSegmentId" has to be defined for the segmentation layer).

This is super obscure. I suggest the following things:
- allow to switch category in "simple mode"
- allow the user to set "largest segment id" manually or have wk derive it (long-running job?)
- when the DS is open, make the "color"/"segmentation" badge clickable in the left-sidebar. show a hint or link to the settings view directly? this will be the place the users look for first.

**Comment by fm3** [comment]
note that the downsampling used for color produces invalidly downsampled segmentation layers

**Comment by hotzenklotz** [comment]
@philippotto I wonder if we can consider this issue done?
- The new datasource editor that you built fro Zar has a dropdown for "color"/"segmentation"
- largest segment IDs are optional now

**Comment by philippotto** [comment]
Yes, this is done :tada:
