### ISSUE TITLE
Implement batching for backend analytics to avoid quota limits

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5785]
Currently we send individual requests for the analytics events. Looks like we are hitting quota limits there for some instances. We should implement some batching there.

Compare logging from webknossos.org at `2021-10-13 16:00:08` for example.

**Comment by philippotto** [comment]
Can this issue be closed? I think we moved away from an external service for back-end logging and therefore don't have quota limits anymore?

**Comment by fm3** [comment]
yes :tada:
