### ISSUE TITLE
Better explain the concept of "Explorative Annotation"

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5808]
## Detailed Description
- [x] Better explain the concept of "Explorative Annotation". The term is used in the UI, but never explained as far as I know.
- [ ] Show the annotation ID in the info tab when the annotation is open (the URL alone is not enough as it contains other stuff, such as the position hash, which makes it hard to extract)

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by hotzenklotz** [comment]
Is this issue still relevant?

To 1: We switched to using the more general term "annotation"

To 2: Is the annotation ID relevant for something? Additionally, the new short sharing URLs are pretty cool when exchanging links with people.

**Comment by philippotto** [comment]
> Is the annotation ID relevant for something?

I think there was an instance in which a user was puzzled where to find the annotation id. maybe when creating a task with a base annoation? however, I don't think that a more prominent ID is the solution here. instead, we should allow to paste links or something like that. however, let's do that if we get such feedback again. the main part (1) is done, I think, which is why I'm closing this now.
