### ISSUE TITLE
Annotation cannot be added to "Shared Annotations"

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5814]
## Context

Share modal for an annotation.

## Expected Behavior

adding a team to "Should this annotation appear in the sharing tab?" saving + reloading --> team should still be listed

## Current Behavior
adding a team to "Should this annotation appear in the sharing tab?" saving + reloading --> team should is not listed

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
I cannot reproduce this bug. @normanrz Can you remember any specific constraints which might have provoked this issue? I tested this locally with `isDemoInstance == true`. The user in question was an admin which should be representative for the original issue report..

**Comment by philippotto** [comment]
2 new insights:

- ublock origin blocks the request and wk still says "success" --> front-end problem
- without an adblocker, I can repro this. in that case, the front-end sends a not-empty team array, but the back-end responds with an empty array --> back-end problem?

**Comment by fm3** [comment]
I tried again with @philippotto and this worked for us in all combinations that we tried. Closing this until another occurence shows up.
