### ISSUE TITLE
Data is rendered incorrectly on iOS 14

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5823]
## Context
When viewing a dataset via browserstack on iPad Air 4 (iOS 14), data is often rendered incorrectly. The console outputs:

```
maxTextureImageUnits 16
vendors~main.js?nocache=2f751a7…:249 maximumLayerCountToRender 8
vendors~main.js?nocache=2f751a7…:249 Supporting 4096 buckets
vendors~main.js?nocache=2f751a7…:249 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
vendors~main.js?nocache=2f751a7…:249 Requested api version: 3 which is the latest version.
```

For iOS 13, the same bug does not occur and the output is:
```
vendors~main.js?nocache=2f751a7…:249 maxTextureImageUnits 8
vendors~main.js?nocache=2f751a7…:249 maximumLayerCountToRender 2
vendors~main.js?nocache=2f751a7…:249 Supporting 2048 buckets
vendors~main.js?nocache=2f751a7…:249 Requested api version: 3 which is the latest version.
vendors~main.js?nocache=2f751a7…:249 THREE.WebGLProgram: gl.getProgramInfoLog() WARNING: Output of vertex shader 'vUv' not read by fragment shader
WARNING: Output of vertex shader 'modelCoord' not read by fragment shader
```

I'm not really sure whether the `OES_texture_float_linear` bit is really the culprit, since my research showed that earlier iOS versions didn't support that bit either (but didn't say so).

## Expected Behavior

Data should be rendered correctly.

## Current Behavior

![image](https://user-images.githubusercontent.com/2486553/139850032-6f1696b8-487c-4758-aeff-5ea8cdc5e590.png)

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. open wk on iPad 4 with iOS 14
2. open a dataset
3. zoom in to mag 1
4. move a bit

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
> I'm not really sure whether the OES_texture_float_linear bit is really the culprit, since my research showed that earlier iOS versions didn't support that bit either (but didn't say so).

Since we always use `THREE.NearestFilter` for textures, this shouldn't explain the bug.

Further insights: I can only reproduce this issue for non-uint8 (namely, uint16) layers (regardless of color or segmentation). Unfortunately, I couldn't find any workaround or more details about what's exactly going wrong on iOS 14.

**Comment by hotzenklotz** [comment]
Voting to close this issue, since iOS14 is outdated (iOS16 was just released) and we update wK to WebGL2 + ThreeJS updates.
