### ISSUE TITLE
Upgrade Three.js

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#5836]
Newer Three.js (current is 134, wk is on 110) has a couple more features, but also breaking changes such as removing `Geometry` (see [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r124--r125)). Needs a proper assessment by a JS god :hindu_temple:

**Comment by philippotto** [comment]
We are at 142 now :) Was done in #4852 I think.
