### ISSUE TITLE
"Refresh" button not immediately usable

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#5854]
## Context
When loading the dashboard, the "Refresh" button is spinning for a few seconds and cannot be clicked. It's not actually doing something, though, because any new dataset still doesn't show up in the dashboard when it stops spinning.

I have to wait until it stops spinning, and then click it to do the actual refresh.

## Expected Behavior
I'd expect this button to be immediately clickable once the dashboard is loaded.

## Current Behavior
See above

## Steps to Reproduce the bug
1. Load the dashboard

## Your Environment for bug
- Browser name and version: e.g. Chrome Version 95.0.4638.69 (Official Build) (arm64)
- Operating System and version: e.g. MacOS 12.0
- Version of WebKnossos (Release or Commit): 15971

**Comment by philippotto** [comment]
This is not really a bug but instead a symptom of (hackily) re-using the button for different things. 1) The button is used to initiate a re-scan of the binaryData folder on disk and 2) The button is used as a loading indicator when the front-end refreshes the datasets cache (by refetching the datasets without initiating a re-scan).

So, this is more of a UX problem. A quick solution might be to have a separate loading indicator for the "reload cache" part. However, we probably need to explain to the user what the difference between "rescan disk" and "reload from server" is..
