### ISSUE TITLE
Weird flickering when hovering segment

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5878]
Sometimes the hovered segment is not rendered properly. See second 4:

https://user-images.githubusercontent.com/2486553/144025118-e222fd21-567c-4405-8f23-667da510e823.mp4

Cannot reproduce on OS X or Ubuntu. Maybe Windows specific?

**Comment by hotzenklotz** [comment]
@philippotto Have you encountered this bug again? With the recent switch to WebGL2, update to ThreeJs and major modifications to our rendering code, I would assume that we either solved this particular bug or have other rendering issues/flickers these days. Voting to close the issue.

**Comment by philippotto** [comment]
I think this was reported by an external user. We can reopen when we get a new report.
