### ISSUE TITLE
wkw datasets with numerical layer name strings are not loaded correctly

### ISSUE THREAD

**Issue by filippocastelli** [scalableminds/webknossos#5884]
## Context
When creating a WKW dataset, setting a layer name to a numerical string will cause webknossos to not load correctly the entire dataset

## Expected Behavior
The dataset is loaded correctly

## Current Behavior
When trying to read the dataset in webknossos two errors are raised:
 

- `Error processing layer 'cdbbcad7d293338e/test_dataset_1638452336/color' - Error reading resolutions`

- `Error processing resolution 'Left(2513)' - binaryData/cdbbcad7d293338e/test_dataset_1638452336/color/2513/header.wkw (No such file or directory)`

## Steps to Reproduce the bug
This python script creates a bug-reproducing dataset and uploads it

``` [python]
from pathlib import Path
import random

import numpy as np
from datetime import datetime
import webknossos as wk

dataset_name = "test_dataset_" + str(int(round(datetime.timestamp(datetime.now()))))
output_path = Path(dataset_name)

shape = (100, 100, 2)
data = np.random.randint(0, 255, shape, dtype=np.uint8)
with wk.webknossos_context(token="my_token"):
    dataset = wk.Dataset.create(dataset_path=str(output_path), name=dataset_name, scale=(1, 1, 1))
    color_layer = dataset.add_layer(layer_name=str(random.randint(0, 9999)), category="color", dtype_per_layer=data.dtype)
    mag = color_layer.add_mag(1)
    mag.write(data)
    mag.compress()

    url = dataset.upload()
    print(f"error reproducing dataset uploaded to {url}")
```

## Workaround
Use alphanumeric strings for layer names

## Environment

- python==3.8
- webknossos==0.8.24

**Comment by fm3** [comment]
Hello and thanks for your detailed report! We can reproduce the issue and will investigate what is going on here. We hope using alphanumerical names is an acceptable workaround for you for the moment. Sorry for the inconvenience!

**Comment by philippotto** [comment]
Thanks for the bug report! I can reproduce it and we will build a fix for it.

**Comment by filippocastelli** [comment]
perfectly acceptable workaround, just had a bit of head scratching before realizing where the problem was :)
