### ISSUE TITLE
Back-end sometimes suggests incorrect resolution format

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5915]
In the "Edit Dataset" view, the suggested `datasource-properties.json` sometimes seems to contain something like:

```
    {
      "name": "segmentation",
      "boundingBox": {
        "topLeft": [
          32400,
          6970,
          463
        ],
        "width": 13000,
        "height": 11000,
        "depth": 200
      },
      "wkwResolutions": [
        {
          "resolution": [
            2,
            2
          ],
          "cubeLength": 256
        },
        {
          "resolution": [
            4,
            4
          ],
          "cubeLength": 256
        },
        {
          "resolution": [
            8,
            8
          ],
          "cubeLength": 256
        },
        {
          "resolution": [
            16,
            16,
            2
          ],
          "cubeLength": 256
        },
        {
```

Note the resolutions which are 2-tuples (e.g., `2, 2`) which should either be `2` or `2, 2, 2`.

**Comment by fm3** [comment]
The json you pasted is the _diff_ between the old and the new json, hence the weird array values. This is not the json that the server sends. In the UI, the »Click here to use the new suggested values« option works for me. We should further investigate how the user was led into an invalid state here.
