### ISSUE TITLE
Add cancel functionality to jobs

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5932]
## Detailed Description
Add a cancel feature to jobs that also cleans up any intermediate/unfinished data that has been produced.
This feature should be exposed through a button in the jobs list.

## Context
Some jobs need to be cancelled for user reasons (eg. re-run because of wrong parameter selected) or for technical reasons (eg. job is stuck or takes up too much resources).

* [x] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Corresponding worker issue is https://github.com/scalableminds/webknossos-worker/issues/80

**Comment by fm3** [comment]
Taking out the “cleanup” part here as that is on the worker-side only and tracked separately in https://github.com/scalableminds/webknossos-worker/issues/83
