### ISSUE TITLE
Buggy volume annotation when using "overwrite empty"

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5937]
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Create new volume annotation (without fallback)
2. Annotate one cell
3. Create new segment id
4. Enable "overwrite empty" mode
5. Zoom to mag 4
6. Brush over the edge of the first cell
7. Zoom in --> inconsistent segment

Mag 4:
![image](https://user-images.githubusercontent.com/2486553/148083228-927caa68-cc5a-4779-abf8-76d700274cfd.png)

Mag 2:
![image](https://user-images.githubusercontent.com/2486553/148083243-45125be2-3300-425f-90a5-f9044e11beec.png)

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
could this be a duplicate of #5796?

**Comment by philippotto** [comment]
Good point :+1:
