### ISSUE TITLE
Fix "create annotation" for uint64 datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5964]
## Detailed Description
Fix "create annotation" for the datasets described below.

## Context
The neuroglancer datasets (e.g. https://webknossos.org/datasets/Demo_Organization/h01_20210601/view#620659,317098,2662,0,91.819) have `uint64` segmentations. When clicking "create annotation" there is an error.
```
Creating volume annotations with uint64 fallback layer is not supported by wK yet.
```
Creating skeleton-only annotations works, but is not what happens when clicking the "create annotation".

**Comment by fm3** [comment]
I see three options:
 (1) For datasets with uint64 segmentations, make the default of the button skeleton-only 
 (2) For datasets with uint64 segmentations, make the default of the button skeleton + volume but without fallback layer
 (3) Actually implement uint64 data https://github.com/scalableminds/webknossos/issues/4852

**Comment by fm3** [comment]
closing this, as we decided to actually go for https://github.com/scalableminds/webknossos/issues/4852
