### ISSUE TITLE
tree Liste Markierung

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#601]
Wenn viele trees eingeladen sind und man im 4. viewport einen auswählt, sollte die Auswahl in der tree Liste deutlich werden (z.B. der tree der ausgewählt ist ganz oben in der Liste zu sehen sein ).
Also nicht die Reihenfolge der gezeigten trees ändern, nur so weit runter scrollen lassen, dass dieser tree oben in der Liste der sichtbaren steht.

LG,
Heiko

 Reported by: Heiko Wissler (hwissler@brain.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/601/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
This has been fixed in the meantime. The active tree is always focuses and the list is scrolled.
