### ISSUE TITLE
Support for uint32 color data

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6014]
Currently, wk can only render segmentation layers in uint32, but not color layers in uint32.

See this issue for the uint16 pendant. https://github.com/scalableminds/webknossos/issues/3781

The backends histogram support would also need to be adapted (see https://github.com/scalableminds/webknossos/pull/4195 which adds float and uint24 support).

**Comment by fm3** [comment]
superseded by #6581
