### ISSUE TITLE
Toggling to/from showing archived annotations can lead to inconsistent states

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6018]
## Context
dashboard > my annotations

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. archive an annotation X
2. click "show archived annotations"
3. click "show unarchived annotations"
4. annotation X appears again

I also managed to toggle several   times between archived/unarchived and everytime an additional annotation X (duplicate) showed up in the list.

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Not sure how I managed to get to that state but with an intact archived list, I then hit F5 (browser page refresh) and then I saw many annotations that are actually open in the list again (even though it was still the archived list and the reopen button was rendered for them)
