### ISSUE TITLE
Task search page should have placeholder text

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6025]
When opening `/tasks` no tasks are shown until you enter at least one search criterion. This fact should be in an explaining placeholder text, instead of “no data”

**Comment by r0ushann** [comment]
would you please provide a screenshot of the issue you were facing?
i'm looking forward for this..

**Comment by fm3** [comment]
Sure thing! This is what localhost:9000/tasks looks like in current master webKnossos, even if tasks do exist.

![image](https://user-images.githubusercontent.com/1390035/152797339-1936c76e-49c7-4dbc-9e73-7f62bd535d3c.png)

**Comment by r0ushann** [comment]
would you guide me? how to initiate this? :)
