### ISSUE TITLE
Consistent Terminology

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6053]
Since we agreed on a specific terminology (see comment below), the following steps need to be done to adapt the user-facing parts:
* [x] supply terminology overview in the docs (#6154)
* [x] adapt terminology usage throughout existing docs
* [x] adapt terminology usage in the frontend
* [ ] adapt terminology usage in wk-libs (part 1: https://github.com/scalableminds/webknossos-libs/pull/704, part 2: https://github.com/scalableminds/webknossos-libs/pull/706)

--------------------
## Detailed Description
The (user-facing) terminology throughout webKnossos could need some structuring and standardization. Atm there are multiple terms to describe the same thing, and also single terms describing various things (e.g. tracing). To get some consistency, at least in user-facing text (e.g. webknossos frontent, documentation, APIs), I'd propose to start an terminology overview, where terms are collected an either relevant docs are referenced or a short explanation is added. This overview could be part of the documentation, basically as an index for those terms.

Some examples that confused me at some point:
- volume-annotation, volume-layer, volume-annotation-layer, annotation-layer (which of those is what)
- annotation, tracing, skeleton(s), graphs, trees, groups, NML, Task (what is what)
- what is a branchpoint?
- data set vs dataset or datasource or data source
- chunk, file, bucket, shard, block
- explorative vs explorational
- mag vs magnification vs mip vs resolution vs zoomstep
- mag exponent vs index vs ?
- higher/lower mag vs finer/coarser?

Besides clarifying "default" names (and maybe abbreviations) internally, I think this would just be a great documentation for users by itself. Also dependencies between them might be useful, e.g. as an ER diagram:
```mermaid
erDiagram
    Project ||--|{ Task : has
    Project }o--|| Team : has
    Project ||--|| User : "owned by"
    Team }o--|{ User : "consists of"
    Task }o--o{ Annotation : has
    User ||--|| Annotation : annotates
```

**Comment by fm3** [comment]
I agree that converging on canonical names (with explanations) would be extremely valuable 👍 
I’d say the dependency visualization is nice-to-have (but hard to get right)

**Comment by jstriebel** [comment]
Notes from the discussion today:
* volume-annotation, volume-layer, volume-annotation-layer, annotation-layer (which of those is what)
* annotation, tracing, skeleton(s), graphs, trees, groups, NML, Task (what is what)
  -> long term goal: editable segmentation layer
  -> annotation: n annotation layers
  -> annotation layer can be volume (annotation) layer or skeleton (annotation) layer
  -> volume-only annotation, skeleton-only annotation
  -> "tracing" dies/died
  -> Skeleton = Skeleton layer, no plural
  -> tree (but can have cycles)
  -> no more graph
  -> (tree) group
  -> NML is file format:
    * skeleton-only annotations
    * zipped: for any annotations (& task instances)
  -> task type, task, task instance (can be abbreviated as task for non-admins)
* what is a branchpoint
  -> jumpstack node markers
* data set vs dataset or datasource or data source
  -> dataset (internal some parts are datasource)
* chunk, file, bucket, shard, block (chunk=block=bucket)
  -> chunks, shards, chunks per shard, chunk shape, shard shape
* explorative vs explorational
  -> annotation without task
  -> consider dropping "explorative"/"task" part in URI
  -> compound views are separate route
    (maybe redirects from current routes)
* mag vs magnification vs mip vs resolution
  -> Mag(nification) (might change later with OME adoption)
* scale vs voxel-size
  -> frontend: add unit dropdown?
  -> longterm add unit support
  -> voxel size
* mag exponent vs index vs zoomstep
  -> dies, send 3 numbers
* higher/lower mag vs finer/coarser vs best
  -> finer, coarser, finest, coarsest


---------------

I'll add a section to the webknossos documentation with the canonical words and very short explanations, and also check usages in https://github.com/scalableminds/webknossos-libs (@normanrz adapts shard & chunk shape). We'll also need to double-check this in the existing docs and in the frontend. I'll add separate issues for the URI pattern changes.
