### ISSUE TITLE
Uploading annotation zip with empty volume layers leads to error

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6063]
## Context
When uploading an annotation zip-file which includes empty volume tracings (which is produced e.g. when downloading an annotation without brushing, or via wk-libs), then I get the following error:
```
Unsuccessful WS request to https://webknossos.org/tracings/volume/5aa9f1e2-fa19-467c-8d1b-85d776548aa1/initialData (ID: 551).Status: 400. Response: {"messages":[{"error":"Resolution restrictions result in zero resolutions"}]}
```

This should not happen.

## Steps to Reproduce the bug
1. Drag'n'Drop the following annotation zip into webknossos
  [l4dense_motta_et_al_nuclei__explorational__jstriebel__b3eddd.zip](https://github.com/scalableminds/webknossos/files/8108776/l4dense_motta_et_al_nuclei__explorational__jstriebel__b3eddd.zip)
2. The error mentioned above is shown, no annotation opens :crying_cat_face:

**Comment by jstriebel** [comment]
One possible workflow might also include to prepare an annotation (as a basis for a task or explorative annotation) via the wk-libs, where empty volume layers are prepared. (Writing data into those is currently not possible via wk-libs, as this should rather be a normal dataset-layer, I'd assume volume annotations are for manual annotation data.)
In this use case it might be helpful to be able to specify the resolution list via the API.

It could be written to the nml, as you proposed. One alternative might be to only have the `header.wkw` files per mag, which also specifies them via the folder structure. I guessed this might even be possible already, but seems like it is not, I got the same error with this file:

Btw, simply omitting the zip-file leads to an annotation which says
![Screenshot from 2022-02-21 12-45-08](https://user-images.githubusercontent.com/7216331/154949291-0c283260-3b93-4f33-923b-b5fd1fbc0c42.png)

Either way, we could use the dataset's / fallback-layer's mags as a default for now (and maybe add a feature allowing to specify the mags via the header-files or nml entries later), or include the `header.wkw` files in the download as well and use them to specifiy the resolution list.

**Comment by philippotto** [comment]
> One alternative might be to only have the header.wkw files per mag, which also specifies them via the folder structure.

This would be my preference currently. Extending the NML format poses the risk of unsynced meta data vs actually available data.
