### ISSUE TITLE
Maximum stack size exceeded when brushing large areas very fast

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6074]
## Context
Volume Annotation.

## Current Behavior
Crashes with maximum call stack size exceeded error.

Also see https://github.com/scalableminds/webknossos/pull/6055#issuecomment-1048057756

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

Unfortunately, the repro is not 100% reliable:
1. Open new volume annotation
2. Brush large areas very fast and click save in between

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by daniel-wer** [comment]
Just adding my repro steps. For me it was enough to select the largest brush size, zoom out a fair bit and then do three to four fast and large brush strokes across the whole viewports.
