### ISSUE TITLE
Ad-hoc meshing does not work for non-integrated datastores

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6077]
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. open https://webknossos.org/annotations/Explorational/6216432a010000c700ce40cc#4261,13026,1573,0,8.746
2. try to load an adhoc mesh

error:
```
Access to fetch at '...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
For the record, we now think that this is not actually a CORS error, but that the CORS headers are not set in the error case (see https://github.com/scalableminds/webknossos/issues/6078 ) – we should of course check what the underlying error is here

**Comment by fm3** [comment]
Turns out the relevant datastore is out of date, and the real error was the renaming of voxelDimensions to subsamplingStrides in https://github.com/scalableminds/webknossos/pull/6048, which the datastore did not understand. @philippotto Could you upgrade the datastore? I think this issue can be closed then

**Comment by philippotto** [comment]
> @philippotto Could you upgrade the datastore? I think this issue can be closed then

Yes, you are right. Now it works :+1:
