### ISSUE TITLE
Zarr backend followup: OME-NGFF, user-side improvements

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6120]
Follow-up for reading zarr images in wk-backend backend (https://github.com/scalableminds/webknossos/pull/6019)

 - [x] handle multi-layers/ngff
     - [x] handle OME-NGFF metadata https://github.com/scalableminds/webknossos/pull/6335
     - [x] handle non-standard axis order (as specified by ome metadata?) https://github.com/scalableminds/webknossos/pull/6335
 - [ ] pass through channels all the way to the front-end
 - [ ] expose as first-class feature to users
     - [ ] adapt frontend compatibility detection for upload
     - [x] routes to add remote datasets https://github.com/scalableminds/webknossos/pull/6335
     - [x] adapt documentation
     - [ ] Store Credentials on wk side in db rather than in datasource-properties.json
     - [ ] Do remote datasets need a datasource-properties.json at all?

**Comment by normanrz** [comment]
> [ ] pass through channels all the way to the front-end

This could also be solved by adding a `channelIndex` field to the datasource metadata, which allows to cut out different channels of a dataset. Then, no frontend changes would be required.

**Comment by fm3** [comment]
The remaining todos are tracked in individual issues now:  #6578 and #6525
