### ISSUE TITLE
Make mag list detection for volume uploads more resilient

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6128]
The mag list detection in the volume annotation upload cannot handle some edge cases:
 - buckets that are all-zero are skipped and if (in a mag) all buckets are zero, that mag is not added to the Mag list. Example zip: https://scm.slack.com/archives/C5AKLAV0B/p1648576115769449
 - volume annotations with no buckets at all (could still have header.wkw files per mag) also result in an empty Mag list.

https://github.com/scalableminds/webknossos/pull/6116 is a workaround that will transform this empty list to a complete list. But this should only happen if there is really no way to obtain the correct list. I’d say we should also consider all-zero buckets and header.wkw files when detecting the Mag set.

**Comment by fm3** [comment]
Unassigning myself for the moment as the debugging task was what we scheduled for this sprint. Now we know what happened and that this case is fairly rare. We can decide again later when to schedule this enhancement.
