### ISSUE TITLE
Clean up annotation & task URI schema, get rid of term "explorational"

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6156]
Atm, the following URIs exist:
* `https://webknossos.org/annotations/Explorational/<id>`
* `https://webknossos.org/annotations/Task/<id>`
* `https://webknossos.org/annotations/CompoundTask/<id>`
* `https://webknossos.org/annotations/CompoundProject/<id>`
* `https://webknossos.org/annotations/CompoundTaskType/<id>`

However, we wan't to get rid of the term "explorational" and rather call those "annotations" (without an associated task) (see #6053).
Since tasks and annotations can not have the same id, we might simply have a common URI for annotations with and without tasks (former task & exploration URIs):
`https://webknossos.org/annotations/<id>`

To simplify the URI schema, we might also use something like the following for compound annotations:
`https://webknossos.org/compoundAnnotations/byTaskType/<id>` or even as a subpart of the respective item, e.g.
`https://webknossos.org/taskTypes/<id>/compoundAnnotation`.

For backwards-compatibility, we should have redirects to those from the previous URIs.

cc @fm3 @normanrz @philippotto @hotzenklotz

**Comment by fm3** [comment]
Note that this is (at first) about the front-end router, not about the api routes.
Furthermore, I’d say that the annotations/Compound* URIs can possibly even stay as they are, just with hard-coded difference that handles them not being ids in that spot in the URI

**Comment by hotzenklotz** [comment]
I am in favor of the sub-part routes e.g. `https://webknossos.org/tasktypes/<id>/compoundAnnotation`. Likely, the `projects` could have a similar route: `https://webknossos.org/projects/<id>/compoundAnnotation`.

Not sure if we need the name `compoundAnnotation` or just `annotation`.

**Comment by fm3** [comment]
Jonathan pointed out that the back-end does have to provide one new possibility: request a (stored) annotation by id without supplying whether it is a task or explorational. I will provide this :)
