### ISSUE TITLE
remove zoomstep from chunk request URI

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6157]
Atm, we use the "resolution" aka zoomstep (corresponding to `log2(max(mag))`) for the chunk GET requests (see [here](https://github.com/scalableminds/webknossos/blob/d5c42e126180de6519da36e308045aaa22b84e8b/webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala#L80-L85). Let's use the full mag here, which is less ambiguous, see #6053.

cc @fm3

**Comment by fm3** [comment]
duplicate of #4893
