### ISSUE TITLE
Add tags to Mailchimp

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#6164]
## Detailed Description
For users tagged "registered_as_admin":

21 days after the sign-up, add the tag "active_user" if they have been active on webknossos in the last 9 days.
21 days after the sign-up, add the tag "inactive_user" if they have not been active on webknossos in the last 9 days.

Active means they have uploaded a dataset, created an annotation, or invited users to their organization. 

## Context
When new users subscribe to webknossos, they are either tagged as registered_as_admin or as registered_as_user. The admins receive a series of onboarding emails and activity needs to be tracked. After a few days, they receive different emails if they have been active in webknossos in not.

**Comment by fm3** [comment]
closed by #6214
