### ISSUE TITLE
blosc data decompression fails silently if blosc is not installed

### ISSUE THREAD

**Issue by leowe** [scalableminds/webknossos#6174]
## Context
When reading a zarr dataset that is blosc compressed and c-blosc is not installed, requests fail silently and just return empty response bodies.

## Expected Behavior
When starting webknossos or when reading a blosc compressed file and the `c-blosc` dependency is not present, it should (a) warn or (b) fail with a meaningful message.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Don't have `c-blosc` installed on system
2. Put a zarr dataset in `binaryData`
3. Try to open it in webknossos

**Comment by fm3** [comment]
We had this case again on @Dagobert42 ’s machine when he first set up the wk environment. However, there we got readable error messages in the backend logging. @leowe do you remember if we checked that at the time? I’d say that readable backend-logging is enough, passing errors to the front-end is difficult for bucket requests (everything is caught and empty-bucket headers are used for the responses). So I’d close this issue if you don’t object?

**Comment by leowe** [comment]
I am not sure whether we checked that, let's close it for now.
