### ISSUE TITLE
Zarr streaming - give folder overview over zarr buckets

### ISSUE THREAD

**Issue by leowe** [scalableminds/webknossos#6181]
## Detailed Description
Follow-up for [#6144](https://github.com/scalableminds/webknossos/pull/6144).

To use webknossos as a http file server and therefore for zarr streaming, it is necessary to give an overview of the contents of the folders `<dataSource>` (listing all layer names), `<dataSource>/<layerName>` (listing all mags), and the existence of `<dataSource>/<layerName>/<mag>`.

We should also provide the actual bucket file names (`0.0.0.0`, `0.0.0.1`, etc) when accessing `<dataSource>/<layerName>/<mag>` similarly to the other folders.

**Comment by fm3** [comment]
as discussed in https://scm.slack.com/archives/C5AKLAV0B/p1659520520584879?thread_ts=1659444085.360839&cid=C5AKLAV0B we decided that we do not want to list all chunks/buckets, as the listings would get quite large and the info is already contained in the bounding box.
to optimize streaming in sparse datasets, we will wait for sharding implementation.
