### ISSUE TITLE
Precompute meshes job should run for active mapping

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#6190]
## Detailed Description

When running a mesh precomputation job, I would expect the active mapping to be used, since this is the segmentation the user sees.

## Context

Looks like the backend, worker, and even the respective frontend `admin_rest_api` function already have this capability, so this should be a quick change.

**Comment by philippotto** [comment]
Should be fixed by https://github.com/scalableminds/webknossos/pull/6651.
