### ISSUE TITLE
Task creation should batch requests not only in bulk mode, but also in from-files mode

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6194]
## Detailed Description
In the task creation, there is a limit for how many tasks can be created in one request. This is 1000 for skeleton, only, 100 otherwise. The front-end automatically chunks larger amounts of tasks, but only in task_create_bulk_view. A user now tried to create tasks from 289 files, and the backend rejected the request. task_create_form_view should also implement this batching logic if the user appends multiple files.

Side node: If the user does not append the files individually but instead zips them all together, the batching cannot run. I’d say this is acceptable for the moment, though.

**Comment by MichaelBuessemeyer** [comment]
> Side node: If the user does not append the files individually but instead zips them all together, the batching cannot run. I’d say this is acceptable for the moment, though.

Maybe it is possible to unzip the files in the browser and then batch them? @fm3 Do you think I should take time time to investigate whether this approach works or not? (maybe also cc @philippotto)

**Comment by fm3** [comment]
I’d vote for not going into that at right now. Might bring additional questions concerning perf/memory in the browser, and would have to re-implement the logic for dealing with nested zips
