### ISSUE TITLE
Add form item to enter the name of the output segmentation layer for the inferral jobs

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#6197]
## Detailed Description

Currently, wk has two inferral jobs: Nuclei and neuron inferral. Both have a segmentation layer as an output. The name of this output layer is currently not configurable by the user, but it should be. The materialize volume annotation job already has this option by using the `OutputSegmentationLayerNameFormItem`. This form item should be able to be reused for this change. 
Note that this also includes handing the new parameter to the backend and then to the worker.

## Context

This feature is useful to rename the output segmentation layer of a job to something that makes sense and is not fixed.
* [x] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)

**Comment by MichaelBuessemeyer** [comment]
Sorry, this issue wasn't solved. My Bad 🙈.

**Comment by fm3** [comment]
@philippotto Do you know if this is still relevant after https://github.com/scalableminds/webknossos/pull/7368 ?
