### ISSUE TITLE
Zarr streaming - Generous CORS headers

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6199]
## Detailed Description
We want the Zarr streaming to be used as datasource in other tools. For that, we need to add generous CORS headers to the relevant routes.

**Comment by fm3** [comment]
should only be `override def allowRemoteOrigin: Boolean = true`  in the controller

**Comment by leowe** [comment]
> should only be `override def allowRemoteOrigin: Boolean = true` in the controller

That seems to be already in the `ZarrStreamingController`: https://github.com/scalableminds/webknossos/blob/03db25f648b394a6b68e68577456b83a2257a7e7/webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala#L34 I'll investigate whether this is still a problem right now

**Comment by leowe** [comment]
The CORS headers are also correctly set:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/13684843/169071258-9f97a525-b6fe-40bc-8f3f-399b165cc007.png">

**Comment by normanrz** [comment]
I actually can't reproduce the error. Sorry!
