### ISSUE TITLE
Bounding box doesn't affect segmentation layer

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#620]
As described in summary, bounding box that can be defined for tasks doesn't cut segmentation layer in segNew dataset

 Reported by: Kevin Boergens (boergens@neuro.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/620/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
@kevinbbb87 is this still a bug?

**Comment by kevinbbb87** [comment]
@normanrz I just checked and it seems fixed
