### ISSUE TITLE
Respect "Starting Position" in task when using an Annotation ID as Base

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6200]
## Context
Tasks with a base annotation will always use the edit position from that base annotation instead of the one which is provided when creating a task.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Create a new task type with volume enabled
2. Create an annotation, go to position `100, 100, 100`, save and copy its id
3. Create a new task, select the task type from (1) and select "Use Annotation ID as Base" where the id from (2) should be pasted in
4. Enter a Starting Position (e.g., `1, 2, 3`)
5. Go to dashboard, get a new task and open it
6. The active position should be the one from (4). Instead, it is `100, 100, 100`.

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Should the same go for bounding box and edit rotation? I’d guess so, right?
