### ISSUE TITLE
Improve "convert to hybrid" flow with regard to segmentation layers

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6209]
When having a skeleton-only annotation, one can click on "create to hybrid", but one doesn't have control over the creation of the volume layer (which one will be editable?).

In the case of a skeleton-only annotation, I'd argue that one should simply use the "Add Volume Annotation Layer" button (which should enable to select which layer should be used). Or even better: add a "make editable" button to each segmentation layer (which is not editable yet). In that case, the "convert to hybrid" button would be superfluous.

**Comment by fm3** [comment]
I agree with your suggestions, we should get rid of the term hybrid and the convert-to-hybrid button. I think the “add segmentation layer” button is needed, for example if you do not want a fallback layer. An additional make-editable button would be a nice shortcut, though

**Comment by philippotto** [comment]
Todo:

- [ ] remove convert-to-hybrid button (instead the user should use the "add X layer" button in the left sidebar)
- [ ] remove "Annotation Type: Hybrid" line from info tab
- [ ] add "Add Skeleton layer" to "Layers" tab if no skeleton layer exists yet (clicking this tab should do the same action as the old "convert-to-hybrid" button)
- [ ] add a "make editable" button to each segmentation layer (which is not editable yet) <-- this would be a shortcut to the "add volume layer" modal with the layer being preselected
