### ISSUE TITLE
Flip dimensions

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6233]
We are using F-order with c,x,y,z dimensions for our Zarr streaming. I am asking if we should switch to C-order with z,y,x,c. This would mean that the chunks are binary-equivalent. C-order seems to be more common and better supported by other tools.

This would also have implications for wklibs, which we should discuss. One option would be to read/write zarr data in C-order in [`ZarrArray`](https://github.com/scalableminds/webknossos-libs/blob/master/webknossos/webknossos/dataset/_array.py#L282), but keep exposing the F-order dimensions (ie. c,x,y,z) for the rest of the lib and client code.

cc @fm3 @jstriebel @leowe

**Comment by jstriebel** [comment]
> C-order seems to be more common and better supported by other tools.

If that's the case for some important tools, I agree. We should also check what the default axis order is usually. I've also seen that channels are not a separate dimension, but rather a [structured dtype](https://zarr.readthedocs.io/en/stable/spec/v2.html#data-type-encoding) in some cases. If compatibility and defaults are an issue, we might also consider serving the same data under different formats (probably as long as the chunks/shards stay binary equivalent), e.g. to have channel-dimension vs channels-in-dtype, or F-order with xyz and C-order with zyx.

> This would also have implications for wklibs, which we should discuss. One option would be to read/write zarr data in C-order in [ZarrArray](https://github.com/scalableminds/webknossos-libs/blob/master/webknossos/webknossos/dataset/_array.py#L282), but keep exposing the F-order dimensions (ie. c,x,y,z) for the rest of the lib and client code.

I agree we should stick with the current cxyz order for anything user facing in wk-libs, translating this in ZarrArray seems perfect :+1:

**Comment by fm3** [comment]
I agree that if this is required for compatibility, we can do this. However, i think it may add future headaches when we wonder why and how we translate the F-order wkw to C-order output without changing anything (as it instead changes the semantics)

**Comment by leowe** [comment]
What other tools are we talking about here? Viewing tools? Would that also impact the streaming API or only the "storage" part? I think if we need to expose different orderings we have to come up with a clever way to handle this, otherwise this will end up in a small mess

**Comment by normanrz** [comment]
> What other tools are we talking about here? Viewing tools?

I meant other viewing tools.

Thanks to your feedback, I now think that F-order belongs to the Zarr standard. Ideally, all conforming tools/libraries should support it. Perhaps we can help to implement that in other libraries (e.g. https://github.com/gzuidhof/zarr.js/issues/118).
