### ISSUE TITLE
search for experience

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#624]
Hi,
could you please implement on master that search by experience is possible in the user-menu?
Possibly do this in the existing search field
That would be very helpful.
Kind regards,
Heiko

 Reported by: Heiko Wissler (a@bc.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/624/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
@heikowissler This is now possible, simply enter the experience domain in the existing search field.
Is this sufficient or do you need to search for things like experienceDomain > 10?
