### ISSUE TITLE
Refactor backend: dataclass static function naming: from vs createFrom

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6241]
Some of our dataClasses have static methods `from(x)`, some have `createFrom(x)`, some have `parse(x)`. 
Also, if there are multiple sources a class instance can be created from, the overloading is sometimes done with actual overloading (all named the same) and sometimes the names differ (`fromArray`, `fromMagLiteral`).

I’d say we should define a unified convention and re-name functions we come across accordingly.

Personally, I’d vote to use the last mentioned variant, i.e. overloading explicitly in names, and no “create” – The [Vec3Int class ](https://github.com/scalableminds/webknossos/blob/master/util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala#L56) already uses this convention.

@leowe @jstriebel any preferences?

**Comment by fm3** [comment]
Thanks for your input :) Then I’ll set the new convention as I suggested above. Yes, the `create` prefix should be removed. Ideally it should say `fromSomething(x)`.

Note that this is only about dataclass static methods. More complex creation operations like `taskCreationService.createTracingsFromBaseAnnotations(…)` should still have the create prefix to indicate what is happening.

**Comment by jstriebel** [comment]
Sorry, I missed to answer here. I fully agree, using `from()` and `fromThisThing()` sounds coherent and seems to be a more clear change :+1:
