### ISSUE TITLE
Support Reading N5 Datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6256]
## Detailed Description
Building on top of our Zarr implementation, it would be great to also support N5. N5 is very similar to Zarr, but has slightly different file names and metadata. N5 provides a multi-scale convention.

**Comment by normanrz** [comment]
[Open organelle](https://openorganelle.janelia.org/) has a ton of datasets for testing, e.g. [`s3://janelia-cosem-datasets/jrc_macrophage-2/jrc_macrophage-2.n5`](https://open.quiltdata.com/b/janelia-cosem-datasets/tree/jrc_macrophage-2/jrc_macrophage-2.n5/)

**Comment by normanrz** [comment]
Reading

**Comment by leowe** [comment]
N5 format: https://github.com/saalfeldlab/n5
