### ISSUE TITLE
Provide entrypoint to stream complete annotations

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6270]
## Detailed Description
Due to #6203 we already support zarr-streaming of single volume annotations (including their fallback data), which is great! To make this feature more usable, it would be great to provide an entrypoint a datasource-properties and possibly OME spec for the whole annotation (except skeletons), including color layers and segmentations without annotations.
It's not clear yet where to put this endpoint (wk, ds, ts). For compatibility, it would be great if all related routes can be accessed from the same URL.

## Context
This allows to view/stream an annotation from other tools, such as wk-libs or OME-compatible tools.

Somewhat related issues are #6192, #6251, #6193, #6225

**Comment by normanrz** [comment]
Closing in favor of #6193
