### ISSUE TITLE
Remember active tool during toggle segmentation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6293]
When brushing/erasing in a volume annotation, it is often helpful to temporarily hide the segmentation layer (shortcut 3) for a clear view of the raw data. When un-hiding it shortly thereafter, the user is stuck in the move tool, for the brush/erase tools were temporarily disabled. It would be great if the tool that was previously active could be remembered and if I could continue brushing after hitting “3” twice quickly to check the raw data.

**Comment by philippotto** [comment]
(Should probably be implemented as a saga)

**Comment by fm3** [comment]
went through the issues again, turns out this is a duplicate of #4978
