### ISSUE TITLE
Allow setting custom colors for segments

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6306]
## Detailed Description
Analogously to setting a color for a tree, it would be nice to assign a specific color to a segment.

## Implementation Thoughts
- should be independent of mappings to avoid complexity
- could reuse existing custom color support for mappings, though
- would be limited to a maximum amount of custom colors (for mappings, custom colors can only be assigned for the first 256 segments)
- cuckoo hashing could be useful for implementation
- work packages:
  - provide UI to change colors and use these everywhere (in webgl as well as in JS world)
  - store custom colors in volume tracing
  - potentially, also use these in the back-end when generating thumbnails

**Comment by fm3** [comment]
From what I understand this is about user-defined colors per segment, right? So I would save this as r,g,b (uint8 each) with the segment in the proto object?

**Comment by philippotto** [comment]
Yes :+1:
