### ISSUE TITLE
Allow to filter /api/datasets by organization, uploader

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#6329]
## Detailed Description
Atm `/api/datasets` shows all datasets (even public ones of other orgs, which we might want to reconsider). It would be nice to be able to filter those for the python client by the owning organization, the uploader, and tags (using `any` semantics for the tags).

**Comment by fm3** [comment]
@jstriebel How important, do you think, are the tags here? I would prefer not to add them to the existing dataset GET request (as we don’t usually have GET requests with complex parameters like List-of-string. Maybe it is sufficient to filter by tags in the client (for now)?

**Comment by jstriebel** [comment]
@fm3 I don't think that's super important, since client-side filtering seems fine performance-wise for the moment :+1:
