### ISSUE TITLE
After histogram clipping fails (e.g. no data in viewport), button stays disabled

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6341]
I clicked the histogram-auto-clipping button while being in a black-only area in the dataset. It correctly showed a warning that this does not work. However, I then moved to a spot with real data and wanted to click again, but the button stays in the spinner mode and is disabled. After the error it should go back to a clickable state.

![image](https://user-images.githubusercontent.com/1390035/179971639-ea9f0d0b-a7ac-4635-8625-a832bc977aed.png)

**Comment by philippotto** [comment]
The relevant code happens in `useLoadingClickHandler`. There's a try-finally clause which is responsible for setting `isLoading` to false in case of an error (or in the success case, too). This spot needs to be debugged apparently.
