### ISSUE TITLE
Maximizing 3D viewport triggers mag warning

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6354]
I hit “.” to maximize the 3D viewport. This toast was shown:
![image](https://user-images.githubusercontent.com/1390035/181252742-8dccd9c7-ebc5-4904-aefe-378dd63bf336.png)
I don’t think it applies here, as no actual data is shown in this case, only wireframes + meshes

**Comment by hotzenklotz** [comment]
> I don’t think it applies here, as no actual data is shown in this case, only wireframes + meshes

There is data show on the cross-sectional planes in the 3D viewport. But perhaps, the data in the cross-sectional planes is not as crucial for viewing 3D meshes etc and the message can be tuned down.

**Comment by fm3** [comment]
I believe this data vanishes when maximizing the 3D viewport, as the other planes are no longer rendered.
