### ISSUE TITLE
preserve volume annotation largestSegmentId and elementClass across re-upload

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6390]
When downloading and re-uploading a volume annotation, the largestSegmentId and elementClass properties are lost.
In case of an existing fallback layer, the latter is harmless, as the elementClass of the fallback layer is always used. But if there is no fallback layer, the elementClass is set to uint32 in upload, which may not be large enough.

**Comment by philippotto** [comment]
> When downloading and re-uploading a volume annotation, the largestSegmentId and elementClass properties are lost.
In case of an existing fallback layer, the latter is harmless, as the elementClass of the fallback layer is always used.

This only becomes relevant when we expose a different dtype than 32-bit for new volume layers (without fallback), right?

**Comment by fm3** [comment]
for elementClass, yes, but the largestSegmentId would already be nice, I think
