### ISSUE TITLE
Allow loading data from public S3 buckets without credentials

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6401]
When attempting to load zarr data from public S3 buckets without credentials, The S3 file system errors with `Unable to load AWS credentials from any provider in the chain` – We should double-check if the S3 client ( https://github.com/lasersonlab/Amazon-S3-FileSystem-NIO2 ) has an option similar to anon=True in python ( compare https://github.com/fsspec/s3fs/blob/2a53f0f4b64edf315df52898bdbaabcca3a54e1f/s3fs/core.py#L428-L444 ). If not, we may want to implement it

**Comment by jstriebel** [comment]
This PR at an upstream project might help:
https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/pull/107

**Comment by fm3** [comment]
Thanks for having a look! That upstream PR is actually from the fork we are using, though. It is not really related to this issue. I’ll dig into the code some more
