### ISSUE TITLE
Keep tree names when merging nmls

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#641]
ußerdem: wenn ich ein nml mit vielen trees (die einen bestimmten Namen haben) einlade und dann ein anderes nml dazu-merge, werden die tree-names vom ersten nml umbenannt.
Es wäre schön, wenn die beibehalten werden könnten.

Grundsätzlich wäre es auch super wenn in dem tree-name der filename des hochgelandenen files stehen würde. 
Wenn es mehrere trees pro nml sind, kann ja tree1, 2, 3... vorgestellt werden.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/641/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
The first part (keep tree names when merging tracings) is already the behavior of the new skeletontracing backend ([code](https://github.com/scalableminds/braingames-libs/blob/brave_new_world/braingames-datastore/app/com/scalableminds/braingames/datastore/tracings/skeleton/SkeletonTracingService.scala#L177)).

I’m a little unsure about the second part. Uploaded NMLs can already contain tree names. Should we overwrite those on every NML upload? Change them to `<nml-filename>_tree<number>_<oldname>`?

**Comment by jfrohnhofen** [comment]
@kevinbbb87 @heikowissler I don't remember who wrote the initial email, that lead to me creating this issue. Do you still remember? Do you have any input on this?
