### ISSUE TITLE
[Super Voxel Editing] Merge segments along shortest path

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#6426]
## Detailed Description
When editing the super voxel graph, it should be easy to combine two segments (=merge operation). Instead of having to manually create edge between the underlaying graphs, wK should automatically create the best/shortest/easiest? connection between the two graphs when executing this operation.

Ideally, I could imaging this workflow like this:
1. Select first segment / select a node of the first segment2. 
2. Click on the second segment/Right-click on the second segment and select merge from context menu.
3. Baaaam, they merge.

Ideally, this workflow does not require to load any of the underlaying super voxel graphs at all. It should be as few clicks as possible and comparable to the existing "Merger Mode".

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
> wK should automatically create the best/shortest/easiest? connection between the two graphs when executing this operation.

I think, this connection path would always be simply one edge. The user selects two segments a and b for which the representative nodes in the supervoxel graph should be looked up in the background. Then, an edge from a to b would be constructed to merge the segments.

**Comment by philippotto** [comment]
> The user selects two segments a and b for which the representative nodes in the supervoxel graph should be looked up in the background. 

I think, this will be the crucial aspect. If we have that, the same mechanism should be used for the (min) cut operations.

Thus, the to dos are:

- [ ] allow to merge segments without selecting their RAG nodes
- [ ] allow to cut segments without selecting their RAG nodes
- [ ] allow to min-cut segments without selecting their RAG nodes

**Comment by philippotto** [comment]
Closed by https://github.com/scalableminds/webknossos/pull/6464.
