### ISSUE TITLE
Allow to select which datastore to use when importing Zarr

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6463]
## Detailed Description
Currently, the first datastore that allows uploading is used. The user cannot influence this.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
I’d say the user probably does not need to care about this. I don’t think we have any instance where multiple datastores allow upload. Also, no actual data is stored other than the datasource-properties.json (except for in-memory cache). In fact, long-term we might want to move this feature away from datastores generally.
