### ISSUE TITLE
zarr streaming routes should produce 404 on any kind of error, not 400

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6499]
Something in the route matching produced 400 errors in the zarr private links (neuroglancer requested .zattrs, .zarray in every hierarchy level, but not every one has both)

**Comment by normanrz** [comment]
Essentially, the zarr routes should not produce 400 errors but 404 when routes cannot be matched/found.

**Comment by fm3** [comment]
Oh they already do that :D the problem is that they _are_ matched by the router, which inserts `.zattrs` for example as mag. Then the implementation rejects that, since `.zattrs` is not a valid mag literal. So we need to make sure all combinations are taken care of
