### ISSUE TITLE
[Proofreading] Make use of precomputed mesh of oversegmentation

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6506]
If a precomputed mesh of the oversegmentation exists, this should be used when meshing a segments. One approach could be that the backend applies the agglomerate mapping on the mesh data and serves that to the frontend. The chunk borders might need special handling.

Algorithmically, I imagine something like this roughly:
- frontend sends segment ID (mapped)
- backend looks up which (unmapped) ids in the oversegmentation map to the given ID using the agglomerate file (is this operation possible?)
- backend looks up the meshes of each id and generates a list of mesh chunks
- the frontend can load the mesh chunks

**Comment by valentin-pinkau** [comment]
The approach looks reasonable to me 👍 
The reverse mapping from agglomerate id to segment ids is possible with the agglomerate_view.

**Comment by leowe** [comment]
Seems feasible to me 👍

**Comment by philippotto** [comment]
Great :+1: 

> * backend looks up the meshes of each id and generates a list of mesh chunks

Here an open question would probably be:

Should the backend simply reply with all "raw" mesh chunks of all unmapped ids? This would probably be the easiest approach right now, but would entail quite a lot of requests.

Alternatively, the backend could reply with chunk descriptors (e.g., saying sth like `at [x, y, z] there is mesh data for the requested mapped ID X`) which will then be requested by the frontend. Then, the backend would use one descriptor to join the mesh data of the individual unmapped IDs together so that one mesh is returned for one descriptor. This might require some temporary storage to avoid that data loading is done twice.

It's probably easier to discuss this in person. However, let's do it when the priority is right.
