### ISSUE TITLE
View for Task Instances

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6508]
For one task there can be several instances (happens when redundancy is desired for a task). For these instances, the following actions can be of interest:

- see which instances is assigned to which user
- assign a specific instance to a specific user
- see the the state of each instance (e.g., running, pending, finished)

**Comment by normanrz** [comment]
Perhaps to be implemented alongside https://github.com/scalableminds/webknossos/issues/5810

**Comment by hotzenklotz** [comment]
I am not sure I understand the issue. This information is already available for each task, as part of an collapse panel under each task:



![Image](https://user-images.githubusercontent.com/1105056/195841240-6f84ec7c-d42e-4e57-bf49-844abe8d17f4.png)

Do you suggest to have another dedicated, high-level list/table for these?

**Comment by normanrz** [comment]
This per-task list only includes instances that have already been started. There is no way to see un-assigned instances in order to assign them to someone. Maybe that should rather be a task action than an instance action.

**Comment by philippotto** [comment]
> There is no way to see un-assigned instances in order to assign them to someone. Maybe that should rather be a task action than an instance action.

I agree and think this is also how @hotzenklotz solved it now. I hadn't the expandable view in mind when writing this issue. I think, most use cases are covered now. Therefore, I'm closing this issue now.
