### ISSUE TITLE
Hotkey for delete node doesn't work in Mac OS

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#6511]
## Context
Skeleton annotation mode

## Expected Behavior
On pressing the Mac Os DEL key, the currently selected node should be deleted

## Current Behavior
Node remains

## Your Environment for bug
Mac Os Monterey
Chrome 104
webknossos as deployed on webknossos.org as of 9/28/2022

**Comment by hotzenklotz** [comment]
For reference, the equivalent to the windows `DEL` key on MacOS is FN + backspace.

**Comment by boergens** [comment]
Wonderful, thank you!
