### ISSUE TITLE
Sort Datasets in a Virtual Folder Structure

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6524]
Users should be enabled to sort datasets in a folder structure in the webKnossos UI.

(I suggest we move the checkboxes to the PR description once one exists)
- [ ] Backend
  - [ ] SQL Schema, compare https://www.slideshare.net/billkarwin/models-for-hierarchical-data
  - [ ] CRUD routes for folders
  - [ ] routes to move datasets
  - [ ] permission system
     - [ ] directories get allowedTeams just like datasets
     - [ ] dataset managers + admins can read+write in any folder
     - [ ] users can read
     - [ ] team managers can write in directories where the team they manage is allowed
     - [ ] additive permission bubbling through the folder tree
     - [ ] when you can read a leaf but not the parent, you still get to know the full path (but listdir will only lead you to the particular leaf)
- [ ] Frontend
  - [ ] current directory table view
  - [ ] sidebar with actions + metadata
  - [ ] context menu with actions
  - [ ] left-side tree view

**Comment by normanrz** [comment]
Mockup for new dataset list view
![IMG_7103](https://user-images.githubusercontent.com/335438/195565458-632b58b5-fe68-4e33-8caa-d54398b76afe.jpeg)

**Comment by philippotto** [comment]
@fm3 Is there already a branch for this issue?

**Comment by fm3** [comment]
There is :) I just linked the new PR, branch name is folders
