### ISSUE TITLE
NGFF Explorer: add labels as segmentation layer

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6538]
NGFF Zarr Metadata has a labels concept, compare https://ngff.openmicroscopy.org/latest/#labels-md. our explorer should convert that into a segmentation layer.

That means that the NGFF explorer should always request `labels/.zattrs` to check if something exists there. And if so, go a level deeper and look for .zattrs there.

From the examples posted by norman (see comment below):

The dataset at 
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/

has a label set at
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/.zattrs
(a new case class, maybe NgffLabelsGroup will be needed to parse that)

it in turn points to `0`, resulting in 
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/0/.zattrs 
which (among other things that we’ll ignore for this issue) has a standard multiscales metadata, pointing to datasets/mags such as `0`, resulting in
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/0/0/.zarray

layers from such a `labels` multiscales should be added as segmentation layers. note that those do not need to worry about channels (if a channel axis exists, the shape there will always be 1).

Bonus points if the layer names in the resulting datasource are prefixed with `labels`

**Comment by fm3** [comment]
@normanrz I think you mentioned you had an example file for this?

**Comment by normanrz** [comment]
Yes. See
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/.zattrs
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/0/.zattrs

**Comment by frcroth** [comment]
When I try to import the label layer as a segmentation layer, it is not possible because the elementClass of the resulting layer is int16, which is not included in the segmentationElementClasses.  [uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/0/0/.zarray](https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr/labels/0/0/.zarray) has "<i2" as dtype value. Any idea how to go further with this?

**Comment by normanrz** [comment]
@fm3 @philippotto Is there a good reason not to support signed int segmentation layers?

**Comment by fm3** [comment]
For the moment I’d suggest to just change int16 to uint16 in the metadata during the import. For most segmentations, the actual number values are irrelevant, so long as the values are distinct.

For longer-term, we can of course discuss supporting signed int segmentations, but that would create a lot of spots where we would have to either guard against or semantically handle negative ids.
