### ISSUE TITLE
Right mouse drag doesn't work in oblique mode

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#6539]
## Context
Dataset viewing (not annotation), oblique mode.

## Expected Behavior
In the right side menu, it says
![image](https://user-images.githubusercontent.com/1429753/194374023-3adba61b-e139-4edd-887b-ad954dbc3179.png)

## Current Behavior
right click drag moves view instead of rotation

## Your Environment for bug
Windows, Chrome, webknossos.org

**Comment by hotzenklotz** [comment]
I am not sure I understand the issue. In `oblique` mode no 3D viewport is displayed. By 3D viewport I am referring to the bottom right viewport showing the 3D meshes and all 3 data planes at once.

**Comment by boergens** [comment]
Fair point. In my head I thought that in oblique mode the main viewport was called the 3D viewport.
But then, shouldn't in oblique mode the information shown be different, i.e. how to rotate the view in the data viewport?

**Comment by hotzenklotz** [comment]
> But then, shouldn't in oblique mode the information shown be different, i.e. how to rotate the view in the data viewport?

Yes, you are right. The right-hand side info panel is not context-sensitive. Then again, none of the information presented there is wrong  when in oblique mode.

For context-aware usage and shortcut hints, check the webKnossos status bar at the bottom of the screen:
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/1105056/195092646-8b05aee8-b664-43b4-bba4-7ed599a88ed6.png">
