### ISSUE TITLE
Create overflow menu for layer actions in left sidbar

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6608]
It’s getting very crowded there

![image](https://user-images.githubusercontent.com/1390035/199975992-50fd7d04-9adc-4830-ae29-4dbb053e5d26.png)

#6593 adds the next button (delete annotation layer)

I think we could decide for each possible button if it is important enough to be directly displayed or if it can be hidden behind an overflow menu (this does not have to happen dynamically, I’d for example always hide the delete layer button behind that menu)

**Comment by dieknolle3333** [comment]
https://scm.slack.com/archives/C5AKLAV0B/p1685122919591729
