### ISSUE TITLE
Share chunkContents cache across multiple arrays

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6630]
We imported https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0047A/4496763.zarr and data loading took forever (like >5 minutes)
It is expected that populating the chunk cache is relatively slow (chunk shape is 1*1*2048*2048) but after that, data loading should be faster.

We should double check that now superfluous requests are made, that all caches are shared as expected, and investigate whatever else may be slowing this down.

**Comment by normanrz** [comment]
Are the histogram requests connected to the cache as well?

**Comment by fm3** [comment]
Should be, yes

**Comment by fm3** [comment]
Looks like the chunk cache is limited to 100 MB per array, that’s not enough for 32 slices of this dataset.

We should look into sharing a single cache for all arrays, with a fixed size and shared LFU strategy.

**Comment by fm3** [comment]
related: #6969 (item weight)
