### ISSUE TITLE
Speed up multi-channel Zarr dataset explorer/discovery

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#6631]
## Context
When importing a multi-channel Zarr dataset with a lot of channels, the import dialogue / Zarr discovery takes quite a long time, e.g. ~30seconds for 27 channels.

Example DS with 27 channels:
https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0054A/5025551.zarr

## Expected Behavior
Zarr import/discovery should be done in <5 seconds even for multi-channel datasets with a lot of channels.

## Current Behavior
While the feature works as expect it is a bit slow. Maybe the backend executes a request per channel which could takes some time and slow things down. 

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Dashboard --> Add Dataset --> Import Remote Zarr Dataset Tab
2. Import this 27-channel DS
3. Observe the slowness

<img src="https://media.giphy.com/media/lgIyvBoSKEhuo/giphy.gif">

## Your Environment for bug

- Browser name and version: all browsers
- Operating System and version: all OS

**Comment by fm3** [comment]
I’d suggest to switch the execution order:
first fetch and construct a single layer, like it was before, but also return the channel count
*then* iterate over (0 until channelCount), and duplicate the layer n times, with the channelIndex added then (probably via copy(channelIndex=x))

**Comment by hotzenklotz** [comment]
I just tested this again. The import time is now down to 13-14 seconds for the example dataset above. That is acceptable to me. 
Closing the issue for now.
