### ISSUE TITLE
Scala compilation error.

### ISSUE THREAD

**Issue by deepakkarunakaran** [scalableminds/webknossos#6636]
After executing yarn start, when trying to access https://localhost:9001 got the following error ...

backend: [info] compiling 166 Scala sources and 1 Java source to /home/user/webknossos/webknossos/target/scala-2.12/classes ...
backend: [error] /home/user/webknossos/webknossos/app/models/annotation/Annotation.scala:138:32: not found: type AnnotationsRow
backend: [error]     extends SQLDAO[Annotation, AnnotationsRow, Annotations](sqlClient) {
backend: [error]                                ^
backend: [error] /home/user/webknossos/webknossos/app/models/annotation/Annotation.scala:138:48: not found: type Annotations
....

backend: ! @7pho26fd0 - Internal server error, for (GET) [/] ->
backend:
backend: play.sbt.PlayExceptions$CompilationException: Compilation error[not found: type AnnotationsRow]
backend:        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
backend:        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
backend:        at scala.Option.map(Option.scala:230)
backend:        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:131)
backend:        at scala.Option.map(Option.scala:230)
backend:        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:104)
backend:        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:38)
backend:        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:156)
backend:        at scala.util.Either$LeftProjection.map(Either.scala:573)
backend:        at play.sbt.run.PlayReload$.compile(PlayReload.scala:156)

**Comment by normanrz** [comment]
Getting webKnossos to compile correctly is not straightforward. If you wish to run webKnossos on your own computer, you can use your prebuilt docker containers. Otherwise, you can use webKnossos for free at webknossos.org.
