### ISSUE TITLE
Support multiple levels of detail (LoD) for precomputed meshes

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6671]
- [x] investigate how to implement LoD support with threejs
  - see https://threejs.org/docs/#api/en/objects/LOD
  - can the precomputed mesh use different chunk sizes for different LoDs? that info would be useful to implement LoD in vx <-- yes, this should be possible.
- [x] wait for VX support
- [ ] integrate

**Comment by philippotto** [comment]
sample data: https://scm.slack.com/archives/C5AKLAV0B/p1674140733622169?thread_ts=1674138004.502719&cid=C5AKLAV0B

**Comment by MichaelBuessemeyer** [comment]
Workflow that computed the LOD Meshes for the l4 dataset LOD [https://webknossos.brain.mpg.de/workflows/988692dfd5](https://webknossos.brain.mpg.de/workflows/988692dfd5).
