### ISSUE TITLE
Notify users by email after a long-running jobs finishes

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#6673]
## Detailed Description
Right now, it is hard to tell when a long-running job finishes. Some users were not aware of the `Jobs` page altogether. I suggest to send users an email after each job finishes either with a link to the jobs page or even better directly with an actionable link, e.g. "View Dataset", "Download Tiffs" etc. 

Considerations up for discussion:
- Should we only send emails in the success case? Or also for failed jobs? 
- Should we blacklist some long-running jobs that do not produce a link, e.g. "find largest segment id"?

## Context

* [x] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

Long-running jobs are not easily discoverable when triggered somewhere in the UI. It also not easy to gauge the runtime of certain jobs. Notifying users of success - and perhaps equally important - of failures seems a good communication strategy.

**Comment by fm3** [comment]
The slack messages are sent in `trackNewlySuccessful` and `trackNewlyFailed` in the `JobService` class in Job.scala. I guess that is where the emails should be sent as well
