### ISSUE TITLE
Sometimes zarr data requests return too few buckets

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6709]
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Set up this dataset here https://scm.slack.com/archives/C3RUHRXBM/p1671526934198699?thread_ts=1671526852.728559&cid=C3RUHRXBM
2. View dataset and move in mag 2
3. Sometimes a warning is shown: `bucket.ts?f9e9:578 bucket.data has unexpected length {arrayBuffer: Uint8Array(0), actual: 0, expected: 32768, channelCount: 1}` which can result in corrupt rendering

Some details for the occurrence I inspected:
- one request for the uint8 color layer requested 6 buckets, but got only 4.
  - requested:
```
[4253, 5940, 123, 1]
[4254, 5945, 123, 1]
[4261, 5944, 123, 1]
[4252, 5940, 123, 1]
[4253, 5945, 123, 1]
[4252, 5944, 123, 1]
```
- the missingbuckets header was set to `[]` though
- the received buffer was 131072 entries long (131072 / 32**3 == 4)
- for some other volume request, the missingbuckets header contained buckets. so, the header itself seems to work at least sometimes

## Your Environment for bug
Localhost

**Comment by philippotto** [comment]
@fm3 While working on the multi modality feature, I'm experiencing this bug from time to time. Could you have a look at the back-end code to see whether there is something fishy? Or maybe just add a simple assertion which checks the length of the array buffer in comparison to the requested bucket count. If the counts mismatch, the request could simply fail (then, the front-end will retry). Right now, the bug causes incorrect rendering which can be quite confusing when changing the rendering code (since the artifacts are unrelated to the front-end code).

![image](https://user-images.githubusercontent.com/2486553/214352872-d590ee89-3484-4113-8b08-fd070f9a9178.png)

**Comment by fm3** [comment]
Adding an assertion is a good idea and easily done. I’m at a bit of a loss as to how to debug this, as we have no steps to reproduce. But maybe with the assertion I can provoke this. Was the dataset zarr-streamed in the backend again? But the relevant requests here are the normal webknossos data requests, right? Not zarr streaming?

**Comment by philippotto** [comment]
> I’m at a bit of a loss as to how to debug this, as we have no steps to reproduce. But maybe with the assertion I can provoke this.

The issue description has STR which work almost reliably for me (at least on the multi-modality branch; not sure whether this matters). We could have a call to debug this together, if you think this makes sense.

> Was the dataset zarr-streamed in the backend again? But the relevant requests here are the normal webknossos data requests, right? Not zarr streaming?

I'm not sure about the terminology here, but I have a dataset opened in the webknossos front-end for which the source is streamed via zarr (the front-end is on localhost and the dataset on another wk instance). The dataset on the remote wk instance is in wkw (I think) and streamed from there using the private zarr link feature. The front-end uses "normal webknossos data" requests as usual.

**Comment by fm3** [comment]
Ok thanks for the clarification! I’ll look into this tomorrow and ping you again if I have further questions :)
