### ISSUE TITLE
Allow import of 2D OME-Zarr data

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6740]
## Detailed Description
If a dataset only has 2 space dimensions, wk should be able to import it. We even have optimized ui for datasets with depth=1.

**Comment by frcroth** [comment]
Seems to be already possible. The dataset https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0083A/9822152.zarr can be imported. When opening, the XY view automatically uses the entire viewport.
When clicking on YZ or XZ wk is very confused
![image](https://github.com/scalableminds/webknossos/assets/6863832/3adb2d28-04b4-456c-bddb-03b6eb3fbd70)
![image](https://github.com/scalableminds/webknossos/assets/6863832/be184f2c-31ec-4850-9c28-6b4e9490678c)
Perhaps these buttons should be disabled by the frontend?

**Comment by normanrz** [comment]
Did you find a non-plate dataset with just `XYC` axes? eg https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0076A/10501752.zarr

**Comment by frcroth** [comment]
I added the remaining datasets to the sheet. The mentioned dataset has all data in dtype double, which is not supported.
To import the dataset I had to adjust axisorder things, which I did on https://github.com/scalableminds/webknossos/tree/2d-datasets, however there does not seem to be a data set to test it on
