### ISSUE TITLE
Optimize loading of precomputed meshes of oversegmentation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6752]
If a meshfile exists for the oversegmentation, webknossos can load meshes for any agglomerate mapping, by fetching the oversegmentation meshes for all segments of an agglomerate and giving them all the same color. The back-end side for this is implemented in `listMeshChunksForSegmentForVersion` and `readMeshChunkForVersion` in `DSMeshController.scala`.

We had a couple of ideas for optimizing the performance
 - the front-end currently sends one request per chunk per segment id
 - instead it could send just one request per chunk, including a list of meshFile/byteOffset/byteSize tuples for all relevant segments, reducing the number of http requests
 - the back-end could sort this by byte offset to optimize for spinning-disk based reading of the hdf5 file
 - optional: similar to bucket loading, we can think about loading more than one chunk per http request

Proposal: request contains json list, as described above. Reply is binary, consisting of
 - Length of jumptable (one long)
 - The jumptable (start offsets for each segment content)
 - the concatenated draco contents

**Comment by fm3** [comment]
@philippotto I just talked to @daniel-wer about a possible protocol. The front-end would have to decode a binary response when multiple draco meshes are sent in one request. Do you think reading a jump table like I described above would be feasible? Alternatively we could wrap the response in protobuf, or possibly use the http header to encode byte offsets, but since there could theoretically be thousands of those, I thought http header might not be the best place

**Comment by fm3** [comment]
Yes, sounds good :) thanks!

**Comment by daniel-wer** [comment]
> I think it's fair to assume a constant meshFile for this use case? So, it would be: meshFile and a list of [byteOffset, byteSize] tuples.

If the meshFile is assumed constant per request, I'd vote to change the request from `data: { meshFile, segmentId, position }` to `data: { meshFile, segmentIds, positions }` (or zipped segment IDs and positions) for the multi-segment case and then leave the meshFile out of the response.

**Comment by daniel-wer** [comment]
I've deleted my last comment as it did not make sense. Sounds good to me :)

**Comment by frcroth** [comment]
I implemented it for readChunkMesh in the backend.
	- I already talked with @philippotto about the implementation of the jump table. The first value (the length) seems to be superfluous right now, since the length of the jump table will always be the length of the request list (if one request fails, the whole request fails).
	- Any preference on endianness for the jump table data?
	- What needs to be done for the other route (listMeshChunksForSegmentForVersion)?

**Comment by philippotto** [comment]
> I’d forward the endianness question to Philipp, I have no strong preference. The last time we had to decide for one, we went with little endian (voxel values in wkw), so maybe it’s most consistent to stick with that? Not important though, since this is a different context anyway.

I read up on it now and would also say that we should do little endian. To quote from [here](https://hacks.mozilla.org/2017/01/typedarray-or-dataview-understanding-byte-order/):

> It is safe to assume systems to be little-endian.

In theory, we could get into trouble if a system uses big endian by default, but I think there are other spots where this would bite us, too. So, let's solve this problem once it's actually there.

**Comment by philippotto** [comment]
Just a small update here: the front-end can compute the jump table on its own because it knows the byteSizes it requests. That simplifies the approach a bit :)
