### ISSUE TITLE
changing "render missing data black" setting causes an error while not logged in

### ISSUE THREAD

**Issue by thopp-tudelft** [scalableminds/webknossos#6769]
## Context

viewing any dataset while not logged in

## Expected Behavior

nothing

## Current Behavior

![image](https://user-images.githubusercontent.com/113943154/213760780-29f87715-3a7e-4d0b-b02f-abc455233fbd.png)
a 401 and a 403 status are logged in the console

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. log out of webknossos
2. visit a dataset, eg https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo
3. click the settings tab
4. toggle "render missing data black"

## Your Environment for bug

- Browser name and version: firefox 108.0.2
- Operating System and version: Arch linux, kernel 6.1.6
- Version of WebKnossos (Release or Commit): 23.01 or 21218
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Hi and thanks for your report! I can reproduce the behavior you described. We will have a look!

@philippotto Both the `data/triggers/reload` and `clearThumbnailCache` routes are not available to logged-out users (which I’d say is correct). The reload layer button is simply not available for logged-out users, solving this problem there. But changing “render missing data black“ triggers these requests too. Do you think we should disable the button completely? Or may it be worth the effort to skip the requests that mutate server state in this case?

**Comment by philippotto** [comment]
Thanks for the report, @thopp-tudelft! Should be fixed now.
