### ISSUE TITLE
Speed up Annotation List Request

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6779]
Similar to the dataset list request that is being tackled in #6759 the Annotation list request could also be sped up by moving some of its logic to SQL.

However, there the priority for this change is a bit lower, since the annotation list is paginated and loading one page currently takes about 3s, as opposed to the 20s we saw for some dataset list requests.

**Comment by frcroth** [comment]
d, typ, name, description, owner, othersMayEdit, teams, owner, modified, stats, dataSetName
owner: id, firstName, lastName
team: id, name, organization
