### ISSUE TITLE
Unify naming: extent vs shape vs size for width-height-depth objects

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6818]
Should be unified in the backend. For bounding boxes, and during data loading (e,g, `val chunkShape = chunkSizeAtIndex` is suspicious)

I’d vote for `shape`, this is also what we use in the python world. Any opinions? @frcroth @jstriebel

**Comment by fm3** [comment]
jstriebel and I talked offline about this, and he convinced me that size is actually the better choice. It is also already used in the wk-libs python library in the bounding box class.

**Comment by frcroth** [comment]
Agree that it should be unified, but I do not have an opinion on which to use.

**Comment by fm3** [comment]
Alright, let’s go with `size` then wherever possible :)
