### ISSUE TITLE
Tree viewer: show open branch points

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#682]
Dear WK team (Georg?)

Would it be possible to show the open (i.e. so far un-branched) branchpoints in the abstract tree viewer? This would be super helpful if you lost track of your branchpoints. (maybe even in different color)

THANKS
m

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/682/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Duplicat e of #682
