### ISSUE TITLE
Lazy-load contents of "What's New" interface

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6851]
The olvy content seems to always load the content eagerly. In case of big images or gifs, this is a bit unfortunate since the requests can also make actual bucket requests stall.

**Comment by valentin-pinkau** [comment]
This would be great!

**Comment by fm3** [comment]
I wrote a duplicate of this today, not realizing that this exists. Some of the info I wrote in #7704 may be relevant to this. I included some measurements also.
