### ISSUE TITLE
Show owning organization in dataset info tab

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6922]
When looking at a dataset which belongs to another organization (could be a public dataset), there's no easy way of knowing which organization owns the dataset. This could be shown in the dataset info tab view. Probably, the same should happen for annotations.

![image](https://user-images.githubusercontent.com/2486553/225569800-fb0201b3-f8fc-430e-bf2a-ed0d9a7f6be4.png)

**Comment by dieknolle3333** [comment]
so the idea is to show the owning organization in every case in which I am allowed to view the dataset itself?

**Comment by philippotto** [comment]
Almost! If you are not allowed to see the dataset, an error page will be shown anyway. So, you don't need to take care of that case.

I would suggest to show the owning organization if and only if the current dataset or annotation does not belong to the organization of the activeUser (check out `APIUser->organization` and `APIDataset->owningOrganization` and `APIAnnotation->organization`).

Testing this can be a bit tricky, because you need to set up an additional organization locally. The easiest way to do this is to set `isWkorgInstance` and `mail.logToStdout` to true each in the application.conf. Then, log out and create a new account. An confirmation link should be printed in the console. Click the link and then finish the registration. Then, the second account will belong to a separate organization.
Then, switch back to the first account (or do this beforehand) and make a dataset public via the dataset settings. Then, open the dataset url with the second account so that the base condition is met.

Let me know if something is unclear!

**Comment by dieknolle3333** [comment]
So right now I added it in the dataset info tab in the dataset list view, when viewing the dataset and when creating annotations. (I attached pics to make sure I described this correctly)
![Screenshot from 2023-05-16 12-28-37](https://github.com/scalableminds/webknossos/assets/57364771/a133b496-a310-4ff5-a18d-ac6ae6fb2b74)
![Screenshot from 2023-05-16 12-28-51](https://github.com/scalableminds/webknossos/assets/57364771/8d8a1bc0-f0b8-480b-b5b4-0f58364d1cd7)
![Screenshot from 2023-05-16 12-29-02](https://github.com/scalableminds/webknossos/assets/57364771/d8075223-486f-4a34-acae-144637049605)
Are these the places you imagined?

**Comment by philippotto** [comment]
Yes, these places are correct :+1: 

Some things I noticed on the screenshots:
1) The icon should be horizontally aligned with the other icons (doesn't need to be pixel-perfect, but currently the offset is quite big)
2) Ideally, the color of the icons would match a bit better (currently, it's almost-white vs gray if I'm not being confused)
3) Your screenshots show the id "sample_organization". However, there's also a human-readable "Sample Organization" property somewhere (have a look at how it's done in the avatar menu, for example)

![image](https://github.com/scalableminds/webknossos/assets/2486553/ec4f73a7-bc4b-41b2-84cd-e5914c5240c9)
![image](https://github.com/scalableminds/webknossos/assets/2486553/aeb335db-bcad-437a-9742-b4549b78736d)
