### ISSUE TITLE
Disable editing of super voxel skeletons in skeleton mode

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6935]

**Comment by philippotto** [comment]
All your statements sounds very good :+1: Some thoughts on them:

> Ideally, if a user tries to modify an agglomerate skeleton and is not in proofreading mode, webknossos prompts the user to switch to the mode (automatically) or to cancel the action. Alternatively, an error toast is shown, informing the user to activate proofreading mode before manipulating an agglomerate skeleton.

I could imagine that preventing these actions can get tricky/cumbersome. I see the following options there:

- don't even dispatch the action (before dispatching check whether the proofreading tool is activated) or
- don't react to the action (reducers and sagas would not to do the check) or
- first dispatch something like "request_delete_edge" and then have a centralized saga do the check and then dispatch the actual action (would need to be implemented for a variety of action types)

For that reason, I'm wondering whether it would be alright to also allow proofreading in skeleton mode. I think, we needed the distinction before since we didn't know which skeletons were proofreading ones. But if we know that, proofreading in skeleton mode should be fine, too, right? The proofreading tool would still exist.

> Trees will likely need a read-only property that will need to be added to the protobuf definition. Currently, the connectome skeletons are made read-only by keeping them in a different location in the store. This prevents their nodes from being selected, though. They also don't appear in the skeleton list and cannot be organized into folders, for example.

I agree that we should probably adapt this then, too. However, this might not be a hard requirement for this issue. If it's easy, then, sure, let's do it.

> If only modifications of agglomerate skeletons should trigger proofreading actions, wk needs to identify agglomerate skeletons somehow. Maybe this would need to be an additional tree property (or it would replace the read-only property) thinking Or maybe trees could have a scope/function/type property that could track this and could be reused for the connectome view. The getTree family of functions could then take this property and only return trees with the respective scope/function/type - this would allow to choose which types of trees to show in which lists or which are available for certain actions.

I like the `type` idea (or maybe `role`?) :+1: I think, the read-only property wouldn't be necessary then, since the semantics could be derived from the role property. Also, read-only seems a bit weird naming-wise, since it can be mutated in the proofreading tool.

**Comment by daniel-wer** [comment]
> I could imagine that preventing these actions can get tricky/cumbersome.

Absolutely! I think we have experience with your first suggestion (e.g. to activate a mapping before loading meshes). I'd think it should be doable to implement something similar for the proofreading purpose. Also, there's only very few actions where we'd need to do that (delete edge, add edge).

> For that reason, I'm wondering whether it would be alright to also allow proofreading in skeleton mode. I think, we needed the distinction before since we didn't know which skeletons were proofreading ones. But if we know that, proofreading in skeleton mode should be fine, too, right? The proofreading tool would still exist.

Interesting idea! However, since starting to proofread has the side-effect of locking the activated mapping and disallowing any other segmentation modification actions, I think the user should at least be warned before processing the first proofreading action (if the user didn't deliberately activate the proofreading tool). I can imagine users modifying agglomerate skeletons without wanting to proofread. This boils down to the same issue as above, I think.

> I like the type idea (or maybe role?) +1 I think, the read-only property wouldn't be necessary then, since the semantics could be derived from the role property. Also, read-only seems a bit weird naming-wise, since it can be mutated in the proofreading tool.

Agreed, the `read-only` property would be weird and is no longer needed if we have some sort of `type` property.

**Comment by philippotto** [comment]
> > I could imagine that preventing these actions can get tricky/cumbersome.
> 
> Absolutely! I think we have experience with your first suggestion (e.g. to activate a mapping before loading meshes). I'd think it should be doable to implement something similar for the proofreading purpose. Also, there's only very few actions where we'd need to do that (delete edge, add edge).

Yeah, I'd also favor that route probably. It's probably only delete/add edge/node, right? renaming, changing color and even commenting nodes would be allowed, I assume.

> > For that reason, I'm wondering whether it would be alright to also allow proofreading in skeleton mode. I think, we needed the distinction before since we didn't know which skeletons were proofreading ones. But if we know that, proofreading in skeleton mode should be fine, too, right? The proofreading tool would still exist.
> 
> Interesting idea! However, since starting to proofread has the side-effect of locking the activated mapping and disallowing any other segmentation modification actions, I think the user should at least be warned before processing the first proofreading action (if the user didn't deliberately activate the proofreading tool). I can imagine users modifying agglomerate skeletons without wanting to proofread (which will no longer be possible with the proposal, but since the mapping lock is not reversable it shouldn't catch them by surprise). This boils down to the same issue as above, I think.

Hm, you are right. Once one is locked in, it doesn't matter anymore, but guarding the locking action in the first place needs something like the request_* pattern.
