### ISSUE TITLE
Add hint to teams page on how to add users to teams

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6958]
The teams list page does not feature a way to add users to teams. This is done in the users page. There should be an explanation and link on the teams page

**Comment by hotzenklotz** [comment]
I could even imaging having another "Add / Remove Users" action in the list. Either that open some sort of modal or links to the users admin page?

<img width="1613" alt="Screenshot 2023-04-13 at 17 03 13" src="https://user-images.githubusercontent.com/1105056/231802282-2b1ffaa8-0a6c-46f4-ad19-7c82fde643e4.png">
