### ISSUE TITLE
If the upper limit is infinity, the reported storage doesn't have a unit

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6987]
## Context
- on wkorg (set isWkorgInstance=true in `application.conf`)
- organization needs to have the power pricing plan (can be changed with pgadmin for example, but should be the default locally)
- also see discussion in https://github.com/scalableminds/webknossos/pull/6893#issuecomment-1484796152

## Current behavior
The organization page (http://localhost:9000/organizations/sample_organization) shows `0.0/infinity` as the used storage even when multiple GB are in fact used. The reason for this is that apparently TB is chosen as a unit which is then rounded to 0.0.

![image](https://user-images.githubusercontent.com/2486553/232703325-a4c3fd8a-077a-4346-9839-5aa1f4d8bec1.png)

## Expected behavior
There should be a (sensible) unit. In the above scenario I would expect something like `5.5 / infinity GB` or maybe `5.5 GB / infinity`?

## Hints for developing
The used storage can also be changed in the organizations sql table instead of trying to upload many datasets.

**Comment by dieknolle3333** [comment]
in the code, the unit is changed based on the pricing plan. Are you aware of the initial reason for this distinction?

```
     organization.pricingPlan === PricingPlanEnum.Basic
      ? `${(organization.includedStorageBytes / 10 ** 9).toFixed(0)}GB`
      : `${(organization.includedStorageBytes / 10 ** 12).toFixed(0)}TB`;
```

**Comment by philippotto** [comment]
Yes, this is because of our [pricing plan](https://webknossos.org/pricing). The basic plan provides 50 GB, I think, and everything above is in the realms of TB or above.
