### ISSUE TITLE
Implement Zarr v3 and sharding

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6993]
## Detailed Description
[Zarr v3 is now under consideration for approval](https://github.com/zarr-developers/zarr-specs/issues/227). I think it is fine for us to now start implementing read support for it. There might be smaller changes down the road, but I don't expect major changes. [Sharding](https://zarr-specs.readthedocs.io/en/latest/v3/codecs/sharding-indexed/v1.0.html) is not as far in the approval process, but again I think we can start implementing.
The OME-NGFF spec is not yet prepared for Zarr v3, but [I created a proposal](https://github.com/ome/ngff/issues/182) that we could use preliminarily.

There is a sample dataset that we can use for testing (doesn't have the OME metadata yet): https://static.webknossos.org/data/zarr_v3/l4dense_motta_et_al_demo

**Comment by fm3** [comment]
@frcroth Also compare https://github.com/scalableminds/zarrita
