### ISSUE TITLE
Neuroglancer Precomputed voxel_offset is not respected for sharded datasets

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7006]
When loading Neuroglancer Precomputed datasets, the header can have a `voxel_offset`, compare  https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/volume.md#info-json-file-specification

webknossos reads this voxel_offset, and holds it as `lazy val voxelOffset: Array[Int]`, but it is not used when loarding sharded datasets. Should be used when loading data etc.

One approach might also be to use the new transformations feature, compare #6748 (not sure if it is the easiest way, though)

**Comment by frcroth** [comment]
It is already used in `chunkIndexToNDimensionalBoundingBox`, but that method is not used in the sharded case
