### ISSUE TITLE
Ask users to confirm their email address

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7040]
We should introduce a protocol to let users verify that they can receive emails via the address they supplied during signup

**Comment by normanrz** [comment]
I think it would be cool to give users a few days times time to try wk before we force them to verify their email.

**Comment by frcroth** [comment]
What would "force them to verify their email" mean? No sign in possible after that time? Should a failed sign in then allow to resend the verification mail?

**Comment by normanrz** [comment]
> No sign in possible after that time?

Yes 

> Should a failed sign in then allow to resend the verification mail?

That would certainly be a nice UX!
