### ISSUE TITLE
Add tooltips to "Cancel" and "Reset and Cancel" for tasks

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7047]
Either improve the wording or add tooltips to clearly explain what these actions do. I'm not even sure what they do, to be honest.

See https://scm.slack.com/archives/CBV2Q463E/p1682696320484449?thread_ts=1682693336.277499&cid=CBV2Q463E for context.

**Comment by fm3** [comment]
related:  #7012

**Comment by philippotto** [comment]
Great find :+1: To summarize:

- “Reset” deletes any annotation work that was done in a specific task instance. In other words, the task is reset to its initial state. The assignment of the task will not change (i.e., the user that had assigned the task before will still be able to trace it again).
- "Reset and cancel" goes one step further and additionally removes the task from the user's account. The task will again be available for annotators via the “get a new task button” in their Dashboard. Note that the original annotator which was unassigned will **not** be able to get the task assigned (unless the annotator is an admin).
