### ISSUE TITLE
ZARR streaming sometimes returns empty buckets

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7073]
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Follow the steps from [this issue](https://github.com/scalableminds/webknossos/issues/7072)
2. Correct the mags in the datasource properties so that url and mag match
3. open the dataset
4. some buckets remain black

See screenshot:
![image](https://github.com/scalableminds/webknossos/assets/2486553/ba61e3e0-212e-43d0-a34c-090e372cbf84)

The back-end replies with bucket data (missing-bucket header is set to empty), but the received data is black.

**Comment by frcroth** [comment]
The black cubes are sometimes at different positions when reloading the data
