### ISSUE TITLE
Display existing artifacts for skipped tasks in voxelytics reports

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#7080]
## Detailed Description

Consider the case where artifact A is computed by workflow A. Then, there is a workflow B which reuses artifact A, but continues differently. Currently, the output paths, logs, and statistics for artifact A are only displayed in the voxelytics report for workflow A. It would be very helpful if it would also be displayed in the report for workflow B.

Apart from artifact reuse, this issue also occurs when iterating on a workflow. Every time a name is changed or another task is added to the workflow, a new voxelytics report is created losing all information about previously computed artifacts.

Displaying the logs and statistics for artifacts computed in another workflow could be challenging, because they exist per-run and there is a global run selection. One idea would be to only show the output paths for existing artifacts for skipped tasks and then link to the original workflow report where the logs and stats can be inspected.

**Comment by normanrz** [comment]
Note to self: Find duplicates of artifacts of skipped tasks by path. Add link to workflow to the task directly. Make output artifacts first tab.
