### ISSUE TITLE
Redesign info tab in right sidebar

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#7097]
We want to slightly change the design of the info tab in the right sidebar for datasets and annotations. 

Two mockups have been prepared to give a design direction and are to be found [on this Notion page](https://www.notion.so/scalableminds/Design-right-side-bar-info-tab-29d7adb8c76040e09e6dee8b1d2a863a).

The SVGs are attached here. 

![SVG info tab](https://github.com/scalableminds/webknossos/assets/83946334/a217af44-c32a-4338-8d02-d816c628cca2)

**Comment by hotzenklotz** [comment]
Related to #6739
