### ISSUE TITLE
In dev instances, separate datastore module from rest, to test this case?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7156]
In order to test problems that only arise when the datastore module and webknossos backend main module are separated, we should consider setting up the dev deployments in the same way. Do you think this would be complicated @normanrz ?

**Comment by normanrz** [comment]
Yes. That is quite complicated.

**Comment by fm3** [comment]
Ok then i’d say it is not justified to spend the effort. This kind of error happens maybe about once a year, and usually the kubernetes auto-switcher catches it.
