### ISSUE TITLE
Adding dataset in folder with rights while not having rights to organization root folder

### ISSUE THREAD

**Issue by frcroth** [scalableminds/webknossos#7199]
When a user does not have access rights to the root folder of an organization but access to a different (sub)folder, they can upload a dataset (which is automatically in the root folder) but then not access it (or even complete the import procedure). (additional context: https://scm.slack.com/archives/C5AKLAV0B/p1689069626934229?thread_ts=1689064935.050179&cid=C5AKLAV0B)

## Expected Behavior
Two options to fix this:
	- Store folder directly on upload so that the dataset is not uploaded into the root directory (preferred)
	- Disallow uploading generally when a user does not have access rights to the root directory

## Steps to Reproduce the bug

1. As the admin user, create a directory and give acess to a non-admin user via team permission (the non-admin user does not have rights to upload in the root directory)
2. Make the non-admin user team manager
3. As the non-admin user, try to upload a dataset in that folder

**Comment by fm3** [comment]
I agree that users with this rights configuration should be able to upload into the directories that they have write access for. The information in which folder the dataset should land should be propagated accordingly. I would have expected this to happen already, via `/datastores/:name/reserveUpload` but apparently there is some bug in that logic.

**Comment by fm3** [comment]
I double-checked that this works for upload, and this issue concerned with the addRemote aka put datasource variant
