### ISSUE TITLE
Supply Target Folder when adding Remote Dataset

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7215]
Starting in #7176 (still WIP as of this writing) the backend supports a `folderId` field for the add route called by the frontend in `storeRemoteDataset`. The frontend should use that (and show a folder selection menu just like in the upload view).

This way the normal folder rights management is also respected when storing remote datasets. Otherwise, the user can only add remote datasets when having write access to the root folder

Related: #7199

**Comment by fm3** [comment]
I extracted the relevant changes from #7176 to the new smaller PR #7221 to avoid this being blocked for so long. Could you add the front-end changes there?

**Comment by philippotto** [comment]
> Could you add the front-end changes there?

Done :)
