### ISSUE TITLE
Message about 3 characters is blanked if folder exists

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#7226]
If there is a folder in the dataset structure it doesn't show that you need to enter at least three characters to search for dataset

![image](https://github.com/scalableminds/webknossos/assets/1429753/754fd854-4435-4bdc-afb0-a83b17249af7)

**Comment by philippotto** [comment]
Thanks for the report! I fixed this in https://github.com/scalableminds/webknossos/pull/7232. Will be deployed in the next days probably.
