### ISSUE TITLE
For neuroglancer dataset info mismatches reality

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#7227]
You can see on the right that the dataset is 13088 in Z, but on the left you can see it's larger

![image](https://github.com/scalableminds/webknossos/assets/1429753/456031e6-ec07-4639-861c-83e3c02d70c0)

**Comment by fm3** [comment]
Hi @boergens and thanks for your report!

I think the displayed number is correct, if possibly displayed in a confusing manner.
The dataset does not start at z=0. It’s z range is from 14816 to 27904, meaning that the extent is in fact 13088 voxels.

I assume it may be a cropout from a larger dataset and someone wanted to preserve the z coordinates, which could be a reason it does not start at 0.

You can use the layer info tooltips in the left sidebar to see the exact bounding boxes of each layer:
![image](https://github.com/scalableminds/webknossos/assets/1390035/40662b5f-f0de-4aea-a52f-eb0bb4701e2c)

Hope this helps!

**Comment by boergens** [comment]
Very helpful, thank you @fm3
