### ISSUE TITLE
Support index_codecs in zarr sharding

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7241]
The Zarr sharding specification was recently changed to introduce `index_codecs`. This is the PR with the changes to the spec: https://github.com/zarr-developers/zarr-specs/pull/253 Briefly, the index is now treated as a regular array that needs to be passed through a configurable codec pipeline. The crc32c checksum is turned into a bytes->bytes codec. A limitation is that only fixed-size codecs (ie. no compression) may be used for the index to ensure that the size/offset can be determined beforehand.

**Comment by normanrz** [comment]
Also there is a new `zstd` codec coming: https://github.com/zarr-developers/zarr-specs/pull/256/files

**Comment by normanrz** [comment]
Also, the `endian` codec will be renamed to `bytes`. Probably best to accept/process both names for the time being.

**Comment by frcroth** [comment]
I can implement the zstd codec now, but it is not really specified how the checksum is used, so it would leave it for now.
