### ISSUE TITLE
Rename “isosurface“ to “adHocMesh” in code

### ISSUE THREAD

**Issue by frcroth** [scalableminds/webknossos#7243]
Ad-hoc meshing may be a better term, backend still uses "isosurface", which is a quite general term (MATLAB legacy?)

**Comment by fm3** [comment]
Yes, I’d say we should rename isosurface to adHocMesh in our code. I think we already decided to hide the term isosurface from the users. Adapting the code is the logical next step.

**Comment by philippotto** [comment]
> Yes, I’d say we should rename isosurface to adHocMesh in our code. I think we already decided to hide the term isosurface from the users. Adapting the code is the logical next step.

I agree :+1:

**Comment by frcroth** [comment]
Do it after #7244

**Comment by frcroth** [comment]
What is the scope of this issue? I did the renaming in the backend, which was straight-forward, however looking at the front-end, isosurface seems to have a slightly different meaning, because there are PrecomputedIsosurfaces and AdHocIsosurfaces, so I'm not sure what to do here.

**Comment by fm3** [comment]
@philippotto could you comment on that? My guess is that we can safely rename AdHocIsosurfaces to AdHocMesh – should we also rename PrecomputedIsosurfaces in the frontend to PrecomputedMeshes? Do you see any dangers/problems there?
