### ISSUE TITLE
Maintenance banner

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7257]
## Detailed Description
To inform users about upcoming or ongoing maintenance work, it would be great to add a maintenance banner to Webknossos. This would also be interesting for our dedicated instances that may have maintenance work on their local datastores.
I would imagine a simple banner above the top navigation bar that has some configurable text (via application.conf). We can discuss whether the banner should be user-dismissible or not.

**Comment by philippotto** [comment]
just fyi: there are already some maintenance routes with which we can signal that WK is in maintenance mode. If this is the case and the REST API errors, the user will be notified about it. If we want to extend this with a banner, this is probably a front-end-only job.

**Comment by normanrz** [comment]
Good to know. I forgot that we had such a maintenance mode. I think we should extend that so that a maintenance can be scheduled ahead of time. Also, there should be a configurable message that will be shown to users. And, webknossos doess't have to be locked down during a maintenance; it could be just a way to show users that something might be broken currently.

**Comment by fm3** [comment]
Just talked to norman again, here are the TODOs

 - add maintenances table (id, start time, end time, message)
 - add CRUD routes (no frontend for CUD required)
 - frontend should show upcoming and current maintenance in top bar (with different emphasis). Not only on requrest errors, as before

This can replace the current isMaintenance flag. (maybe still add a shortcut route to trigger a maintenance for the next 5 minutes starting immediately, similar to the existing route)
