### ISSUE TITLE
Gracefully handle dashboard load for deleted folder

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7265]
When the dashboard is loaded and the folderId that is selected by the user’s local storage does not exist anymore (e.g. because it was deleted by another user), The user gets a toast “the requested folder does not exist” (or similar), and is stuck with an empty-looking dashboard.

It would be nice if the frontend could in this case automatically redirect them to the root folder (or to whatever they would see if they had no foldrId in their local storage).

This frequently happens during development because of dropped db content, but I think it can also easily happen in production, when people delete folders.

**Comment by hotzenklotz** [comment]
Duplicate of https://github.com/scalableminds/webknossos/issues/7658?

**Comment by fm3** [comment]
yep, apparently this has been bugging me for some time 😅
