### ISSUE TITLE
Slider UX improvements

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7266]
The Antd sliders webknossos uses in many places offer rudimentary slider functionality. I am used to adobe lightroom’s sliders, which have some additional functionality, which are very helpful.

I would guess that wrapping the antd sliders to allow some of those would not be super difficult (but I may be entirely wrong)

 1. double click the slider knob to reset the value to the default
 2. mouse wheel on hover should change the slider value
 3. clicking on the slider (but not on the knob) already sets the value to that position, but if you keep the mouse pressed and move it, the knob no longer moves. It would be nice if you could move the slider in this way.

**Comment by philippotto** [comment]
My guesses are: 2 should be simple. 1 might be simple if we have the default at hand (probably not the case often). 3 is probably tricky to fix in a wrapper.

@dieknolle3333 you could have a look at 2 as a first step :) for 1 and 3, you could check how far you get without major road bumps.

**Comment by dieknolle3333** [comment]
next step: make default values accessible and reset them. maybe save initial value (upon page reload) and reset it there
