### ISSUE TITLE
Segment Index + Stats for ND volume annotations

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7276]
Segment Index that is stored in FossilDB should include additionalCoordinates. We should consider adding these to the key as well (just like the mag) or design a more elaborate lookup structure, depending on the queries we might get.

My guess is that the typical query is for a single spot along the additionalCoordinates axes.

**Comment by fm3** [comment]
@normanrz @philippotto I think we need some input here.

Currently the segment index maps from a segment id to a list of buckets(xyz).

To adapt this for ND we could make the value a list of buckets (xyz+additionalCoordinates). However, I’m not sure that can answer all relevant queries.

We could also include the additional coordinates in the key instead, so it would be (segment id + additional coordinates) → list of buckets (xyz)

That would support getting the full list for a particular additional-coordinates point (e.g. time-point).

However, on top of that, we might also implement an index for segment id to list of additional coordinates, where this segment exists at all.

This way, we could also answer queries about in which time-points the segment exists.

What do you think?

**Comment by normanrz** [comment]
> However, on top of that, we might also implement an index for segment id to list of additional coordinates, where this segment exists at all.

This could be done via an index scan, no?

Putting the additional coords in the key sound fine to me.
