### ISSUE TITLE
Segment list focus is not in sync with active segment

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#7311]
## Detailed Description
When clicking on an entry in the segment list a blueish overlay appears with "No mesh loaded" to highlight your are interacting/focussing with this segment. When clicking on a different segment in one of the viewports focus overlay is not updated accordingly. Neither is the old segment disfocused nor is the new entry highlight.

I constantly get lost because the two are out of sync.

<img width="406" alt="image" src="https://github.com/scalableminds/webknossos/assets/1105056/64bf9383-6602-4065-bbb4-3170ee9abb0b">

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
Just a note for implementation:
There's already a `CLICK_SEGMENT` action which could be listened to probably. `selectedIds` in `segments_view.tsx` would be the relevant counter part.

However, we should be careful with changing the selection. E.g., if the user uses multi-selection in the segments tab, it should not get overwritten if the user clicks on a segment in the data viewports. If no multi-selection exists, changing the "active" segment might be okay.

**Comment by dieknolle3333** [comment]
I am thinking about the case where the segment isn't in the list yet. It seems to be quite obvious to me that it should simply be added, so I'll build it that way in the first iteration. Let me know if you disagree :)

**Comment by philippotto** [comment]
> I am thinking about the case where the segment isn't in the list yet, and I want to jump to it from an entry in the context-menu in the view port. It seems quite obvious to me that it should simply be added to the list and , so I'll build it that way in the first iteration. Let me know if you disagree :)

Yes, this makes sense :+1:
