### ISSUE TITLE
[Proof Reading] Segment names get lost on split

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#7312]
## Detailed Description
When using the proof reading tool I constantly get lost. I renamed my main cell/segment to keep track of it, e.g. "Neuron #3". Whenever I execute a split there is a 50:50 chance that my main segment (which is considerably larger) is split of as a new segment with a generic "Segment 123" name. The remaining split-off segment (==trash) keeps the custom name, which is incorrect. 

Expected: The larger segment should always retain the same name (and color).

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by hotzenklotz** [comment]
Related to https://github.com/scalableminds/webknossos/issues/6470

**Comment by philippotto** [comment]
Closing in favor of https://github.com/scalableminds/webknossos/issues/6470.
