### ISSUE TITLE
[Proofreading] Active segment is not highlighted on hover

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#7314]
## Context
The currently active segment is not further highlighted when I hover over it in a different viewport or its 3D mesh. It is very hard to match different parts of the active segment across viewports/meshes without any slight highlighting.

## Expected Behavior
It should be highlighted like any other segment on mouseover.

## Current Behavior
The active segment has a constant color.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

0. Activate proofreading mode
1. Click on any segment
2. Hover over it in a different viewport or it's mesh
3. No highlighting

## Your Environment for bug

- Browser name and version: e.g. Chrome 116
- Operating System and version: e.g. MacOS
- Version of WEBKNOSSOS (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
Note to myself: Also take care that the active segment is highlighted better in proofreading (also without hover).

**Comment by daniel-wer** [comment]
Would be fixed by https://github.com/scalableminds/webknossos/pull/7654

**Comment by philippotto** [comment]
Should be fixed by #7654.
