### ISSUE TITLE
SAM for squiggly lines

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7339]
## Detailed Description
Add a new tool (or adapt an existing one) so that the user can use SAM with "squiggly lines" (e.g., an outline) to annotate a segment.

I think, @valentin-pinkau can provide details about how to use the embedding to achieve the above. This issue should be frontend-only.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by MichaelBuessemeyer** [comment]
Note: It looks like https://github.com/facebookresearch/segment-anything/blob/main/notebooks/onnx_model_example.ipynb under Example mask input shows how to do the inference with a mask
