### ISSUE TITLE
Allow ad-hoc mesh rendering for visible but ineditable segmentation layer

### ISSUE THREAD

**Issue by dieknolle3333** [scalableminds/webknossos#7356]
Within a visible but ineditable/locked segmentation layer, ad-hoc mesh rendering throws an error. 

In the network tab it's visible that the tracing store is called, but according to @fm3 it should actually be the datastore. The faulty request appears in `isosurface_saga`, where `useDataStore` is set and afterwards when `getChunkPositionsFromSegmentStats` is called. 

## Steps to Reproduce the bug
1. Create an empty segmentation layer in a dataset with a given segmentation
2. Activate the given segmentation
3. Try to load meshes ad-hoc from segments tab

**Comment by fm3** [comment]
Trying to clarify a bit:

Dataset view mode works, volume annotation layer works.

The relevant case is an annotation *that has* volume annotation layers, but also shows on-disk segmentation layers. For those, the request should go to the datastore, but currently is sent to the tracingstore (which does not recognize the sent name as a tracing id)

**Comment by dieknolle3333** [comment]
may be fixed by #7333

**Comment by philippotto** [comment]
> maybe fixed by https://github.com/scalableminds/webknossos/pull/7333

Now that #7333 is merged, do you think we can close this issue? Or is this still a problem?

**Comment by fm3** [comment]
works for me now :)
