### ISSUE TITLE
Explore/Import from Neuroglancer URI

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7385]
It would be nice if you could just paste the URI of a dataset viewed in neuroglancer into wk and have it searched for explorable dataset layers.

**Comment by frcroth** [comment]
We need to determine what we want to read:
Here is an example Neuroglancer URI JSON:
```
!{"dimensions":{"x":[4e-9,"m"],"y":[4e-9,"m"],"z":[3e-8,"m"]},"position":[100074.5,100000.5,4998.23583984375],"crossSectionScale":1,"projectionScale":262144,"layers":[{"type":"image","source":"precomputed://s3://bossdb-open-data/morgan2020/lgn/em","tab":"rendering","opacity":0.46,"blend":"additive","name":"em"}],"selectedLayer":{"visible":true,"layer":"em"},"layout":"4panel","selection":{"layers":{"em":{"annotationId":"data-bounds","annotationSource":0,"annotationSubsource":"bounds"}}}}
```
We could read:
- Dimensions (they may be inferred from the dataset)
- position?
- layers with name, type and source uri
- opacity of layers
- blendmode of layers
There are also some additional properties, I don't understand all of them. What should be read within the scope of this issue?

**Comment by fm3** [comment]
I’d say layer name, type and source uri should be enough for the moment :) Thanks for looking into this!
