### ISSUE TITLE
Add segment counts to dashboard

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#7431]
## Detailed Description
Similar to the skeleton statistics (node count, tree count etc) we should show the segment count of an annotation/task in the various lists and views:

- Dashboard > Annotations
- Admin > Tasks > Sub-View for the annotations per Task 
- (Maybe in the right-hand side info panel of an annotation)

This requires a little bit of frontend work but mostly backend. The segment counts could be cached using a similar structure as for the skeleton nodes.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Open Questions:
 - [ ] How should this behave for annotations with multiple volume annotation layers – should the segment counts be added, merged (by ids) or the largest count displayed, or should the list show all segment counts of all layers separatelyß
 - [ ] How should this behave for volume annotation layers with fallback segmentations? The fallback segmentation may have millions of segments. My guess would be that we want to show the number of segments in the list in the segments tab? So, all that have been “selected” or brushed, right?

**Comment by hotzenklotz** [comment]
>  How should this behave for annotations with multiple volume annotation layers – should the segment counts be added, merged (by ids) or the largest count displayed, or should the list show all segment counts of all layers separately

all segments

> How should this behave for volume annotation layers with fallback segmentations? The fallback segmentation may have millions of segments. My guess would be that we want to show the number of segments in the list in the segments tab? So, all that have been “selected” or brushed, right?

For skeletons from automated tasks, we show the full node count. I guess we should do the same for segments.

**Comment by fm3** [comment]
> all segments

Could you clarify which of the options you mean (or another altogether)? Should it show multiple numbers in case of multiple layers?

> For skeletons from automated tasks, we show the full node count. I guess we should do the same for segments.

Sounds fair. Note that we can only know this full segment count for datasets with a segment index file. That means that for annotation layers with fallback segmentations that don’t have a segment index file, the number won’t be available.

**Comment by hotzenklotz** [comment]
> Note that we can only know this full segment count for datasets with a segment index file. That means that for annotation layers with fallback segmentations that don’t have a segment index file, the number won’t be available.

That's ok.

**Comment by fm3** [comment]
Ok cool, we can do that :) Unfortunately, the other question still remains unclear to me. For annotations with multiple volume annotation layers, would you expect

(1) multiple segment counts shown, one for each layer?
(2) the sum of the segment counts
(3) the merged segment counts (total number of distinct segment ids across all layers)
(4) the largest count of the layers
(5) something else?

@normanrz @philippotto Maybe you also have a preference?

(3) is certainly the most complex to implement, since the layers can’t just report their individual segment counts but have to report enough information for this merging

**Comment by normanrz** [comment]
I would expect (2) and maybe a onhover-tooltip that lists per layer

**Comment by philippotto** [comment]
I agree with norman.

> (3) the merged segment counts (total number of distinct segment ids across all layers)

This wouldn't make much sense to me as a default, since there's no guarantee that equal ids mean equal things. The segment objects (that can be named) are stored separately. Thus, I'd also count these segments separately.
