### ISSUE TITLE
Use GPU in Render Animation Worker Job

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7445]
## Detailed Description
As a follow-up to #7348, speed might be improvable by using the GPU in the worker job.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by hotzenklotz** [comment]
Time measurements for a single frame based on job `655b4d0e01000026094d9893__render_animation__1700482319547`

- Cycles @ Blender 3.3 CPU [NYT-Docker](https://github.com/nytimes/rd-blender-docker) on Humerus : 01:13.68
- Eevee @ Blender 3.6.5 CPU on ???: 03:50.79
- Cycles @ native Blender 3.6.5 CPU Humerus: 01:05.13
- Eevee @ Blender 3.6.5 GPU Euphorix: 00:01.12

**Comment by philippotto** [comment]
> * 
> * Eevee @ native Blender 3.6.5 GPU Euphorix: 00:01.12

Awesome! So, very good news, right?

**Comment by hotzenklotz** [comment]
> Awesome! So, very good news, right?

Well... we already knew that GPU support is quick. But the WK worker is no running a on a GPU server. Nor was this in Docker....

**Comment by hotzenklotz** [comment]
Blender had a peak usage of slightly more then 900MB of VRAM for my test dataset (2 large meshes). 

<img width="725" alt="image" src="https://github.com/scalableminds/webknossos/assets/1105056/056ca35e-1074-4e3b-9287-0992b45f308d">
