### ISSUE TITLE
"Announce" datasets before they are placed on disk directly

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7457]
When non-privileged users (no dataset manager or admin) place a dataset on-disk, they are not able to view that dataset in Webknossos because they are not allowed to make the necessary team assignment.

One solution would be to announce a dataset via the API before it is written to disk. In that case, webknossos would already have a database entry for the dataset with a team assignment when the dataset is being reported by the datastore. This could be allowed for team managers.

**Comment by fm3** [comment]
Could reuse reserveUpload – how would users trigger this? In the UI?

**Comment by normanrz** [comment]
> how would users trigger this? In the UI?

Preferably via the Python libs
