### ISSUE TITLE
Expand Skeletons with SAM

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7541]
## Detailed Description
Given a skeleton, SAM could be used to annotate volume data for all nodes and the edges between the nodes. It remains to clarify how SAM should be invoked:

- simply invoke SAM with a point for each node
- should a bbox be passed to SAM? if so, how large?
- should the user label the sections where the nodes are and then the feature is basically interpolating along the edges (similar to #7540)?

The first option is certainly the simplest. Let's try this first.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by MichaelBuessemeyer** [comment]
We decided against this feature as SAM doesn'T handle point input so well and the feature not offering enough value
