### ISSUE TITLE
Split supervoxel from all other segments

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7607]
The proofreading tool currently supports split and merge operations. We should also add a "Split from all other segments" operation to the context menu. The supervoxel that was rightclicked should then have no edges in the editable mapping, anymore.

**Comment by fm3** [comment]
I’d propose a new route similar to min-cut, called neighbors,

that takes
 - a position
 - a mag
 - an agglomerate id

and returns
 - the segment id at that position
 - the set of direct neighbors of that segment in the graph, specified by
   - their segment id
   - their position

Then the frontend can construct split update actions that together should perform the desired operation. What do you think @philippotto ?
