### ISSUE TITLE
Zoom hotkey hint could be improved on macOS

### ISSUE THREAD

**Issue by dstansby** [scalableminds/webknossos#7652]
## Detailed Description
After opening a dataset, the hotkey hint for zooming shows "Alt + {scroll mouse}":
<img width="184" alt="Screenshot 2024-02-24 at 22 33 47" src="https://github.com/scalableminds/webknossos/assets/6197628/bccd804a-fbf2-4556-a718-aa68941e9de4">

Macs don't have an "Alt" key though - it would be nice to detect if on macOS, and if so show "option + {scroll mouse}" instead.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by philippotto** [comment]
Thanks for opening this issue. Should get fixed with #7678.
