### ISSUE TITLE
Remove (or update) outdated static.webknossos.org/docs/client_doc

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos#7656]
Hi,

just fyi:

we internally had a discussion about mesh visualization in webknossos and stumbled across this side:
https://static.webknossos.org/docs/client_docs/webknossos/mesh_visualization.html

after some back and forth without finding the promised features we realized that this must be a left over from an old documentation, since the corresponding content was deleted a couple of years ago:
https://github.com/scalableminds/webknossos/commit/082e4c37b3c9980854d0cba1347c98fded78cb5d#diff-4322b6d02f46ba22c4939a40a95df8e931ca5d40cad92eaf10aa001ad9a78f11

You might want to consider removing this site (https://static.webknossos.org/docs/client_docs) all together or adapt your CD pipeline such that it is updated together with https://docs.webknossos.org/webknossos/ 

Best wishes,
Eric

**Comment by hotzenklotz** [comment]
Thanks for letting us know. We will remove it and adjust the deployment settings.
