### ISSUE TITLE
URL-based remote dataset import

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7686]
## Detailed Description
We should have a URL-based method for exploring and automatically importing data into Webknossos. That could in the form of `https://webknossos.org/import?uri=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr`.
If logged in the dataset will automatically be imported with a guessed name. If the the import cannot be done automatically, the explore UI should be shown. If not logged in the login/signup screen should be shown and import queued to after login/signup.

## Context
Such a URL-based import allows an easy integration for other websites that link to OME-Zarr datasets. It is the technical basis for a `Open with WEBKNOSSOS...` button.

**Comment by normanrz** [comment]
Ideally, we could provide a "view" of the dataset even without logging in. Not sure how that would work in our infrastructure.

**Comment by dieknolle3333** [comment]
> Ideally, we could provide a "view" of the dataset even without logging in. 

is there a suitable organization where the dataset could be stored in in that case? From what I see in the code this is what the user is needed for currently.

**Comment by normanrz** [comment]
Let's skip that for now. I think that would be a big lift both on the front and backend.
