### ISSUE TITLE
Annotation description resets itself if deleted until empty

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos#7699]
## Context
I tried to edit an annotation description via the webknossos webinterface.

## Expected Behavior
I can delete the default value "[no description]" and then write whatever I want.

## Current Behavior
As soon as I delete the last character from the default string, it resets to the default string.
State before:
![Capture1](https://github.com/scalableminds/webknossos/assets/36883188/3280e035-b878-48d6-86a5-3ee45edbcd58)
If I delete remaining bracket:
![Capture2](https://github.com/scalableminds/webknossos/assets/36883188/2312a038-3d5c-46f8-b212-5cff2fe47226)

Another problem: I can not edit multiple characters at a time. Once I edited a character within the string (not at the end). The cursor jumps to the end.

No need to mention that this is super annoying ... 

## Steps to Reproduce the bug
try to edit an annotation description yourself ...

## Your Environment for bug
- Browser name and version: Firefox 123.0.1 (64-bit)
- Operating System and version: Microsoft Windows [Version 10.0.19045.4046]
- Version of WEBKNOSSOS (Release or Commit): Version 23.04.02

**Comment by hotzenklotz** [comment]
Thanks for reporting. Will have a look.

**Comment by hotzenklotz** [comment]
@erjel I fixed the weird jumping cursor and the "empty textbox" behavior. The fix will be deployed as part of your next monthly update.
