### ISSUE TITLE
Min/max need to support negative values for signed datatypes

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7715]
Webknossos supports signed datatypes such as float. However, the min/max settings below the histogram don't accept negative values.
![2024-03-25 15 13 20](https://github.com/scalableminds/webknossos/assets/335438/e29c7975-abcf-43ec-93dc-b823c6510305)

**Comment by normanrz** [comment]
@philippotto Does the rendering support negative float values already?

**Comment by philippotto** [comment]
I think, the rendering itself should work fine wiht negative floats.
