### ISSUE TITLE
Add banner "Upgrade version" for self-hosted when version is older than 6 months

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#7745]
## Detailed Description
Create a banner similar to the one in the mockup below. The banner should appear as soon as the self-hosted version of WEBKNOSSOS has not updated since 6 months. It should be possible to close it, but it should appear again with every new session, until a newer version is used (sessionstore). 
Text: You are using an old version of WEBKNOSSOS. Switch to webknossos.org for automatic updates and exclusive features! 
Button: Learn more (Links to [https://webknossos.org/self-hosted-upgrade](url))
![banner top self hosted](https://github.com/scalableminds/webknossos/assets/83946334/e036ae7b-98d7-4de0-a54c-1d3a33e1e2af)

## Context
When users of the self-hosted version of WEBKNOSSOS haven't upgraded since 6 months, this banner should appear, motivating them to switch to webknossos.org. The button "Learn more" will lead them to a landing page where the advantages of wk.org compared to the open-source version are listed.

**Comment by philippotto** [comment]
Implementation note: could be done similarly to the maintenance banner. /api/buildinfo contains commit date that could be parsed.

**Comment by fm3** [comment]
Should the user be able to click this away? Do we need to store the info that they clicked it away? I guess the `novelUserExperienceInfos` block could be used for that.
