### ISSUE TITLE
Update the text in the "Upload Dataset" Screen in the Open Source version

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#7760]
## Detailed Description
Change the text displayed on the "Upload Dataset" screen to the following:
"Drag and drop your files in WKW format.
Need to upload files in other formats? Switch to [webknossos.org](http://webknossos.org/) for more file types support and automatic conversion.
[Learn more!](https://webknossos.org/self-hosted-upgrade)"

<img width="1664" alt="Screenshot 2024-04-15 at 14 23 51" src="https://github.com/scalableminds/webknossos/assets/83946334/08540b59-62ca-4694-b185-596eee5165b4">

## Context
We want to encourage users of the open-source version to consider migrating to webknossos.org. The "Upload Dataset" screen, which currently accepts only WKW format, is an ideal place to inform users about the extended capabilities available on webknossos.org. Highlighting the support for more file formats on our full platform can motivate users to explore and potentially switch.

**Comment by philippotto** [comment]
What about instances that we manage for our clients and that don't have a worker? I think in this case we shouldn't point to webknossos.org, right? (because they pay for the on-premise version)

**Comment by Albane-dlv** [comment]
Yes you're right, this change should only be made for the self-hosted, open-source version (so not for our clients).

**Comment by philippotto** [comment]
Ok, for the implementation, I'm not sure how we can differentiate between self-hosted open-source and managed by us. @fm3 Maybe you have an idea for this? Could be an extra field in the application.conf, but I'm not sure whether this is ideal...

If all managed installations had a worker, we could make the distinction by checking for the extence of a worker..

**Comment by fm3** [comment]
I wouldn’t go for anything more involved than an application.conf switch. It’s an open-source project, so if self-hosting users want to disable “encouraging messages”, I’d say that we should let them. The act of changing this config setting will already have them considering the possibility of switching to webknossos.org. What do you think?

**Comment by philippotto** [comment]
Yes, I agree, then let's add a property to application.conf. Maybe `recommendWkorgInstance`? (similar to `isWkorgInstance`)
