### ISSUE TITLE
Reloading the page should retain collapsed-state of (segment) groups

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#7825]
Reloading the page should retain collapsed-state of (segment) groups. Also meshes should re-appear or at least be listed.

**Comment by MichaelBuessemeyer** [comment]
@philippotto Should I try working on this? 
I already found that I need to modify the protobuf files for this. the backend part seems rather easy if we only want to persist in the collapsed state. Keeping the meshes might get more complicated (haven't looked into that)

**Comment by philippotto** [comment]
> @philippotto Should I try working on this?
I already found that I need to modify the protobuf files for this. the backend part seems rather easy if we only want to persist in the collapsed state.

Yes, I think, this would be cool if you have the capacity for it. Maintaining the boolean per group should be easy to build.

> Keeping the meshes might get more complicated (haven't looked into that)

Yes, let's defer this for now.
