### ISSUE TITLE
Triggering proofreading actions on precomputed meshes calculated for a mapping should be disabled

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7868]
The user manually loaded some precomputed meshes, and then selected »merge with active« in the 3d viewport.

This should not be allowed for precomputed meshes that stem for a meshfile that was not computed for the unmapped data.

**Comment by dieknolle3333** [comment]
I tried to reproduce this by loading precomputed meshes and afterwards switching to the proofreading tool, but for me the action "Merge with active segment" was disabled and the tooltip was "The mesh wasnt loaded in proofreading mode. Please reload the mesh." Can you eloborate (here or on slack) what I was missing to get to this state?

**Comment by fm3** [comment]
Hmm, sounds like the issue may already be solved.

Do you have a dataset with a meshfile that was computed for a mapping? Otherwise, I can supply one for testing (but only next week, probably).

If so, could you select that meshfile in the proofreading mode, and try to load some meshes? This should probably also be forbidden in this case (since proofreading only makes sense on meshfiles that were computed for the oversegmentation). If that still works, and you can then click merge-with-active-segment on those meshes, then that’s this issue.

Hope this clarifies things a bit, let me know if you need more input and I’ll respond on monday :)

**Comment by dieknolle3333** [comment]
I see. I used an oversegmentation mesh file. I didnt find a dataset with a meshfile that was created for a mapping, so I'd be glad if you could provide me with the mesh file :)

**Comment by fm3** [comment]
I put one at https://www.notion.so/scalableminds/Test-Datasets-c0563be9c4a4499dae4e16d9b2497cfb?pvs=4#10ab51644c63805faa63c2bd1dec22c1

**Comment by dieknolle3333** [comment]
@fm3 Do I understand it correctly that it shouldnt be possible to load the meshes from the mesh file in the first place in the given scenario?

**Comment by fm3** [comment]
Good question. We haven’t really talked about that yet. I’d say disabling the actions is probably enough for the moment. It will keep people from trying proofreading and being confused about why the IDs don’t match. It will hopefully point them towards creating an oversegmentation meshfile, or proofreading without meshes.

Long-Term, I guess, we could clear all non-oversegmentation-meshes once people go to the proofreading tools, and refuse to load them again then. But I’m not sure what the best flow would be for that. Let’s defer that.
