### ISSUE TITLE
`Compose a dataset from existing dataset layers` does not function

### ISSUE THREAD

**Issue by arentkievits** [scalableminds/webknossos#7888]
## Context

I'm trying to compose a dataset from existing dataset layers with the "Add dataset" button.

## Expected Behavior

The dataset should be created when pressing "Create dataset". Instead nothing happens. 

## Current Behavior

Nothing happens when pressing the button, the page remains as it is. 

https://github.com/scalableminds/webknossos/assets/63721181/3095d1fa-e0d4-47db-ad9e-a9d6e58dca7b

## Steps to Reproduce the bug

1. In the datasets menu, click on "Add dataset"
2. Go to the "Compose from existing dataset layers" tab.
3. Create a new dataset name, add existing layers from other datasets.
4. Press "Create Dataset" at the bottom.

## Your Environment for bug

- Bug in Chrome version 125.0.6422.176, Firefox Version 127.0 (64-bit)
- Operating System: Windows 10
- Version of WEBKNOSSOS (Release or Commit):  24.06.0

**Comment by philippotto** [comment]
Hi @arentkievits, thanks for your bug report! It looks like the feature fails currently if only one dataset is used for the composition. Are you trying to use the composition feature to shallow-copy a dataset while omitting some of its layers?

**Comment by philippotto** [comment]
I'm glad you found a workaround! I fixed the actual bug in the meantime. The change will go live today or tomorrow morning.

**Comment by philippotto** [comment]
The fix is now live. Thanks again for the report!
