### ISSUE TITLE
Create Segments for all ids in a bounding box

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7906]
## Detailed Description
The bounding box tab could get a feature that registers segments for all ids that are within that bounding box.

## Implementation
See code snippet in the context link. We need to be careful with large bounding boxes, because this could become very slow.

## Context
https://scm.slack.com/archives/C5AKLAV0B/p1719482479270149

**Comment by dieknolle3333** [comment]
additionally, a context menu should be created for bounding boxes. export data, go to center and delete should be moved there, as well as the new "register all segments in the bounding box" entry
