### ISSUE TITLE
Copy to my account does not transfer user bounding boxes under certain conditions

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#7907]
## Context

An annotation with multiple boxes is not properly copied to another account, as the user bounding boxes are dropped. 

## Expected Behavior

The bounding boxes should be included in the copy.
## Current Behavior

The bounding boxes are not included in the copy.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

These steps are just a guess and might not be correct:
1. Create an annotation without a skeleton layer.
2. Add some bounding boxes.
3. Make the annotation visible internally
4. Open the annotation as another user of the orga with access to the dataset.
5. Copy the annotation over to one's account.

**Comment by fm3** [comment]
We did a bit of digging but could not reproduce this anymore, even with the annotation the original bug report was for. Feel free to reopen if it happens again, then we’ll have a new clue to investigate.
