### ISSUE TITLE
Disable AI models for 2D and ND datasets

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#7953]
## Context
Our AI models are configured and tuned for 3D EM datasets. It does not work well on 2D datasets (and was never intended for those).

Example segmentation of some 2D dataset:  <img width="801" alt="Screenshot 2024-07-26 at 11 16 47" src="https://github.com/user-attachments/assets/a1579b8a-696b-4edd-9ed6-ba9e57b03c50">

See https://scm.slack.com/archives/CMBMU5684/p1721985399703099?thread_ts=1721318145.073349&cid=CMBMU5684

## Expected Behavior
Probably add some validation before launching any of the AI features. 2D and ND datasets should probably be denied from running any AI inference. 

Perhaps also include guards against weird datatypes, e.g. `uint24`. IIRC, the AI inference only works with `uint8` (please double-check).

Have a look at the "Create Animation job" modal. That includes validation against 2D and ND datasets.

## Current Behavior
The AI job runs on the 2D dataset but the output is not useful. All voxels were merged into one segment per chunk and agglomerated into one single segment.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

See https://scm.slack.com/archives/CMBMU5684/p1721985399703099?thread_ts=1721318145.073349&cid=CMBMU5684

## Your Environment for bug

- Version of WEBKNOSSOS (Release or Commit): Version: 28878 (Server is currently at 28881!)
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by dieknolle3333** [comment]
Are there any more features than those that can be accessed via the "AI Analysis" button? Would it work if I simply disable said button with a fitting tooltip or should the button disappear for 2D and ND datasets?
![image](https://github.com/user-attachments/assets/2ae8113e-828c-44d7-a8cf-e6561899bcb0)

**Comment by dieknolle3333** [comment]
note to self: button shouldnt disappear, disable or error on start

**Comment by dieknolle3333** [comment]
https://scm.slack.com/archives/C5AKLAV0B/p1722361416801889
latest requirements: disable uint24
