### ISSUE TITLE
Remove superfluous `_type` field from zarr codec jsons

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7968]
Now that we are starting with zarr3 streaming, we should really get rid of the auto-generated `_type` field in the json-serialized CodecConfiguration classes.

If we can’t get the json macros to skip them, we’ll have to postprocess the json.

![image](https://github.com/user-attachments/assets/a85cd863-32f2-4607-b87e-8422b9a04753)

**Comment by MichaelBuessemeyer** [comment]
I would push this: @brokkoli71 encountered an error when trying to use zarr3 streaming with tensorstore (some zarr client) which complains about the additional `_type` field with an error
