### ISSUE TITLE
Allow to delete/archive voxelytics workflow reports

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7973]
Occasionally, users want to delete voxelytics workflow reports to avoid sharing secret information.
We should have a look how such a functionality would fit in.

**Comment by Tobias314** [comment]
For internal use, there is now an SQL script available under:
[https://www.notion.so/scalableminds/Webknossos-Move-Voxelytics-Runs-Between-Orgnizations-fd44fef189224589b699c6287f9d4860?pvs=4](https://www.notion.so/scalableminds/Webknossos-Move-Voxelytics-Runs-Between-Orgnizations-fd44fef189224589b699c6287f9d4860?pvs=4)

**Comment by fm3** [comment]
I’d say a delete route makes sense. Delete by hash. Only allowed for superusers. Use hard DELETE in postgres. This needs to cascade to all voxelytics tables.
If the _voxelytics_workflowHash is referenced in the jobs tables, set it to NULL there.

Add a button in frontend in workflow view, with confirm modal.

an isDeleted boolean would not work well, because the hash would stay reserved. I think a hard delete is ok.
