### ISSUE TITLE
Support Zarr3 / OME NGFF V0.5 Exploration

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#7978]
Currently, the backend only supports exploring NGFF version 0.4. It would be nice to support version 0.5. At least the current backend expiration code of the NgffExplorer reads like it only support the internal zarr format and not zarr3. Same goes for OME NGFF version 0.5 which is currently being implemented for zarr streaming afaik not yet explorable.

Here is an OME version 0.5 example: https://ngff.openmicroscopy.org/rfc/2/index.html#examples

**Comment by normanrz** [comment]
The 0.5 spec is pretty much stable now and will be released soon: https://ngff--242.org.readthedocs.build/latest/index.html

**Comment by frcroth** [comment]
@normanrz Is there test data for v0.5 datasets?

**Comment by normanrz** [comment]
Yes, Webknossos actually exposes them:
https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M1/color/zarr.json
