### ISSUE TITLE
[OX-637] Bulk list of admin interactions

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#8]
<b><i>[reporter="autoreporter", created="Tue, 7 May 2013 16:55:24 +0200"]</i></b>

<p>Today, we needed to find out who created a specific task.<br/>
Is it possible to access a log of all admin interactions?<br/>
Like:<br/>
2013-05-07 16:43: boergens@neuro.mpg.de task 054e3a changed instances to 3<br/>
That would be good</p>

<p> Reported by: Kevin Boergens (boergens@neuro.mpg.de)</p>

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/8/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
I don't think this is relevant, anymore.
