### ISSUE TITLE
It is no longer possible to horizontally scroll the skeleton tab with many skeletons

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#8000]
## Context

When having many skeletons the horizontal scrollbar is pushed out of the skeleton tab thus making scrolling horizontally impossible. However in case some skeletons have long names this should still be possible IMO.

## Expected Behavior

The horizontal scrollbar should always be accessible as long as there are long skeleton name present in the skeleton tab.
## Current Behavior

The scrollbar is pushed outside the skeleton tab. See the demo video below.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

For demo video see: https://scm.slack.com/archives/C5AKLAV0B/p1723722807775539

## Your Environment for bug
nothing special :)

**Comment by dieknolle3333** [comment]
in #8148 a linebreak was introduced for long skeleton names. is this issue still up-to-date?

**Comment by MichaelBuessemeyer** [comment]
Jup, thats correct :dancers: . Maybe we should have linked this issue to https://github.com/scalableminds/webknossos/pull/8148 :+1:

=> Closing :tada:
