### ISSUE TITLE
Improve BBox Selection Mechanism

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#8004]
## Detailed Description
Currently, it is only possible to select a bounding box as active and highlight it in the bbox tab in the ortho views while the bbox tool is active. It would be nice to be able to select bbox also in move tool; just like tree nodes. Moreover, BBox selection in 3d viewport would also be very awesome.

From (high-pri + easy) to (low-pri + medium):

- [x] Right-click on a bbox should also have "Focus in BBox tab" entry
- [x] Allow to select a bbox in move tool via `ctrl + click` (just like in bbox tool)
- [ ] Allow to select a bbox in 3d viewport

## Context

Use cases:
- easier navigate bboxes
- No need to be afraid of accidentally moving or creating a bounding box bc. the selection works also in move tool and not only when bbox tool is active.

**Comment by dieknolle3333** [comment]
> Allow to select a bbox in move tool via ctrl + click (just like in bbox tool)

AFAICT it is possible to select a BBox with click and with ctrl+click. Should it be possible to select a BBox with both interactions/combinations while using the move tool?

**Comment by MichaelBuessemeyer** [comment]
I'd say keep it similar to how we handle tree nodes in the move tool to make the behaviour consistent. As node selection works in the move tool wich click & click+ctrl, I would go for both.

**Comment by dieknolle3333** [comment]
I mean, if it works on click then ctrl+click will be working too, except if we actively prevent it :sweat_smile:
