### ISSUE TITLE
Rename organization_name to organization_id in worker args

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#8038]
Follow-up for https://github.com/scalableminds/webknossos/pull/7386
(We didn’t want to change the worker in that PR as it is already pretty big)

Should be adapted both in JobController and AiModelController (and of course the worker side)

**Comment by fm3** [comment]
@MichaelBuessemeyer would it be simple to include this in #8075 ? As I understand, you are already slightly changing the worker arguments there?

**Comment by MichaelBuessemeyer** [comment]
Sure let's go. Sounds easy to me :tada:
