### ISSUE TITLE
Register all segments in this bounding box should be mag-aware

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#8044]
## Detailed Description

- The "Register all segments in this bounding box" functionality has an upper limit on the volume in vx the bounding box is allowed to have. The limit should be in voxels _in the current mag_ and the segmentation in the current mag should be used.

## Context

This would allow to register segments for large objects, for example somata or nuclei which is usually done in a much coarser mag, for example mag 32. With the current mag-unaware limit this is not possible at all.

**Comment by daniel-wer** [comment]
One more issue I noticed is that the functionality always uses the first segmentation layer, regardless of whether it's visible or not. Other functions operating on segmentation layers, preferably select the visible segmentation layer. Maybe this is a quick fix, otherwise I'll create a separate issue for this.

**Comment by philippotto** [comment]
> Maybe this is a quick fix, otherwise I'll create a separate issue for this.

Should be a quick fix afaik :+1:
