### ISSUE TITLE
log all data loading errors

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#8081]
Bucket requests always return 200, if something went wrong during loading, the array is all-black and the MISSING-BUCKETS header is set. However, no error information is contained.

There is already good error logging in `BinaryDataService.handleBucketRequest` for everything that happens inside of `BucketProvider.load`.

However, if the errors occur after that, e.g. while applying the agglomerate mapping, nothing is shown. This error logging should be moved to `handleDataRequests` or another type of error logging should be created at that level there. Maybe include the errors in the response headers? (Or is that too verbose/can sensitive information be leaked?)

**Comment by frcroth** [comment]
Log errors in "convertIfNecessary" (might need to give request as argument for more info in log)
