### ISSUE TITLE
Problems with shared datasets being locked

### ISSUE THREAD

**Issue by rabiesrisk** [scalableminds/webknossos#8086]
Hi Yall!

I uploaded a dataset, but then encountered problems while trying to share the dataset. I made it public, used the share link, and my collaborators were receiving an error that said "failed to create annotation." When I shared the annotation itself with them (and edited the share settings), they were able to access the annotation, but it always says "locked by unknown user," even when no one else had the annotation open. When I am trying to annotate, it does lock when one of my collaborators is on the same annotation, but the locked status goes away right away when the tab is closed. I am unsure how to proceed, thank you in advance.

Jessica

**Comment by fm3** [comment]
Hi Jessica and thanks for your report,

My guess is that the permission / error messages are not clear enough, I hope we can figure out what exactly is going on here so we can improve them.

I would suspect that your collaborators created their WEBKNOSSOS accounts individually, and not using the invite feature. That way, they would usually create an “organization” of their own. Sharing annotations and datasets across organizations is currently possible only in a very limited way. This may explain the “locked by unknown user” message. So I would suggest you invite your collaborators into your own organization.

Some details on organizations and invites can be found at https://docs.webknossos.org/webknossos/users.html

However, this does not explain the “failed to create annotation”. It should already be possible to create annotations for public datasets even cross-organization. Are there any more details with the error message by any chance?

It would also help us to know the URL of the dataset in question. If you don’t want to share that here publicly, you could also send it to hello@webknossos.org with a quick reference to this bug report.

**Comment by fm3** [comment]
Closing this for now due to inactivity.

Creating annotation for public datasets of other organizations should be fixed now (compare #8105).

If you have further problems, feel free to reopen this issue or send an email.
