### ISSUE TITLE
Add Sum row in Time Tracking Overview

### ISSUE THREAD

**Issue by Albane-dlv** [scalableminds/webknossos#8088]
## Detailed Description
It would be nice to have the sum of the total time spent on tasks and annotations when viewing the time tracking. We could add a row and have the total number of tasks/annotations, the average time per task/annotation, and the sum of the time spent on the tasks/annotations.

![Screenshot 2024-09-19 at 13 29 46](https://github.com/user-attachments/assets/f2363f88-a42e-4c75-8f96-b73e96c016cd)

## Context
This is important when you quickly want to know how much time has been spent in total on these tasks or annotations.

**Comment by dieknolle3333** [comment]
I hope something simple like this is fine :)
![image](https://github.com/user-attachments/assets/5af85e25-80b1-43ec-971e-de381725ba7b)

**Comment by dieknolle3333** [comment]
![image](https://github.com/user-attachments/assets/2a218c42-4e6a-437d-8f98-8057512edf68)
I hope something very simple like this is fine :)

**Comment by dieknolle3333** [comment]
Is it okay if I leave the sums out of the CSV? I think its very easy to add this manually in Excel/Numbers etc
