### ISSUE TITLE
Cursor in Bounding Box Tool 

### ISSUE THREAD

**Issue by knollengewaechs** [scalableminds/webknossos#8132]
## Context
 

In bounding box tool, the "move" cursor does not appear as expected

## Expected Behavior

Within the bounding box tool, the move cursor should appear when ctrl is pressed, as moving the whole box is possible from there on

## Current Behavior

If one is hovering the edges of a bounding box and then pressing ctrl, the cursor does not change. One has to move the cursor a little for it to change and take the shape of four arrows. 

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Open annotation, activate BBox Tool
2. Hover edge of a BBox
3. Press Ctrl

## Your Environment for bug

Firefox for Mac
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by MichaelBuessemeyer** [comment]
> Within the bounding box tool, the move cursor should appear when ctrl is pressed, as moving the whole box is possible from there on

> If one is hovering the edges of a bounding box and then pressing ctrl, the cursor does not change. One has to move the cursor a little for it to change and take the shape of four arrows.

Yeah, I did not develop this to the fullest. Maybe https://github.com/scalableminds/webknossos/pull/7892#pullrequestreview-2156328378 and https://github.com/scalableminds/webknossos/pull/7892#issuecomment-2211269989 are relevant here. So this is expected, although I agree that this is no ideal.

Feel free to improve the behaviour :)
