### ISSUE TITLE
Merge Mode 

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#8206]
## Context
Merger Mode has issues updating the segment colors.

from Sahil:
```
I am trying to use the “Toggle Merger Mode” feature.

Some of the segments corresponding to the annotated skeleton get updated to the same color but some don’t. See image below.
WK link https://webknossos.brain.mpg.de/annotations/673b018e0100001601d446fc#8232,7448,2559,0,1.503,1109
```

![image](https://github.com/user-attachments/assets/6f1667d5-571e-4d3b-9edb-ddf8edeeb274)

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WEBKNOSSOS (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Turned out that the merger mode was working as expected. It was the dataset that was broken (downsampled voxels didn’t match the mag1 ones).
