### ISSUE TITLE
Add second password input to wkorg registration form to prevent accidental mistyping of the password

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#8215]
## Detailed Description

The registration form shown on wk org has only a single password input and not a second one checking for equality of the entered password.
![image](https://github.com/user-attachments/assets/c7204828-3bb7-4e04-be29-b13705474dc8)

But the registration form for dev and other instances has such a second password input. IMO wk.org should also have a second password input.

=> The result should look similar to what the def instance sign up form looks like.

## Context
There is not much context to this besides trying to prevent accidental mistyping of passwords during sign-up. Just like it is common practice in other sign up forms

**Comment by fm3** [comment]
I’m not sure I am a fan of this. There is already a password reset flow via email in case of a mistyped password on registration. Most users won’t mistype, but would be faced with this additional little hurdle on signup.

**Comment by MichaelBuessemeyer** [comment]
> There is already a password reset flow via email in case of a mistyped password on registration.

Hmm I see :thinking: 
In that case, maybe supporting sign up via google might be useful :thinking:? But I think I mentioned this already a few times :see_no_evil:

**Comment by fm3** [comment]
Yeah, that I could get behind :) Wrote https://github.com/scalableminds/webknossos/issues/8224 to track that. But I still think it has fairly low priority.
