### ISSUE TITLE
Changing a segment's color modifies the color of the previously changed segment

### ISSUE THREAD

**Issue by kabilar** [scalableminds/webknossos#8223]
## Context
As an example to reproduce the error, I copied the `Featured Publication` below to my trial account on webknossos.org so that I could edit the segment colors.

![image](https://github.com/user-attachments/assets/6ef6edda-cbaa-403e-a37e-4de6e32384a2)

## Expected Behavior
I would expect that the `Change Segment Color` component allows for editing the selected segment's color.

## Current Behavior
When I edit the color of more that 1 segment, selecting `Change Segment Color` modifies the color of the previously changed segment.

## Steps to Reproduce the bug
See screen recording below.  This behavior also occurs if I press `Save` after editing each segment color.

https://github.com/user-attachments/assets/a7d1bbe5-76e0-4676-95c3-75197f9fcfeb

## Your Environment for bug
- Browser name and version: Safari 18.0.1
- Operating System and version: MacOS 15.0.1
- Version of WEBKNOSSOS (Release or Commit): Version currently deployed at webknossos.org
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

cc @aaronkanzer @jssyq

**Comment by fm3** [comment]
Thanks for the detailed report! We’ll have a look at what’s going on there.

**Comment by MichaelBuessemeyer** [comment]
@kabilar Could you please give this a retry? The bug fix should now be deployed on webknossos.org

**Comment by kabilar** [comment]
Thank you for the quick response.  I tested on webknossos.org and can confirm that this issue is resolved.
