### ISSUE TITLE
Rename `typ` to `type` in annotation routes

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#8232]
## Detailed Description

Quite a lot of annotation routes have a `typ` parameter in their path. We could consider renaming them to `type`. This should not need any legacy routes as:
1. These routes are as far as I know not used by wklibs
2. The parameter is a "route path" parameter, thus making renaming it version irrelevant
 See this image which highlights the occurrences of `typ`: 
![image](https://github.com/user-attachments/assets/472e7c91-7cb7-4743-9aff-c7972fe0ad59)

**Comment by MichaelBuessemeyer** [comment]
A quick investigation showed that the frontend and route return types would also be involved in such a refactoring :/

**Comment by fm3** [comment]
I think the reason for this is that `type` is a keyword in scala. You can still use `type` as a variable name, but it always has to be in backticks in the code. Not sure if you can use it in routes files at all.

**Comment by MichaelBuessemeyer** [comment]
oh no, big uff. Then I guess that's a no to the refactoring :/
