### ISSUE TITLE
Ensure most of the frontend sites are covered by the is-site-alive-bot

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#910]
Let's add most of the views to the bot to make sure all pages load. This still won't check if the page shows the correct result or is displayed correctly, but will us alert if a certain page is unreachable. 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/910/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
With newrelic monitoring this has become obsolete.
