### ISSUE TITLE
Simplify Team Administration

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#935]
The current team administration model is good, but quite complicated, leads to headaches and posses some issues here and there. How about simplifying the model to the following:
- [ ] Rename root teams to "organizations" e.g. "Connectomics department" is going to be an organization
- [ ] Each Organization contains Teams
- [ ] Each Organization contains 2 Roles (user, admin)
- [ ] Each Team contains 2 Roles (user, supervisor)
- [ ] There are no subteams. There are only two levels, organizations and their teams.
- [ ] A user always belongs to exactly one organization but possibly multiple teams.
- [ ] Admins are admins at the organization level. Therefore they can always administrate all teams of that organization.
- [ ] Admins of an organization can administrate all users belonging to that organization.
- [ ] Datasets are always assigned to Teams (possibly multiple), never to organizations.

Does that work for you @kevinbbb87 @heikowissler?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/935/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Open Frontend Issues:
- [Team List View ] Creating a new team should no longer ask for a "root" team (or organisation)
- [User List View ] Fix team and role assignments
- [ Task Type Creation] Team Selection Dropdown
- [ Project Creation] Team Selection Dropdown 
- [ Task Creation] Team Selection Dropdown 
- Fix Flow Types

**Comment by hotzenklotz** [comment]
@youri-k Here is something that I noticed: I am admin of the organization but not in any team. When I try to view all projects / task types I can't see any. The backend delivers and empty array as result to the corresponding REst call. Toplevel admin access is probably not yet integrated in some of the permission checks.

**Comment by youri-k** [comment]
@philippotto The route is called `/api/organizations`

**Comment by hotzenklotz** [comment]
@youri-k I think the frontend part is done for now. Can you please comment on the status of the backend? Please list the open issues here. Perhaps I can support you with any open tasks.

**Comment by youri-k** [comment]
All checks were just restructured from team admin to team manager(supervisor), so it might be necessary to also include admins of the organization(that would make things asynchronous though), otherwise it looks pretty good.
There is no mechanism inside the code to create organizations except for the standard dao principle so the org-wide team has to be created manually, too but every user gets automatically put into the org-wide team on registration.
I just saw, that I need to fix some checks in `Braintracing.scala`.
Additionally we need to test if the datastore still works but there shouldn't be a problem.
So all in all it's mainly about tests and permissions I think.

**Comment by hotzenklotz** [comment]
- [ ] Give org admins permission for everything
- [ ] Fix `Braintracing.scala`
- [ ] Test all permissions
- [ ] Assign newly created users to organization's team

Let's not worry about creating new organisations right now. This is a feature that we can add later if needed.

@youri-k I would be happy to help testing permissions. Please fix the remaining issues and deploy a working version on the test server (use the slack commands).

**Comment by youri-k** [comment]
@hotzenklotz open frontend issues:
- [ ] team id instead of team name in dataset view, admin project view, admin tasktype view
- [ ] when trying to delete an org team the backend sends an error message but the frontend doesnt recognize it

**Comment by hotzenklotz** [comment]
@youri-k I can no longer seem my dataset. I am not sure what's going on. Did you change anything regarding permission and what datasets I should be able to see?

**Comment by youri-k** [comment]
@hotzenklotz I could find the problem and fixed it. I don't know why it didn't occur earlier in my tests.
