### ISSUE TITLE
add test config for database and binary data

### ISSUE THREAD

**Issue by mischkew** [scalableminds/webknossos#956]
test.conf is necessary for isolated test environment

this relates to #291 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/956/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@jstriebel this be closed, since the tests seem to work?

**Comment by jstriebel** [comment]
I guess so, I am not sure what this is about. As tests are fine now, closing this.
