### ISSUE TITLE
Show branch-points in abstract tree viewer

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#979]
Moritz: "ebenso will ich immer noch die branch points im abstract tree viewer sichtbar haben"

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/979/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
In my opinion branch points are very visible in the abstract tree viewer, simply because the tree branches there. If someone insists on making them more visible, they could get a different color as is being done for nodes with a comment. Closing for now.
